Repository section-engineering-education/engineering-education, pull requests merged in 2020-12, with the labels that each got.

#634 Getting-started-with-inheritance-using-c#
  articles/getting-started-with-inheritance-using-c/hero.jpg
  articles/getting-started-with-inheritance-using-c/index.md
  articles/getting-started-with-inheritance-using-c/tree-of-inheritance.png
  authors/mohamed-alghadban/avatar.jpg
  authors/mohamed-alghadban/index.md
Labels: good first article, preliminary revision in progress, ready for final review, tech review

#659 Deep dive into RxJava operators
  articles/rxjava-operators/hero.png
  articles/rxjava-operators/index.md
Labels: assigned for review, ready for final review

#664 Django crud api
  articles/django-crud-api/delete.png
  articles/django-crud-api/get.png
  articles/django-crud-api/hero.jpg
  articles/django-crud-api/index.md
  articles/django-crud-api/post.png
  articles/django-crud-api/put.png
Labels: needs front matter, ready for final review

#677 Building a Rock Paper Scissors Game Using Socket
  articles/rock-paper-scissor-online/hero.jpg
  articles/rock-paper-scissor-online/index.md
  articles/rock-paper-scissor-online/rps.png
Labels: assigned for review, needs front matter, ready for final review, tiered payout

#753 JavaScript High Order Functions
  articles/javascript-higher-order-functions/function-as-an-argument.png
  articles/javascript-higher-order-functions/hero.jpg
  articles/javascript-higher-order-functions/index.md
  articles/javascript-higher-order-functions/value-of-another-function.png
Labels: needs front matter, ready for final review

#763 Intelligent Agents in Artificial Intelligence
  articles/intelligent-agents-in-ai/ai-system.png
  articles/intelligent-agents-in-ai/hero.jpg
  articles/intelligent-agents-in-ai/how-an-intelligent-agent-works.png
  articles/intelligent-agents-in-ai/index.md
Labels: needs front matter, ready for final review

#764 Basics of The Object Model
  articles/basics-of-the-object-model/hero.jpg
  articles/basics-of-the-object-model/hierarchy.gif
  articles/basics-of-the-object-model/index.md
Labels: needs front matter, ready for final review

#767 Conditional Automation in Driving: Level 3 Autonomous Cars
  articles/conditional-automation-in-driving/autonomous-car.jpg
  articles/conditional-automation-in-driving/features-of-level-3-cars.png
  articles/conditional-automation-in-driving/hero.jpg
  articles/conditional-automation-in-driving/how-level-3-cars-work.png
  articles/conditional-automation-in-driving/index.md
Labels: ready for final review

#778 Data Lake vs. Data Warehouse vs. Database
  articles/data-lake-vs-data-warehouse-vs-database/hero.jpg
  articles/data-lake-vs-data-warehouse-vs-database/index.md
Labels: needs front matter, ready for final review

#784 Handling Imbalanced Datasets in Machine Learning
  articles/imbalanced-data-in-ml/bagging.png
  articles/imbalanced-data-in-ml/hero.jpg
  articles/imbalanced-data-in-ml/index.md
Labels: needs front matter, ready for final review

#800 Ensuring ACID Compliance in Database Transactions
  articles/ensuring-acid-compliance-in-database-transactions/hero.jpg
  articles/ensuring-acid-compliance-in-database-transactions/index.md
Labels: needs front matter, ready for final review

#692 How to use databinding in android using kotlin
  articles/how-to-use-databinding-in-android-using-kotlin/hero.png
  articles/how-to-use-databinding-in-android-using-kotlin/index.md
Labels: needs front matter, ready for final review

#702 How to use array operators in js
  articles/how-to-use-array-operators-in-js/hero.jpg
  articles/how-to-use-array-operators-in-js/index.md
  authors/kennedy-mwangi/avatar.jpg
  authors/kennedy-mwangi/index.md
Labels: assigned for review, enhancement, good first article, ready for final review

#748 Getting started with operator overloading in C++
  articles/getting-started-with-operator-overloading-in-c++/hero.jpg
  articles/getting-started-with-operator-overloading-in-c++/index.md
  authors/dawe-daniel/avatar.jpg
  authors/dawe-daniel/index.md
Labels: assigned for review, good first article, ready for final review

#765 Introduction to Digital Twin Technology
  articles/introduction-to-digital-twin-technology/digital-twin-cars.jpg
  articles/introduction-to-digital-twin-technology/digital-twin.jpg
  articles/introduction-to-digital-twin-technology/hero.jpg
  articles/introduction-to-digital-twin-technology/how-digital-twin-technology-works.jpg
  articles/introduction-to-digital-twin-technology/index.md
Labels: ready for final review

#647 Minecraft Plugin Development: A Hands-On Crash Course
  articles/minecraft-plugin-development-a-hands-on-crash-course/hero.png
  articles/minecraft-plugin-development-a-hands-on-crash-course/index.md
  articles/minecraft-plugin-development-a-hands-on-crash-course/plugin-main-class.png
  articles/minecraft-plugin-development-a-hands-on-crash-course/plugin-setup.png
Labels: assigned for review, ready for final review

#691 Implementing secret key cryptography in JavaScript
  articles/secret-key-cryptography-in-js/hero.jpg
  articles/secret-key-cryptography-in-js/index.md
Labels: assigned for review, needs author page, ready for final review

#792 Introduction to Data Integration in Talend Open Studio (TOS)
  articles/introduction-to-data-integration-in-tos/adding-a-new-job.jpg
  articles/introduction-to-data-integration-in-tos/creating-a-new-job.jpg
  articles/introduction-to-data-integration-in-tos/dragging-a-component.jpg
  articles/introduction-to-data-integration-in-tos/hero.jpg
  articles/introduction-to-data-integration-in-tos/index.md
  articles/introduction-to-data-integration-in-tos/step-11.jpg
  articles/introduction-to-data-integration-in-tos/step-12.jpg
  articles/introduction-to-data-integration-in-tos/step-13.jpg
  articles/introduction-to-data-integration-in-tos/step-14.png
  articles/introduction-to-data-integration-in-tos/step-15.png
  articles/introduction-to-data-integration-in-tos/step-2.jpg
  articles/introduction-to-data-integration-in-tos/step-3.jpg
  articles/introduction-to-data-integration-in-tos/step-4.jpg
  articles/introduction-to-data-integration-in-tos/step-5.jpg
  articles/introduction-to-data-integration-in-tos/step-6.jpg
  articles/introduction-to-data-integration-in-tos/step-7.jpg
  articles/introduction-to-data-integration-in-tos/step-8.jpg
  articles/introduction-to-data-integration-in-tos/step-9.jpg
  articles/introduction-to-data-integration-in-tos/the-gui-of-tos.jpg
Labels: needs front matter, ready for final review

#799 Understanding MapReduce in Hadoop
  articles/understanding-map-reduce-in-hadoop/example-of-mapreduce.png
  articles/understanding-map-reduce-in-hadoop/hero.jpg
  articles/understanding-map-reduce-in-hadoop/index.md
  articles/understanding-map-reduce-in-hadoop/job-trackers-and-task-trackers.png
  articles/understanding-map-reduce-in-hadoop/map-reduce-architecture.png
  articles/understanding-map-reduce-in-hadoop/mapreduce-flow-diagram.jpg
  articles/understanding-map-reduce-in-hadoop/mapreduce-with-combiner-phase.jpg
Labels: needs front matter, ready for final review

#681 React Native Agora Video Conference App
  articles/react-native-agora-video-conference-app/agora_dashboard.png
  articles/react-native-agora-video-conference-app/agora_new_project.png
  articles/react-native-agora-video-conference-app/agora_project_management_console.png
  articles/react-native-agora-video-conference-app/buttons.jpeg
  articles/react-native-agora-video-conference-app/hero.jpg
  articles/react-native-agora-video-conference-app/homescreen.jpeg
  articles/react-native-agora-video-conference-app/index.md
  articles/react-native-agora-video-conference-app/remote_buttons.jpg
  articles/react-native-agora-video-conference-app/styled_buttons.jpeg
  authors/mohan-raj/index.md
Labels: assigned for review, tech review

#770 how-css-works-behind-the-scenes
  articles/how-css-works-behind-the-scenes/css-om.png
  articles/how-css-works-behind-the-scenes/hero.jpg
  articles/how-css-works-behind-the-scenes/importance-code.png
  articles/how-css-works-behind-the-scenes/index.md
  articles/how-css-works-behind-the-scenes/parsing.png
  articles/how-css-works-behind-the-scenes/render-tree.png
  articles/how-css-works-behind-the-scenes/rendered-website.png
  articles/how-css-works-behind-the-scenes/specificity-code.png
  authors/sarthak-duggal/avatar.jpg
  authors/sarthak-duggal/index.md
Labels: enhancement, needs front matter

#761 Optimizing Stock Price Profit Using Greedy Algorithms
  articles/greedy-algorithms/hero.jpg
  articles/greedy-algorithms/index.md
Labels: assigned for review, enhancement, needs front matter, ready for final review

#750 How to create an API using Laravel
  articles/how-to-create-an-api-using-laravel/hero.png
  articles/how-to-create-an-api-using-laravel/index.md
  articles/how-to-create-an-api-using-laravel/routes.png
Labels: needs front matter, ready for final review

#758 How JavaScript Uses Web Browser APIs To Achieve Asynchronisity
  articles/javascript-and-web-apis/hero.jpg
  articles/javascript-and-web-apis/index.md
Labels: assigned for review, ready for final review

#768 Software Testing Part 1 - Introduction to Unit Testing
  articles/software-testing-part1/Hero.jpg
  articles/software-testing-part1/index.md
Labels: needs front matter, ready for final review, tiered payout

#855 Introduction to constructors in c++
  articles/introduction-to-constructors-in-c++/hero.jpg
  articles/introduction-to-constructors-in-c++/index.md
Labels: assigned for review, needs front matter, ready for final review

#785 Software Testing Part 2 - Introduction to Test-Driven Development
  articles/software-testing-part2/hero.jpg
  articles/software-testing-part2/index.md
Labels: needs front matter, ready for final review

#749 Amazon Web Services (AWS) vs Google Cloud
  articles/aws-vs-google-cloud/amazon-web-services.png
  articles/aws-vs-google-cloud/google-cloud-platform.jpg
  articles/aws-vs-google-cloud/hero.jpg
  articles/aws-vs-google-cloud/index.md
Labels: needs front matter, ready for final review

#656 Atom vs. Visual Studio Code: Functionality and Features Comparison
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/VSdownload.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/at-multiline.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/at-vsline.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/atmfolding.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/atom-symbols.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/atomdownload.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/check-box.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/drop-down.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/emmet.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/git-atom.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/hero.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/index.md
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/input.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/json.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/plugininstall.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/vs-code-settings.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/vs-git-integration.jpg
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/vs-multiline.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/vs-symbol.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/vsfolding.gif
  articles/atom-vs-visual-studio-code-functionality-and-features-comparison/vswelcome.jpg
Labels: assigned for review, ready for final review, tiered payout

#676 Implementing scoped model in your Flutter application
  articles/implementing-scoped-model-in-your-flutter-application/creating-project.png
  articles/implementing-scoped-model-in-your-flutter-application/hero.jpg
  articles/implementing-scoped-model-in-your-flutter-application/index.md
  articles/implementing-scoped-model-in-your-flutter-application/ui.jpg
Labels: ready for final review

#700 Getting started with Admob in React Native | Expo Ecosystem
  articles/getting-started-using-admob-with-react-native-expo/1-admob-all-apps-dashboard.png
  articles/getting-started-using-admob-with-react-native-expo/10-finish-create-ad-unit.png
  articles/getting-started-using-admob-with-react-native-expo/11-export-project-from-snack.png
  articles/getting-started-using-admob-with-react-native-expo/12-running-react-native-expo-in-local.png
  articles/getting-started-using-admob-with-react-native-expo/13-show-ad-banner.png
  articles/getting-started-using-admob-with-react-native-expo/14-remove-ad-button.png
  articles/getting-started-using-admob-with-react-native-expo/15-remove-ad-in-action.gif
  articles/getting-started-using-admob-with-react-native-expo/2-create-new-admob-app-choose-platform.png
  articles/getting-started-using-admob-with-react-native-expo/3-naming-admob-app.png
  articles/getting-started-using-admob-with-react-native-expo/4-create-add-unit.png
  articles/getting-started-using-admob-with-react-native-expo/5-admob-ad-type.png
  articles/getting-started-using-admob-with-react-native-expo/6-create-banner-ad.png
  articles/getting-started-using-admob-with-react-native-expo/7-success-create-ad-unit.png
  articles/getting-started-using-admob-with-react-native-expo/8-ad-unit-dashboard.png
  articles/getting-started-using-admob-with-react-native-expo/9-create-reward-ad.png
  articles/getting-started-using-admob-with-react-native-expo/hero.jpg
  articles/getting-started-using-admob-with-react-native-expo/index.md
Labels: assigned for review, ready for final review, tech review, tiered payout

#812 Capsule Networks: An Enhancement to Convolutional Neural Networks (CNN)
  articles/capsule-networks-an-enhancement-to-convolution-neural-networks/caps-net-3-layers.PNG
  articles/capsule-networks-an-enhancement-to-convolution-neural-networks/caps-net-digicaps-reconstruct.PNG
  articles/capsule-networks-an-enhancement-to-convolution-neural-networks/flipped-image.jpg
  articles/capsule-networks-an-enhancement-to-convolution-neural-networks/hero.jpg
  articles/capsule-networks-an-enhancement-to-convolution-neural-networks/index.md
  articles/capsule-networks-an-enhancement-to-convolution-neural-networks/original-image.jpg
  articles/capsule-networks-an-enhancement-to-convolution-neural-networks/squashing-function.PNG
  articles/capsule-networks-an-enhancement-to-convolution-neural-networks/vector-length-orientation.PNG
Labels: needs front matter, ready for final review

#821 Introduction to Android App Development with Basic4Android B4A Part1
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-android-sdk-folder-structure.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-bridge-android.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-configuring-paths.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-connecting-visual-designer-to-device.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-create-new-default-project.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-generating-button-onclick.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-hello-world.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-install-visual-designer-prompt.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-launching-visual-designer.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-modules.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-new-default-project-source-code.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-sample-app-output.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-visual-designer-screenshot.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/b4a-visual-designer-views.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/connecting-b4a-bridge-ip-prompt.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/connecting-b4a-bridge.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/hero.jpg
  articles/Introduction-to-android-app-development-basic4android-b4a-part1/index.md
Labels: ready for final review

#834 A complete beginner guide on installing flask for beginners
  articles/complete-guide-on-installing-flask-for-beginners/hero.jpg
  articles/complete-guide-on-installing-flask-for-beginners/index.md
  articles/complete-guide-on-installing-flask-for-beginners/web-app-structure.jpg
  authors/adetu-ridwan/avatar.jpg
  authors/adetu-ridwan/index.md
Labels: good first article, needs front matter, needs hero image, ready for final review

#837 Introduction to Random Forest in Machine Learning
  articles/introduction-to-random-forest-in-machine-learning/decision-tree-nodes.png
  articles/introduction-to-random-forest-in-machine-learning/example-of-decision-tree.png
  articles/introduction-to-random-forest-in-machine-learning/example-of-random-forest-classifier.png
  articles/introduction-to-random-forest-in-machine-learning/hero.jpg
  articles/introduction-to-random-forest-in-machine-learning/index.md
  articles/introduction-to-random-forest-in-machine-learning/random-forest-classifier.png
Labels: needs front matter, ready for final review

#714 added laravel blog post article
  articles/laravel-beginners-guide-blogpost/10_home.png
  articles/laravel-beginners-guide-blogpost/11_blog_page.png
  articles/laravel-beginners-guide-blogpost/12_expand.png
  articles/laravel-beginners-guide-blogpost/13_blog_post_page.png
  articles/laravel-beginners-guide-blogpost/14_new_post_form.png
  articles/laravel-beginners-guide-blogpost/1_db_create.PNG
  articles/laravel-beginners-guide-blogpost/2_home.png
  articles/laravel-beginners-guide-blogpost/3_files.png
  articles/laravel-beginners-guide-blogpost/4_app_files.png
  articles/laravel-beginners-guide-blogpost/5_tinker.png
  articles/laravel-beginners-guide-blogpost/6_blog_dump.png
  articles/laravel-beginners-guide-blogpost/7_blog_post.png
  articles/laravel-beginners-guide-blogpost/8_blade_syntax.PNG
  articles/laravel-beginners-guide-blogpost/9_blade_directives.PNG
  articles/laravel-beginners-guide-blogpost/hero.jpg
  articles/laravel-beginners-guide-blogpost/index.md
  authors/mauline-mwaniki/avatar.jpg
  authors/mauline-mwaniki/index.md
Labels: assigned for review, ready for final review, tech review

#861 Intro to junit and mockito
  articles/introduction-to-junit-and-mockito/hero.jpg
  articles/introduction-to-junit-and-mockito/index.md
Labels: needs front matter, ready for final review

#873 Ensemble learning techniques to improve Machine Learning
  articles/ensemble-learning/bagging.png
  articles/ensemble-learning/hero.jpg
  articles/ensemble-learning/index.md
  articles/ensemble-learning/stacking.png
  articles/ensemble-learning/stackingregression.png
Labels: needs front matter, ready for final review

#794 Google Play In-App Review using Android Studio
  articles/google-play-in-app-reviews/hero.png
  articles/google-play-in-app-reviews/in-app-dialog-and-fallback-dialog.png
  articles/google-play-in-app-reviews/in-app-review-flow.jpg
  articles/google-play-in-app-reviews/in-app-reviews.png
  articles/google-play-in-app-reviews/index.md
Labels: assigned for review, ready for final review

#838 IoT Deployments with SD-WAN
  articles/iot-deployments-with-sd-wan/hero.jpg
  articles/iot-deployments-with-sd-wan/index.md
Labels: needs front matter, ready for final review

#766 Autoscaling in Amazon Web Services (AWS): An Overview
  articles/autoscaling-in-amazon-web-services/amazon-web-services.png
  articles/autoscaling-in-amazon-web-services/autoscaling-group.png
  articles/autoscaling-in-amazon-web-services/aws-autoscaling.png
  articles/autoscaling-in-amazon-web-services/creating-autoscaling-group.png
  articles/autoscaling-in-amazon-web-services/hero.jpg
  articles/autoscaling-in-amazon-web-services/index.md
  articles/autoscaling-in-amazon-web-services/launch-configuration.png
Labels: assigned for review, needs front matter, ready for final review

#816 Introduction to Transfer Learning in NLP
  articles/nlp-transfer-learning/hero.jpg
  articles/nlp-transfer-learning/index.md
  articles/nlp-transfer-learning/rnn.png
  articles/nlp-transfer-learning/transfomer_with_attention.png
  articles/nlp-transfer-learning/transformers.png
Labels: needs front matter, ready for final review

#762 Understanding Divide and Conquer Method using Stock Price Optimization Problem
  articles/divide-and-conquer-algorithms/hero.jpg
  articles/divide-and-conquer-algorithms/index.md
Labels: assigned for review, needs front matter, preliminary revision in progress, revisions needed

#961 adding front matter review process walkthrough
  peer_reviewers/front-matter-process.md
Labels: documentation

#854 Android workmanager
  articles/android-workmanager/hero.jpg
  articles/android-workmanager/index.md
Labels: needs front matter, ready for final review

#851 Securing Django API
  articles/securing-django-api/get-token.png
  articles/securing-django-api/get-using-token.png
  articles/securing-django-api/hero.jpg
  articles/securing-django-api/index.md
  articles/securing-django-api/jwt-error.png
  articles/securing-django-api/jwt-get-token.png
  articles/securing-django-api/jwt-refresh.png
  articles/securing-django-api/jwt-rquest.png
Labels: needs front matter, ready for final review

#902 Breaking Down Public Cloud vs. Hybrid Cloud vs. Private Cloud
  articles/breaking-down-public-cloud-vs-hybrid-cloud-vs-private-cloud/hero.jpg
  articles/breaking-down-public-cloud-vs-hybrid-cloud-vs-private-cloud/index.md
Labels: needs front matter, ready for final review

#883 Understanding Hill Climbing Algorithm in Artificial Intelligence
  articles/understanding-hill-climbing-in-ai/hero.jpg
  articles/understanding-hill-climbing-in-ai/hill-climbing-algorithm-in-ai.png
  articles/understanding-hill-climbing-in-ai/index.md
  articles/understanding-hill-climbing-in-ai/plateau.png
  articles/understanding-hill-climbing-in-ai/ridge-in-hill-climbing.png
Labels: needs front matter, ready for final review

#872 Exception Handling in JavaScript
  articles/exception-handling-in-javascript/hero.jpg
  articles/exception-handling-in-javascript/index.md
Labels: assigned for review, ready for final review

#790 An Introduction to Activation Functions
  articles/activation-functions/hero.jpg
  articles/activation-functions/index.md
  articles/activation-functions/leakyrelu.png
  articles/activation-functions/relu.png
  articles/activation-functions/sigmoid.png
  articles/activation-functions/softmax.png
  articles/activation-functions/step_function.png
  articles/activation-functions/tanh.png
Labels: preliminary revision in progress

#937 Graph Implementation and Traversal Algorithms (Java)
  articles/graph-traversals-java/directed.png
  articles/graph-traversals-java/graph.jpg
  articles/graph-traversals-java/hero.jpg
  articles/graph-traversals-java/index.md
  articles/graph-traversals-java/undirected.png
  authors/tenson-cai/index.md
  authors/tenson-cai/tenson.jpg
Labels: duplicate, good first article, ready for final review

#874 Introduction to room db
  articles/introduction-to-room-db/app.gif
  articles/introduction-to-room-db/hero.jpg
  articles/introduction-to-room-db/index.md
Labels: assigned for review, ready for final review

#906 Introduction to Active Learning
  articles/active-learning/hero.jpg
  articles/active-learning/index.md
  articles/active-learning/membership.png
  articles/active-learning/pool.png
  articles/active-learning/stream.png
Labels: ready for final review

#915 Digital Assistants vs. Digital Companions
  articles/digital-assistants-vs-digital-companions/hero.jpg
  articles/digital-assistants-vs-digital-companions/index.md
  authors/pius-macharia/avatar.jpg
  authors/pius-macharia/index.md
Labels: good first article, ready for final review

#884 Diving deeper into js objects.
  articles/diving-deeper-into-js-objects/hero.jpg
  articles/diving-deeper-into-js-objects/index.md
Labels: ready for final review

#890 User registration in django using Google OAuth
  articles/django-google-oauth/add-social-app.jpg
  articles/django-google-oauth/authorised-redirects.jpg
  articles/django-google-oauth/create-dj-site.jpg
  articles/django-google-oauth/create-g-oauth-project.jpg
  articles/django-google-oauth/g-oauth-consent-screen-1.jpg
  articles/django-google-oauth/hero.jpg
  articles/django-google-oauth/index.md
  articles/django-google-oauth/sign-in-with-google.jpg
Labels: needs front matter, ready for final review

#998 How to Optimize Cloud Computing Costs with Cloud Bursting
  articles/how-to-optimize-cloud-computing-costs-with-cloud-bursting/hero.jpg
  articles/how-to-optimize-cloud-computing-costs-with-cloud-bursting/index.md
Labels: duplicate, ready for final review

#833 Initial Draft for RegEx in Python
  articles/regular-expressions-in-python/fsm.png
  articles/regular-expressions-in-python/hero.jpg
  articles/regular-expressions-in-python/index.md
Labels: ready for final review

#868 Building XML webpages using XSLT
  articles/building-xml-webpages-using-xslt/hero.jpg
  articles/building-xml-webpages-using-xslt/index.md
  articles/building-xml-webpages-using-xslt/output.PNG
Labels: preliminary revision in progress, ready for final review

#893 Building a CI/CD pipeline using Gitlab
  articles/building-a-cicd-pipeline-using-gitlab/blank_project.png
  articles/building-a-cicd-pipeline-using-gitlab/build.png
  articles/building-a-cicd-pipeline-using-gitlab/cicd_pipelines.png
  articles/building-a-cicd-pipeline-using-gitlab/create_new.png
  articles/building-a-cicd-pipeline-using-gitlab/hero.jpg
  articles/building-a-cicd-pipeline-using-gitlab/index.md
  articles/building-a-cicd-pipeline-using-gitlab/passed_pipeline.png
  articles/building-a-cicd-pipeline-using-gitlab/test.png
Labels: assigned for review, ready for final review

#923 Addressing Underspecification in Machine Learning
  articles/underspecification-machine-learning/hero.jpg
  articles/underspecification-machine-learning/index.md
Labels: ready for final review

#925 Introduction to c#
  articles/introduction-to-csharp/Consoleapp.png
  articles/introduction-to-csharp/Newproject2.png
  articles/introduction-to-csharp/Program.png
  articles/introduction-to-csharp/hero.jpg
  articles/introduction-to-csharp/index.md
  articles/introduction-to-csharp/installation.png
  articles/introduction-to-csharp/netframework.png
  articles/introduction-to-csharp/projectname.png
  articles/introduction-to-csharp/vs1.png
  authors/geoffrey-mwangi/avatar.png
  authors/geoffrey-mwangi/index.md
Labels: assigned for review, good first article, ready for final review

#938 Comparing Intrusion Detection Systems (IDS) and Intrusion Prevention Systems (IPS)
  articles/comparing-intrusion-detection-systems-ids-and-intrusion-prevention-systems-ips/hero.jpg
  articles/comparing-intrusion-detection-systems-ids-and-intrusion-prevention-systems-ips/ids-security.png
  articles/comparing-intrusion-detection-systems-ids-and-intrusion-prevention-systems-ips/index.md
  articles/comparing-intrusion-detection-systems-ids-and-intrusion-prevention-systems-ips/ips-security.png
Labels: ready for final review

#917 An Overview of Fuzzy Logic System
  articles/an-overview-of-fuzzy-logic-system/architecture-of-fuzzy-logic-system.png
  articles/an-overview-of-fuzzy-logic-system/hero.jpg
  articles/an-overview-of-fuzzy-logic-system/index.md
  articles/an-overview-of-fuzzy-logic-system/membership-function.jpg
Labels: ready for final review

#933 Understanding Loops and Iteration in Dart
  articles/understanding-dart-loops/hero.jpg
  articles/understanding-dart-loops/index.md
  authors/diana-mutheu/avatar.jpg
  authors/diana-mutheu/index.md
Labels: assigned for review, good first article, ready for final review

#1087 Fixed Static Site to Node.js Article Syntax Error
  articles/static-site-dynamic-nodejs-web-app/index.md
Labels: article update

#844 laravel 8 new features
  articles/laravel-8-new-features/hero.jpg
  articles/laravel-8-new-features/index.md
  authors/miller-juma/avatar.jpeg
  authors/miller-juma/index.md
Labels: good first article, ready for final review

#905 Android navigation components
  articles/android-navigation-components/deep-linking.gif
  articles/android-navigation-components/hero.jpg
  articles/android-navigation-components/index.md
Labels: ready for final review

#913 Getting started with windows forms using c#
  articles/Getting-started-with-windows-forms-using-c-#/Controls_display.png
  articles/Getting-started-with-windows-forms-using-c-#/Final_look.png
  articles/Getting-started-with-windows-forms-using-c-#/Final_touch_example.png
  articles/Getting-started-with-windows-forms-using-c-#/First_look1.png
  articles/Getting-started-with-windows-forms-using-c-#/Form_name_text.png
  articles/Getting-started-with-windows-forms-using-c-#/hero.jpg
  articles/Getting-started-with-windows-forms-using-c-#/index.md
  articles/Getting-started-with-windows-forms-using-c-#/properties_window_and_toolbox.png
Labels: assigned for review, ready for final review

#796 Android Application In-app Update Using Android Studio
  articles/android-application-in-app-update-using-android-studio/flexible.png
  articles/android-application-in-app-update-using-android-studio/hero.png
  articles/android-application-in-app-update-using-android-studio/immediate.png
  articles/android-application-in-app-update-using-android-studio/index.md
Labels: ready for final review

#801 An Introduction to Question Answering Systems
  articles/question-answering/architecture-qna.png
  articles/question-answering/hero.jpg
  articles/question-answering/index.md
  articles/question-answering/python_example.png
Labels: needs front matter, ready for final review
