Repository section-engineering-education/engineering-education, pull requests merged in 2020-11, with the labels that each got.

#550 How to prepare for coding interviews
  articles/how-to-prepare-for-coding-interviews/hero.jpg
  articles/how-to-prepare-for-coding-interviews/index.md
Labels: ready for final review

#517 Getting-Started-With-Web-Scraping-Using-Python
  articles/getting-started-with-web-scraping-using-python/1.PNG
  articles/getting-started-with-web-scraping-using-python/2.PNG
  articles/getting-started-with-web-scraping-using-python/3.PNG
  articles/getting-started-with-web-scraping-using-python/hero.png
  articles/getting-started-with-web-scraping-using-python/index.md
Labels: assigned for review, tech review

#390 Article - Using the Graph Data Structure in Python, Part 1
  articles/graph-data-structure-python/complete-graph.png
  articles/graph-data-structure-python/dag.png
  articles/graph-data-structure-python/directed-graph.png
  articles/graph-data-structure-python/graph.png
  articles/graph-data-structure-python/hero.jpg
  articles/graph-data-structure-python/index.md
  articles/graph-data-structure-python/rooted-trees.png
  articles/graph-data-structure-python/tree-graph.png
  articles/graph-data-structure-python/undirected-graph.png
  articles/graph-data-structure-python/unweighted-graph.png
  articles/graph-data-structure-python/weighted-graph.png
Labels: assigned for review, enhancement, tech review

#521 Perceptron Algorithm: A Hands-On Introduction
  articles/perceptron-algorithm/hero.jpg
  articles/perceptron-algorithm/index.md
  articles/perceptron-algorithm/output.jpg
  articles/perceptron-algorithm/perceptron.png
  articles/perceptron-algorithm/unit-step.jpg
Labels: assigned for review, tech review

#505 How to control dark mode in React Native using Redux #485
  articles/how-to-build-chrome-extension/hero.jpg
  articles/how-to-control-dark-mode-in-react-native-using-redux/add-material-icon-to-bottom-tab.gif
  articles/how-to-control-dark-mode-in-react-native-using-redux/change-theme-with-redux.gif
  articles/how-to-control-dark-mode-in-react-native-using-redux/hero.jpg
  articles/how-to-control-dark-mode-in-react-native-using-redux/index.md
  articles/how-to-control-dark-mode-in-react-native-using-redux/integrate-react-navigation-to-react-native.gif
  articles/how-to-control-dark-mode-in-react-native-using-redux/react-native-dark-theme.png
  articles/how-to-control-dark-mode-in-react-native-using-redux/react-native-paper-in-home-screen.png
  articles/how-to-control-dark-mode-in-react-native-using-redux/react-native-setting-screen.png
  authors/worawat-kaewsanmaung/avatar.jpg
  authors/worawat-kaewsanmaung/index.md
Labels: assigned for review, good first article, ready for final review, tech review

#561 Android Custom Views - Extending View Subclass
  articles/android-custom-views-extending-view-subclass/app-name.png
  articles/android-custom-views-extending-view-subclass/app.gif
  articles/android-custom-views-extending-view-subclass/hero.jpg
  articles/android-custom-views-extending-view-subclass/index.md
  articles/android-custom-views-extending-view/index.md
Labels: ready for final review

#547 A Push Towards More Sustainable AI with Tiny Machine Learning
  articles/sustainable-ai-with-tinyml/hero.jpg
  articles/sustainable-ai-with-tinyml/index.md
Labels: needs front matter, ready for final review

#571 Introduction To Extended Reality
  articles/introduction-to-extended-reality/augmented-reality.jpeg
  articles/introduction-to-extended-reality/hero.jpg
  articles/introduction-to-extended-reality/index.md
  articles/introduction-to-extended-reality/virtual-reality-in-medicine.jpeg
  articles/introduction-to-extended-reality/virtual-reality.jpg
  articles/introduction-to-extended-reality/xr-games.jpg
  authors/onesmus-mbaabu/avatar.jpg
  authors/onesmus-mbaabu/index.md
Labels: good first article, needs front matter, ready for final review

#584 Getting started with Data Visualization using Pandas
  articles/getting-started-with-data-visualization-using-pandas/all_histogram.PNG
  articles/getting-started-with-data-visualization-using-pandas/bar.PNG
  articles/getting-started-with-data-visualization-using-pandas/hbar.PNG
  articles/getting-started-with-data-visualization-using-pandas/hero.png
  articles/getting-started-with-data-visualization-using-pandas/histogram.PNG
  articles/getting-started-with-data-visualization-using-pandas/index.md
  articles/getting-started-with-data-visualization-using-pandas/line_chart.PNG
  articles/getting-started-with-data-visualization-using-pandas/protein_all.png
  articles/getting-started-with-data-visualization-using-pandas/scatter_plot.PNG
Labels: needs front matter, ready for final review

#595 [Documentation] Added Readmes to Doc Folders
  new_contributors/README.md
  peer_reviewers/README.md
Labels: documentation

#560 List transformations in JavaScript
  articles/list-transformations-js/hero.jpg
  articles/list-transformations-js/index.md
  authors/geoffrey-mungai/avatar.jpg
Labels: assigned for review, ready for final review

#596 Transfer Learning for Deep Learning
  articles/transfer-learning-with-deep-learning/hero.jpg
  articles/transfer-learning-with-deep-learning/index.md
Labels: needs front matter, ready for final review

#514 Introduction to Reinforcement Learning (RL)
  articles/introduction-to-reinforcement-learning/actor-critic.png
  articles/introduction-to-reinforcement-learning/hero.jpg
  articles/introduction-to-reinforcement-learning/index.md
  articles/introduction-to-reinforcement-learning/q-learning.PNG
  articles/introduction-to-reinforcement-learning/rl-architecture.png
  authors/willies-ogola/index.md
Labels: assigned for review, preliminary revision in progress, revisions needed

#617 Improved Templates
  new_contributors/how-to-guide-template.md
  new_contributors/software-review-template.md
  new_contributors/tutorial-template.md
Labels: documentation

#519 JavaScript Iterations. Which One is Fast?
  articles/javascript-iterations-which-one-is-faster/hero.png
  articles/javascript-iterations-which-one-is-faster/index.md
Labels: assigned for review, ready for final review

#532 Validating XML using DTD
  articles/validating-xml-using-dtd/data_serialization.jpg
  articles/validating-xml-using-dtd/hero.jpg
  articles/validating-xml-using-dtd/index.md
Labels: assigned for review, revisions needed, tech review

#563 RxJava in Android
  articles/android-rxjava/hero.jpg
  articles/android-rxjava/index.md
Labels: ready for final review, tech review

#591 Best JavaScript Animation Libraries
  articles/best-javascript-animation-libraries/animejs.gif
  articles/best-javascript-animation-libraries/gsapjs.gif
  articles/best-javascript-animation-libraries/hero.jpg
  articles/best-javascript-animation-libraries/index.md
  articles/best-javascript-animation-libraries/kutejs.gif
  articles/best-javascript-animation-libraries/mojs.gif
  articles/best-javascript-animation-libraries/threejs.gif
  articles/best-javascript-animation-libraries/typejs.gif
Labels: assigned for review, needs front matter, ready for final review

#585 The Role of Artificial Intelligence for Smarter Cybersecurity
  articles/the-role-of-artificial-intelligence-for-smarter-cybersecurity/hero.jpg
  articles/the-role-of-artificial-intelligence-for-smarter-cybersecurity/index.md
Labels: ready for final review

#575 Prototyping Machine learning models with streamlit
  articles/prototyping-machine-learning-models-with-streamlit/hero.jpg
  articles/prototyping-machine-learning-models-with-streamlit/img1.jpg
  articles/prototyping-machine-learning-models-with-streamlit/img2.jpg
  articles/prototyping-machine-learning-models-with-streamlit/img3.jpg
  articles/prototyping-machine-learning-models-with-streamlit/index.md
Labels: needs front matter, ready for final review

#476 Data Binding with Angular
  articles/data-binding-with-angular/event-binding.gif
  articles/data-binding-with-angular/hero.jpg
  articles/data-binding-with-angular/index.md
  articles/data-binding-with-angular/property-binding-disabled.png
  articles/data-binding-with-angular/property-binding-enabled.png
  articles/data-binding-with-angular/string-Interpolation.png
  articles/data-binding-with-angular/two-way-binding.gif
  authors/mahantesh-r/avatar.jpeg
  authors/mahantesh-r/index.md
Labels: assigned for review, tech review

#601 Basics of Convolution Neural Networks (CNNs)
  articles/basics-of-convolution-neural-networks/average-pooling.png
  articles/basics-of-convolution-neural-networks/benign-malignant.PNG
  articles/basics-of-convolution-neural-networks/cnn-architecture.PNG
  articles/basics-of-convolution-neural-networks/cnn-rnn-explanation.PNG
  articles/basics-of-convolution-neural-networks/conv-op1.png
  articles/basics-of-convolution-neural-networks/conv-op2.png
  articles/basics-of-convolution-neural-networks/conv-op3.png
  articles/basics-of-convolution-neural-networks/deepgestalt.PNG
  articles/basics-of-convolution-neural-networks/fully-connected.PNG
  articles/basics-of-convolution-neural-networks/hero.jpg
  articles/basics-of-convolution-neural-networks/image-as-array.PNG
  articles/basics-of-convolution-neural-networks/index.md
  articles/basics-of-convolution-neural-networks/malignant-tumor.PNG
  articles/basics-of-convolution-neural-networks/max-pooling.PNG
  articles/basics-of-convolution-neural-networks/max-pooling.png
  articles/basics-of-convolution-neural-networks/relu-function.PNG
  articles/basics-of-convolution-neural-networks/stride.PNG
Labels: needs front matter, ready for final review

#624 Validating XML using XSD
  articles/validating-xml-using-xsd/hero.jpg
  articles/validating-xml-using-xsd/index.md
Labels: assigned for review, ready for final review

#628 Css in js solution
  articles/css-in-js-solutions/hero.jpg
  articles/css-in-js-solutions/index.md
  articles/css-in-js-solutions/js.png
  authors/aransiola-ayodele/avatar.jpeg
  authors/aransiola-ayodele/index.md
Labels: ready for final review

#586 Python generators
  articles/python-generators/hero.jpg
  articles/python-generators/index.md
  authors/odhiambo-paul/avatar.jpeg
  authors/odhiambo-paul/index.md
Labels: ready for final review

#590 Making api requests using volley android
  articles/google-authentication-for-android/index.md
  articles/making-api-requests-using-volley-android/app.jpg
  articles/making-api-requests-using-volley-android/hero.jpg
  articles/making-api-requests-using-volley-android/index.md
  articles/making-api-requests-using-volley-android/name.jpg
  articles/making-api-requests-using-volley-android/postman.jpg
Labels: assigned for review, ready for final review

#620 Implementing MVVM architecture in android using Kotlin
  articles/implementing-mvvm-architecture-in-android-using-kotlin/getting-started.png
  articles/implementing-mvvm-architecture-in-android-using-kotlin/hero.jpg
  articles/implementing-mvvm-architecture-in-android-using-kotlin/index.md
  articles/implementing-mvvm-architecture-in-android-using-kotlin/result.png
  authors/wanja-mike/avatar.png
  authors/wanja-mike/index.md
Labels: good first article, ready for final review

#551 Android recyclerviews
  articles/android-recyclerviews/hero.jpg
  articles/android-recyclerviews/index.md
  articles/android-recyclerviews/item.png
  articles/android-recyclerviews/recyclerview.jpg
Labels: ready for final review

#657 Machine Teaching to Improve Artificial Intelligence
  articles/machine-teaching-to-improve-ai/hero.jpg
  articles/machine-teaching-to-improve-ai/index.md
Labels: ready for final review

#641 A Brief Guide to Wireless Mobile Networking
  articles/wireless-mobile-networking/hero.jpg
  articles/wireless-mobile-networking/index.md
Labels: enhancement

#552 What is Ransomware?
  articles/what-is-ransomware/hero.jpg
  articles/what-is-ransomware/index.md
  authors/maitreyi-karanjkar/avatar.jpg
  authors/maitreyi-karanjkar/index.md
Labels: assigned for review, revisions needed

#642 Clustering in Unsupervised Machine Learning
  articles/clustering-in-unsupervised-ml/cluster-inertia.png
  articles/clustering-in-unsupervised-ml/dbscan-clustering.jpg
  articles/clustering-in-unsupervised-ml/gaussian-mixture-model.png
  articles/clustering-in-unsupervised-ml/hero.jpg
  articles/clustering-in-unsupervised-ml/hierarchical-clustering-dendrogram.png
  articles/clustering-in-unsupervised-ml/illustration-of-clustering.png
  articles/clustering-in-unsupervised-ml/index.md
  articles/clustering-in-unsupervised-ml/k-mean-algorithm.jpg
  articles/clustering-in-unsupervised-ml/squared-euclidean-distance.png
Labels: ready for final review

#636 Securing Artificial Intelligence from Adversaries
  articles/securing-ai-systems-from-adversaries/boundary.png
  articles/securing-ai-systems-from-adversaries/hero.jpg
  articles/securing-ai-systems-from-adversaries/index.md
  articles/securing-ai-systems-from-adversaries/matrix.jpg
  articles/securing-ai-systems-from-adversaries/miscategorization.png
Labels: ready for final review

#630 How Does Cryptocurrency Mining Work?
  articles/how-crypto-mining-works/hashingexampe.PNG
  articles/how-crypto-mining-works/hero.jpg
  articles/how-crypto-mining-works/index.md
  articles/how-crypto-mining-works/merkle-tree.jpg
Labels: ready for final review

#587 Breaking Down Kafka vs. Pulsar
  articles/breaking-down-kafka-vs-pulsar/hero.jpg
  articles/breaking-down-kafka-vs-pulsar/index.md
Labels: ready for final review

#607 How to build a GraphQL Server Using Node.js
  articles/build-a-graphql-server-using-nodejs/express-init-browser.png
  articles/build-a-graphql-server-using-nodejs/express-init-terminal.png
  articles/build-a-graphql-server-using-nodejs/express-init.png
  articles/build-a-graphql-server-using-nodejs/graphql-docs.png
  articles/build-a-graphql-server-using-nodejs/graphql-init-2.png
  articles/build-a-graphql-server-using-nodejs/graphql-init-query.png
  articles/build-a-graphql-server-using-nodejs/graphql-init.png
  articles/build-a-graphql-server-using-nodejs/graphql-mongo-connect.png
  articles/build-a-graphql-server-using-nodejs/graphql-mongo-mutation.png
  articles/build-a-graphql-server-using-nodejs/graphql-query-browser.png
  articles/build-a-graphql-server-using-nodejs/graphql-query.png
  articles/build-a-graphql-server-using-nodejs/hero.jpg
  articles/build-a-graphql-server-using-nodejs/index.md
Labels: preliminary revision in progress

#594 Building a documentation site from scratch using Hugo
  articles/documentation-website-hugo/hero.jpg
  articles/documentation-website-hugo/index.md
  articles/documentation-website-hugo/website.png
  authors/quadri-sheriff/avatar.jpg
  authors/quadri-sheriff/index.md
Labels: good first article, needs author page, ready for final review

#582 Create React CLI applications
  articles/create-react-cli/first-1.png
  articles/create-react-cli/hero.jpg
  articles/create-react-cli/index.md
  articles/create-react-cli/section-final.png
Labels: assigned for review, needs front matter, ready for final review

#627 Android ViewPager2 With TabLayout
  articles/android-viewpager2/app-name.png
  articles/android-viewpager2/hero.jpg
  articles/android-viewpager2/index.md
  articles/android-viewpager2/tab-layout.gif
  articles/android-viewpager2/toasts.gif
  articles/android-viewpager2/vertical-scroll.gif
  articles/android-viewpager2/view-pager.gif
Labels: assigned for review, ready for final review

#632 Logging with Winston (Node.js)
  articles/logging-with-winston/hero.jpg
  articles/logging-with-winston/index.md
  articles/logging-with-winston/log-file.png
  articles/logging-with-winston/mongo-db-transport.png
  articles/logging-with-winston/project-structure.png
Labels: assigned for review, ready for final review, tiered payout

#629 How to build a static site with GatsbyJS
  articles/how-to-build-astatic-site-with-gatsbyjs/hero.png
  articles/how-to-build-astatic-site-with-gatsbyjs/index.md
Labels: assigned for review, tiered payout

#666 Secured Deep Learning in Remote Devices
  articles/secured-deeplearning-in-remote-devices/Introduction_to_federated_learning.png
  articles/secured-deeplearning-in-remote-devices/hero.jpg
  articles/secured-deeplearning-in-remote-devices/index.md
Labels: needs front matter, ready for final review

#613 House Price Prediction using Machine Learning
  articles/house-price-prediction/hero.jpg
  articles/house-price-prediction/index.md
Labels: assigned for review, ready for final review

#615 Creating Word Clouds in Python
  articles/word-cloud/hero.jpg
  articles/word-cloud/index.md
  articles/word-cloud/output.jpg
Labels: assigned for review, ready for final review

#603 React Native Livestream Application using Agora
  articles/react-native-agora-livestreaming-app/agora_dashboard.png
  articles/react-native-agora-livestreaming-app/agora_new_project.png
  articles/react-native-agora-livestreaming-app/agora_project_management_console.png
  articles/react-native-agora-livestreaming-app/hero.jpg
  articles/react-native-agora-livestreaming-app/homescreen.jpeg
  articles/react-native-agora-livestreaming-app/index.md
  articles/react-native-agora-livestreaming-app/loading_screen.gif
  authors/mohan-raj/avatar.jpg
  authors/mohan-raj/index.md
Labels: assigned for review, good first article, preliminary revision in progress

#635 Dive into Batch scripting language
  articles/dive-into-batch-scripting-language/1.PNG
  articles/dive-into-batch-scripting-language/hero.png
  articles/dive-into-batch-scripting-language/index.md
  authors/ahmad-mardeni/index.md
Labels: assigned for review, needs front matter, revisions needed

#640 User Interface Animation with Anime.js
  articles/user-interface-animation-with-anime.js/hero.jpg
  articles/user-interface-animation-with-anime.js/index.md
  articles/user-interface-animation-with-anime.js/keyframes-animation.gif
  articles/user-interface-animation-with-anime.js/pendulum-animation.gif
  articles/user-interface-animation-with-anime.js/shape-animation.gif
  articles/user-interface-animation-with-anime.js/svg-path-animation.gif
  articles/user-interface-animation-with-anime.js/text-path-animation.gif
Labels: assigned for review, ready for final review

#658 Linear Discriminant Analysis from Scratch
  articles/linear-discriminant-analysis/hero.jpg
  articles/linear-discriminant-analysis/index.md
  articles/linear-discriminant-analysis/lda.png
  articles/linear-discriminant-analysis/output.jpg
  articles/linear-discriminant-analysis/spiral_data.gif
Labels: assigned for review, needs front matter, ready for final review

#685 Forward and Backward Chaining in Artificial Intelligence
  articles/forward-and-backward-chaining-in-ai/backward-chaining.jpg
  articles/forward-and-backward-chaining-in-ai/expert-system.jpg
  articles/forward-and-backward-chaining-in-ai/forward-chaining.jpg
  articles/forward-and-backward-chaining-in-ai/hero.jpg
  articles/forward-and-backward-chaining-in-ai/index.md
Labels: needs front matter, ready for final review

#689 Article - Tuple Data Structure in Python
  articles/tuples-data-structure-python/hero.jpg
  articles/tuples-data-structure-python/index.md
  articles/tuples-data-structure-python/tuple-negative-index.png
  articles/tuples-data-structure-python/tuple-positive-index.png
  articles/tuples-data-structure-python/tuples-performance.png
Labels: needs front matter, ready for final review

#675 Evaluating Machine Learning Model Performance
  articles/evaluating-ml-model-performance/confusion.png
  articles/evaluating-ml-model-performance/fscore.jpg
  articles/evaluating-ml-model-performance/hero.jpg
  articles/evaluating-ml-model-performance/index.md
  articles/evaluating-ml-model-performance/mae.jpg
  articles/evaluating-ml-model-performance/mse.jpg
  articles/evaluating-ml-model-performance/precisionrecall.png
Labels: needs front matter, ready for final review

#687 Deciding between Cloud Spanner and Microsoft Cosmos DB
  articles/deciding-between-cloud-spanner-and-microsoft-cosmos-db/cosmos-db-regions.jpg
  articles/deciding-between-cloud-spanner-and-microsoft-cosmos-db/gcp-regions-and-zones.jpg
  articles/deciding-between-cloud-spanner-and-microsoft-cosmos-db/hero.jpg
  articles/deciding-between-cloud-spanner-and-microsoft-cosmos-db/index.md
Labels: needs front matter, ready for final review

#709 How to Implement MLOps
  articles/how-to-implement-mlops/hero.jpg
  articles/how-to-implement-mlops/index.md
Labels: needs front matter, ready for final review

#712 Tips and Tricks for Deep Learning
  articles/tips-and-tricks-for-deep-learning/batch-normalization.PNG
  articles/tips-and-tricks-for-deep-learning/before-after-dropout.PNG
  articles/tips-and-tricks-for-deep-learning/color-shifted-image.jpg
  articles/tips-and-tricks-for-deep-learning/contrast-changed-image.jpg
  articles/tips-and-tricks-for-deep-learning/convergence.PNG
  articles/tips-and-tricks-for-deep-learning/cropped-image.jpg
  articles/tips-and-tricks-for-deep-learning/dropout.PNG
  articles/tips-and-tricks-for-deep-learning/early-stopping.PNG
  articles/tips-and-tricks-for-deep-learning/flip-image.jpg
  articles/tips-and-tricks-for-deep-learning/hero.jpg
  articles/tips-and-tricks-for-deep-learning/index.md
  articles/tips-and-tricks-for-deep-learning/large-tl.PNG
  articles/tips-and-tricks-for-deep-learning/medium-tl.PNG
  articles/tips-and-tricks-for-deep-learning/noisy-image.jpg
  articles/tips-and-tricks-for-deep-learning/original-image.jpg
  articles/tips-and-tricks-for-deep-learning/rotate-image.jpg
  articles/tips-and-tricks-for-deep-learning/small-tl.PNG
Labels: needs front matter, ready for final review

#731 Robotic Process Automation (RPA) Use Cases in the Healthcare Industry
  articles/robotic-process-automation-use-cases-in-the-healthcare-industry/hero.jpg
  articles/robotic-process-automation-use-cases-in-the-healthcare-industry/index.md
Labels: needs front matter, ready for final review

#740 Correcting Dataset Shift in Machine Learning
  articles/correcting-data-shift/covariate.png
  articles/correcting-data-shift/covariate2.png
  articles/correcting-data-shift/hero.jpg
  articles/correcting-data-shift/index.md
  articles/correcting-data-shift/prior2.png
Labels: needs front matter, ready for final review
