Repository section-engineering-education/engineering-education, pull requests merged in 2020-09, with the labels that each got.

#266 How to Build and Test a Node.js REST API
  articles/building-a-basic-api-with-nodejs/hero.jpg
  articles/building-a-basic-api-with-nodejs/index.md
  articles/building-a-basic-api-with-nodejs/postman_testing.png
Labels: assigned for review, ready for final review

#271 Pointers in C
  articles/pointers-in-c/hero.jpg
  articles/pointers-in-c/index.md
  authors/nimra-aftab/avatar.jpg
  authors/nimra-aftab/index.md
Labels: assigned for review, ready for final review

#276 Abi article
  articles/what-is-an-abi/hero.jpg
  articles/what-is-an-abi/image1.png
  articles/what-is-an-abi/index.md
  articles/what-is-an-abi/table1.JPG
  articles/what-is-an-abi/table2.JPG
  authors/zack-jorquera/index.md
Labels: assigned for review, ready for final review

#265 Debug a node app using Chrome DevTools
  articles/debug-node-devtools/add-to-localhost.gif
  articles/debug-node-devtools/hero.jpg
  articles/debug-node-devtools/index.md
  articles/debug-node-devtools/inspect.jpg
  articles/debug-node-devtools/launch-js-console.gif
  articles/debug-node-devtools/node-devtools-breakpoints.jpg
  articles/debug-node-devtools/node-devtools-debug-started.jpg
  articles/debug-node-devtools/node-devtools.jpg
  articles/debug-node-devtools/open-dev-tools.gif
Labels: assigned for review, tech review

#278 Functions in C++
  articles/functions-in-cpp/hero.jpg
  articles/functions-in-cpp/index.md
Labels: ready for final review

#285 Developer's Guide to Search Engine Optimization
  articles/web-developers-guide-seo/hero.jpg
  articles/web-developers-guide-seo/index.md
  articles/web-developers-guide-seo/opengraph.jpg
  articles/web-developers-guide-seo/twittercards.jpg
Labels: ready for final review

#291 [Link Update] Getting to Grips with APIs Part 1
  articles/simple-guide-to-using-apis-nodejs/index.md
Labels: article update

#293 Article - Customize CSS using Bulma
  articles/customization-using-bulma/buttons-font.png
  articles/customization-using-bulma/buttons-themed.png
  articles/customization-using-bulma/buttons.png
  articles/customization-using-bulma/card.png
  articles/customization-using-bulma/hero.jpg
  articles/customization-using-bulma/index.md
  articles/customization-using-bulma/three-column-uneven.png
  articles/customization-using-bulma/three-column.png
Labels: assigned for review, ready for final review

#275 Introduction to koa.js
  articles/introduction-to-koa.js/hero.jpg
  articles/introduction-to-koa.js/index.md
Labels: ready for final review

#280 Building a nodejs app with Docker
  articles/building-a-nodejs-application-using-docker/hero.jpg
  articles/building-a-nodejs-application-using-docker/index.md
Labels: assigned for review, needs front matter, ready for final review

#292 Huffman Coding
  articles/huffman-coding-in-python/Code_Output.jpg
  articles/huffman-coding-in-python/hero.jpg
  articles/huffman-coding-in-python/index.md
  articles/huffman-coding-in-python/optimaltree.jpg
Labels: help wanted, ready for final review

#269 Integrating Stripe with React
  articles/stripe-integration-react/api_test_keys.jpg
  articles/stripe-integration-react/dashboard.jpg
  articles/stripe-integration-react/final_output.jpg
  articles/stripe-integration-react/hero.jpg
  articles/stripe-integration-react/index.md
  articles/stripe-integration-react/paymentflow.jpg
  articles/stripe-integration-react/paywithcard.jpg
Labels: revisions needed

#272 Most Useful Node.js Packages
  articles/most-useful-nodejs-packages/hero.jpg
  articles/most-useful-nodejs-packages/index.md
Labels: assigned for review, help wanted, tech review

#295 How to Optimize WordPress Website Speed
  articles/how-to-optimize-wordpress-website-speed/hero.jpg
  articles/how-to-optimize-wordpress-website-speed/index.md
  articles/how-to-optimize-wordpress-website-speed/wordpress-post-revisions-screenshot.jpeg
  articles/how-to-optimize-wordpress-website-speed/wp-config.php-edit.jpg
  articles/how-to-optimize-wordpress-website-speed/wp-optimize-database-optimization.jpeg
  articles/how-to-optimize-wordpress-website-speed/wp-optimize-post-revisions-cleanup.jpeg
  authors/benson-kariuki/avatar.jpeg
  authors/benson-kariuki/index.md
Labels: assigned for review, good first article, needs front matter, ready for final review

#298 Article - Node.js vs Nuxt: The Key Differences
  articles/node-vs-nuxt/create-nuxt-app.png
  articles/node-vs-nuxt/csr.png
  articles/node-vs-nuxt/hello-node.png
  articles/node-vs-nuxt/hero.jpg
  articles/node-vs-nuxt/index.md
  articles/node-vs-nuxt/node-emoji.png
  articles/node-vs-nuxt/npm-run-dev.png
  articles/node-vs-nuxt/nuxt-app.png
  articles/node-vs-nuxt/ssr.png
Labels: assigned for review, ready for final review

#264 Bloom Filters: An Introduction
  articles/bloom-filters-data-structure/hashingProblem.jpg
  articles/bloom-filters-data-structure/hero.jpg
  articles/bloom-filters-data-structure/index.md
  articles/bloom-filters-data-structure/membership.jpg
Labels: assigned for review, tech review

#297 Debug a Node Js app running in Docker
  articles/debug-node-docker/attach-to-node-docker.gif
  articles/debug-node-docker/build-docker-image.jpg
  articles/debug-node-docker/docker-extension.jpg
  articles/debug-node-docker/enable-auto-attach.jpg
  articles/debug-node-docker/hero.jpg
  articles/debug-node-docker/index.md
  articles/debug-node-docker/set-breakpoints-vscode.jpg
  articles/debug-node-docker/start-debug.gif
  authors/geoffrey-mungai/avatar.jpg
  authors/geoffrey-mungai/index.md
Labels: assigned for review, tech review

#288 Node rxjs
  articles/node-rxjs/hero.jpg
  articles/node-rxjs/index.md
  articles/node-rxjs/rx-observer.png
Labels: ready for final review

#306 Using Macros
  articles/macros/hero.jpg
  articles/macros/index.md
Labels: assigned for review, ready for review

#286 nmp registry, open-source packages, and code security using npm@6
  articles/npm-registry-opensource-code-security-with-npm6/concerned-experien-based.png
  articles/npm-registry-opensource-code-security-with-npm6/hero.jpg
  articles/npm-registry-opensource-code-security-with-npm6/index.md
  articles/npm-registry-opensource-code-security-with-npm6/least-most-experienced.png
  articles/npm-registry-opensource-code-security-with-npm6/level-of-experience.png
  articles/npm-registry-opensource-code-security-with-npm6/npm-influnce-statistics.png
  articles/npm-registry-opensource-code-security-with-npm6/npx.gif
  articles/npm-registry-opensource-code-security-with-npm6/opensource-downcode.png
  articles/npm-registry-opensource-code-security-with-npm6/oss-noncerned.png
  articles/npm-registry-opensource-code-security-with-npm6/overall-concerned.png
  articles/npm-registry-opensource-code-security-with-npm6/package-lockfile.png
  articles/npm-registry-opensource-code-security-with-npm6/popular-languages.PNG
  articles/npm-registry-opensource-code-security-with-npm6/satisfied.png
  articles/npm-registry-opensource-code-security-with-npm6/weekly-downloads.jpg
Labels: assigned for review, tech review

#270 Article on the Blockchain as a revolution in healthcare
  articles/blockchain-as-a-revolution-in-healthcare/Blockchain-ledger.png
  articles/blockchain-as-a-revolution-in-healthcare/hero.jpg
  articles/blockchain-as-a-revolution-in-healthcare/index.md
Labels: assigned for review, preliminary revision in progress

#308 Article - Binary Tree: Python Data Structures, Part 6 ⚡
  articles/binary-tree-data-structure-python/binarytree.png
  articles/binary-tree-data-structure-python/hero.jpg
  articles/binary-tree-data-structure-python/index.md
Labels: assigned for review, tech review

#290 ARM vs x86: Explained
  articles/arm-x86/hero.jpg
  articles/arm-x86/index.md
Labels: assigned for review, revisions needed

#304 Introduction to Robotic Process Automation
  articles/what-is-robotic-process-automation/hero.jpg
  articles/what-is-robotic-process-automation/index.md
Labels: assigned for review, tech review

#279 Book Recommendation System using SparkSQL and MLlib- Spark Part 3
  articles/sparksql-mllibspark-part-3/books_df.png
  articles/sparksql-mllibspark-part-3/distinct.png
  articles/sparksql-mllibspark-part-3/hero.jpg
  articles/sparksql-mllibspark-part-3/index.md
  articles/sparksql-mllibspark-part-3/join.png
  articles/sparksql-mllibspark-part-3/ratings.png
  articles/sparksql-mllibspark-part-3/recommendisbn.png
  articles/sparksql-mllibspark-part-3/select.png
  articles/sparksql-mllibspark-part-3/sql.png
  articles/sparksql-mllibspark-part-3/user-rating.png
Labels: assigned for review, tech review

#302 File Handling in Node.js
  articles/node-file-handling/hero.jpg
  articles/node-file-handling/index.md
Labels: assigned for review, tech review

#283 What is Jenkins
  articles/what-is-jenkins/hero.jpg
  articles/what-is-jenkins/index.md
Labels: assigned for review, revisions needed

#282 Plagiarism Detector Blog Post
  articles/plagiarism-detection/3d-projection-plagarism-blog.jpg
  articles/plagiarism-detection/3d-projection-plagarism-blog.png
  articles/plagiarism-detection/funny.jpg
  articles/plagiarism-detection/hero.jpg
  articles/plagiarism-detection/index.md
  articles/plagiarism-detection/jacard-index.png
  articles/plagiarism-detection/plagarism_blog_post.png
  articles/plagiarism-detection/screenshot1.png
  articles/plagiarism-detection/screenshot2.png
  articles/plagiarism-detection/ven-diagrahm.png
  articles/plagiarism-detection/wiki.png
Labels: ready for final review

#307 Dry manifesto
  articles/dry-manifesto/hero.jpg
  articles/dry-manifesto/index.md
Labels: assigned for review, revisions needed, tech review

#296 How to Sync/update a forked repo from the original repo using Github Web UI and Git and submit your contributions to the project team
  articles/how-to-sync-and-update-a-forked-repo/after-github-signin.png
  articles/how-to-sync-and-update-a-forked-repo/articles-folder.png
  articles/how-to-sync-and-update-a-forked-repo/branch-pull-request.png
  articles/how-to-sync-and-update-a-forked-repo/changes.png
  articles/how-to-sync-and-update-a-forked-repo/cloning-github-window.png
  articles/how-to-sync-and-update-a-forked-repo/cloning-progress.png
  articles/how-to-sync-and-update-a-forked-repo/commit-to-branch.png
  articles/how-to-sync-and-update-a-forked-repo/commits-to-update.png
  articles/how-to-sync-and-update-a-forked-repo/compare-and-pull-request.png
  articles/how-to-sync-and-update-a-forked-repo/compare.png
  articles/how-to-sync-and-update-a-forked-repo/confirm-merge.png
  articles/how-to-sync-and-update-a-forked-repo/create-folder.png
  articles/how-to-sync-and-update-a-forked-repo/create-pull-request.png
  articles/how-to-sync-and-update-a-forked-repo/creating-branch.png
  articles/how-to-sync-and-update-a-forked-repo/current-repo.png
  articles/how-to-sync-and-update-a-forked-repo/done.png
  articles/how-to-sync-and-update-a-forked-repo/editor-opened.png
  articles/how-to-sync-and-update-a-forked-repo/folder-contents.png
  articles/how-to-sync-and-update-a-forked-repo/forked.png
  articles/how-to-sync-and-update-a-forked-repo/forking.png
  articles/how-to-sync-and-update-a-forked-repo/hero.jpg
  articles/how-to-sync-and-update-a-forked-repo/https.png
  articles/how-to-sync-and-update-a-forked-repo/index.md
  articles/how-to-sync-and-update-a-forked-repo/merge-pull-request.png
  articles/how-to-sync-and-update-a-forked-repo/open-editor.png
  articles/how-to-sync-and-update-a-forked-repo/publish-branch.png
  articles/how-to-sync-and-update-a-forked-repo/pull-redirect.png
  articles/how-to-sync-and-update-a-forked-repo/repo-comparison.png
  articles/how-to-sync-and-update-a-forked-repo/ssh.png
  articles/how-to-sync-and-update-a-forked-repo/start-creating-pull-request.png
  articles/how-to-sync-and-update-a-forked-repo/start-github-clone.png
  articles/how-to-sync-and-update-a-forked-repo/switch-to-base.png
  articles/how-to-sync-and-update-a-forked-repo/switch-to-branch.png
  articles/how-to-sync-and-update-a-forked-repo/to-create-branch.png
  articles/how-to-sync-and-update-a-forked-repo/update-to-local-repo.png
Labels: ready for final review, revisions needed

#300 Automated fake news detection
  articles/automated-fake-news-detection/hero.jpg
  articles/automated-fake-news-detection/index.md
  articles/automated-fake-news-detection/misinformation.jpg
  authors/collins-ayuya/avatar.jpg
  authors/collins-ayuya/index.md
Labels: ready for final review

#301 String Manipulation
  articles/string-manipulation/hero.jpg
  articles/string-manipulation/index.md
Labels: ready for final review

#320 Article - Build Two-Dimensional Layouts using CSS Grid 🔥
  articles/css-grid/display-grid.png
  articles/css-grid/grid-areas.png
  articles/css-grid/grid-basic.png
  articles/css-grid/grid-fr.png
  articles/css-grid/grid-sub-child.png
  articles/css-grid/grid-template.png
  articles/css-grid/grid-terminology.png
  articles/css-grid/hero.jpg
  articles/css-grid/image-grid.png
  articles/css-grid/index.md
  articles/css-grid/inline-grid.png
Labels: ready for final review

#289 Industry 4.0 and Cybersecurity
  articles/industry-4.0-and-cybersecurity/hero.jpg
  articles/industry-4.0-and-cybersecurity/index.md
Labels: assigned for review, tech review

#311 Article: ExpressJS
  articles/express/express.png
  articles/express/hero.jpg
  articles/express/index.md
  articles/express/node.png
Labels: assigned for review, ready for final review

#312 Working with Node.js/javascript date and time objects using Moment.js date library
  articles/nodejs-date-and-time-objects-with-moment/github-stats.png
  articles/nodejs-date-and-time-objects-with-moment/hero.png
  articles/nodejs-date-and-time-objects-with-moment/index.md
  articles/nodejs-date-and-time-objects-with-moment/npm-download-insights.png
  articles/nodejs-date-and-time-objects-with-moment/popularity-and-activity.png
  articles/nodejs-date-and-time-objects-with-moment/size.png
Labels: ready for final review

#299 Top 10 in demand technologies to learn
  articles/top-ten-in-demand-technologies-to-learn/hero.jpg
  articles/top-ten-in-demand-technologies-to-learn/index.md
Labels: assigned for review, revisions needed, tech review

#316 Supervised Learning Algorithms
  articles/supervised-learning-algorithms/distance.jpg
  articles/supervised-learning-algorithms/hero.jpg
  articles/supervised-learning-algorithms/index.md
  articles/supervised-learning-algorithms/knnexample.jpg
  articles/supervised-learning-algorithms/svm.jpg
Labels: assigned for review, tech review

#347 Article - Using the Heap Data Structure in Python
  articles/heap-data-structure-python/complete-binary-tree.png
  articles/heap-data-structure-python/hero.jpg
  articles/heap-data-structure-python/index.md
  articles/heap-data-structure-python/level-order-traversal.png
Labels: ready for final review

#309 Hapi vs koa vs express
  articles/hapi-vs-koa-vs-express/hero.jpg
  articles/hapi-vs-koa-vs-express/index.md
Labels: assigned for review, ready for final review

#350 Create and Deploy NPM Packages
  articles/npm-packages/hero.jpg
  articles/npm-packages/index.md
  articles/npm-packages/npm-login.png
  articles/npm-packages/npm-publish.png
  articles/npm-packages/npm-signup.png
  articles/npm-packages/npmjs-homepage.png
  articles/npm-packages/result.png
Labels: assigned for review, ready for final review

#314 File Handling in C++
  articles/file-handling-in-Cpp/hero.jpg
  articles/file-handling-in-Cpp/index.md
Labels: ready for final review

#330 SSH in NodeJs
  articles/ssh-in-nodejs/df.png
  articles/ssh-in-nodejs/hero.jpg
  articles/ssh-in-nodejs/index.md
Labels: assigned for review, ready for final review
