Repository section-engineering-education/engineering-education, pull requests merged in 2020-08, with the labels that each got.

#210 What is anti-maware article
  articles/what-is-anti-virus-software/New_Sheriff_in_Town.jpg
  articles/what-is-anti-virus-software/bandit_arsenal.jpg
  articles/what-is-anti-virus-software/flat-wild-west-background-with-colorful-buildings_23-2147587719.jpg
  articles/what-is-anti-virus-software/hero.jpg
  articles/what-is-anti-virus-software/index.md
  articles/what-is-anti-virus-software/marshal_badges.jpg
  articles/what-is-anti-virus-software/rogue-bandits.jpg
  articles/what-is-anti-virus-software/security_shield.jpg
  articles/what-is-anti-virus-software/virus-protection.jpg
Labels: ready for review, tech review

#168 Article: Introduction To Data Studio
  articles/data-studio/addField.png
  articles/data-studio/connection.png
  articles/data-studio/create.png
  articles/data-studio/datecontrol.png
  articles/data-studio/dropdown.png
  articles/data-studio/flow.png
  articles/data-studio/hero.jpg
  articles/data-studio/index.md
  articles/data-studio/inloss.png
  articles/data-studio/overview.png
  articles/data-studio/sharing.png
  articles/data-studio/sheets.png
  articles/data-studio/source.png
  articles/data-studio/sure.png
  articles/data-studio/totloss.png
Labels: ready for review, tech review

#199 Article : Sentiment Analysis on Tweets
  articles/sentiment-analysis/apply.png
  articles/sentiment-analysis/bar.png
  articles/sentiment-analysis/clean-word.png
  articles/sentiment-analysis/create1.png
  articles/sentiment-analysis/dirty-word.png
  articles/sentiment-analysis/form.png
  articles/sentiment-analysis/hero.jpg
  articles/sentiment-analysis/index.md
  articles/sentiment-analysis/search.png
  articles/sentiment-analysis/tokens.png
Labels: ready for review, tech review

#186 Function Overloading(C++)
  articles/function-overloading/hero.jpg
  articles/function-overloading/index.md
  authors/kanishkvardhan-a-n/avatar.jpg
  authors/kanishkvardhan-a-n/index.md
Labels: ready for review, tech review

#212 Getting to Grips with Databases Part 2
  articles/working-with-databases-part1/index.md
  articles/working-with-databases-part2/hero.jpg
  articles/working-with-databases-part2/index.md
Labels: ready for review, tech review

#169 Introduction to DNA Computing and its applications
  articles/dna-computing/hero.jpg
  articles/dna-computing/image1.png
  articles/dna-computing/index.md
  authors/aditi-jayakumar/avatar.jpg
  authors/aditi-jayakumar/index.md
Labels: ready for review, tech review

#185 Five Obscure but Useful HTML Tags
  articles/obscure-html/details1.png
  articles/obscure-html/details2.png
  articles/obscure-html/hero.jpg
  articles/obscure-html/index.md
Labels: ready for review, tech review

#190 Introduction to Spark - Part 1
  articles/introduction-to-spark/hero.jpg
  articles/introduction-to-spark/index.md
  articles/introduction-to-spark/mapreduce.png
  articles/introduction-to-spark/spark.png
Labels: ready for review, tech review

#195 How to Install a GUI on an Ubuntu Server 18.04 or Easier Remote Management
  articles/install-a-gui-on-an-ubuntu-server-1804/hero.jpg
  articles/install-a-gui-on-an-ubuntu-server-1804/index.md
  authors/gregory-manley/index.md
Labels: ready for review, tech review

#206 keyword extraction in python
  articles/keyword-extraction-in-python/flowchart.png
  articles/keyword-extraction-in-python/hero.jpg
  articles/keyword-extraction-in-python/index.md
Labels: ready for review, tech review

#142 Article: Popular Data Science Libraries in python
  articles/data-science-libraries-python/Index.md
  articles/data-science-libraries-python/cuberoot.png
  articles/data-science-libraries-python/hero.jpg
Labels: ready for review, tech review

#164 Article - Layouts using CSS Flexbox
  articles/css-flexbox/flex-diag.png
  articles/css-flexbox/hero.jpg
  articles/css-flexbox/img-grid.png
  articles/css-flexbox/index.md
Labels: ready for review, tech review

#203 CRAP Design
  articles/crap-design/center_align.jpg
  articles/crap-design/contrast.jpg
  articles/crap-design/hero.jpg
  articles/crap-design/index.md
  articles/crap-design/proximity.jpg
  articles/crap-design/repetition.png
  articles/crap-design/testing_grounds.png
Labels: ready for review, tech review

#167 Golang part 2: programming basics
  articles/golang-part-2-programming-basics/control-flow.jpg
  articles/golang-part-2-programming-basics/go-keywords.png
  articles/golang-part-2-programming-basics/go-run.png
  articles/golang-part-2-programming-basics/hero.jpg
  articles/golang-part-2-programming-basics/index.md
Labels: ready for review, tech review

#208 understanding-socket.io
  articles/understanding-socket.io/hero.jpg
  articles/understanding-socket.io/index.md
  authors/peter-kayere/avatar.png
  authors/peter-kayere/index.md
Labels: ready for review, tech review

#178 An Introduction to WebAssembly - part 2
  articles/introduction-web-assembly-continued/hero.png
  articles/introduction-web-assembly-continued/index.md
  articles/introduction-web-assembly-continued/wasm-example.png
Labels: ready for review, tech review

#170 Article Intro to Webpack
  articles/webpack/hero.jpg
  articles/webpack/index.md
Labels: revisions needed

#179 Article - Web Application Architectures 101
  articles/web-application-architectures-101/csr-ssr.png
  articles/web-application-architectures-101/csr.png
  articles/web-application-architectures-101/hero.jpg
  articles/web-application-architectures-101/index.md
  articles/web-application-architectures-101/iso.png
Labels: revisions needed

#141 Breadth First Search
  articles/breadth-first-search/complex_graph.png
  articles/breadth-first-search/demo2_1.png
  articles/breadth-first-search/demo2_2.png
  articles/breadth-first-search/demo2_3.png
  articles/breadth-first-search/demo2_4.png
  articles/breadth-first-search/demo2_5.png
  articles/breadth-first-search/hero.jpg
  articles/breadth-first-search/index.md
  articles/breadth-first-search/maze.png
  articles/breadth-first-search/normal_graph.png
Labels: ready for review, tech review

#182 Introduction to Kafka
  articles/introduction-to-kafka/hero.jpg
  articles/introduction-to-kafka/index.md
  articles/introduction-to-kafka/kafka-architecture.png
  articles/introduction-to-kafka/publish-subscribe.png
Labels: revisions needed

#215 Article - NodeJS Environment Variables
  articles/nodejs-environment-variables/env-vars.png
  articles/nodejs-environment-variables/hero.jpg
  articles/nodejs-environment-variables/index.md
  articles/nodejs-environment-variables/netlify-dash.png
  articles/nodejs-environment-variables/set-vars.png
Labels: ready for review, tech review

#221 build-outlook-clone-with-react-hooks
  articles/build-an-outlook-clone-using-react-hooks/hero.jpg
  articles/build-an-outlook-clone-using-react-hooks/index.md
Labels: duplicate, preliminary revision in progress

#207 Getting started with pyspark - spark part2
  articles/Getting-started-with-Pyspark-Spark-Part2/filter.png
  articles/Getting-started-with-Pyspark-Spark-Part2/hero.jpg
  articles/Getting-started-with-Pyspark-Spark-Part2/import.png
  articles/Getting-started-with-Pyspark-Spark-Part2/index.md
  articles/Getting-started-with-Pyspark-Spark-Part2/kv.png
  articles/Getting-started-with-Pyspark-Spark-Part2/map.png
  articles/Getting-started-with-Pyspark-Spark-Part2/reducebykey.png
  articles/Getting-started-with-Pyspark-Spark-Part2/sort.png
  articles/Getting-started-with-Pyspark-Spark-Part2/top10.png
Labels: assigned for review, tech review

#192 Introduction to Generative Adversarial Networks
  articles/introduction-to-generative-adversarial-networks/gan-architecture.jpg
  articles/introduction-to-generative-adversarial-networks/hero.jpg
  articles/introduction-to-generative-adversarial-networks/index.md
Labels: assigned for review, ready for review, tech review

#233 Why Node.js is popular among developers
  articles/why-node-js-is-popular/hero.jpg
  articles/why-node-js-is-popular/index.md
  articles/why-node-js-is-popular/stackoverflow1.jpg
  articles/why-node-js-is-popular/stackoverflow2.jpg
  authors/geoffrey-mungai/avatar.jpg
  authors/geoffrey-mungai/index.md
Labels: assigned for review, ready for review

#211 Article: Testing Node.js application
  articles/node-testing/hero.jpg
  articles/node-testing/index.md
  articles/node-testing/mocha1.png
  articles/node-testing/mocha2.png
  articles/node-testing/tdd.png
Labels: assigned for review, revisions needed

#226 Node firebase
  articles/node-firebase/hero.jpg
  articles/node-firebase/index.md
  articles/node-firebase/log.jpg
  articles/node-firebase/socket.jpg
Labels: assigned for review, tech review

#234 Networking Models - Introductory Guide
  articles/networking-models-introductory-guide/hero.jpg
  articles/networking-models-introductory-guide/index.md
  articles/networking-models-introductory-guide/manchester_coding.jpg
  articles/networking-models-introductory-guide/nrz_coding.jpg
Labels: assigned for review, ready for review

#235 Node mailer
  articles/node-mailer/hero.jpg
  articles/node-mailer/index.md
Labels: assigned for review, ready for review

#250 Http requests in nodejs
  articles/http-requests-nodejs/hero.jpg
  articles/http-requests-nodejs/httpmodel.jpg
  articles/http-requests-nodejs/index.md
  articles/http-requests-nodejs/request_message.jpg
Labels: assigned for review, ready for review

#251 Steganography: An Experiment in Python
  articles/steganography-in-python/decrypt.jpg
  articles/steganography-in-python/encrypt.jpg
  articles/steganography-in-python/hero.jpg
  articles/steganography-in-python/index.md
Labels: assigned for review, ready for review

#225 MEAN vs MERN
  articles/mean-vs-mern/hero.jpg
  articles/mean-vs-mern/index.md
Labels: assigned for review, ready for review

#218 Intro to C++ - Part 01
  articles/intro-to-C++-part01/hero.jpg
  articles/intro-to-C++-part01/index.md
Labels: enhancement

#255 debugging node.js using vscode
  articles/debug-nodejs-vscode/configurations.jpg
  articles/debug-nodejs-vscode/hero.jpg
  articles/debug-nodejs-vscode/index.md
  articles/debug-nodejs-vscode/no-configurations.jpg
  articles/debug-nodejs-vscode/nodemon.jpg
  articles/debug-nodejs-vscode/settings.jpg
Labels: assigned for review, ready for review

#230 Article - Node vs Python APIs
  articles/node-vs-python/hero.jpg
  articles/node-vs-python/index.md
Labels: good first issue, revisions needed

#256 What it Takes to be a DevOps Engineer
  articles/what-it-takes-to-be-a-devops-engineer/hero.jpg
  articles/what-it-takes-to-be-a-devops-engineer/index.md
Labels: assigned for review, ready for review

#252 Typescript
  articles/typescript-static-typing/hero.jpg
  articles/typescript-static-typing/index.md
Labels: assigned for review, ready for review

#237 Article - Maintain Code Quality in Node using ESLint
  articles/node-eslint/eslint-error1.png
  articles/node-eslint/eslint-error2.png
  articles/node-eslint/eslint-error3.png
  articles/node-eslint/hero.jpg
  articles/node-eslint/index.md
  articles/node-eslint/vscode-settings.png
Labels: assigned for review, ready for review

#246 Node.js vs Next.js: A React Approach
  articles/node-versus-next-react-approach/csr.jpg
  articles/node-versus-next-react-approach/hero.jpg
  articles/node-versus-next-react-approach/index.md
  articles/node-versus-next-react-approach/ssr.jpg
  articles/node-versus-next-react-approach/ssr_lookup.jpg
Labels: assigned for review, ready for review

#248 History of Nodejs
  articles/history-of-nodejs/hero.jpg
  articles/history-of-nodejs/index.md
  articles/history-of-nodejs/nodejs-use-case-infographic.png
  articles/history-of-nodejs/nodejs-use-cases-cover-image.png
Labels: assigned for review, tech review

#267 Intro to C++ - Part 2 (If Else Loops)
  articles/if-else-loops/hero.jpg
  articles/if-else-loops/index.md
Labels: assigned for review

#263 How to Encrypt Google Drive using Rclone
  articles/encrypting-gdrive-using-rclone/auto-config.png
  articles/encrypting-gdrive-using-rclone/creating-project.png
  articles/encrypting-gdrive-using-rclone/encrypt-remote.png
  articles/encrypting-gdrive-using-rclone/gdrive-access.png
  articles/encrypting-gdrive-using-rclone/gdrive-api.png
  articles/encrypting-gdrive-using-rclone/hero.png
  articles/encrypting-gdrive-using-rclone/index.md
  articles/encrypting-gdrive-using-rclone/oauth-client.png
  articles/encrypting-gdrive-using-rclone/rclone-copy.png
  articles/encrypting-gdrive-using-rclone/storage-providers.png
Labels: assigned for review, ready for review

#268 Getting to Grips with APIs: Authentication
  articles/simple-guide-to-using-apis-part2/final-result.png
  articles/simple-guide-to-using-apis-part2/hero.png
  articles/simple-guide-to-using-apis-part2/index.md
Labels: assigned for review, duplicate, ready for review

#259 10-tips-for-working-with-node.js
  articles/ten-tips-for-working-with-nodejs/hero.jpg
  articles/ten-tips-for-working-with-nodejs/index.md
  articles/ten-tips-for-working-with-nodejs/node.js_error_types.png
  authors/joseph-chege/avatar.jpg
  authors/joseph-chege/index.md
Labels: assigned for review, tech review

#260 Node.js - Frontend or Backend?
  articles/nodejs-frontend-backend/hero.jpg
  articles/nodejs-frontend-backend/index.md
  articles/nodejs-frontend-backend/stackoverflowresults.jpg
Labels: assigned for review, tech review

#261 TCP in Node.js
  articles/tcp-node/hero.jpg
  articles/tcp-node/index.md
Labels: assigned for review, tech review

#216 Discord Bot Using Node.js
  articles/discord-bot-node/discordbot0.png
  articles/discord-bot-node/discordbot1.png
  articles/discord-bot-node/discordbot10.png
  articles/discord-bot-node/discordbot2.png
  articles/discord-bot-node/discordbot3.png
  articles/discord-bot-node/discordbot4.png
  articles/discord-bot-node/discordbot5.png
  articles/discord-bot-node/discordbot6.png
  articles/discord-bot-node/discordbot7.png
  articles/discord-bot-node/discordbot8.png
  articles/discord-bot-node/discordbot9.png
  articles/discord-bot-node/hero.jpg
  articles/discord-bot-node/index.md
Labels: enhancement
