Repository section-engineering-education/engineering-education, pull requests merged in 2020-10, with the labels that each got.

#344 Javascript Dates manipulation with date-fns
  articles/javascript-dates-manipulation-with-date-fns/date-fns.png
  articles/javascript-dates-manipulation-with-date-fns/github-stats.png
  articles/javascript-dates-manipulation-with-date-fns/hero.jpg
  articles/javascript-dates-manipulation-with-date-fns/index.md
  articles/javascript-dates-manipulation-with-date-fns/moment.png
  articles/javascript-dates-manipulation-with-date-fns/npm-download-insights.png
  articles/javascript-dates-manipulation-with-date-fns/popularity-and-activity.png
Labels: assigned for review, ready for final review

#318 Building a blog from scratch using jekyll
  articles/build-a-jekyll-site/hero.jpg
  articles/build-a-jekyll-site/index.md
Labels: assigned for review, ready for final review, tech review

#355 Kotlin extensions
  articles/kotlin-extensions/hero.jpg
  articles/kotlin-extensions/index.md
Labels: assigned for review, tech review

#313 Cloud firestore
  articles/cloud-firestore/hero.jpg
  articles/cloud-firestore/index.md
Labels: enhancement, preliminary revision in progress

#397 Refined upload instructions
  UPLOAD_INSTRUCTIONS.md
Labels: documentation

#334 Mysql query performance optimization tips
  articles/mysql-query-performance-optimization-tips/hero.jpg
  articles/mysql-query-performance-optimization-tips/index.md
  articles/mysql-query-performance-optimization-tips/mysql-cli-query-time-screenshot.jpg
  articles/mysql-query-performance-optimization-tips/mysql-explain-query-screenshot.jpg
  articles/mysql-query-performance-optimization-tips/mysql-workbench-query-time-screenshot.jpg
Labels: revisions needed

#365 Introduction to Scrum
  articles/introduction-to-scrum/burndown-chart-example.jpg
  articles/introduction-to-scrum/hero.jpg
  articles/introduction-to-scrum/index.md
  articles/introduction-to-scrum/scrum_framework.jpg
Labels: enhancement, ready for final review

#325 Performance optimization techniques and tips to speedup Node.js Applications
  articles/performance-optimization-techniques-for-node-js/asynchronous.png
  articles/performance-optimization-techniques-for-node-js/hero.jpg
  articles/performance-optimization-techniques-for-node-js/index.md
  articles/performance-optimization-techniques-for-node-js/synchronous.png
Labels: assigned for review, ready for final review

#346 Why data scientists need to move from jupyter notebooks to scripts
  articles/why-data-scientists-need-to-move-from-jupyter-notebooks-to-scripts/hero.jpg
  articles/why-data-scientists-need-to-move-from-jupyter-notebooks-to-scripts/index.md
  authors/eric-kahuha/avatar.jpg
  authors/eric-kahuha/index.md
Labels: assigned for review, tech review

#315 Understanding Database Architecture and Models
  articles/understanding-dbms/hero.jpg
  articles/understanding-dbms/index.md
Labels: assigned for review, ready for final review

#384 Objects, Arrays and Destructuring in JavaScript
  articles/object-arrays-destructuring/hero.jpg
  articles/object-arrays-destructuring/index.md
Labels: assigned for review, tech review

#356 Golang part 3: Advanced programming concepts
  articles/golang-advanced-programming-concepts/array.png
  articles/golang-advanced-programming-concepts/hero.jpg
  articles/golang-advanced-programming-concepts/index.md
Labels: assigned for review, ready for final review

#416 Handling Bias in Machine Learning
  articles/handling-bias-in-machine-learning/hero.jpg
  articles/handling-bias-in-machine-learning/index.md
Labels: assigned for review, ready for final review

#369 How to fix and prevent SQL injection in WordPress
  articles/how-to-fix-and-prevent-sql-injection-in-wordpress/hero.jpg
  articles/how-to-fix-and-prevent-sql-injection-in-wordpress/index.md
  articles/how-to-fix-and-prevent-sql-injection-in-wordpress/wordpress-core-files.png
  authors/james-kahwai/avatar.jpg
  authors/james-kahwai/index.md
Labels: good first article, tech review

#370 Introducing GPT-3
  articles/introducing-gpt3/hero.jpg
  articles/introducing-gpt3/index.md
Labels: assigned for review, tech review

#377 SQL or NoSQL
  articles/sql-or-nosql-when-to-choose-what/database-admins.jpg
  articles/sql-or-nosql-when-to-choose-what/hero.jpg
  articles/sql-or-nosql-when-to-choose-what/index.md
  articles/sql-or-nosql-when-to-choose-what/most-loved.png
  articles/sql-or-nosql-when-to-choose-what/most-popular.png
  articles/sql-or-nosql-when-to-choose-what/most-wanted.png
  articles/sql-or-nosql-when-to-choose-what/popular-among-professionals.png
  articles/sql-or-nosql-when-to-choose-what/relations.png
  articles/sql-or-nosql-when-to-choose-what/tables.png
Labels: assigned for review, revisions needed, tech review

#393 Introduction to Airflow
  articles/introduction-to-airflow/dag.png
  articles/introduction-to-airflow/hero.jpg
  articles/introduction-to-airflow/index.md
  articles/introduction-to-airflow/pipelines.png
Labels: assigned for review, ready for final review

#428 Data analysis using Pandas
  articles/data-analytics-using-pandas/fifth.png
  articles/data-analytics-using-pandas/first.png
  articles/data-analytics-using-pandas/fourth.png
  articles/data-analytics-using-pandas/hero.jpg
  articles/data-analytics-using-pandas/index.md
  articles/data-analytics-using-pandas/second.png
  articles/data-analytics-using-pandas/seventh.png
  articles/data-analytics-using-pandas/sixth.png
  articles/data-analytics-using-pandas/third.png
Labels: assigned for review, needs front matter, ready for final review

#448 Fix a bug in code snippet in nodejs-enviornment-variables article
  articles/nodejs-environment-variables/index.md
Labels: enhancement

#392 Understanding Node.js Asynchronous Control Flows
  articles/understanding-node-js-async-control-flows/hero.jpg
  articles/understanding-node-js-async-control-flows/index.md
Labels: assigned for review, tech review

#419 Understanding differential privacy
  articles/understanding-differential-privacy/differential_privacy.png
  articles/understanding-differential-privacy/hero.png
  articles/understanding-differential-privacy/index.md
  articles/understanding-differential-privacy/local_global_privacy.png
  authors/srishilesh-p-s/avatar.jpg
  authors/srishilesh-p-s/index.md
Labels: assigned for review, good first article

#453 Job scheduling in node.js
  articles/job-scheduling-in-nodejs/hero.jpg
  articles/job-scheduling-in-nodejs/index.md
Labels: assigned for review, ready for final review

#348 Nginx reverse proxy
  articles/nginx-reverse-proxy/client1.png
  articles/nginx-reverse-proxy/client2.png
  articles/nginx-reverse-proxy/hero.jpg
  articles/nginx-reverse-proxy/http-config.png
  articles/nginx-reverse-proxy/index.md
  articles/nginx-reverse-proxy/reverse_proxy_working.png
  articles/nginx-reverse-proxy/server1.png
  articles/nginx-reverse-proxy/server2.png
  authors/harish-ramesh-babu/avatar.jpg
  authors/harish-ramesh-babu/index.md
Labels: assigned for review, good first article, ready for final review

#400 Google Authentication for Android applications
  articles/google-authentication-for-android/empty.png
  articles/google-authentication-for-android/finalone.jpg
  articles/google-authentication-for-android/finalthree.jpg
  articles/google-authentication-for-android/finaltwo.jpg
  articles/google-authentication-for-android/hero.jpg
  articles/google-authentication-for-android/index.md
  articles/google-authentication-for-android/name.png
  articles/google-authentication-for-android/newproject.png
  articles/google-authentication-for-android/xml.png
  authors/briana-nzivu/avatar.png
  authors/briana-nzivu/index.md
Labels: assigned for review, good first article, ready for final review

#395 Roles in Data Science Industry
  articles/roles-data-science/big_data_tech.jpg
  articles/roles-data-science/hero.jpg
  articles/roles-data-science/index.md
  articles/roles-data-science/self-driving.jpg
  articles/roles-data-science/word_vec.jpg
Labels: assigned for review, tech review

#427 Differences between Artificial Intelligence, Machine Learning and Deep Learning Explained
  articles/differences-between-artificial-intelligence-machine-learning-and-deep-learning/ai-ml-dl.png
  articles/differences-between-artificial-intelligence-machine-learning-and-deep-learning/hero.png
  articles/differences-between-artificial-intelligence-machine-learning-and-deep-learning/index.md
  articles/differences-between-artificial-intelligence-machine-learning-and-deep-learning/neural-networks.png
  authors/willies-ogola/avatar.jpg
  authors/willies-ogola/index.md
Labels: ready for final review

#444 create-a-node-cli
  articles/create-a-nodejs-cli/hero.png
  articles/create-a-nodejs-cli/index.md
  articles/create-a-nodejs-cli/terminal.png
  authors/daniel-katungi/avatar.jpg
  authors/daniel-katungi/index.md
Labels: assigned for review, good first article, ready for final review

#372 Introduction to deep learning
  articles/introduction-to-deep-learning/ai-ml-dl.jpg
  articles/introduction-to-deep-learning/hero.jpg
  articles/introduction-to-deep-learning/index.md
  articles/introduction-to-deep-learning/neural-networks.jpg
Labels: ready for final review

#425 Feature Engineering in Machine Learning
  articles/feature-engineering-in-machine-learning/hero.jpg
  articles/feature-engineering-in-machine-learning/index.md
Labels: ready for final review, ready for review, tech review

#442 Python Database Programming-SQLite
  articles/python-database-programming-sqlite/first-pic.jpg
  articles/python-database-programming-sqlite/hero.png
  articles/python-database-programming-sqlite/index.md
  articles/python-database-programming-sqlite/second-pic.jpg
  authors/ahmad-mardeni/avatar.jpg
  authors/ahmad-mardeni/index.md
Labels: revisions needed

#458 Explainable AI: An Introduction
  articles/explainable-ai/hero.jpg
  articles/explainable-ai/index.md
Labels: ready for final review, tech review

#446 Introduction to Network Types and Topologies
  articles/network-types-topologies/bus.jpg
  articles/network-types-topologies/hero.jpg
  articles/network-types-topologies/index.md
  articles/network-types-topologies/lan.jpg
  articles/network-types-topologies/man.jpg
  articles/network-types-topologies/mesh.jpg
  articles/network-types-topologies/ring.jpg
  articles/network-types-topologies/star.jpg
  articles/network-types-topologies/tree.jpg
  articles/network-types-topologies/wan.jpg
  articles/network-types-topologies/wlan.jpg
Labels: enhancement, preliminary revision in progress

#488 Kotlin collections
  articles/kotlin-collections/hero.png
  articles/kotlin-collections/index.md
Labels: assigned for review, tech review

#496 Functional-Programming in Java Article
  articles/functional-programming-in-java/hero.jpg
  articles/functional-programming-in-java/index.md
  authors/john-amiscaray/avatar.jpg
  authors/john-amiscaray/index.md
Labels: assigned for review, ready for final review

#460 Step by Step Implementation Guide for K-Means Algorithm in R
  articles/k-means-from-scratch-R/hero.jpg
  articles/k-means-from-scratch-R/index.md
  articles/k-means-from-scratch-R/plot1.jpg
  articles/k-means-from-scratch-R/plot2.jpg
  articles/k-means-from-scratch-R/plot3.jpg
  articles/k-means-from-scratch-R/plot4.jpg
Labels: assigned for review, tech review

#466 An Absolute Beginner Guide to Node Package Manager
  articles/beginner-guide-to-npm/globals-path.png
  articles/beginner-guide-to-npm/hero.jpg
  articles/beginner-guide-to-npm/index.md
  articles/beginner-guide-to-npm/node-module.png
  articles/beginner-guide-to-npm/packag-lock-json.png
  articles/beginner-guide-to-npm/package-json.png
Labels: assigned for review, tech review

#510 Tableau vs Power BI
  articles/tableau-vs-power-bi/hero.jpg
  articles/tableau-vs-power-bi/index.md
Labels: needs front matter, ready for final review

#431 Introduction to neural networks
  articles/introduction-to-neural-networks/cnn.png
  articles/introduction-to-neural-networks/fnn.png
  articles/introduction-to-neural-networks/hero.jpg
  articles/introduction-to-neural-networks/index.md
  articles/introduction-to-neural-networks/mnn.png
  articles/introduction-to-neural-networks/neuron.png
  articles/introduction-to-neural-networks/nn.png
  articles/introduction-to-neural-networks/perceptron.png
  articles/introduction-to-neural-networks/rbn.png
  articles/introduction-to-neural-networks/rnn.jpeg
Labels: revisions needed

#507 Android custom views - Extending View class
  articles/android-custom-views-extending-view/app-name.png
  articles/android-custom-views-extending-view/app.png
  articles/android-custom-views-extending-view/hero.jpg
  articles/android-custom-views-extending-view/index.md
  articles/android-custom-views-extending-view/new-class.png
  articles/android-custom-views-extending-view/new-resource-file.png
Labels: assigned for review, ready for final review

#487 5 Real Life Use Cases of Natural Language Processing (NLP)
  articles/five-real-life-use-cases-of-natural-language-processing-nlp/google-autocomplete-and-autocorrect.png
  articles/five-real-life-use-cases-of-natural-language-processing-nlp/grammar-check-using-grammarly.png
  articles/five-real-life-use-cases-of-natural-language-processing-nlp/hero.jpg
  articles/five-real-life-use-cases-of-natural-language-processing-nlp/index.md
  articles/five-real-life-use-cases-of-natural-language-processing-nlp/language-translation-using-deepl-translate.png
  articles/five-real-life-use-cases-of-natural-language-processing-nlp/nlp-vs-nlu-vs-nlg.jpg
Labels: needs front matter, ready for review

#449 Why Julia is Slowly Replacing Python for Machine Learning and Data Science
  articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/hero.jpg
  articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
Labels: enhancement, ready for final review

#426 Kotlin Ranges
  articles/kotlin-ranges/hero.png
  articles/kotlin-ranges/index.md
Labels: assigned for review, tech review

#504 Basics of Transfer Learning
  articles/basics-of-transfer-learning/hero.jpg
  articles/basics-of-transfer-learning/index.md
  articles/basics-of-transfer-learning/strategies.jpg
Labels: ready for final review

#401 Duplicate Branch: Introduction to R Programming
  articles/introduction-to-r/R-Script.jpg
  articles/introduction-to-r/console.jpg
  articles/introduction-to-r/environment.jpg
  articles/introduction-to-r/hero.jpg
  articles/introduction-to-r/image_channel.jpg
  articles/introduction-to-r/index.md
  articles/introduction-to-r/plot.jpg
  articles/introduction-to-r/rstudio.jpg
Labels: preliminary revision in progress

#509 An Introduction to Graph Neural Network
  articles/an-introduction-to-graph-neural-network/CGNN.PNG
  articles/an-introduction-to-graph-neural-network/GAE.PNG
  articles/an-introduction-to-graph-neural-network/STGNN.PNG
  articles/an-introduction-to-graph-neural-network/edges-links.png
  articles/an-introduction-to-graph-neural-network/gnn-structure.PNG
  articles/an-introduction-to-graph-neural-network/hero.jpg
  articles/an-introduction-to-graph-neural-network/image-as-graph.PNG
  articles/an-introduction-to-graph-neural-network/index.md
  articles/an-introduction-to-graph-neural-network/molecule-as-a-graph.PNG
  articles/an-introduction-to-graph-neural-network/social-network.PNG
  articles/an-introduction-to-graph-neural-network/text-to-graphs.PNG
Labels: needs front matter, ready for final review

#512 Bottom navigation bar in Android
  articles/bottom-navigation-bar-in-android/createmenu.jpg
  articles/bottom-navigation-bar-in-android/empty.jpg
  articles/bottom-navigation-bar-in-android/favourites.jpg
  articles/bottom-navigation-bar-in-android/favourites.png
  articles/bottom-navigation-bar-in-android/fragment.jpg
  articles/bottom-navigation-bar-in-android/hero.jpg
  articles/bottom-navigation-bar-in-android/home.jpg
  articles/bottom-navigation-bar-in-android/index.md
  articles/bottom-navigation-bar-in-android/instagram.jpg
  articles/bottom-navigation-bar-in-android/list.jpg
  articles/bottom-navigation-bar-in-android/menu.jpg
  articles/bottom-navigation-bar-in-android/name.jpg
  articles/bottom-navigation-bar-in-android/navgraph.jpg
  articles/bottom-navigation-bar-in-android/profile.jpg
  articles/bottom-navigation-bar-in-android/progress.gif
  articles/bottom-navigation-bar-in-android/search.jpg
  articles/bottom-navigation-bar-in-android/start.jpg
  articles/bottom-navigation-bar-in-android/structure.jpg
  articles/bottom-navigation-bar-in-android/twitter.jpg
  articles/bottom-navigation-bar-in-android/vector.jpg
  articles/bottom-navigation-bar-in-android/youtube.jpg
Labels: assigned for review, needs plagiarism check, ready for final review

#381 Advanced Programming Concepts in R
  articles/advanced-r-concepts/hero.jpg
  articles/advanced-r-concepts/index.md
  authors/lalithnarayan-c/index.md
Labels: enhancement, preliminary revision in progress, revisions needed

#534 What happens when you execute js code
  articles/js-execution-under-the-hood/after_garbage_collection.jpg
  articles/js-execution-under-the-hood/call_stack_add_multiplyBy2.jpg
  articles/js-execution-under-the-hood/call_stack_intro.jpg
  articles/js-execution-under-the-hood/execution_context.png
  articles/js-execution-under-the-hood/global_execution_context_after_executing_js_code.jpg
  articles/js-execution-under-the-hood/global_execution_context_before_executing_js_code.jpg
  articles/js-execution-under-the-hood/hero.jpg
  articles/js-execution-under-the-hood/index.md
  articles/js-execution-under-the-hood/local_execution_context.jpg
  articles/js-execution-under-the-hood/step_one_line_one.jpg
  articles/js-execution-under-the-hood/step_one_line_six.jpg
  articles/js-execution-under-the-hood/step_one_line_two.jpg
Labels: assigned for review, ready for final review

#494 Article - Introduction to Numpy
  articles/introduction-to-numpy/hero.jpg
  articles/introduction-to-numpy/index.md
  articles/introduction-to-numpy/numpyGraph.jpg
  articles/introduction-to-numpy/numpyfunc.jpg
  articles/introduction-to-numpy/vectorized.jpg
  authors/adithi-giridharan/avatar.jpeg
  authors/adithi-giridharan/index.md
Labels: assigned for review, good first article, revisions needed, tech review
