Repository section-engineering-education/engineering-education, pull requests merged in 2020-07, with the labels that each got.

#90 migrating Private block chain
  articles/how-to-build-your-own-private-blockchain/block-model.png
  articles/how-to-build-your-own-private-blockchain/block1.png
  articles/how-to-build-your-own-private-blockchain/block2.png
  articles/how-to-build-your-own-private-blockchain/block3.png
  articles/how-to-build-your-own-private-blockchain/block4.png
  articles/how-to-build-your-own-private-blockchain/block5.png
  articles/how-to-build-your-own-private-blockchain/blockchain-framework.png
  articles/how-to-build-your-own-private-blockchain/hero.jpg
  articles/how-to-build-your-own-private-blockchain/index.md
  authors/jethro-magaji/avatar.jpeg
  authors/jethro-magaji/index.md
Labels: ready for review

#78 Article: Cross-platform applications using electron
  articles/cross-platform-applications-electron/electron-logo.png
  articles/cross-platform-applications-electron/electron-workflow.png
  articles/cross-platform-applications-electron/hero.jpg
  articles/cross-platform-applications-electron/index.md
  articles/cross-platform-applications-electron/node-chrome.png
  articles/cross-platform-applications-electron/popular-electron-apps.png
Labels: ready for review

#92 migrated web assembly article
  articles/introduction-web-assembly/diagram.png
  articles/introduction-web-assembly/example.png
  articles/introduction-web-assembly/hero.jpg
  articles/introduction-web-assembly/index.md
  authors/lucas-gompou/avatar.png
  authors/lucas-gompou/index.md
Labels: ready for review

#95 Assembly Part Two
  articles/assembly-part-1/index.markdown
  articles/assembly-part-2/hero.jpg
  articles/assembly-part-2/index.md
Labels: ready for review

#96 Sorting algorithms
  articles/sorting-algorithms/complexity.png
  articles/sorting-algorithms/counting.jpg
  articles/sorting-algorithms/hero.jpg
  articles/sorting-algorithms/index.md
  articles/sorting-algorithms/insertion1.jpg
  articles/sorting-algorithms/insertion2.jpg
  articles/sorting-algorithms/merge.jpg
  articles/sorting-algorithms/quick.jpg
Labels: ready for review

#99 Kubernetes as a service
  .DS_Store
  articles/kubernetes-as-a-service/amazon-eks-logo-amazon-eks.png
  articles/kubernetes-as-a-service/aws_eks_logo.png
  articles/kubernetes-as-a-service/download.png
  articles/kubernetes-as-a-service/hero.jpg
  articles/kubernetes-as-a-service/image.png
  articles/kubernetes-as-a-service/index.md
Labels: ready for review

#86 How To Setup & SSH into Ubuntu 18.04 server on AWS
  articles/setup-ssh-ubuntu-vm-aws/ami.png
  articles/setup-ssh-ubuntu-vm-aws/configure_security_group.png
  articles/setup-ssh-ubuntu-vm-aws/hero.jpg
  articles/setup-ssh-ubuntu-vm-aws/index.md
  articles/setup-ssh-ubuntu-vm-aws/instance_type.png
  articles/setup-ssh-ubuntu-vm-aws/ip_address.png
  articles/setup-ssh-ubuntu-vm-aws/launch_instance.png
  articles/setup-ssh-ubuntu-vm-aws/terminate_instance.png
  authors/adrian-murage/avatar.jpeg
  authors/adrian-murage/index.md
Labels: tech review

#102 Guide: How to submit your first article on Section.io using Github Desktop & VS Code
  articles/how-to-submit-your-first-article/clone.png
  articles/how-to-submit-your-first-article/commitPR.png
  articles/how-to-submit-your-first-article/createPRdesktop.png
  articles/how-to-submit-your-first-article/createPRfinalgithub.png
  articles/how-to-submit-your-first-article/done.png
  articles/how-to-submit-your-first-article/fork.png
  articles/how-to-submit-your-first-article/fork2.png
  articles/how-to-submit-your-first-article/fork3.png
  articles/how-to-submit-your-first-article/hero.jpg
  articles/how-to-submit-your-first-article/index.md
  articles/how-to-submit-your-first-article/publishPR.png
  articles/how-to-submit-your-first-article/vscode.png
  authors/aman-saxena/index.md
Labels: ready for review

#100 DDoS and Botnets
  articles/ddos-attacks-using-botnets/hero.png
  articles/ddos-attacks-using-botnets/index.md
  articles/ddos-attacks-using-botnets/structuresBotNets.jpg
  articles/ddos-attacks-using-botnets/what-is-a-botnet-and-how-to-protect-yourself-in-2019-1.png.png
Labels: tech review

#112 Chrome Extensions for Dummies
  articles/how-to-build-chrome-extension/chrome-extension-developer-mode-off.png
  articles/how-to-build-chrome-extension/chrome-extension-developer-mode-on.png
  articles/how-to-build-chrome-extension/chrome-extension-toolbar.png
  articles/how-to-build-chrome-extension/hero.jpg
  articles/how-to-build-chrome-extension/index.md
  articles/how-to-build-chrome-extension/popup.png
  articles/how-to-build-chrome-extension/working-popup.png
  authors/ria-thakkar/avatar.jpeg.jpg
  authors/ria-thakkar/index.md
Labels: ready for review

#127 How to Shuffle a List
  articles/shuffle-a-list-algorithm/dressing_room.png
  articles/shuffle-a-list-algorithm/fisher_yates.jpg
  articles/shuffle-a-list-algorithm/hero.jpg
  articles/shuffle-a-list-algorithm/index.md
  articles/shuffle-a-list-algorithm/placeholders.png
  articles/shuffle-a-list-algorithm/swap.jpg
Labels: assigned for review, ready for review

#132 Border Gateway Protocol : Why do we need it and how does it work?
  articles/border-gateway-protocol/BGP.jpg
  articles/border-gateway-protocol/hero.jpg
  articles/border-gateway-protocol/index.md
  authors/shreya-a-n/avatar.jpg
  authors/shreya-a-n/index.md
Labels: assigned for review, ready for review

#137 Article - Serverless APIs in Firebase
  articles/serverless-api-firebase/api-res.png
  articles/serverless-api-firebase/deploy.png
  articles/serverless-api-firebase/firebase-init.png
  articles/serverless-api-firebase/functions-setup.png
  articles/serverless-api-firebase/hero.jpg
  articles/serverless-api-firebase/index.md
  articles/serverless-api-firebase/npm-setup.png
  articles/serverless-api-firebase/project-setup.png
  articles/serverless-api-firebase/serverless.jpeg
Labels: assigned for review, ready for review

#73 New Article: Data Visualization with D3.js
  articles/data-visualization-with-d3js/enter.png
  articles/data-visualization-with-d3js/first.png
  articles/data-visualization-with-d3js/hero.jpg
  articles/data-visualization-with-d3js/index.md
  articles/data-visualization-with-d3js/second.png
  articles/data-visualization-with-d3js/with.gif
  articles/data-visualization-with-d3js/without.gif
Labels: assigned for review, tech review

#135 Article: Github Actions
  articles/github-actions/actions.png
  articles/github-actions/ga4.png
  articles/github-actions/greencheck.png
  articles/github-actions/hero.jpg
  articles/github-actions/index.md
  articles/github-actions/log.png
  articles/github-actions/repo.png
  articles/github-actions/secret.png
Labels: assigned for review, revisions needed

#113 Article: Text Generation With Neural Networks
  articles/text-generation-nn/62.png
  articles/text-generation-nn/63.png
  articles/text-generation-nn/RNN-rolled.png
  articles/text-generation-nn/hero.jpg
  articles/text-generation-nn/index.md
Labels: assigned for review, ready for review

#139 Man in the middle attack Old article
  articles/man-in-the-middle-attack/hero.jpg
  articles/man-in-the-middle-attack/index.md
Labels: ready for review

#111 Google Search Console: An Introduction
  articles/google-search-console-introduction/change-of-address-tool.png
  articles/google-search-console-introduction/google-search-console.jpg
  articles/google-search-console-introduction/hero.png
  articles/google-search-console-introduction/index.md
  articles/google-search-console-introduction/mobile-friendly-pages.png
  articles/google-search-console-introduction/search-traffic.png
  articles/google-search-console-introduction/sitemap-preview.png
Labels: ready for review, revisions needed

#105 migrated knapsack article
  articles/the-knapsack-problem/hero.jpg
  articles/the-knapsack-problem/index.md
  articles/the-knapsack-problem/table-arrows.PNG
  articles/the-knapsack-problem/table-empty.png
Labels: ready for review, revisions needed

#117 How to Create a Professional Email: Setting up GSuite
  articles/creating-professional-email/hero.png
  articles/creating-professional-email/index.md
Labels: assigned for review, ready for review

#130 IT automation using Ansible
  articles/it-automation-using-ansible/create-directory.png
  articles/it-automation-using-ansible/hero.jpg
  articles/it-automation-using-ansible/index.md
  authors/adith-bharadwaj/avatar.jpg
  authors/adith-bharadwaj/index.md
Labels: assigned for review, ready for review

#114 Article - Lists: Python Data Structures, Part-2
  articles/list-data-structure-python/array-mindexpands.png
  articles/list-data-structure-python/hero.jpg
  articles/list-data-structure-python/index.md
  articles/list-data-structure-python/list-vis.png
Labels: ready for review

#119 sitemapping article
  articles/introduction-to-sitemaps/google-search-console-sitemap.png
  articles/introduction-to-sitemaps/hero.jpg
  articles/introduction-to-sitemaps/index.md
  articles/introduction-to-sitemaps/sitemap-generator.png
  authors/gregory-manley/gregory-manley.jpg
Labels: assigned for review, ready for review

#115 Article - Stack: Python Data Structures, Part-3
  articles/stack-data-structure-python/hero.jpg
  articles/stack-data-structure-python/index.md
  articles/stack-data-structure-python/pushpop.png
  articles/stack-data-structure-python/stack-books.jpg
Labels: revisions needed

#133 Tasks to Docs added
  articles/tasks-to-docs/college-work.png
  articles/tasks-to-docs/create-credentials.png
  articles/tasks-to-docs/create-project.png
  articles/tasks-to-docs/enable-api.png
  articles/tasks-to-docs/hero.jpg
  articles/tasks-to-docs/index.md
  articles/tasks-to-docs/my-list.png
  articles/tasks-to-docs/questionary-prompt.png
  articles/tasks-to-docs/select-project.png
  articles/tasks-to-docs/updated-doc.png
Labels: ready for review

#123 Article - Queue: Python Data Structures, Part-4
  articles/queue-data-structure-python/hero.jpg
  articles/queue-data-structure-python/index.md
  articles/queue-data-structure-python/queue.png
Labels: revisions needed

#143 Node authentication api
  articles/node-authentication-api/app-router.png
  articles/node-authentication-api/hero.jpg
  articles/node-authentication-api/index.md
  articles/node-authentication-api/json-token.png
  articles/node-authentication-api/jwt-generate.png
  articles/node-authentication-api/jwt-test.png
  articles/node-authentication-api/login.png
  articles/node-authentication-api/nodemon.png
  articles/node-authentication-api/postman-signup-1.png
  articles/node-authentication-api/route-signup.png
  articles/topic/nodejs.md
  authors/linus-muema/avatar.png
  authors/linus-muema/index.md
Labels: ready for review

#150 Added a docker article
  articles/docker-concepts/Docker-logo.png
  articles/docker-concepts/hero.jpg
  articles/docker-concepts/index.md
Labels: ready for review, tech review

#134 Templating your Static Site Part 1
  articles/templating-your-static-site/eleventy-folder-structure.png
  articles/templating-your-static-site/hero.jpg
  articles/templating-your-static-site/includes-folder.png
  articles/templating-your-static-site/index.md
  articles/templating-your-static-site/netlify-basic-build-settings.png
  articles/templating-your-static-site/netlify-new-site-from-folder.png
Labels: revisions needed

#187 Node MVC Architecture
  articles/node-mvc-architecture/controller-utils.png
  articles/node-mvc-architecture/function-blocks.png
  articles/node-mvc-architecture/hero.jpg
  articles/node-mvc-architecture/index.md
  articles/node-mvc-architecture/mvc-files.png
Labels: ready for review

#118 Article - Reddit Autoposter Telegram Bot
  articles/telegram-bot-python/botsuccess.png
  articles/telegram-bot-python/botusername.png
  articles/telegram-bot-python/hero.jpg
  articles/telegram-bot-python/herokudash.png
  articles/telegram-bot-python/index.md
  articles/telegram-bot-python/newbot.png
  articles/telegram-bot-python/redditcreds.png
Labels: assigned for review, ready for review

#173 Add Raising Exception article
  .DS_Store
  articles/raising-exceptions/hero.jpg
  articles/raising-exceptions/index.md
Labels: ready for review

#160 Golang part 1: Introduction
  articles/golang-part-1-introduction/go-downloads.png
  articles/golang-part-1-introduction/go-version.png
  articles/golang-part-1-introduction/hello-world-go.png
  articles/golang-part-1-introduction/hero.jpg
  articles/golang-part-1-introduction/index.md
Labels: ready for review, tech review

#158 Setting Up Own Login vs Login via External Services
  articles/setting-up-own-login-vs-login-via-external-services/hacker-stealing-representation.jpg
  articles/setting-up-own-login-vs-login-via-external-services/hero.jpg
  articles/setting-up-own-login-vs-login-via-external-services/index.md
  authors/abel-mathew/avatar.jpg
  authors/abel-mathew/index.md
Labels: ready for review

#144 Introduction to MPLS and MPLS VPN technology
  articles/introduction-to-mpls-and-mpls-vpn-technology/hero.jpg
  articles/introduction-to-mpls-and-mpls-vpn-technology/index.md
  articles/introduction-to-mpls-and-mpls-vpn-technology/mpls.jpg
  articles/introduction-to-mpls-and-mpls-vpn-technology/mplsHeader.jpg
  articles/introduction-to-mpls-and-mpls-vpn-technology/mplsVPN.jpg
Labels: ready for review, tech review

#140 Article: Machine learning on edge with r pi and tf lite
  articles/edge-tf-lite/doginput.png
  articles/edge-tf-lite/dogoutput.png
  articles/edge-tf-lite/edge.png
  articles/edge-tf-lite/hero.jpg
  articles/edge-tf-lite/index.md
  articles/edge-tf-lite/logo.png
  articles/edge-tf-lite/steps.png
  articles/edge-tf-lite/traditional.png
Labels: ready for review, tech review

#166 A Simple Guide to Using APIs with Node.js and EJS
  articles/simple-guide-to-using-apis-nodejs/hero.jpg
  articles/simple-guide-to-using-apis-nodejs/index.md
Labels: ready for review, tech review

#147 Iot and cloud computing security threats
  articles/iot-and-cloud-computing-security-threats/hero.jpg
  articles/iot-and-cloud-computing-security-threats/index.md
  authors/judy-nduati/avatar.jpg
  authors/judy-nduati/index.md
Labels: ready for review, tech review

#152 Guide: How to Create Your First Mock Server
  articles/guide-to-create-mock-server/hero.jpg
  articles/guide-to-create-mock-server/image00.png
  articles/guide-to-create-mock-server/image01.png
  articles/guide-to-create-mock-server/image1.png
  articles/guide-to-create-mock-server/image2.png
  articles/guide-to-create-mock-server/image3.png
  articles/guide-to-create-mock-server/image4.png
  articles/guide-to-create-mock-server/image5.png
  articles/guide-to-create-mock-server/image6.png
  articles/guide-to-create-mock-server/image7.png
  articles/guide-to-create-mock-server/index.md
Labels: ready for review, tech review

#153 Managing the Heap in C
  articles/managing-heap/hero.jpg
  articles/managing-heap/index.md
Labels: ready for review, tech review

#165 Build Outlook Clone Using React
  articles/build-an-outlook-clone-using-react/Lifecycle-Methods.png
  articles/build-an-outlook-clone-using-react/hero.jpg
  articles/build-an-outlook-clone-using-react/index.md
  authors/lalithnarayan-c/avatar.jpg
  authors/lalithnarayan-c/index.md
Labels: ready for review
