Repository section-engineering-education/engineering-education, pull requests merged in 2021-11, with the labels that each got.

#4193 Php bulk operations
  content/articles/php-bulk-operations/hero.jpg
  content/articles/php-bulk-operations/index.md
  content/articles/php-bulk-operations/interface.png
  content/articles/php-bulk-operations/pdf-export.png
Labels: assigned for review, ready for final review, tech tutorial

#4141 Building a Deep Learning Web App using Python
  content/articles/building-a-deep-learning-selfie-segmentation-web-app-using-gradio/hero.png
  content/articles/building-a-deep-learning-selfie-segmentation-web-app-using-gradio/index.md
  content/authors/lilian-cheptoo/avatar.png
  content/authors/lilian-cheptoo/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4208 How to run Contentful CMS as Headless with Next.js
  content/articles/how-to-run-contentful-cms-as-headless-with-nextjs/final-post-page.png
  content/articles/how-to-run-contentful-cms-as-headless-with-nextjs/hero.png
  content/articles/how-to-run-contentful-cms-as-headless-with-nextjs/home-page.png
  content/articles/how-to-run-contentful-cms-as-headless-with-nextjs/index.md
  content/articles/how-to-run-contentful-cms-as-headless-with-nextjs/initial-post-page.png
  content/articles/how-to-run-contentful-cms-as-headless-with-nextjs/post-page-with-description.png
Labels: assigned for review, ready for final review, tech tutorial

#4165 Work on Data Streams in a Quarkus project using Reactive Streams Operator
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/async-display.png
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/folder-structure.png
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/hero.png
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/index.md
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/new-quarkus-project-dependencies.png
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/new-quarkus-project.png
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/quarkus-dependencies.png
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/quick-quarkus-class-run.png
  content/articles/data-streams-in-quarkus-using-reactive-streams-operator/reload-project.png
Labels: assigned for review, ready for final review

#4187 How to Create a Carousel Using React Class Components and Tailwind CSS
  content/articles/how-to-create-a-carousel-using-react-class-components-and-tailwind-css/hero.jpg
  content/articles/how-to-create-a-carousel-using-react-class-components-and-tailwind-css/index.md
Labels: ready for final review

#4222 Creating a progress bar for the terminal/console using Python
  content/articles/terminal-progress-bar-python/hero.jpg
  content/articles/terminal-progress-bar-python/index.md
Labels: assigned for review, ready for final review

#4220 Getting started with Spring Boot microservices with Redis
  content/articles/spring-boot-redis/hero.jpg
  content/articles/spring-boot-redis/index.md
  content/articles/spring-boot-redis/publisher.png
  content/articles/spring-boot-redis/subscriber.png
Labels: assigned for review, ready for final review

#4761 Removed unused issue templates
  .github/ISSUE_TEMPLATE/how-to-guide-template.md
  .github/ISSUE_TEMPLATE/software-review-template.md
  .github/ISSUE_TEMPLATE/tutorials-format-template.md
  .github/how-to-guide-template.md
  .github/pull_request_template.md
  .github/software-review-template.md
  .github/tutorial-template.md
Labels: enhancement

#4244 Using Amazon S3 for Django Media File Uploads and Storage
  content/articles/using-amazon-web-service-for-django-media-files-storage/aws-console.jpg
  content/articles/using-amazon-web-service-for-django-media-files-storage/aws-keys.jpg
  content/articles/using-amazon-web-service-for-django-media-files-storage/aws-landingpage.jpg
  content/articles/using-amazon-web-service-for-django-media-files-storage/aws-users.jpg
  content/articles/using-amazon-web-service-for-django-media-files-storage/detailsone-aws.jpg
  content/articles/using-amazon-web-service-for-django-media-files-storage/detailstwo-aws.jpg
  content/articles/using-amazon-web-service-for-django-media-files-storage/hero.jpg
  content/articles/using-amazon-web-service-for-django-media-files-storage/index.md
  content/articles/using-amazon-web-service-for-django-media-files-storage/test-application.jpg
Labels: assigned for review, ready for final review, tech tutorial

#4212 How to Plot a Candlestick Chart in Python using the Matplotlib Finance API
  content/articles/how-to-plot-a-candlestick-chart-in-python-using-the-matplotlib-finance-api/btc.png
  content/articles/how-to-plot-a-candlestick-chart-in-python-using-the-matplotlib-finance-api/hero.png
  content/articles/how-to-plot-a-candlestick-chart-in-python-using-the-matplotlib-finance-api/index.md
Labels: ready for final review, tech tutorial

#4227 Java Timer Tasks
  content/articles/java-timer-tasks/commandline.jpg
  content/articles/java-timer-tasks/environ.jpg
  content/articles/java-timer-tasks/hero.jpg
  content/articles/java-timer-tasks/index.md
  content/articles/java-timer-tasks/java.jpg
  content/articles/java-timer-tasks/new.jpg
  content/authors/joseph-ongoma/avatar.jpg
  content/authors/joseph-ongoma/index.md
Labels: assigned for review, ready for final review, tech tutorial, test reviewer assigned

#4289 Real time search with react and laravel
  content/articles/how-to-build-real-time-search-with-react-and-laravel/base-frontend-view.png
  content/articles/how-to-build-real-time-search-with-react-and-laravel/enabling-cache-switch-filter-on-frontend.png
  content/articles/how-to-build-real-time-search-with-react-and-laravel/frontend-architecture.png
  content/articles/how-to-build-real-time-search-with-react-and-laravel/hero.png
  content/articles/how-to-build-real-time-search-with-react-and-laravel/index.md
  content/articles/how-to-build-real-time-search-with-react-and-laravel/initial-query-results.png
  content/articles/how-to-build-real-time-search-with-react-and-laravel/initial-query-with-cache-enabled.png
  content/articles/how-to-build-real-time-search-with-react-and-laravel/no-cache-backend-flow.png
  content/articles/how-to-build-real-time-search-with-react-and-laravel/redis-cache-backend-flow.png
  content/articles/how-to-build-real-time-search-with-react-and-laravel/subsequent-query-with-cache-enabled.png
Labels: ready for final review

#4418 Visualization in Python
  content/articles/visualizing-python-repositories-using-pygal/adding-clickable-links-to-our-graph.jpeg
  content/articles/visualizing-python-repositories-using-pygal/adding-custom-tooltips.png
  content/articles/visualizing-python-repositories-using-pygal/hero.jpg
  content/articles/visualizing-python-repositories-using-pygal/index.md
  content/articles/visualizing-python-repositories-using-pygal/refining.jpeg
  content/articles/visualizing-python-repositories-using-pygal/visualizing.jpeg
  content/authors/duncan-ndegwa/index.md
Labels: duplicate, ready for final review, test reviewer assigned

#4248 Building Data Driven Applications in React
  content/articles/building-data-driven-application-in-react/hero.jpg
  content/articles/building-data-driven-application-in-react/index.md
  content/authors/valentine-gatwiri/index.md
  content/authors/valentine-gatwiri/valentine.jpg
Labels: good first article, assigned for review, ready for final review

#4266 Understanding babel and How it will help you Write JavaScript
  content/articles/understanding-babel-and-how-it-will-help-you-write-javascript/hero.png
  content/articles/understanding-babel-and-how-it-will-help-you-write-javascript/index.md
  content/authors/robert-wanjau/avatar.jpg
  content/authors/robert-wanjau/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4333 Getting started with Apriori algorithm in python
  content/articles/apriori-algorithm-in-python/hero.png
  content/articles/apriori-algorithm-in-python/index.md
  content/articles/apriori-algorithm-in-python/lift.png
  content/articles/apriori-algorithm-in-python/unsorted_output.png
  content/authors/bejamin-naibei/avatar.jpg
  content/authors/bejamin-naibei/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4284 Object Oriented Programming in Python
  content/articles/object-oriented-programming-in-python/hero.jpg
  content/articles/object-oriented-programming-in-python/index.md
  content/authors/joseph-abiola/avatar.jpg
  content/authors/joseph-abiola/index.md
Labels: good first article, ready for final review

#4296 Configuring EIGRP on a CISCO Router
  content/articles/configuring-eigrp/config.jpg
  content/articles/configuring-eigrp/hero.jpg
  content/articles/configuring-eigrp/index.md
  content/articles/configuring-eigrp/topo.png
Labels: assigned for review, ready for final review

#4806 Article update
  content/articles/spring-boot-crud-api/index.md
Labels: article update

#4342 Building a personality test app with python
  content/articles/personality-test-app/avatar.jpg
  content/articles/personality-test-app/index.md
Labels: ready for final review

#4330 Organizing execution of programs using timer object in matlab - (Duplicate of #4047)
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/hero.jpg
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/index.md
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_eight.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_five.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_four.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_nine.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_one.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_seven.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_six.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_ten.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_three.PNG
  content/articles/organizing-execution-of-programs-using-timer-objects-in-matlab/timer_two.PNG
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#4274 Managing Spring Boot database migrations using Flyway database migration tool
  content/articles/spring-boot-flyway-migrations/data.png
  content/articles/spring-boot-flyway-migrations/hero.jpg
  content/articles/spring-boot-flyway-migrations/index.md
  content/articles/spring-boot-flyway-migrations/result.png
  content/articles/spring-boot-flyway-migrations/result_two.png
Labels: ready for final review, tech tutorial

#4288 Building Backend Applications using Astra DB
  content/articles/astradb-nodejs/hero.jpg
  content/articles/astradb-nodejs/image1.png
  content/articles/astradb-nodejs/image10.png
  content/articles/astradb-nodejs/image11.png
  content/articles/astradb-nodejs/image12-delete.png
  content/articles/astradb-nodejs/image2.png
  content/articles/astradb-nodejs/image3.png
  content/articles/astradb-nodejs/image4.png
  content/articles/astradb-nodejs/image5.png
  content/articles/astradb-nodejs/image6.png
  content/articles/astradb-nodejs/image7.png
  content/articles/astradb-nodejs/image8.png
  content/articles/astradb-nodejs/image9.png
  content/articles/astradb-nodejs/index.md
Labels: ready for final review

#4338 Genie slide in jelly and scale pop up notification effects
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/Webpage-framework.png
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/add-default-notification-box-styling.png
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/add-modernizr.custom.js-file.png
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/changing-color-template.png
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/genie-effect-gif.gif
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/hero.png
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/index.md
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/jelly-effect-gif.gif
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/scale-effect-gif.gif
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/slide-in-effect-gif.gif
  content/articles/genie-slide-in-jelly-and-scale-pop-up-notification-effects/style-the-pages.png
  content/authors/prosper-grateful-juma/avatar.jpg
  content/authors/prosper-grateful-juma/index.md
Labels: good first article, ready for final review, tech tutorial

#4348 Deploy flask to gce
  content/articles/deploy-flask-to-gce/activate-shell.jpg
  content/articles/deploy-flask-to-gce/cloud-shell.jpg
  content/articles/deploy-flask-to-gce/create-instance.jpg
  content/articles/deploy-flask-to-gce/deployed.png
  content/articles/deploy-flask-to-gce/hero.png
  content/articles/deploy-flask-to-gce/index.md
  content/articles/deploy-flask-to-gce/instance-conf.jpg
  content/articles/deploy-flask-to-gce/running-instances.jpg
  content/authors/ryan-jonnes/avatar.jpeg
  content/authors/ryan-jonnes/index.md
Labels: ready for final review

#4297 A Beginner Guide to Fullstack Next.js with TypeScript and Firebase Database
  content/articles/introduction-to-nextjs-with-typescript-and-firebase-database/add-todo-form.png
  content/articles/introduction-to-nextjs-with-typescript-and-firebase-database/default-landing-page.png
  content/articles/introduction-to-nextjs-with-typescript-and-firebase-database/hero.png
  content/articles/introduction-to-nextjs-with-typescript-and-firebase-database/index.md
  content/articles/introduction-to-nextjs-with-typescript-and-firebase-database/initial-collection-setup-form.png
  content/articles/introduction-to-nextjs-with-typescript-and-firebase-database/initial-collection.png
  content/articles/introduction-to-nextjs-with-typescript-and-firebase-database/querying-todos.png
  content/articles/introduction-to-nextjs-with-typescript-and-firebase-database/successful-add-todo-form.png
Labels: ready for final review

#4363 Implementation of eigen decomposition orthogonalization and orthonormalization in matlab
  content/articles/eigen-decomposition-orthogonolization-and-orthonormalization-in-matlab/hero.jpeg
  content/articles/eigen-decomposition-orthogonolization-and-orthonormalization-in-matlab/index.md
  content/articles/eigen-decomposition-orthogonolization-and-orthonormalization-in-matlab/matrix_four.jpeg
  content/articles/eigen-decomposition-orthogonolization-and-orthonormalization-in-matlab/matrix_one.jpeg
  content/articles/eigen-decomposition-orthogonolization-and-orthonormalization-in-matlab/matrix_three.jpeg
  content/articles/eigen-decomposition-orthogonolization-and-orthonormalization-in-matlab/matrix_two.jpeg
Labels: ready for final review, tech tutorial

#4372 Getting started with Principal Component Analysis with sklearn in python
  content/articles/principal-components-with-sklearn-in-python/hero.png
  content/articles/principal-components-with-sklearn-in-python/image.png
  content/articles/principal-components-with-sklearn-in-python/index.md
  content/articles/principal-components-with-sklearn-in-python/logistic-test-set.png
  content/authors/nelson-ruto/avatar.jpg
  content/authors/nelson-ruto/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4377 Implementing multiple ViewHolders in Android using Kotlin
  content/articles/implementing-multiple-viewholder-classes-in-android-using-kotlin/hero.png
  content/articles/implementing-multiple-viewholder-classes-in-android-using-kotlin/index.md
  content/articles/implementing-multiple-viewholder-classes-in-android-using-kotlin/item-with-image.png
  content/articles/implementing-multiple-viewholder-classes-in-android-using-kotlin/item-without-image.png
  content/articles/implementing-multiple-viewholder-classes-in-android-using-kotlin/recyclerview-preview.png
  content/articles/implementing-multiple-viewholder-classes-in-android-using-kotlin/test-app.png
Labels: assigned for review, ready for final review, tech tutorial

#4380 API Authentication with Django Knox and Postman Testing
  content/articles/api-authentication-with-django-knox-and-postman-testing/hero.png
  content/articles/api-authentication-with-django-knox-and-postman-testing/index.md
  content/articles/api-authentication-with-django-knox-and-postman-testing/login.png
  content/articles/api-authentication-with-django-knox-and-postman-testing/register.png
Labels: preliminary revision in progress, ready for final review

#4396 Getting Started with Stripe in SpringBoot
  content/articles/stripe-springboot/accept-a-payment.png
  content/articles/stripe-springboot/checkout-form.png
  content/articles/stripe-springboot/hero.jpg
  content/articles/stripe-springboot/index.md
  content/articles/stripe-springboot/payment-form.png
  content/articles/stripe-springboot/project-setup.png
  content/articles/stripe-springboot/stripe-dashboard.png
Labels: assigned for review, ready for final review, tech tutorial

#4367 Valuetuple and valuetuple structure in c#
  content/articles/understanding-valuetuples/hero.jpg
  content/articles/understanding-valuetuples/index.md
  content/authors/michelle-ngei/avatar.jpg
  content/authors/michelle-ngei/index.md
Labels: ready for final review

#4910 [Article update] Moving videos to different account
  content/articles/video-editing-python-moviepy/index.md
Labels: article update

#4401 Getting Started With Alpine.js
  content/articles/getting-started-with-alpinejs/app-design.png
  content/articles/getting-started-with-alpinejs/colorful.png
  content/articles/getting-started-with-alpinejs/completed.png
  content/articles/getting-started-with-alpinejs/dynamic-list.png
  content/articles/getting-started-with-alpinejs/hero.png
  content/articles/getting-started-with-alpinejs/index.md
  content/articles/getting-started-with-alpinejs/starter.png
  content/authors/zubair-idris-aweda/avatar.png
  content/authors/zubair-idris-aweda/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4434 Model Interpretation using LIME
  content/articles/model-interpretation-using-lime/dataset-structure.jpg
  content/articles/model-interpretation-using-lime/explainer-results.jpg
  content/articles/model-interpretation-using-lime/flower-sizes.jpg
  content/articles/model-interpretation-using-lime/hero.jpg
  content/articles/model-interpretation-using-lime/index.md
  content/articles/model-interpretation-using-lime/model-output.jpg
  content/articles/model-interpretation-using-lime/testing-output.jpg
  content/authors/willyngashu/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#4440 Getting started with Data Visualization using P5.js
  content/articles/getting-started-with-data-visualization-using-p5js/a-line-graph.png
  content/articles/getting-started-with-data-visualization-using-p5js/a-rectangular-sketch-explained.png
  content/articles/getting-started-with-data-visualization-using-p5js/a-rectangular-sketch.png
  content/articles/getting-started-with-data-visualization-using-p5js/array-data-graph.png
  content/articles/getting-started-with-data-visualization-using-p5js/create-canvas-background.png
  content/articles/getting-started-with-data-visualization-using-p5js/csv-previewed-data.png
  content/articles/getting-started-with-data-visualization-using-p5js/hero.png
  content/articles/getting-started-with-data-visualization-using-p5js/index.md
  content/articles/getting-started-with-data-visualization-using-p5js/pong-game.png
  content/articles/getting-started-with-data-visualization-using-p5js/visualized-csv-data.png
Labels: assigned for review, ready for final review

#4413 Blockchain as a form of E-voting
  content/articles/blockchain-as-a-form-of-e-voting/hero.jpg
  content/articles/blockchain-as-a-form-of-e-voting/index.md
  content/authors/samuel-santos/avatar.jpg
  content/authors/samuel-santos/index.md
Labels: good first article, assigned for review, ready for final review, article

#4486 Snorkel Python for Labeling Datasets Programmatically
  content/articles/snorkel-python-for-labeling-datasets-programmatically/dataset-snip.jpg
  content/articles/snorkel-python-for-labeling-datasets-programmatically/dataset-structure.jpg
  content/articles/snorkel-python-for-labeling-datasets-programmatically/hero.jpg
  content/articles/snorkel-python-for-labeling-datasets-programmatically/index.md
  content/articles/snorkel-python-for-labeling-datasets-programmatically/loaded-dataset.jpg
  content/articles/snorkel-python-for-labeling-datasets-programmatically/prediction-results.jpg
  content/articles/snorkel-python-for-labeling-datasets-programmatically/shuffled-dataset.jpg
Labels: ready for final review

#4587 Functional Programming with Java Lambda
  content/articles/functional-programming-with-java-lambda/hero.jpg
  content/articles/functional-programming-with-java-lambda/index.md
  content/authors/popoola-tunde/avatar.jpg
  content/authors/popoola-tunde/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#4306 Getting Started With AGM
  content/articles/getting-started-with-agm/api-key.jpg
  content/articles/getting-started-with-agm/hero.png
  content/articles/getting-started-with-agm/index.md
  content/articles/getting-started-with-agm/map.png
Labels: ready for final review, tech tutorial

#4443 Getting started with Gradient descent algorithm in python
  content/articles/gradient-descent-algorithm-in-python/cost-function-plot.png
  content/articles/gradient-descent-algorithm-in-python/cost_function.png
  content/articles/gradient-descent-algorithm-in-python/error.png
  content/articles/gradient-descent-algorithm-in-python/hero.png
  content/articles/gradient-descent-algorithm-in-python/index.md
  content/articles/gradient-descent-algorithm-in-python/output.png
  content/authors/jackson-munyai/avatar.png
  content/authors/jackson-munyai/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4429 Add an external CSS file to a JavaFX Application
  content/articles/add-an-external-css-file-to-a-javafx-application/delete-vbox.png
  content/articles/add-an-external-css-file-to-a-javafx-application/final-external-styling.png
  content/articles/add-an-external-css-file-to-a-javafx-application/hero.png
  content/articles/add-an-external-css-file-to-a-javafx-application/index.md
  content/articles/add-an-external-css-file-to-a-javafx-application/login-page-output.png
  content/articles/add-an-external-css-file-to-a-javafx-application/logintitle-scenebuilder-styling.png
  content/articles/add-an-external-css-file-to-a-javafx-application/new-javafx-app-dependencies.png
  content/articles/add-an-external-css-file-to-a-javafx-application/new-javafx-style.png
  content/articles/add-an-external-css-file-to-a-javafx-application/no-styling-javafx-app.png
  content/articles/add-an-external-css-file-to-a-javafx-application/output.png
  content/articles/add-an-external-css-file-to-a-javafx-application/run-application.png
  content/articles/add-an-external-css-file-to-a-javafx-application/second-output.png
  content/articles/add-an-external-css-file-to-a-javafx-application/variable-styling.png
Labels: revisions needed, assigned for review, tech tutorial

#4447 Understanding enum types in Java
  content/articles/understanding-enum-types-in-java/class_diagram.jpg
  content/articles/understanding-enum-types-in-java/hero.jpg
  content/articles/understanding-enum-types-in-java/index.md
  content/authors/ehis-edemakhiota/avatar.jpg
  content/authors/ehis-edemakhiota/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4448 How to Create and Publish your own Android Library
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/create_project.png
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/hero.png
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/index.md
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/jitpack_file.png
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/new_module.png
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/release.png
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/share.png
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/share_project_github.png
  content/articles/understanding-how-to-create-and-publish-your-own-android-library/switch_module.png
Labels: assigned for review, ready for final review, tech tutorial

#4502 Object classification using histogram of oriented gradients(HOG) features and ECOC Multi-Class Support Vector machine(SVM) in Matlab
  content/articles/object-classification-using-histogram-of-object-oriented-gradients/classification-five.png
  content/articles/object-classification-using-histogram-of-object-oriented-gradients/classification-four.png
  content/articles/object-classification-using-histogram-of-object-oriented-gradients/classification-one.png
  content/articles/object-classification-using-histogram-of-object-oriented-gradients/classification-three.png
  content/articles/object-classification-using-histogram-of-object-oriented-gradients/classification-two.png
  content/articles/object-classification-using-histogram-of-object-oriented-gradients/hero.jpg
  content/articles/object-classification-using-histogram-of-object-oriented-gradients/index.md
Labels: assigned for review, ready for final review

#4709 Using Tailwind CSS Grid Classes
  content/articles/using-tailwind-css-grid-classes/gap-lg.png
  content/articles/using-tailwind-css-grid-classes/gap-md.png
  content/articles/using-tailwind-css-grid-classes/gap-sm.png
  content/articles/using-tailwind-css-grid-classes/hero.jpg
  content/articles/using-tailwind-css-grid-classes/image-lg.png
  content/articles/using-tailwind-css-grid-classes/image-md.png
  content/articles/using-tailwind-css-grid-classes/image-sm.png
  content/articles/using-tailwind-css-grid-classes/index.md
  content/articles/using-tailwind-css-grid-classes/row-and-column-span.png
Labels: assigned for review, ready for final review

#4532 Why load balance application
  content/articles/why-use-a-load-balancer-in-an-application/hero.jpg
  content/articles/why-use-a-load-balancer-in-an-application/index.md
  content/articles/why-use-a-load-balancer-in-an-application/loadbalancing.png
  content/authors/margaret-sitati/avatar.PNG
  content/authors/margaret-sitati/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#4484 Develop multi language translator using streamlit and gettext
  content/articles/multilanguage-translator-using-streamlit-and-gettext/hero.jpg
  content/articles/multilanguage-translator-using-streamlit-and-gettext/index.md
  content/authors/johnnie-mbugua/avatar.jpg
  content/authors/johnnie-mbugua/index.md
Labels: ready for final review

#4497 WhatsApp Sentimental Analysis using Dialogflow Twilio Integration
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/cloud-account.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/cloud-nlp.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/create-project.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/dialogflow-fullfillment.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/dialogflow-intent.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/dialogflow-intent2.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/dialogflow-intent3.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/dialogflow-intent4.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/dialogflow-intent5.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/dialogflow-intent6.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/gcp-appengine.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/gcp-project.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/hero.jpg
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/index.md
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/ngrok-terminal.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/twilio-console.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/twilio-console2.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/twilio-whatapp.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/twitter-developer.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/twitter-developer2.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/whatsapp-twilio.png
  content/articles/whatsapp-sentimental-analysis-using-dialogflow-twilio/whatsapp-twilio2.png
Labels: ready for final review

#4510 Object serialization and deserialization in java
  content/articles/object-serialization-and-deserialization-in-java/hero.png
  content/articles/object-serialization-and-deserialization-in-java/index.md
  content/authors/grace-wanjiru/avatar.jpg
  content/authors/grace-wanjiru/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#4499 Representing data in django using matplotlib
  content/articles/representing-data-in-django-using-matplotlib/BarGraph.png
  content/articles/representing-data-in-django-using-matplotlib/LineGraph.png
  content/articles/representing-data-in-django-using-matplotlib/PieChart.png
  content/articles/representing-data-in-django-using-matplotlib/SalesPage.png
  content/articles/representing-data-in-django-using-matplotlib/hero.jpg
  content/articles/representing-data-in-django-using-matplotlib/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4513 Understanding Node.js Sequelize ORM Models
  content/articles/understanding-nodejs-sequelize-orm-models/hero.jpg
  content/articles/understanding-nodejs-sequelize-orm-models/index.md
  content/articles/understanding-nodejs-sequelize-orm-models/postman-create-post.png
  content/articles/understanding-nodejs-sequelize-orm-models/postman-create-user.png
  content/articles/understanding-nodejs-sequelize-orm-models/postman-delete-user.png
  content/articles/understanding-nodejs-sequelize-orm-models/postman-edit-user.png
  content/articles/understanding-nodejs-sequelize-orm-models/postman-get-posts.png
  content/articles/understanding-nodejs-sequelize-orm-models/postman-get-users.png
Labels: ready for final review, tech tutorial

#4525 Custom Pagination Using Django REST Framework with Vue.
  content/articles/custom-pagination-using-django-rest-framework/class_based.jpg
  content/articles/custom-pagination-using-django-rest-framework/custom_pagination.jpg
  content/articles/custom-pagination-using-django-rest-framework/django.jpg
  content/articles/custom-pagination-using-django-rest-framework/function_based.jpg
  content/articles/custom-pagination-using-django-rest-framework/hero.jpg
  content/articles/custom-pagination-using-django-rest-framework/index.md
  content/articles/custom-pagination-using-django-rest-framework/post_rest.jpg
Labels: ready for final review, tech tutorial

#4421 How to Invoke a SOAP Web Service in Java
  content/articles/how-to-invoke-a-soap-web-service-in-java/hero.jpg
  content/articles/how-to-invoke-a-soap-web-service-in-java/index.md
  content/authors/Tonny-sage/avatar.jpg
  content/authors/Tonny-sage/index.md
Labels: revisions needed, good first article, assigned for review

#4520 An Introduction to Blenderbot
  content/articles/introduction-to-blenderbot/hero.png
  content/articles/introduction-to-blenderbot/index.md
  content/authors/esther-awuor/avatar.png
  content/authors/esther-awuor/index.md
Labels: ready for final review, tech tutorial

#4524 How to use Go Fiber and Gorm Frameworks to run a Golang Application
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/add-a-new-todo.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/air-live-reloaded-server.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/air-live-reloads.gif
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/air-server.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/deleted-todo-not-found.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/fetched-todos.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/gcc-for-windows.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/gcc-installed.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/go-fiber-simple-server.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/hero.jpg
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/index.md
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/postman-plain-text.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/postman.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/single-todo.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/the-newly-added-todo.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/todo-deleted.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/update-a-todo.png
  content/articles/how-to-use-go-fiber-and-gorm-frameworks-to-run-a-golang-application/updated-todo.png
Labels: ready for final review, tech tutorial

#4542 Getting started with Non blocking Toastr notifications in Laravel
  content/articles/implementing-non-blocking-toastr-notifications-laravel/hero.png
  content/articles/implementing-non-blocking-toastr-notifications-laravel/index.md
  content/articles/implementing-non-blocking-toastr-notifications-laravel/toast.png
Labels: ready for final review, tech tutorial

#4564 Creating A Screen Recorder Using Python And Pycharm
  content/articles/create-a-screen-recorder-using-python-and-pycharm/hero.jpg
  content/articles/create-a-screen-recorder-using-python-and-pycharm/index.md
  content/articles/create-a-screen-recorder-using-python-and-pycharm/packages.png
  content/articles/create-a-screen-recorder-using-python-and-pycharm/pycharm.png
  content/articles/create-a-screen-recorder-using-python-and-pycharm/results.png
  content/authors/simon-kiruri/avatar.jpg
  content/authors/simon-kiruri/index.md
Labels: good first article, ready for final review

#4538 Breaking Down the Production System in Artificial Intelligence
  content/articles/breaking-down-the-production-system-in-ai/hero.png
  content/articles/breaking-down-the-production-system-in-ai/index.md
  content/articles/breaking-down-the-production-system-in-ai/production-system.jpg
Labels: assigned for review, ready for final review

#4547 Digital clock in cpp
  content/articles/digital-clock-in-cpp/digital-clock.png
  content/articles/digital-clock-in-cpp/hero.png
  content/articles/digital-clock-in-cpp/index.md
  content/authors/sabina-nyambura/avatar.jpg
  content/authors/sabina-nyambura/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#4540 Building Chat Application with Django Channel
  content/articles/building-chat-application-with-django-channel/chat.png
  content/articles/building-chat-application-with-django-channel/chatroom.png
  content/articles/building-chat-application-with-django-channel/chatroomhtml1.png
  content/articles/building-chat-application-with-django-channel/chatroomhtml2.png
  content/articles/building-chat-application-with-django-channel/consumer1.png
  content/articles/building-chat-application-with-django-channel/consumer2.png
  content/articles/building-chat-application-with-django-channel/hero.png
  content/articles/building-chat-application-with-django-channel/index.md
  content/articles/building-chat-application-with-django-channel/indexhtml.png
  content/articles/building-chat-application-with-django-channel/server-error.png
Labels: assigned for review, ready for final review

#4566 Using a Hard Margin vs Soft Margin in Support Vector Machines
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/distance.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/dual.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/error.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/formula.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/function.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/gradient.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/hero.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/hinge.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/hyper.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/index.md
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/marg.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/margin.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/max.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/min.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/negative.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/primal.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/slack.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/three.jpg
  content/articles/using-a-hard-margin-vs-soft-margin-in-support-vector-machines/xi.jpg
  content/authors/dorcas-wambui/avatar.jpg
  content/authors/dorcas-wambui/index.md
Labels: good first article, assigned for review, ready for final review, article

#4654 A Step by Step Guide to Implement Naive Bayes Algorithm in R
  content/articles/naive-bayes-algorithm-in-python/confusion-matrix.png
  content/articles/naive-bayes-algorithm-in-python/hero.png
  content/articles/naive-bayes-algorithm-in-python/index.md
  content/articles/naive-bayes-algorithm-in-python/output-image.png
Labels: assigned for review, ready for final review, tech tutorial

#4619 Advanced concepts of prog
  content/articles/advanced-concepts-of-programming-using-dart/hero.jpg
  content/articles/advanced-concepts-of-programming-using-dart/index.md
  content/authors/emmanuel-ezenagu/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#4617 How to build a code editor using codemirror
  content/articles/how-to-build-a-code-editor-using-codemirror/editor.JPG
  content/articles/how-to-build-a-code-editor-using-codemirror/hero.jpg
  content/articles/how-to-build-a-code-editor-using-codemirror/index.md
  content/articles/how-to-build-a-code-editor-using-codemirror/main-editor-2.JPG
  content/articles/how-to-build-a-code-editor-using-codemirror/main-editor.JPG
  content/articles/how-to-build-a-code-editor-using-codemirror/navbar.JPG
  content/authors/femi-ige-ayodele/avatar.jpg
  content/authors/femi-ige-ayodele/index.md
Labels: good first article, assigned for review, ready for final review

#4618 JavaFX editable table-view
  content/articles/building-javafx-editable-table-views/created-a-table-layout.png
  content/articles/building-javafx-editable-table-views/final-output.png
  content/articles/building-javafx-editable-table-views/hero.png
  content/articles/building-javafx-editable-table-views/index.md
  content/articles/building-javafx-editable-table-views/new-javafx-editable-tableview-project-dependencies.png
  content/articles/building-javafx-editable-table-views/new-javafx-editable-tableview-project.png
  content/articles/building-javafx-editable-table-views/new-tableview.png
  content/articles/building-javafx-editable-table-views/uneditable-tableview.png
Labels: assigned for review, ready for final review, tech tutorial

#4606 Introduction To Pragmatic Functional Java
  content/articles/introduction-to-pragmatic-functional-java/hero.jpg
  content/articles/introduction-to-pragmatic-functional-java/index.md
Labels: assigned for review, ready for final review

#4608 MySQL Connection Graphical User Interface design Using JavaFX and Scene builder
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure1.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure10.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure2.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure3.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure4.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure5.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure6.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure7.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure8.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/figure9.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/hero.png
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/index.md
  content/articles/mysql-connection-graphical-user-interface-design-using-javafx-and-scene-builder/test.png
Labels: assigned for review, ready for final review, tech tutorial

#4601 How to lazy load components in Angular 12
  content/articles/lazy-loading-angular-12/hero.png
  content/articles/lazy-loading-angular-12/index.md
Labels: ready for final review, tech tutorial

#4579 Using ML.NET For Object Detection In WinForms
  content/articles/using-mldotnet-for-object-detection-in-winforms/appearance.jpg
  content/articles/using-mldotnet-for-object-detection-in-winforms/hero.jpg
  content/articles/using-mldotnet-for-object-detection-in-winforms/index.md
  content/articles/using-mldotnet-for-object-detection-in-winforms/projectname.jpg
  content/authors/geoffrey-omukuba/index.md
Labels: assigned for review, ready for final review

#4598 How to create font chooser Application
  content/articles/how-to-create-font-chooser-app/bitmapfont.jpg
  content/articles/how-to-create-font-chooser-app/fontchooserapp.png
  content/articles/how-to-create-font-chooser-app/hero.jpg
  content/articles/how-to-create-font-chooser-app/index.md
  content/articles/how-to-create-font-chooser-app/strokefont.jpg
  content/articles/how-to-create-font-chooser-app/vectorfont.png
Labels: duplicate, ready for final review

#4607 Why DevOps Need Application Release Orchestration
  content/articles/why-devops-needs-application-release-orchestration/hero.jpg
  content/articles/why-devops-needs-application-release-orchestration/index.md
Labels: assigned for review, ready for final review

#4580 Automation with PyAutoGUI
  content/articles/introduction-to-automation-pyautogui/hero.jpg
  content/articles/introduction-to-automation-pyautogui/index.md
  content/authors/Naomi-Bitutu/hero.jpg
  content/authors/Naomi-Bitutu/index.md
Labels: assigned for review, ready for final review

#4647 Cryptocurrency both as an Enabler and a Solution to Ransomware
  content/articles/cryptocurrency-both-as-an-enabler-and-a-solution-to-ransomware/hero.jpg
  content/articles/cryptocurrency-both-as-an-enabler-and-a-solution-to-ransomware/index.md
Labels: ready for final review, article

#4643 Handling Web App authentication using Auth0, ASP.NET Core and Nuxt.js
  content/articles/handling-web-app-authentication-using-auth0-aspnet-core-and-nuxtjs/auth-api.png
  content/articles/handling-web-app-authentication-using-auth0-aspnet-core-and-nuxtjs/auth-login.png
  content/articles/handling-web-app-authentication-using-auth0-aspnet-core-and-nuxtjs/auth0-domain.png
  content/articles/handling-web-app-authentication-using-auth0-aspnet-core-and-nuxtjs/create-app-auth0.png
  content/articles/handling-web-app-authentication-using-auth0-aspnet-core-and-nuxtjs/hero.jpg
  content/articles/handling-web-app-authentication-using-auth0-aspnet-core-and-nuxtjs/index.md
  content/articles/handling-web-app-authentication-using-auth0-aspnet-core-and-nuxtjs/login-page.png
  content/articles/handling-web-app-authentication-using-auth0-aspnet-core-and-nuxtjs/weather-forecast.png
Labels: duplicate, assigned for review, ready for final review

#4507 How to implement binary search tree using python
  content/articles/implementing-binary-search-tree-using-python/hero.jpg
  content/articles/implementing-binary-search-tree-using-python/index.md
  content/authors/samuel-mutero/avatar.jpeg
  content/authors/samuel-mutero/index.md
Labels: ready for final review

#4594 An introduction to Neumorphism components in android studio
  content/articles/introduction-to-neumorphism-components-in-android-studio/apple-example.png
  content/articles/introduction-to-neumorphism-components-in-android-studio/example2.png
  content/articles/introduction-to-neumorphism-components-in-android-studio/example3.png
  content/articles/introduction-to-neumorphism-components-in-android-studio/hero.jpg
  content/articles/introduction-to-neumorphism-components-in-android-studio/index.md
  content/articles/introduction-to-neumorphism-components-in-android-studio/instagram-new-logo-design-illustration.jpg
  content/articles/introduction-to-neumorphism-components-in-android-studio/light-source.jpg
  content/articles/introduction-to-neumorphism-components-in-android-studio/neumorphism-dashboard-ui-design.jpg
  content/articles/introduction-to-neumorphism-components-in-android-studio/neumorphism-login-ui.jpg
  content/articles/introduction-to-neumorphism-components-in-android-studio/neumorphism-music-player.png
  content/articles/introduction-to-neumorphism-components-in-android-studio/neumorphism-pressed-login-ui.jpg
  content/articles/introduction-to-neumorphism-components-in-android-studio/shape-type.jpg
  content/articles/introduction-to-neumorphism-components-in-android-studio/telegram-mail-example.png
Labels: ready for final review

#4614 Strict Type Validation With Pydantic - (Duplicate of #4445)
  content/articles/strict-type-validation-with-pydantic/hero.png
  content/articles/strict-type-validation-with-pydantic/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#4716 How to plot multiple markers on leaflet map using jquery
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/base-layer.jpg
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/file-upload-navbar.jpg
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/geo-json-file-upload.jpg
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/geo-json-leaflet.jpg
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/hero.jpg
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/index.md
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/marker.gif
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/modal-add.jpg
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/modal-button.jpg
  content/articles/how-to-plot-multiple-marker-on-leaflet-map-using-jquery/modal-popup.jpg
Labels: assigned for review, ready for final review, tech tutorial

#4682 Stream filter in java using lambda expressions
  content/articles/stream-filter-in-java-using-lambda-expressions/hero.jpg
  content/articles/stream-filter-in-java-using-lambda-expressions/index.md
Labels: duplicate, assigned for review, ready for final review

#4535 Advancement Of Swing Framework in Java
  content/articles/advancement-of-swing-frameworks-in-java/Button.png
  content/articles/advancement-of-swing-frameworks-in-java/Event1.png
  content/articles/advancement-of-swing-frameworks-in-java/Event2.png
  content/articles/advancement-of-swing-frameworks-in-java/Painting.png
  content/articles/advancement-of-swing-frameworks-in-java/hero.png
  content/articles/advancement-of-swing-frameworks-in-java/index.md
Labels: assigned for review, ready for final review, article

#4712 Asynchronous JavaScript Using AJAX to fetch data from external API
  content/articles/asynchronous-js-using-ajax/hero.jpg
  content/articles/asynchronous-js-using-ajax/index.md
  content/articles/asynchronous-js-using-ajax/output.png
  content/authors/godwin-martins/avatar.jpg
  content/authors/godwin-martins/index.md
Labels: good first article, ready for final review

#4651 Embracing API-first Approach Beyond Product Designing
  content/articles/embracing-api-first-approach-beyond-product-designing/hero.jpg
  content/articles/embracing-api-first-approach-beyond-product-designing/index.md
  content/authors/gideon-pologi/avatar.jpg
  content/authors/gideon-pologi/index.md
Labels: good first article, assigned for review, ready for final review

#4627 WordPress Penetration Testing
  content/articles/wordpress-penetration-testing/hero.jpg
  content/articles/wordpress-penetration-testing/index.md
  content/articles/wordpress-penetration-testing/kali-vb-install.jpg
  content/articles/wordpress-penetration-testing/sqlmap.jpg
  content/articles/wordpress-penetration-testing/wpscan.jpg
  content/articles/wordpress-penetration-testing/xsser.jpg
  content/authors/esther-waithera/avatar.jpg
Labels: ready for final review

#4658 Understanding React UseEffect and creating custom Hooks
  content/articles/understanding-react-useeffect/counter-log.png
  content/articles/understanding-react-useeffect/counter-log2.png
  content/articles/understanding-react-useeffect/counter-three.png
  content/articles/understanding-react-useeffect/counter-zero.png
  content/articles/understanding-react-useeffect/hero.jpg
  content/articles/understanding-react-useeffect/index.md
  content/articles/understanding-react-useeffect/list-of-users.png
  content/authors/zuko-obi/avatar.jpeg
  content/authors/zuko-obi/index.md
Labels: good first article, assigned for review, ready for final review

#4758 [Duplicate] Automatic SMS verification with SMS Retriever API in Android
  content/articles/automatic-sms-verification-with-sms-retriever-api/create-project.png
  content/articles/automatic-sms-verification-with-sms-retriever-api/hero.png
  content/articles/automatic-sms-verification-with-sms-retriever-api/index.md
  content/articles/automatic-sms-verification-with-sms-retriever-api/screen-one.png
  content/authors/robert-muriithi/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#4736 Is Computational Storage a Newfound Solution to Edge Storage Problems?
  content/articles/computational-storage-a-solution-to-edge-storage-problems/hero.jpg
  content/articles/computational-storage-a-solution-to-edge-storage-problems/index.md
Labels: assigned for review, ready for final review, article

#4575 Working with Quarkus Configuration Profiles
  content/articles/quarkus-configuration-profiles/application.properties-file-location.png
  content/articles/quarkus-configuration-profiles/hero.png
  content/articles/quarkus-configuration-profiles/index.md
  content/articles/quarkus-configuration-profiles/new-quarkus-project-dependencies.png
  content/articles/quarkus-configuration-profiles/new-quarkus-project.png
Labels: tech tutorial

#4683 Write Excel in Python
  content/articles/building-excel-spreadsheets-using-python/Imageeight.PNG
  content/articles/building-excel-spreadsheets-using-python/Imagefive.PNG
  content/articles/building-excel-spreadsheets-using-python/Imagefour.PNG
  content/articles/building-excel-spreadsheets-using-python/Imagenine.PNG
  content/articles/building-excel-spreadsheets-using-python/Imageone.PNG
  content/articles/building-excel-spreadsheets-using-python/Imageseven.PNG
  content/articles/building-excel-spreadsheets-using-python/Imagesix.PNG
  content/articles/building-excel-spreadsheets-using-python/Imagethree.PNG
  content/articles/building-excel-spreadsheets-using-python/Imagetwo.PNG
  content/articles/building-excel-spreadsheets-using-python/hero.png
  content/articles/building-excel-spreadsheets-using-python/index.md
  content/authors/benedict-ifeanyi-iheagwara/Avatar.png
  content/authors/benedict-ifeanyi-iheagwara/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4687 How to Handle Internet Connection and Capabilities using LiveData in Android
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/connected.jpg
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/create-a-kotlin-app.png
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/hero.jpg
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/index.md
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/logcat.png
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/lost-connection.png
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/network-with-capabilities.png
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/network-with-no-capabilities.png
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/no-connections.jpg
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/youtube-offline.jpg
  content/articles/handle-and-implement-no-internet-connections-and-capabilities-using-livedata/youtube-online.jpg
  content/authors/joseph-chege/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4741 How API Management Enables a Data First Approach
  content/articles/how-api-management-enables-a-data-first-approach/hero.jpg
  content/articles/how-api-management-enables-a-data-first-approach/index.md
Labels: assigned for review, ready for final review, article

#4720 Creating a Callback URL for Safaricom Daraja API - (Lipa na Mpesa) with Firebase Cloud Functions in Android
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/changetoblaze.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/create-android-proj.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/create-app.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/deployed.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/functions-console.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/hero.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/index.md
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/mpesa-app.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/send-failed.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/send-success.png
  content/articles/callback-url-for-safaricom-daraja-api-with-firebase-cloud-functions-in-android/successful-transaction.png
  content/authors/osir-evaline/avatar.jpg
  content/authors/osir-evaline/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4737 Composition in Java
  content/articles/composition-in-java/hero.jpg
  content/articles/composition-in-java/index.md
  content/articles/composition-in-java/main.png
  content/authors/emmanuel-kipchumba/avatar.jpg
  content/authors/emmanuel-kipchumba/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4785 How to Perform Threading Timer in Python
  content/articles/how-to-perform-threading-timer-in-python/cancel.png
  content/articles/how-to-perform-threading-timer-in-python/hero.png
  content/articles/how-to-perform-threading-timer-in-python/index.md
  content/articles/how-to-perform-threading-timer-in-python/start.png
  content/articles/how-to-perform-threading-timer-in-python/threading.png
  content/authors/jacob-oduor/avatar.png
  content/authors/jacob-oduor/index.md
Labels: good first article, assigned for review, ready for final review

#4707 Genetic programming models using TPOT.
  content/articles/genetic-programming-models-using-tpot/accuracy-scores.png
  content/articles/genetic-programming-models-using-tpot/accuracy-scores2.png
  content/articles/genetic-programming-models-using-tpot/dataset-image.jpg
  content/articles/genetic-programming-models-using-tpot/hero.jpg
  content/articles/genetic-programming-models-using-tpot/index.md
  content/articles/genetic-programming-models-using-tpot/methods-and-attributes.png
  content/articles/genetic-programming-models-using-tpot/missing-values.png
  content/articles/genetic-programming-models-using-tpot/new-columns.png
  content/articles/genetic-programming-models-using-tpot/new-dataset.png
  content/articles/genetic-programming-models-using-tpot/optimization-process.png
  content/articles/genetic-programming-models-using-tpot/output-columns.png
  content/articles/genetic-programming-models-using-tpot/output.png
Labels: assigned for review, ready for final review

#4809 Getting Started with Question Answering (Q&A) using BERT
  content/articles/getting-started-with-question-answering-using-bert/hero.png
  content/articles/getting-started-with-question-answering-using-bert/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4820 The Basics to Making your Web Application Work Offline
  content/articles/basics-to-making-your-web-application-work-offline/hero.jpg
  content/articles/basics-to-making-your-web-application-work-offline/index.md
  content/articles/basics-to-making-your-web-application-work-offline/service-workers.png
Labels: assigned for review, ready for final review

#4845 [Duplicate] Understanding different types of menus in android with kotlin
  content/articles/different-types-of-menus-in-android/action-mode.png
  content/articles/different-types-of-menus-in-android/checkable.png
  content/articles/different-types-of-menus-in-android/floating-contextual.png
  content/articles/different-types-of-menus-in-android/hero.png
  content/articles/different-types-of-menus-in-android/index.md
  content/articles/different-types-of-menus-in-android/options-menu.png
  content/articles/different-types-of-menus-in-android/popup-menu.png
  content/authors/benta-odek/avatar.jpg
  content/authors/benta-odek/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#4719 Serialization in C#
  content/articles/serialization-in-csharp/hero.png
  content/articles/serialization-in-csharp/index.md
  content/authors/erick-kiragu/avatar.png
  content/authors/erick-kiragu/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4650 Walsh hamard transform for signal and image compression using matlab
  content/articles/walsh-hadamard-transform-for-signal-and-image-compression-using-matlab/hero.jpg
  content/articles/walsh-hadamard-transform-for-signal-and-image-compression-using-matlab/index.md
  content/articles/walsh-hadamard-transform-for-signal-and-image-compression-using-matlab/walsh-five.png
  content/articles/walsh-hadamard-transform-for-signal-and-image-compression-using-matlab/walsh-four.png
  content/articles/walsh-hadamard-transform-for-signal-and-image-compression-using-matlab/walsh-one.png
  content/articles/walsh-hadamard-transform-for-signal-and-image-compression-using-matlab/walsh-six.png
  content/articles/walsh-hadamard-transform-for-signal-and-image-compression-using-matlab/walsh-three.png
  content/articles/walsh-hadamard-transform-for-signal-and-image-compression-using-matlab/walsh-two.png
Labels: assigned for review, ready for final review

#4819 [duplicate] Recovering WiFi Passwords From Windows/MacOS/Linux
  content/articles/recovering-wifi-passwords-from-operating-systems/cmd.jpg
  content/articles/recovering-wifi-passwords-from-operating-systems/fade.jpg
  content/articles/recovering-wifi-passwords-from-operating-systems/hero.jpg
  content/articles/recovering-wifi-passwords-from-operating-systems/index.md
  content/articles/recovering-wifi-passwords-from-operating-systems/keyclear.png
  content/articles/recovering-wifi-passwords-from-operating-systems/lase.jpg
  content/articles/recovering-wifi-passwords-from-operating-systems/profile.png
  content/articles/recovering-wifi-passwords-from-operating-systems/security.jpg
  content/articles/recovering-wifi-passwords-from-operating-systems/terminal.jpg
  content/authors/lenox-majiwa/avatar.jpg.jpg
  content/authors/lenox-majiwa/index.md
Labels: duplicate, assigned for review, ready for final review

#4851 How to Analyze Machine Learning Models Using SHAP
  content/articles/how-to-analyze-machine-learning-models-using-shap/dataset-datatypes.jpg
  content/articles/how-to-analyze-machine-learning-models-using-shap/dataset-image.jpg
  content/articles/how-to-analyze-machine-learning-models-using-shap/dataset-structure.jpg
  content/articles/how-to-analyze-machine-learning-models-using-shap/features.jpg
  content/articles/how-to-analyze-machine-learning-models-using-shap/force-plot.jpg
  content/articles/how-to-analyze-machine-learning-models-using-shap/hero.png
  content/articles/how-to-analyze-machine-learning-models-using-shap/index.md
  content/articles/how-to-analyze-machine-learning-models-using-shap/missing-values.jpg
  content/articles/how-to-analyze-machine-learning-models-using-shap/scaled-dataframe.jpg
  content/articles/how-to-analyze-machine-learning-models-using-shap/shapley-values.jpg
  content/articles/how-to-analyze-machine-learning-models-using-shap/summary-plot.jpg
Labels: duplicate, ready for final review

#4826 SendRedirect in Servlet Collaboration
  content/articles/SendRedirect-in-Servlet-Collaboration/hero.png
  content/articles/SendRedirect-in-Servlet-Collaboration/index.md
Labels: assigned for review, ready for final review

#4832 The concept of cookies in servlets
  content/articles/the-concept-of-cookies-in-servlets/hero.png
  content/articles/the-concept-of-cookies-in-servlets/index.md
Labels: assigned for review, ready for final review

#5140 Fruit Mania Game in JavaScript : JavaScript for Game Development
  content/articles/fruit-mania-game-in-javaScript-JavaScript-for-game-Development/fruit-mania-game.png
  content/articles/fruit-mania-game-in-javaScript-JavaScript-for-game-Development/hero.png
  content/articles/fruit-mania-game-in-javaScript-JavaScript-for-game-Development/index.md
  content/authors/esther-maina/index.md
Labels: duplicate, ready for final review

#4974 Blazor Server-Side Application Using ASP.NET Core To Perform CRUD Operations
  content/articles/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/appearance.png
  content/articles/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/blazor-server.png
  content/articles/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/component.png
  content/articles/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/framework.png
  content/articles/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/hero.jpg
  content/articles/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/index.md
  content/articles/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/nameofapp.png
  content/articles/creating-a-blazor-server-side-application-using-aspdotnet-core-to-perform-crud-operations/new-project.png
Labels: assigned for review, ready for final review, tech tutorial

#4727 Understanding Script Tag Attributes: Async and Defer
  content/articles/understanding-script-tag-attributes-async-defer/Async-Execution.png
  content/articles/understanding-script-tag-attributes-async-defer/Defer-Execution.png
  content/articles/understanding-script-tag-attributes-async-defer/Normal-Execution.png
  content/articles/understanding-script-tag-attributes-async-defer/async-await-result.png
  content/articles/understanding-script-tag-attributes-async-defer/hero.jpg
  content/articles/understanding-script-tag-attributes-async-defer/index.md
Labels: ready for final review

#4846 Build a Hash Generator Application using React.js
  content/articles/build-a-hash-generator-application-using-reactjs/generate-hash-form.png
  content/articles/build-a-hash-generator-application-using-reactjs/generated-hash-form-with-output.png
  content/articles/build-a-hash-generator-application-using-reactjs/hero.png
  content/articles/build-a-hash-generator-application-using-reactjs/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4775 How to create and run a C# unit testing project
  content/articles/create-and-run-a-dot-net-unit-testing-project/hero.jpg
  content/articles/create-and-run-a-dot-net-unit-testing-project/image1.png
  content/articles/create-and-run-a-dot-net-unit-testing-project/image2.png
  content/articles/create-and-run-a-dot-net-unit-testing-project/image3.png
  content/articles/create-and-run-a-dot-net-unit-testing-project/image4.png
  content/articles/create-and-run-a-dot-net-unit-testing-project/image5.png
  content/articles/create-and-run-a-dot-net-unit-testing-project/image6.png
  content/articles/create-and-run-a-dot-net-unit-testing-project/image7.png
  content/articles/create-and-run-a-dot-net-unit-testing-project/index.md
  content/authors/gitau-kimani/avatar.jpg
  content/authors/gitau-kimani/index.md
Labels: assigned for review, ready for final review

#4971 [Blockchain] An Overview of web 3.O
  content/articles/overview-of-web-3-0/hero.jpg
  content/articles/overview-of-web-3-0/index.md
  content/articles/overview-of-web-3-0/web-evolution.jpg
Labels: ready for final review, article

#4694 Getting Started with Polynomial regression in Python
  content/articles/polynomial-regression-in-python/hero.png
  content/articles/polynomial-regression-in-python/index.md
  content/articles/polynomial-regression-in-python/linear-regression.png
  content/articles/polynomial-regression-in-python/poly-regression.png
  content/articles/polynomial-regression-in-python/polynomial-2.png
  content/articles/polynomial-regression-in-python/polynomial-3.png
  content/articles/polynomial-regression-in-python/polynomial-data.png
  content/authors/faith-mwangangi/avatar.jpg
  content/authors/faith-mwangangi/index.md
Labels: assigned for review, ready for final review

#4852 How to Automate Tests for Dockerized Django Applications with GitHub Actions
  content/articles/dockerized-django-application-with-github-actions/display-blog.png
  content/articles/dockerized-django-application-with-github-actions/docker.png
  content/articles/dockerized-django-application-with-github-actions/fail-test.png
  content/articles/dockerized-django-application-with-github-actions/github-actions.png
  content/articles/dockerized-django-application-with-github-actions/github-actions1.png
  content/articles/dockerized-django-application-with-github-actions/hero.jpg
  content/articles/dockerized-django-application-with-github-actions/index.md
  content/articles/dockerized-django-application-with-github-actions/run-test.png
  content/authors/muhammed-ali/avatar.jpg
  content/authors/muhammed-ali/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4581 Learn how to set up Linux's Quagga Routing Suite
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/available-daemons-in-vtysh.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/config2.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/configuration.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/daemons-file.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/daemons.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/df2.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/duplicate-records.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/hero.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/index.md
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/installation.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/installation2.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/netstat.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/quagga-starting.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/rename.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/ripd.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/services.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/telnet-ospfd.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/user-group.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/vtysh.png
  content/articles/learn-how-to-set-up-linux-quagga-routing-suite/zebra-telnet.png
Labels: assigned for review, ready for final review, tech tutorial

#4669 Object based image analysis using matlab
  content/articles/object-based-image-analysis-using-matlab/hero.jpg
  content/articles/object-based-image-analysis-using-matlab/index.md
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_eight.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_eighteen.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_eleven.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_fifteen.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_five.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_four.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_fourteen.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_nine.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_nineteen.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_one.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_seven.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_seventeen.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_six.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_sixteen.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_ten.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_thirteen.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_three.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_twelve.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_twenty.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_twentyone.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_twentythree.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_twentytwo.jpg
  content/articles/object-based-image-analysis-using-matlab/objectanalysis_two.jpg
  content/authors/alphonce-arogo/avatar.jpg
  content/authors/alphonce-arogo/index.md
Labels: good first article, ready for final review, tech tutorial

#4873 Creating a Custom Stepper Form in Android
  content/articles/creating-a-custom-stepper-form-in-android/hero.png
  content/articles/creating-a-custom-stepper-form-in-android/index.md
  content/articles/creating-a-custom-stepper-form-in-android/project.png
  content/articles/creating-a-custom-stepper-form-in-android/step1.png
  content/articles/creating-a-custom-stepper-form-in-android/step2.png
  content/articles/creating-a-custom-stepper-form-in-android/step3.png
  content/articles/creating-a-custom-stepper-form-in-android/step4.png
  content/articles/creating-a-custom-stepper-form-in-android/step5.png
  content/authors/feswal-salim/avatar.jpg
  content/authors/feswal-salim/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#5244 Tailwindwithflask - Updated the npx command
  content/articles/integrate-tailwindcss-into-flask/index.md
Labels: article update

#4856 Building FAQ page using React-styled components and React.js
  content/articles/building-faq-page-using-react-styled-components-and-react/hero.jpg
  content/articles/building-faq-page-using-react-styled-components-and-react/image1.jpg
  content/articles/building-faq-page-using-react-styled-components-and-react/image2.jpg
  content/articles/building-faq-page-using-react-styled-components-and-react/index.md
  content/authors/kingsley-jack/avatar.jpg
  content/authors/kingsley-jack/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#4928 MediaPipe HandPose Detection using Python
  content/articles/handpose-detection-using-mediapipe-and-python/hero.png
  content/articles/handpose-detection-using-mediapipe-and-python/index.md
Labels: ready for final review, tech tutorial

#4881 Building a Toxicity Classifier using Python
  content/articles/building-a-toxicity-classifier/gradio.png
  content/articles/building-a-toxicity-classifier/hero.png
  content/articles/building-a-toxicity-classifier/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4997 Understanding the Map data type in Dart
  content/articles/understanding-the-map-data-type-in-dart/constructor.png
  content/articles/understanding-the-map-data-type-in-dart/deleting.png
  content/articles/understanding-the-map-data-type-in-dart/hero.jpg
  content/articles/understanding-the-map-data-type-in-dart/index.md
  content/articles/understanding-the-map-data-type-in-dart/insert.png
  content/articles/understanding-the-map-data-type-in-dart/key.png
  content/articles/understanding-the-map-data-type-in-dart/length.png
  content/articles/understanding-the-map-data-type-in-dart/merging.png
Labels: assigned for review, ready for final review, tech tutorial

#4980 Flutter state management with Mobx package
  content/articles/flutter-state-management-mobx/command.png
  content/articles/flutter-state-management-mobx/hero.jpg
  content/articles/flutter-state-management-mobx/index.md
  content/articles/flutter-state-management-mobx/news.png
  content/authors/faith-siaji/avatar.jpeg
  content/authors/faith-siaji/index.md
Labels: duplicate, ready for final review

#4939 Client-Server Implementation of reCAPTCHA with React and Django
  content/articles/client-server-react-django-recaptcha/hero.jpg
  content/articles/client-server-react-django-recaptcha/index.md
  content/articles/client-server-react-django-recaptcha/recaptchaSnap.PNG
Labels: ready for final review, tech tutorial

#4757 Class data sharing in java with examples
  content/articles/class-data-sharing-in-java-with-examples/app.jpg
  content/articles/class-data-sharing-in-java-with-examples/custom.jpg
  content/articles/class-data-sharing-in-java-with-examples/hero.jpg
  content/articles/class-data-sharing-in-java-with-examples/index.md
  content/articles/class-data-sharing-in-java-with-examples/xshare.jpg
  content/authors/bancy-wangui/avatar.jpg
  content/authors/bancy-wangui/index.md
Labels: assigned for review, ready for final review, needs plagiarism check, article

#4791 How to work with Lombok on Quarkus
  content/articles/how-to-work-with-lombok-on-quarkus/Lombok-intellij-pliugin.png
  content/articles/how-to-work-with-lombok-on-quarkus/can't-find-setId.png
  content/articles/how-to-work-with-lombok-on-quarkus/custom-logs.png
  content/articles/how-to-work-with-lombok-on-quarkus/hero.png
  content/articles/how-to-work-with-lombok-on-quarkus/index.md
  content/articles/how-to-work-with-lombok-on-quarkus/log-info.png
  content/articles/how-to-work-with-lombok-on-quarkus/log-topic.png
  content/articles/how-to-work-with-lombok-on-quarkus/lombok-annotations-vs-code.png
  content/articles/how-to-work-with-lombok-on-quarkus/new-quarkus-lombok-intellij.png
  content/articles/how-to-work-with-lombok-on-quarkus/new-quarkus-lombok-satrter-web.png
  content/articles/how-to-work-with-lombok-on-quarkus/new-quarkus-lombok-vs-code.png
  content/articles/how-to-work-with-lombok-on-quarkus/quarkus-tools-vs-code.png
  content/articles/how-to-work-with-lombok-on-quarkus/running-tests.png
  content/articles/how-to-work-with-lombok-on-quarkus/set-id-error.png
Labels: assigned for review, tech tutorial

#4987 How to build an NLP based emotion detection model using NeatText and Scikit-learn
  content/articles/nlp-based-detection-model-using-neattext-and-scikit-learn/clean-dataset.png
  content/articles/nlp-based-detection-model-using-neattext-and-scikit-learn/dataset-snip.png
  content/articles/nlp-based-detection-model-using-neattext-and-scikit-learn/dataset-structure.png
  content/articles/nlp-based-detection-model-using-neattext-and-scikit-learn/emotion-value-count.png
  content/articles/nlp-based-detection-model-using-neattext-and-scikit-learn/hero.jpg
  content/articles/nlp-based-detection-model-using-neattext-and-scikit-learn/index.md
  content/articles/nlp-based-detection-model-using-neattext-and-scikit-learn/methods-attributes.png
  content/articles/nlp-based-detection-model-using-neattext-and-scikit-learn/pipeline-output.png
Labels: assigned for review, ready for final review, tech tutorial

#4962 Extensible Messaging and Presence Protocol - XMPP with NodeJs and Docker
  content/articles/extensible-messaging-and-presence-protocol-with-nodejs-and-docker/hero.png
  content/articles/extensible-messaging-and-presence-protocol-with-nodejs-and-docker/index.md
  content/authors/arafat-olayiwola/index.md
Labels: ready for final review, tech tutorial
