Repository section-engineering-education/engineering-education, pull requests merged in 2021-05, with the labels that each got.

#1964 Client-Side Rendering (CSR) vs. Server-Side Rendering (SSR) vs. Static-Site Generation (SSG)
  articles/client-side-rendering-vs-server-side-rendering-vs-static-site-generation/hero.jpg
  articles/client-side-rendering-vs-server-side-rendering-vs-static-site-generation/index.md
Labels: assigned for review, ready for final review

#1978 Multimodal Neurons in Artificial Neural Networks
  articles/multimodal-neurons-in-artificial-neural-networks/chihuahua-pizza.PNG
  articles/multimodal-neurons-in-artificial-neural-networks/emotion-neuron.PNG
  articles/multimodal-neurons-in-artificial-neural-networks/green-color.PNG
  articles/multimodal-neurons-in-artificial-neural-networks/hero.jpg
  articles/multimodal-neurons-in-artificial-neural-networks/index.md
  articles/multimodal-neurons-in-artificial-neural-networks/person-neuron.PNG
  articles/multimodal-neurons-in-artificial-neural-networks/region-neuron.PNG
Labels: article, ready for final review

#1981 Creating A Location-tracking App Using Firebase and Google Maps in Android
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/add-item.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/api-key.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/console-link.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/create-api-key.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/create-project.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/database-state.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/fb-androidstudio.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/firebaseintro.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/hero.jpg
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/index.md
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/locatchecker.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/locatrack-perm.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/locatrack.png
  articles/creating-a-location-tracking-app-using-firebase-and-google-maps-in-android/project-template.png
Labels: ready for final review

#1990 Getting started with Node.js Paypal checkout integration
  articles/nodejs-paypal-checkout/hero.jpg
  articles/nodejs-paypal-checkout/index.md
  articles/nodejs-paypal-checkout/paypal-account-section.png
  articles/nodejs-paypal-checkout/paypal-checkout.png
  articles/nodejs-paypal-checkout/paypal-create-account.png
  articles/nodejs-paypal-checkout/paypal-create-app.png
  articles/nodejs-paypal-checkout/paypal-credentials.png
  articles/nodejs-paypal-checkout/paypal-success.png
Labels: ready for final review, tech tutorial

#2024 Recommender System Explained
  articles/recommender-system-explained/content-based-filtering.jpg
  articles/recommender-system-explained/hero.jpg
  articles/recommender-system-explained/how-collaborative-filtering-works.png
  articles/recommender-system-explained/how-recommender-systems-work.jpg
  articles/recommender-system-explained/index.md
  authors/pennina-wanja/avatar.jpg
  authors/pennina-wanja/index.md
Labels: assigned for review, good first article, ready for final review

#1994 Facebook OAuth using Firebase in React Native
  articles/react-native-firebase-facebook-authentication/add_platform.png
  articles/react-native-firebase-facebook-authentication/app_secret.png
  articles/react-native-firebase-facebook-authentication/auth_get_starterd.png
  articles/react-native-firebase-facebook-authentication/create_app.png
  articles/react-native-firebase-facebook-authentication/download_services.json.png
  articles/react-native-firebase-facebook-authentication/enable_fb_auth.png
  articles/react-native-firebase-facebook-authentication/env_setup.png
  articles/react-native-firebase-facebook-authentication/fb_android_app.png
  articles/react-native-firebase-facebook-authentication/fb_dashboard.png
  articles/react-native-firebase-facebook-authentication/firebase_new.png
  articles/react-native-firebase-facebook-authentication/folder_structure.png
  articles/react-native-firebase-facebook-authentication/hero.jpg
  articles/react-native-firebase-facebook-authentication/index.md
  articles/react-native-firebase-facebook-authentication/new_dashboard.png
  articles/react-native-firebase-facebook-authentication/openssl.png
  articles/react-native-firebase-facebook-authentication/package_name.png
  articles/react-native-firebase-facebook-authentication/redirect_uri.png
  articles/react-native-firebase-facebook-authentication/register_app.png
  articles/react-native-firebase-facebook-authentication/screens.jpg
  articles/react-native-firebase-facebook-authentication/signin.gif
  articles/react-native-firebase-facebook-authentication/signout.gif
Labels: assigned for review, ready for final review, tech tutorial

#1997 Getting Started with Metasploit Framework
  articles/getting-started-with-metasploit-framework/back.png
  articles/getting-started-with-metasploit-framework/exit.png
  articles/getting-started-with-metasploit-framework/hero.jpg
  articles/getting-started-with-metasploit-framework/index.md
  articles/getting-started-with-metasploit-framework/info.png
  articles/getting-started-with-metasploit-framework/metasploit1.png
  articles/getting-started-with-metasploit-framework/search.png
  articles/getting-started-with-metasploit-framework/set.png
  articles/getting-started-with-metasploit-framework/showOptions.png
  articles/getting-started-with-metasploit-framework/showPayload.png
  articles/getting-started-with-metasploit-framework/showTarget.png
  articles/getting-started-with-metasploit-framework/use.png
  authors/kimosop-wakanda/avatar.jpg
  authors/kimosop-wakanda/index.md
Labels: article, assigned for review, ready for final review

#2000 Why Python is good for Machine Learning?
  articles/why-python-is-good-for-machine-learning/hero.jpg
  articles/why-python-is-good-for-machine-learning/index.md
  authors/lilian-ogoti/avatar.jpg
  authors/lilian-ogoti/index.md
Labels: ready for final review

#2005 Diagnosing Diabetes with SVM
  articles/diagnose-diabetes-with-svm/BMI-Pedigree.JPG
  articles/diagnose-diabetes-with-svm/accuracy-of-all-zero-prediction.JPG
  articles/diagnose-diabetes-with-svm/accuracy-score.JPG
  articles/diagnose-diabetes-with-svm/age-outcome.JPG
  articles/diagnose-diabetes-with-svm/class-labels.JPG
  articles/diagnose-diabetes-with-svm/classification-report.JPG
  articles/diagnose-diabetes-with-svm/dataset-features.JPG
  articles/diagnose-diabetes-with-svm/decision-boundary.jpg
  articles/diagnose-diabetes-with-svm/feature-correlations.JPG
  articles/diagnose-diabetes-with-svm/feature-interactions.JPG
  articles/diagnose-diabetes-with-svm/first-rows-of-dataset.JPG
  articles/diagnose-diabetes-with-svm/glucose-bloodpressure.JPG
  articles/diagnose-diabetes-with-svm/hero.png
  articles/diagnose-diabetes-with-svm/index.md
  articles/diagnose-diabetes-with-svm/last-rows-of-dataset.JPG
  articles/diagnose-diabetes-with-svm/missing-values.JPG
  articles/diagnose-diabetes-with-svm/model-prediction.JPG
  articles/diagnose-diabetes-with-svm/normalized-train-set.JPG
  articles/diagnose-diabetes-with-svm/overview.JPG
  articles/diagnose-diabetes-with-svm/precision-recall-f1.JPG
  articles/diagnose-diabetes-with-svm/pregnancy-histogram.JPG
  articles/diagnose-diabetes-with-svm/single-prediction-2.JPG
  articles/diagnose-diabetes-with-svm/single-prediction.JPG
  articles/diagnose-diabetes-with-svm/skinthickness-insulin.JPG
  articles/diagnose-diabetes-with-svm/svm-kernerls-accuracy.JPG
  articles/diagnose-diabetes-with-svm/test-set.JPG
  articles/diagnose-diabetes-with-svm/third-patient-details.JPG
  articles/diagnose-diabetes-with-svm/training-set.JPG
  articles/diagnose-diabetes-with-svm/xtest-shape.JPG
  articles/diagnose-diabetes-with-svm/xtrain-shape.JPG
  articles/diagnose-diabetes-with-svm/ytest-shape.JPG
  articles/diagnose-diabetes-with-svm/ytrain-shape.JPG
Labels: assigned for review, ready for final review, tech tutorial

#2008 Creating a virtual assistant using python
  articles/creating-a-virtual-assistant-using-python/hero.jpg
  articles/creating-a-virtual-assistant-using-python/index.md
  articles/creating-a-virtual-assistant-using-python/pyaudio.png
  articles/creating-a-virtual-assistant-using-python/python-speech.png
  articles/creating-a-virtual-assistant-using-python/pyttsx3.png
  articles/creating-a-virtual-assistant-using-python/terminal-tab.png
Labels: assigned for review, ready for final review

#2017 Why Python is Essential for Data Analysis
  articles/why-python-is-essential-for-data-analysis/hero.jpg
  articles/why-python-is-essential-for-data-analysis/index.md
Labels: article, assigned for review, ready for final review

#2045 Node.js Structural Comparisons
  articles/nodejs-structural-comparisons/define.jpg
  articles/nodejs-structural-comparisons/exampleoutputs.jpg
  articles/nodejs-structural-comparisons/hero.jpg
  articles/nodejs-structural-comparisons/index.md
  articles/nodejs-structural-comparisons/path.jpg
  articles/nodejs-structural-comparisons/plotlyplt.jpg
  articles/nodejs-structural-comparisons/soundcurve.jpg
Labels: assigned for review, ready for final review

#2020 Creating a Simple Real-Time Chat App using React and Socket.io with E2E Encryption
  articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/backend-folders.PNG
  articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/frontend-folders.PNG
  articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/hero.jpg
  articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/index.md
  articles/creating-a-simple-real-time-chat-app-with-react-socket-io-with-e2e-encryption/packagejson.PNG
Labels: assigned for review, ready for final review, tech tutorial

#2046 Speakeasy Two Factor Authentication in Nodejs
  articles/speakeasy-two-factor-authentication-in-nodejs/hero.jpg
  articles/speakeasy-two-factor-authentication-in-nodejs/index.md
  articles/speakeasy-two-factor-authentication-in-nodejs/register-route.png
  articles/speakeasy-two-factor-authentication-in-nodejs/validate-route.png
  articles/speakeasy-two-factor-authentication-in-nodejs/verify-route.png
  authors/mia-roberts/avatar.jpeg
  authors/mia-roberts/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2049 Getting Started With NodeJs Event Emitter Tutorial
  articles/guide-to-nodejs-event-emitter/hero.jpg
  articles/guide-to-nodejs-event-emitter/index.md
Labels: assigned for review, ready for final review

#2022 Integrating B2C mpesa API using Node.js
  articles/integrating-b2c-mpesa-api-using-node-js/access-token-response-screenshot.png
  articles/integrating-b2c-mpesa-api-using-node-js/b2c-console-response-screenshot.png
  articles/integrating-b2c-mpesa-api-using-node-js/b2c-server-response-screenshot.png
  articles/integrating-b2c-mpesa-api-using-node-js/hero.jpg
  articles/integrating-b2c-mpesa-api-using-node-js/index.md
  authors/robert-wachira/avatar.jpg
  authors/robert-wachira/index.md
Labels: ready for final review

#2051 How to use Streams in Node.js
  articles/how-to-use-streams-in-node,js/hero.jpg
  articles/how-to-use-streams-in-node,js/index.md
Labels: assigned for review, ready for final review

#2032 Introduction to machine learning using c++
  articles/an-introduction-to-machine-learning-using-c++/dataset1.PNG
  articles/an-introduction-to-machine-learning-using-c++/gradientdescent.PNG
  articles/an-introduction-to-machine-learning-using-c++/hero.jpg
  articles/an-introduction-to-machine-learning-using-c++/index.md
  articles/an-introduction-to-machine-learning-using-c++/linearRegression.PNG
Labels: assigned for review, ready for final review

#2064 How to use CORS in Node.js with Express
  articles/how-to-use-cors-in-nodejs-with-express/cors-error-policy-header.jpg
  articles/how-to-use-cors-in-nodejs-with-express/cors-policy-error.jpg
  articles/how-to-use-cors-in-nodejs-with-express/diffrent-origin.jpg
  articles/how-to-use-cors-in-nodejs-with-express/hero.png
  articles/how-to-use-cors-in-nodejs-with-express/index.md
  articles/how-to-use-cors-in-nodejs-with-express/origin.jpg
  articles/how-to-use-cors-in-nodejs-with-express/same-origin.jpg
Labels: ready for final review

#2086 Why Node.js is great for Backend Development?
  articles/why-nodejs-is-great-for-backend-development/hero.jpg
  articles/why-nodejs-is-great-for-backend-development/index.md
  authors/ephraim-gathoni/avatar.jpg
  authors/ephraim-gathoni/index.md
Labels: article, assigned for review, good first article, ready for final review

#2056 Introduction to C++ type conversion
  articles/intro-to-c++-type-conversion/hero.jpg
  articles/intro-to-c++-type-conversion/index.md
Labels: assigned for review, ready for final review

#2055 Working with APIs in TypeScript
  articles/working-with-apis-in-typescript/api-response.png
  articles/working-with-apis-in-typescript/hero.png
  articles/working-with-apis-in-typescript/index.md
  articles/working-with-apis-in-typescript/post-response.jpg
  articles/working-with-apis-in-typescript/server-running.png
  articles/working-with-apis-in-typescript/tsconfig.png
Labels: assigned for review, ready for final review, tech tutorial

#2040 Getting started with structs sorting in C++
  articles/getting-started-with-structs-sorting-in-c++/hero.png
  articles/getting-started-with-structs-sorting-in-c++/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2057 How To Auto-generate Admin Panels for Node.js with AdminBro
  articles/nodejs-adminbro/AdminBro.png
  articles/nodejs-adminbro/hero.jpg
  articles/nodejs-adminbro/index.md
  authors/Kevin-Kimani/avatar.jpeg
  authors/Kevin-Kimani/index.md
  authors/avatar
Labels: ready for final review

#2063 Getting Started with deep neural systems in Matlab
  articles/deep-neural-system-matlab/hero.jpg
  articles/deep-neural-system-matlab/image1.jpg
  articles/deep-neural-system-matlab/image2.jpg
  articles/deep-neural-system-matlab/image3.jpg
  articles/deep-neural-system-matlab/image4.jpg
  articles/deep-neural-system-matlab/image5.jpg
  articles/deep-neural-system-matlab/image6.jpg
  articles/deep-neural-system-matlab/image7.png
  articles/deep-neural-system-matlab/image8.png
  articles/deep-neural-system-matlab/index.md
  articles/deep-neural-system-matlab/recognizedDigit.png
  articles/deep-neural-system-matlab/trainingProgress.png
Labels: assigned for review, ready for final review

#2068 A Primer on Bayesian Optimization to Optimize Hyperparameters
  articles/bayesian-search/acquisition.png
  articles/bayesian-search/hero.jpg
  articles/bayesian-search/index.md
  articles/bayesian-search/statistics.jpg
Labels: article, ready for final review

#2145 Uploading Images to Cloudinary using Node.js
  articles/how-to-upload-images-to-cloudinary-using-node.js/cloudinary-dashboard.png
  articles/how-to-upload-images-to-cloudinary-using-node.js/hero.png
  articles/how-to-upload-images-to-cloudinary-using-node.js/index.md
  articles/how-to-upload-images-to-cloudinary-using-node.js/plagiarism-check1.png
  articles/how-to-upload-images-to-cloudinary-using-node.js/plagiarism-check2.png
  articles/how-to-upload-images-to-cloudinary-using-node.js/recieved-file-cloudinary-Node.js.png
  articles/how-to-upload-images-to-cloudinary-using-node.js/uploader-landing-page.png
Labels: assigned for review, ready for final review, tech tutorial

#2163 Node.js Callback Concept
  articles/nodejs-callback-concept/hero.jpg
  articles/nodejs-callback-concept/index.md
  articles/nodejs-callback-concept/output1.PNG
  articles/nodejs-callback-concept/output2.PNG
Labels: assigned for review, ready for final review

#2126 Node.js vs Python for backend Development
  articles/nodejs-vs-python/hero.png
  articles/nodejs-vs-python/index.md
Labels: article, ready for final review

#2368 file name change
  content/articles/how-to-generate-qr-codes-using-nodejs/hero.jpg
  content/articles/how-to-generate-qr-codes-using-nodejs/index.md
  content/articles/how-to-generate-qr-codes-using-nodejs/indexejs-webpage.png
  content/articles/how-to-generate-qr-codes-using-nodejs/scanejs-webpage.png
  content/authors/francis-kaguongo/avatar.jpeg
  content/authors/francis-kaguongo/index.md
Labels: duplicate

#2179 Running and Managing Docker Containers
  content/articles/running-and-managing-docker/hero.jpg
  content/articles/running-and-managing-docker/index.md
Labels: ready for final review, tech tutorial

#2214 Getting started with Container as a Service
  content/articles/getting-started-with-container-as-a-service/hero.jpg
  content/articles/getting-started-with-container-as-a-service/index.md
Labels: article, ready for final review

#2132 Getting started with Strapi Node.js API CMS
  content/articles/getting-started-with-strapi/collection.png
  content/articles/getting-started-with-strapi/delete-item.png
  content/articles/getting-started-with-strapi/get-single-item.png
  content/articles/getting-started-with-strapi/hero.jpg
  content/articles/getting-started-with-strapi/index.md
  content/articles/getting-started-with-strapi/post-item.png
  content/articles/getting-started-with-strapi/postman-get.png
  content/articles/getting-started-with-strapi/publish.png
  content/articles/getting-started-with-strapi/relations.png
  content/articles/getting-started-with-strapi/strapi_first_launch.jpg
  content/articles/getting-started-with-strapi/update-item.png
Labels: assigned for review, ready for final review

#2110 Stripe checkout in flutter
  content/articles/stripe-checkout-in-flutter/choose-card.jpg
  content/articles/stripe-checkout-in-flutter/hero.jpg
  content/articles/stripe-checkout-in-flutter/index.md
  content/articles/stripe-checkout-in-flutter/logs.png
  content/articles/stripe-checkout-in-flutter/new-card.jpg
  content/articles/stripe-checkout-in-flutter/payments.png
  content/articles/stripe-checkout-in-flutter/select-method.jpg
Labels: assigned for review, ready for final review, tech tutorial

#2119 Worker Threads in Node.js
  content/articles/nodejs-worker-thread/hero.jpg
  content/articles/nodejs-worker-thread/index.md
Labels: assigned for review, ready for final review

#2328 Docker Security: Best Practices to Secure a Docker Container
  content/articles/best-practices-to-secure-a-docker-container/hero.jpg
  content/articles/best-practices-to-secure-a-docker-container/index.md
Labels: article, assigned for review, ready for final review

#2156 Push notifications in nodejs using service worker
  content/articles/push-notification-in-nodejs-using-service-worker/hero.png
  content/articles/push-notification-in-nodejs-using-service-worker/index.md
  content/articles/push-notification-in-nodejs-using-service-worker/notification.png
  content/authors/mercy-meave/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2183 Getting started with Webcam and Ipcam in Matlab
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/adds_on.png
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/hero.jpg
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/index.md
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/ip_address.jpg
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/package.jpg
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/paul1.png
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/paul2.png
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/playstore.jpg
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/server.jpg
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/signin.jpg
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/webcam.png
  content/articles/getting-started-with-webcam-and-ipcam-in-matlab/windows3_1.png
  content/authors/queenter-bruce/avatar.jpg
  content/authors/queenter-bruce/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2186 Understanding IPV4 and IPV6 protocols
  content/articles/internet-protocols/hero.jpg
  content/articles/internet-protocols/index.md
  content/articles/internet-protocols/version_one.jpeg
  content/articles/internet-protocols/version_two.jpeg
Labels: article, ready for final review

#2194 Working with Lists and Dictionaries in Python.
  content/articles/lists-and-dictionaries-in-python/hero.jpg
  content/articles/lists-and-dictionaries-in-python/index.md
  content/authors/duncan-ndegwa/avatar.jpg
  content/authors/duncan-ndegwa/index.md
Labels: good first article, ready for final review, tech tutorial

#2173 How to create charts in Node.js with billboard.js
  content/articles/nodejs-charts/basic-chart.png
  content/articles/nodejs-charts/categorical-chart.png
  content/articles/nodejs-charts/chart-types.png
  content/articles/nodejs-charts/hero.jpg
  content/articles/nodejs-charts/index.md
Labels: assigned for review, ready for final review

#2250 hilt android tutorial
  content/articles/hilt-android-tutorial/hero.jpg
  content/articles/hilt-android-tutorial/index.md
Labels: ready for final review, tech tutorial

#2268 Securing your Python application from hackers
  content/articles/securing-your-python-application-from-hackers/hero.png
  content/articles/securing-your-python-application-from-hackers/index.md
Labels: assigned for review, ready for final review

#2262 How to send SMS in Django using Twilio
  content/articles/how-to-send-sms-in-django-using-twilio/add-score.png
  content/articles/how-to-send-sms-in-django-using-twilio/admin.png
  content/articles/how-to-send-sms-in-django-using-twilio/django-admin.png
  content/articles/how-to-send-sms-in-django-using-twilio/hero.png
  content/articles/how-to-send-sms-in-django-using-twilio/index.md
  content/articles/how-to-send-sms-in-django-using-twilio/trial-number.png
  content/articles/how-to-send-sms-in-django-using-twilio/twilio-console.png
  content/articles/how-to-send-sms-in-django-using-twilio/twilio-sms.jpg
Labels: ready for final review, tech tutorial
