Repository section-engineering-education/engineering-education, pull requests merged in 2021-02, with the labels that each got.

#1315 Top Node.js Monitoring Tools
  articles/top-node.js-monitoring-tools/hero.jpg
  articles/top-node.js-monitoring-tools/index.md
Labels: ready for final review

#1207 Landmark Recognition Using Firebase ML in a Non-Expo React Native Application
  articles/react-native-firebase-landmark-recognition/env_setup.png
  articles/react-native-firebase-landmark-recognition/final_result.jpg
  articles/react-native-firebase-landmark-recognition/hero.jpg
  articles/react-native-firebase-landmark-recognition/index.md
  articles/react-native-firebase-landmark-recognition/with_image.jpg
Labels: ready for final review, tech tutorial

#1265 Group Operator in MongoDB
  articles/group-operator/hero.jpg
  articles/group-operator/index.md
  authors/harit-joshi/avatar.jpeg
  authors/harit-joshi/index.md
Labels: article, assigned for review, good first article, ready for final review

#1282 Fundamentals of Big Data Supply Chain
  articles/fundamentals-of-big-data-supply-chain/components-of-big-data-supply-chain.png
  articles/fundamentals-of-big-data-supply-chain/hero.jpg
  articles/fundamentals-of-big-data-supply-chain/index.md
Labels: article, ready for final review

#1288 SQL-user-defined-functions
  articles/sql-user-defined-functions/hero.jpg
  articles/sql-user-defined-functions/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1276 Understanding Memoization in JavaScript
  articles/an-introduction-to-memoization-in-javascript/fib1.png
  articles/an-introduction-to-memoization-in-javascript/graphic-1-3-1.png
  articles/an-introduction-to-memoization-in-javascript/hero.jpg
  articles/an-introduction-to-memoization-in-javascript/index.md
  articles/an-introduction-to-memoization-in-javascript/recursive-fib.jpg
Labels: assigned for review, ready for final review, tech tutorial

#1296 SimCLR: A Simple Framework for Contrastive Learning of Visual Representations
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/adjacent-views.PNG
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/contrastive-loss-function.PNG
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/different-augmentation-techniques.PNG
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/different-compositions-of-data-augmentations.PNG
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/global-to-local.PNG
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/hero.jpg
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/index.md
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/models-with-varied-depths-and-widths.PNG
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/self-supervised-vs-supervised.PNG
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/simclr-accuracy-results.PNG
  articles/simclr-a-simple-framework-for-contrastive-learning-of-visual-representations/training-with-different-batch-sizes-and-epochs.PNG
Labels: ready for final review, tech tutorial

#1094 Data Mining using CRISP-DM methodology
  articles/data-mining-using-crisp-dm-methodology/crisp-dm-framework.png
  articles/data-mining-using-crisp-dm-methodology/hero.jpg
  articles/data-mining-using-crisp-dm-methodology/index.md
  articles/data-mining-using-crisp-dm-methodology/statistics.PNG
  articles/data-mining-using-crisp-dm-methodology/summary.PNG
Labels: article, ready for final review

#1261 How to Carry Out Effective User Acceptance Testing (UAT)
  articles/how-to-carry-out-effective-user-acceptance-testing-uat/hero.jpg
  articles/how-to-carry-out-effective-user-acceptance-testing-uat/index.md
  articles/how-to-carry-out-effective-user-acceptance-testing-uat/software-process.jpg
Labels: assigned for review, ready for final review, tech review

#1177 Getting started with Java JDBC
  articles/java-jdbc/database_table_structure.png
  articles/java-jdbc/hero.jpg
  articles/java-jdbc/index.md
  authors/paul-juma/avatar.jpg
  authors/paul-juma/index.md
Labels: ready for final review

#1318 Understanding the Software Development Life Cycle (SDLC)
  articles/understanding-software-development-life-cycle/agile-model.jpg
  articles/understanding-software-development-life-cycle/hero.jpg
  articles/understanding-software-development-life-cycle/index.md
  articles/understanding-software-development-life-cycle/iterative-model.png
  articles/understanding-software-development-life-cycle/spiral-model.jpg
  articles/understanding-software-development-life-cycle/v-model.png
  articles/understanding-software-development-life-cycle/waterfall-model.png
Labels: ready for final review

#1319 Getting started with Kubernetes
  articles/introduction-to-kubernetes/deployment.png
  articles/introduction-to-kubernetes/hero.png
  articles/introduction-to-kubernetes/index.md
  articles/introduction-to-kubernetes/pod.png
Labels: ready for final review

#1322 Introduction to built-in data structures in Java
  articles/introduction-to-built-in-data-structures-in-java/hero.jpg
  articles/introduction-to-built-in-data-structures-in-java/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1325 Why Be Concerned About AI Safety?
  articles/ai-safety/hero.jpg
  articles/ai-safety/index.md
Labels: article, needs front matter, ready for final review

#1338 Introduction to Elastic Stack(ELK)
  articles/introduction-to-elastic-stack/beats-logo-color.png
  articles/introduction-to-elastic-stack/elastic-search-logo-color.png
  articles/introduction-to-elastic-stack/flow-diagram.png
  articles/introduction-to-elastic-stack/hero.jpg
  articles/introduction-to-elastic-stack/index.md
  articles/introduction-to-elastic-stack/kibana-logo-color.png
  articles/introduction-to-elastic-stack/logstash-logo-color.png
Labels: good first article, ready for final review

#1339 An Overview of Compiler Design
  articles/an-overview-of-compiler-design/compiler-design-architecture.jpg
  articles/an-overview-of-compiler-design/hero.jpg
  articles/an-overview-of-compiler-design/index.md
  articles/an-overview-of-compiler-design/language-processing-system.jpg
  articles/an-overview-of-compiler-design/phases-of-a-compiler.png
Labels: article, assigned for review, ready for final review

#1340 A beginners guide to python
  articles/a-beginners-guide-to-python/hero.jpg
  articles/a-beginners-guide-to-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1342 Node.js CLI Input
  articles/nodejs-cli-input/hero.jpg
  articles/nodejs-cli-input/index.md
Labels: ready for final review, tech tutorial

#1344 Android paging library
  articles/android-paging-library/hero.png
  articles/android-paging-library/index.md
Labels: ready for final review

#1365 Deconstructing Shared Nothing and Shared Disk Clustering Architectures
  articles/deconstructing-shared-nothing-and-shared-disk-clustering-architectures/hero.jpg
  articles/deconstructing-shared-nothing-and-shared-disk-clustering-architectures/index.md
Labels: article, ready for final review

#1367 The Overview of a Database Life Cycle
  articles/the-overview-of-a-database-life-cycle/hero.jpg
  articles/the-overview-of-a-database-life-cycle/index.md
Labels: ready for final review

#1336 Understanding min heap vs max heap in JavaScript
  articles/understanding-min-heap-vs-max-heap/hero.jpg
  articles/understanding-min-heap-vs-max-heap/index.md
  articles/understanding-min-heap-vs-max-heap/max-heap-implementation.jpg
  articles/understanding-min-heap-vs-max-heap/max-heap.jpg
  articles/understanding-min-heap-vs-max-heap/min-heap-implementation.jpg
  articles/understanding-min-heap-vs-max-heap/min-heap.jpg
Labels: assigned for review, ready for final review

#1380 Introduction to Grails Development with IntellJ
  articles/introduction-to-grails-development-with-Intellij/grails-create-app.png
  articles/introduction-to-grails-development-with-Intellij/grails-first-web-app.PNG
  articles/introduction-to-grails-development-with-Intellij/grails-intellij-view.PNG
  articles/introduction-to-grails-development-with-Intellij/grails-run-app.PNG
  articles/introduction-to-grails-development-with-Intellij/grails-views-data.PNG
  articles/introduction-to-grails-development-with-Intellij/hero.jpg
  articles/introduction-to-grails-development-with-Intellij/index.md
Labels: assigned for review, ready for final review

#1412 An Overview of Database Testing
  articles/an-overview-of-database-testing/hero.jpg
  articles/an-overview-of-database-testing/index.md
  articles/an-overview-of-database-testing/types-of-database-testing.jpg
Labels: article, assigned for review, ready for final review

#1414 How Kubernetes Pods Work
  articles/how-kubernetes-pods-work/hero.jpg
  articles/how-kubernetes-pods-work/index.md
Labels: article, assigned for review, ready for final review

#1423 Getting started with Spring Data JPA in Kotlin
  articles/spring-data/hero.jpg
  articles/spring-data/index.md
  articles/spring-data/relationship.png
Labels: ready for final review

#1432 Introduction to javascript Modules
  articles/introduction-to-javascript-modules/hero.jpg
  articles/introduction-to-javascript-modules/index.md
Labels: article, ready for final review, tech tutorial

#1427 Implementing caching in Node.js using redis
  articles/implementing-caching-in-nodejs-using-redis/hero.jpg
  articles/implementing-caching-in-nodejs-using-redis/index.md
Labels: ready for final review, tiered payout

#1422 Introduction to OpenFlow protocol
  articles/openflow-sdn/hero.png
  articles/openflow-sdn/index.md
Labels: article, enhancement

#1402 Cookie Vs Token-based authentication
  articles/cookie-token-auth/hero.jpg
  articles/cookie-token-auth/index.md
Labels: assigned for review, duplicate, ready for final review

#1292 How to Build an Image Classifier with Keras
  articles/image-classifier-keras/1.JPG
  articles/image-classifier-keras/10.JPG
  articles/image-classifier-keras/11.JPG
  articles/image-classifier-keras/12.JPG
  articles/image-classifier-keras/13.JPG
  articles/image-classifier-keras/14.JPG
  articles/image-classifier-keras/15.JPG
  articles/image-classifier-keras/16.JPG
  articles/image-classifier-keras/17.JPG
  articles/image-classifier-keras/18.JPG
  articles/image-classifier-keras/19.JPG
  articles/image-classifier-keras/21.JPG
  articles/image-classifier-keras/22.JPG
  articles/image-classifier-keras/23.JPG
  articles/image-classifier-keras/4.JPG
  articles/image-classifier-keras/5.JPG
  articles/image-classifier-keras/6.JPG
  articles/image-classifier-keras/7.JPG
  articles/image-classifier-keras/8.JPG
  articles/image-classifier-keras/9.JPG
  articles/image-classifier-keras/hero.jpg
  articles/image-classifier-keras/index.md
  articles/image-classifier-keras/runtime.jpg
  articles/image-classifier-keras/runtime2.jpg
  articles/image-classifier-keras/runtime3.jpg
  authors/iniabasi-affiah/avatar.JPG
  authors/iniabasi-affiah/index.md
Labels: good first article, needs front matter, ready for final review, tech tutorial

#1456 Understanding the Basics of Responsive Web Design (RWD)
  articles/understanding-the-basics-of-responsive-web-design/adding-wordpress-theme.png
  articles/understanding-the-basics-of-responsive-web-design/amazon-via-laptop-browser.png
  articles/understanding-the-basics-of-responsive-web-design/amazon-via-mobile-browser.jpg
  articles/understanding-the-basics-of-responsive-web-design/bmw-via-laptop-browser.png
  articles/understanding-the-basics-of-responsive-web-design/bmw-via-mobile-browser.jpg
  articles/understanding-the-basics-of-responsive-web-design/hero.jpg
  articles/understanding-the-basics-of-responsive-web-design/importing-demo-content.jpg
  articles/understanding-the-basics-of-responsive-web-design/index.md
  articles/understanding-the-basics-of-responsive-web-design/installing-a-theme.jpg
  articles/understanding-the-basics-of-responsive-web-design/installing-plugins.jpg
  articles/understanding-the-basics-of-responsive-web-design/oshine-theme.png
  articles/understanding-the-basics-of-responsive-web-design/youtube-via-laptop-browser.png
  articles/understanding-the-basics-of-responsive-web-design/youtube-via-mobile-browser.jpg
Labels: assigned for review, ready for final review, tech tutorial

#1461 Regularization to Prevent Overfitting
  articles/regularization-to-prevent-overfitting/hero.jpg
  articles/regularization-to-prevent-overfitting/index.md
  articles/regularization-to-prevent-overfitting/overfitting.png
Labels: article, assigned for review, ready for final review

#1487 Introduction to Kotlin flows
  articles/introduction-to-kotlin-flows/hero.jpg
  articles/introduction-to-kotlin-flows/index.md
  articles/introduction-to-kotlin-flows/new-project.png
Labels: assigned for review, ready for final review

#1471 Consuming unsplash API using Node.js graphql API
  articles/consuming-unsplash-api-using-node.js-graphql-api/hero.jpg
  articles/consuming-unsplash-api-using-node.js-graphql-api/index.md
Labels: ready for final review

#1293 Connecting Basic4Android (B4A) Application to PHP and MySQL Database
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/add-http-library.PNG
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/b4a-create-new-default-application.png
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/button-editText-design.png
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/create-database.png
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/hero.jpg
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/index.md
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/ipconfig-b4a.png
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/project-path.PNG
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/url-php-api.png
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/xampp-fifth-window.PNG
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/xampp-first-installation.PNG
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/xampp-fourth-language-selection.PNG
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/xampp-second-pick-components.PNG
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/xampp-seventh-installation-process.PNG
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/xampp-sixth-window.PNG
  articles/connecting-basic4android-b4a-application-with-php-and-mysql-database/xampp-third-folder-selection.PNG
Labels: assigned for review, ready for final review, tiered payout

#1453 Android Nested RecyclerView
  articles/android-nested-recycler-view/google-play-store-nested-recyclerview.jpg
  articles/android-nested-recycler-view/hero.jpg
  articles/android-nested-recycler-view/index.md
  articles/android-nested-recycler-view/music-app-nested-recycler-view.png
  articles/android-nested-recycler-view/nested-recycler-view.gif
  articles/android-nested-recycler-view/netflix-nested-recycler-view.png
Labels: assigned for review, ready for final review

#1297 Choosing between Managed WordPress vs Shared WordPress Hosting
  articles/choosing-between-managed-wordpress-vs-shared-wordpress-hosting/hero.jpg
  articles/choosing-between-managed-wordpress-vs-shared-wordpress-hosting/index.md
Labels: assigned for review, ready for final review

#1467 An All-In-One Spring Security Crash Course For Java Developers
  articles/an-all-in-one-spring-security-crash-course-for-java-developers/hero.jpg
  articles/an-all-in-one-spring-security-crash-course-for-java-developers/index.md
  articles/an-all-in-one-spring-security-crash-course-for-java-developers/oauth-with-github-config.png
  articles/an-all-in-one-spring-security-crash-course-for-java-developers/oauth-with-github-page.png
Labels: assigned for review, needs front matter, ready for final review

#1468 How to Create a Dataset for Machine Learning
  articles/how-to-create-a-dataset-for-machine-learning/hero.jpg
  articles/how-to-create-a-dataset-for-machine-learning/index.md
Labels: article, assigned for review, ready for final review

#1472 AJAX request in Django (Using Axios)
  articles/ajax-request-in-django-using-axios/form_page.png
  articles/ajax-request-in-django-using-axios/hero.jpg
  articles/ajax-request-in-django-using-axios/index.md
Labels: ready for final review

#1538 Update React Native Firebase ML Article Titles
  articles/react-native-firebase-image-labeling/index.md
  articles/react-native-firebase-landmark-recognition/index.md
  articles/react-native-firebase-text-recognition/index.md
Labels: article update

#1474 Fork() in C programming language
  articles/fork-in-C-programming-language/ProcessState.jpg
  articles/fork-in-C-programming-language/fork.png
  articles/fork-in-C-programming-language/fork1.png
  articles/fork-in-C-programming-language/fork2.png
  articles/fork-in-C-programming-language/hero.jpg
  articles/fork-in-C-programming-language/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1482 Phone Number Authentication using Firebase in React Native
  articles/react-native-firebase-phone-authentication/advAPI.png
  articles/react-native-firebase-phone-authentication/auth_get_starterd.png
  articles/react-native-firebase-phone-authentication/download_services.json.png
  articles/react-native-firebase-phone-authentication/enabled.png
  articles/react-native-firebase-phone-authentication/env_setup.png
  articles/react-native-firebase-phone-authentication/firebase_new.png
  articles/react-native-firebase-phone-authentication/folder_structure.png
  articles/react-native-firebase-phone-authentication/hero.jpg
  articles/react-native-firebase-phone-authentication/index.md
  articles/react-native-firebase-phone-authentication/new_dashboard.png
  articles/react-native-firebase-phone-authentication/package_name.png
  articles/react-native-firebase-phone-authentication/recaptcha.gif
  articles/react-native-firebase-phone-authentication/register_app.png
  articles/react-native-firebase-phone-authentication/safetynet.gif
  articles/react-native-firebase-phone-authentication/screens.jpg
  articles/react-native-firebase-phone-authentication/signout.gif
  articles/react-native-firebase-phone-authentication/test_phone.png
Labels: ready for final review, tech tutorial

#1226 Pure Node.js? Node.js Without Frameworks? An Overview
  articles/pure-node-js-no-frameworks-or-packages/hero.jpg
  articles/pure-node-js-no-frameworks-or-packages/index.md
  articles/pure-node-js-no-frameworks-or-packages/most-popular-language.jpg
  articles/pure-node-js-no-frameworks-or-packages/most-wanted-technology.jpg
  articles/pure-node-js-no-frameworks-or-packages/node-js-download-metrics.jpg
  articles/pure-node-js-no-frameworks-or-packages/popular-technologies.jpg
  articles/pure-node-js-no-frameworks-or-packages/server-response.jpg
  articles/pure-node-js-no-frameworks-or-packages/server-running.jpg
Labels: assigned for review, enhancement, ready for final review, tech review, tech tutorial, tiered payout

#1313 Hash Table implementation using CRC32 algorithm
  articles/hashtables-implementation-using-CRC32-algorithm/hero.jpg
  articles/hashtables-implementation-using-CRC32-algorithm/index.md
  authors/jerim-kaura/avatar.jpg
  authors/jerim-kaura/index.md
Labels: good first article, ready for final review, tech tutorial

#1327 native vs hybrid app article
  articles/choose-native-vs-hybrid/hero.jpg
  articles/choose-native-vs-hybrid/index.md
Labels: assigned for review, ready for final review, tiered payout

#1347 Implementing Flask WTForm
  articles/implementing-flask-wtform/form_displayraw.jpg
  articles/implementing-flask-wtform/hello_world.jpg
  articles/implementing-flask-wtform/hero.jpg
  articles/implementing-flask-wtform/index.md
Labels: needs front matter, needs hero image, ready for final review, tech tutorial

#1371 Python Projects for Beginners Part 1
  articles/python-projects-for-beginners/Input.PNG
  articles/python-projects-for-beginners/Input2.JPG
  articles/python-projects-for-beginners/RPS.png
  articles/python-projects-for-beginners/guessinggame.png
  articles/python-projects-for-beginners/hero.jpg
  articles/python-projects-for-beginners/index.md
Labels: ready for final review, tech tutorial

#1375 Mobile Automation Testing with Appium: An Introduction
  articles/mobile-automation-testing-with-appium/appium-architecture.jpg
  articles/mobile-automation-testing-with-appium/appium-on-android.png
  articles/mobile-automation-testing-with-appium/appium-on-ios.png
  articles/mobile-automation-testing-with-appium/hero.jpg
  articles/mobile-automation-testing-with-appium/index.md
Labels: article, assigned for review, ready for final review

#1388 How to implement material-ui in React
  articles/how-to-implement-material-ui-in-react/hero.png
  articles/how-to-implement-material-ui-in-react/index.md
Labels: ready for final review, tech tutorial

#1477 Introduction to C++ namespace
  articles/introduction-to-c++-namespace/hero.jpg
  articles/introduction-to-c++-namespace/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1478 Create Login and Register System with C# Winforms
  articles/create-login-and-register-system-with-csharp-winforms/add-mysql-lib-vs.jpg
  articles/create-login-and-register-system-with-csharp-winforms/create-db-cmd.PNG
  articles/create-login-and-register-system-with-csharp-winforms/create-table-cmd.PNG
  articles/create-login-and-register-system-with-csharp-winforms/hero.jpg
  articles/create-login-and-register-system-with-csharp-winforms/index.md
  articles/create-login-and-register-system-with-csharp-winforms/login-interface.jpg
  articles/create-login-and-register-system-with-csharp-winforms/register-interface.jpg
Labels: ready for final review, tiered payout

#1484 Getting started with Alert Dialog in Android-Kotlin
  articles/getting-started-with-dialogs-in-android-kotlin/buttons.png
  articles/getting-started-with-dialogs-in-android-kotlin/default-dialog.png
  articles/getting-started-with-dialogs-in-android-kotlin/empty-dialog.png
  articles/getting-started-with-dialogs-in-android-kotlin/hero.png
  articles/getting-started-with-dialogs-in-android-kotlin/index.md
  articles/getting-started-with-dialogs-in-android-kotlin/round-dialog.png
Labels: ready for final review

#1393 Verifying Website Domains
  articles/verifying-website-domains/dns-ns.jpg
  articles/verifying-website-domains/dns-ptr.jpg
  articles/verifying-website-domains/dns-txt-mx.jpg
  articles/verifying-website-domains/hero.jpg
  articles/verifying-website-domains/index.md
  articles/verifying-website-domains/power-curl-domains.jpg
  articles/verifying-website-domains/power-curl.jpg
  articles/verifying-website-domains/socket1.jpg
  articles/verifying-website-domains/socket2.jpg
  articles/verifying-website-domains/whois-invalid.jpg
  articles/verifying-website-domains/whois-valid.jpg
  authors/priya-kalyanakrishnan/avatar.jpg
  authors/priya-kalyanakrishnan/index.md
Labels: good first article, ready for final review

#1490 How to Set Up CI/CD in a Vue Project with Firebase Hosting and GitHub Actions
  1.png
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/1-create-new-vue-project-with-cli.png
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/10-github-actions-workflow-files.jpg
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/11-testing-deployment-result-1.png
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/2-set-up-new-vue-project-with-cli.png
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/3-first-vue-hello-world-app.png
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/4-create-new-github-repo.png
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/5-create-new-firebase-app.jpg
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/6-firebase-dashboard.jpg
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/7-create-new-firebase-cli-app.jpg
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/8-setup-new-firebase-cli-app.jpg
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/9-setup-ci-cd-in-firebase-cli-2.jpg
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/9-setup-ci-cd-in-firebase-cli-3.jpg
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/9-setup-ci-cd-in-firebase-cli.jpg
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/hero.png
  articles/how-to-setup-ci-cd-to-vue-with-firebase-hosting-and-github-actions/index.md
Labels: assigned for review, preliminary revision in progress, ready for final review

#1493 How To Build A Music Player Using Django
  articles/how-to-build-a-music-player-using-django/admin_home.PNG
  articles/how-to-build-a-music-player-using-django/adminpage.PNG
  articles/how-to-build-a-music-player-using-django/createuser.PNG
  articles/how-to-build-a-music-player-using-django/db_Seen.PNG
  articles/how-to-build-a-music-player-using-django/final_image_music.PNG
  articles/how-to-build-a-music-player-using-django/hero.jpg
  articles/how-to-build-a-music-player-using-django/index.md
  articles/how-to-build-a-music-player-using-django/mvt.png
  articles/how-to-build-a-music-player-using-django/new_admin_add.PNG
  articles/how-to-build-a-music-player-using-django/runapp.PNG
  articles/how-to-build-a-music-player-using-django/structure.PNG
  articles/how-to-build-a-music-player-using-django/sucess_migrate.PNG
  authors/onojakpor-ochuko/avatar.jpg
  authors/onojakpor-ochuko/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1499 Implementing a Splash screen and Introduction Sliders in Android.
  articles/implementing-a-splash-screen-and-introduction-sliders-in-android/hero.jpg
  articles/implementing-a-splash-screen-and-introduction-sliders-in-android/index.md
  articles/implementing-a-splash-screen-and-introduction-sliders-in-android/intro.gif
  articles/implementing-a-splash-screen-and-introduction-sliders-in-android/new.jpg
  articles/implementing-a-splash-screen-and-introduction-sliders-in-android/splash.jpg
Labels: assigned for review, ready for final review

#1500 Understand Loss Functions in ML
  articles/understanding-loss-functions-in-machine-learning/binary-cross-entropy-loss.PNG
  articles/understanding-loss-functions-in-machine-learning/hero.jpg
  articles/understanding-loss-functions-in-machine-learning/hinge-loss.png
  articles/understanding-loss-functions-in-machine-learning/huber-loss.PNG
  articles/understanding-loss-functions-in-machine-learning/index.md
  articles/understanding-loss-functions-in-machine-learning/kl-divergence-loss.PNG
  articles/understanding-loss-functions-in-machine-learning/mean-absolute-error.PNG
  articles/understanding-loss-functions-in-machine-learning/mean-bias-error.png
  articles/understanding-loss-functions-in-machine-learning/mean-squared-error.PNG
  articles/understanding-loss-functions-in-machine-learning/mean-squared-loss-error.PNG
  articles/understanding-loss-functions-in-machine-learning/svm.png
Labels: article, assigned for review, ready for final review

#1439 Getting started with Spring Data MongoDB in Kotlin
  articles/spring-data-mongodb/hero.jpg
  articles/spring-data-mongodb/index.md
  articles/spring-data-mongodb/mongo-atlas-create-user.png
  articles/spring-data-mongodb/mongo-db-collection.png
  articles/spring-data-mongodb/mongo-db-connection-string.png
Labels: assigned for review, ready for final review

#1384 Introduction To Network Management
  articles/getting-started-with-network-management/hero.jpg
  articles/getting-started-with-network-management/hierarchical-nms.jpg
  articles/getting-started-with-network-management/index.md
Labels: article, assigned for review, good first article, ready for final review, ready for review, tiered payout

#1419 Vision Transformer (ViT): Using Transformers for Image Recognition
  articles/vision-transformer-using-transformers-for-image-recognition/examples-of-attention-maps.PNG
  articles/vision-transformer-using-transformers-for-image-recognition/hero.jpg
  articles/vision-transformer-using-transformers-for-image-recognition/image-sequence.PNG
  articles/vision-transformer-using-transformers-for-image-recognition/index.md
  articles/vision-transformer-using-transformers-for-image-recognition/main-results.PNG
  articles/vision-transformer-using-transformers-for-image-recognition/pre-trained-dataset-results.PNG
  articles/vision-transformer-using-transformers-for-image-recognition/representatative-examples.PNG
  articles/vision-transformer-using-transformers-for-image-recognition/vision-transformer-model-overview.PNG
  articles/vision-transformer-using-transformers-for-image-recognition/vtab-accuracy-performance.PNG
Labels: article, ready for final review

#1312 Building a Cryptocurrency Tracking Telegram Bot with Python
  articles/cryptocurrency-tracking-telegram-bot/2en1wn0m-8gcycfjmtvs.png
  articles/cryptocurrency-tracking-telegram-bot/2frh-rcjna_zv5g1epn7.png
  articles/cryptocurrency-tracking-telegram-bot/3svqucj7ez1ntgridksb.png
  articles/cryptocurrency-tracking-telegram-bot/a6kvxsmfgq_slhwtwp5z.png
  articles/cryptocurrency-tracking-telegram-bot/drowpxw1kqxlc2sw7ct8.png
  articles/cryptocurrency-tracking-telegram-bot/foniwp8tirtgmrqugcxc.png
  articles/cryptocurrency-tracking-telegram-bot/hero.jpg
  articles/cryptocurrency-tracking-telegram-bot/index.md
  articles/cryptocurrency-tracking-telegram-bot/iqzwzfv5gdstworaokgj.png
  articles/cryptocurrency-tracking-telegram-bot/ngcq6rvjxrpoibsspq9g.png
  articles/cryptocurrency-tracking-telegram-bot/ru4lx8fvo0u5nnmmp5bj.png
  articles/cryptocurrency-tracking-telegram-bot/w9cqynzuungmtirs_gg6.png
  authors/solomon-esenyi/avatar.jpg
  authors/solomon-esenyi/index.md
Labels: good first article, ready for final review, tech tutorial

#1314 Introduction To Network Analysis Using Wireshark
  articles/introduction-to-wireshark/configure-wireshark.jpg
  articles/introduction-to-wireshark/hero.jpg
  articles/introduction-to-wireshark/index.md
  articles/introduction-to-wireshark/wireshark-bytes-panel.jpg
  articles/introduction-to-wireshark/wireshark-live-capture.jpg
  articles/introduction-to-wireshark/wireshark-network-interface.jpg
  articles/introduction-to-wireshark/wireshark-network-interfaces-2.jpg
  articles/introduction-to-wireshark/wireshark-protocol-details.jpg
  articles/introduction-to-wireshark/wireshark-single-packet-details.jpg
  articles/introduction-to-wireshark/wireshark-window .jpg
  articles/nmap-network-scanner/hero.jpg
Labels: ready for final review, tech tutorial, tiered payout

#1326 Problem Framing in Machine Learning
  articles/problem-framing/hero.jpg
  articles/problem-framing/index.md
Labels: article, ready for final review

#1437 Breaking Down Kubernetes vs Docker Swarm
  articles/breaking-down-kubernetes-vs-docker-swarm/hero.jpg
  articles/breaking-down-kubernetes-vs-docker-swarm/index.md
Labels: article, needs front matter, ready for final review

#1564 fixed typos in code
  articles/cryptocurrency-tracking-telegram-bot/index.md
Labels: article update

#1444 Understanding Dijkstra's Shortest Path Algorithm in Network Routing using Python
  articles/dijkstra-python/dir-undir-graph.png
  articles/dijkstra-python/eigth-illustration.png
  articles/dijkstra-python/fifth-illustration.png
  articles/dijkstra-python/first-illustration.png
  articles/dijkstra-python/fourth-illustration.png
  articles/dijkstra-python/graph-1.png
  articles/dijkstra-python/hero.jpg
  articles/dijkstra-python/index.md
  articles/dijkstra-python/second-illustration.png
  articles/dijkstra-python/seventh-illustration.png
  articles/dijkstra-python/sixth-illustration.png
  articles/dijkstra-python/third-illustration.png
  articles/dijkstra-python/weighted-graph.png
Labels: ready for final review, tech tutorial

#1383 Implementing Bottom Sheet Dialogs Using Android Studio
  articles/bottom-sheet-dialogs-using-android-studio/bottom-sheet-peek-height.jpg
  articles/bottom-sheet-dialogs-using-android-studio/bottom-sheet.jpg
  articles/bottom-sheet-dialogs-using-android-studio/google-drive-modal-bottom-sheet.png
  articles/bottom-sheet-dialogs-using-android-studio/google-map-bottom-sheet.png
  articles/bottom-sheet-dialogs-using-android-studio/hero.jpg
  articles/bottom-sheet-dialogs-using-android-studio/index.md
  articles/bottom-sheet-dialogs-using-android-studio/modal-bottom-sheet-fragment.jpg
  articles/bottom-sheet-dialogs-using-android-studio/modal-dialog.gif
  articles/bottom-sheet-dialogs-using-android-studio/payment-bottom-sheet-dialog.jpg
  articles/bottom-sheet-dialogs-using-android-studio/persistent-dialog.gif
Labels: ready for final review

#1491 StyleGAN: A Style-Based Generator Architecture for Generative Adversarial Networks
  articles/stylegan-a-style-based-generator-architecture-for-gans/adaptive-instance-normalization.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/batch-instance-adin.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/batch-normalization-vs-instance-normalization.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/batch-normalization.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/effect-of-varying-noise-vector.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/fid-score.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/hero.jpg
  articles/stylegan-a-style-based-generator-architecture-for-gans/index.md
  articles/stylegan-a-style-based-generator-architecture-for-gans/instance-normalization.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/mixing-regularization.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/the-ffhq-dataset-variation.PNG
  articles/stylegan-a-style-based-generator-architecture-for-gans/traditional-vs-style-based-generator.PNG
Labels: needs front matter, ready for final review

#1463 Understanding TCP/IP Transport Layer (Layer 3) protocols:TCP and UDP
  articles/understanding-tcp-ip-transport-layer-protocols/handshake.png
  articles/understanding-tcp-ip-transport-layer-protocols/hero.jpg
  articles/understanding-tcp-ip-transport-layer-protocols/index.md
  articles/understanding-tcp-ip-transport-layer-protocols/tcp.png
  articles/understanding-tcp-ip-transport-layer-protocols/termination.png
  articles/understanding-tcp-ip-transport-layer-protocols/udp.png
  authors/rabo-james-bature/avatar.jpg
  authors/rabo-james-bature/index.md
Labels: article, assigned for review, good first article, ready for final review

#1498 Title: A Friendly Beginner's Guide to TypeScript
  articles/a-friendly-beginner-guide-to-typescript/hero.png
  articles/a-friendly-beginner-guide-to-typescript/index.md
  articles/a-friendly-beginner-guide-to-typescript/typescript-feature-img.jpg
  authors/idris-olubisi/avatar.jpeg
  authors/idris-olubisi/index.md
Labels: duplicate, ready for final review

#1509 Introduction to kotlin ktor
  articles/introduction-to-kotlin-ktor/hero.jpg
  articles/introduction-to-kotlin-ktor/index.md
  articles/introduction-to-kotlin-ktor/start.png
  authors/linus-muema/index.md
Labels: ready for final review

#1514 Creating Your First Android Application on Android Studio.
  articles/first-android-app/avd-manager.png
  articles/first-android-app/configure-project.png
  articles/first-android-app/display-page.png
  articles/first-android-app/empty-activity.png
  articles/first-android-app/hero.jpg
  articles/first-android-app/index.md
  articles/first-android-app/input-page.png
  articles/first-android-app/physical-device.png
Labels: ready for final review

#1506 Getting Started With Datastore In Kotlin
  articles/getting-started-with-datastore-in-kotlin/dark-mode.png
  articles/getting-started-with-datastore-in-kotlin/hero.jpg
  articles/getting-started-with-datastore-in-kotlin/index.md
  articles/getting-started-with-datastore-in-kotlin/light-mode.png
  authors/carol-musyoka/avatar.jpg
  authors/carol-musyoka/index.md
Labels: assigned for review, ready for final review

#1528 Python Boto3 and Amazon DynamoDB Programming Tutorial
  articles/python-boto3-and-amazon-dynamodb-programming-tutorial/hero.jpg
  articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
Labels: assigned for review, ready for final review

#1517 CSS Flexbox vs CSS Grid
  articles/css-flexbox-vs-css-grid/column-gap-row-gap.png
  articles/css-flexbox-vs-css-grid/column-gap-wrapped.png
  articles/css-flexbox-vs-css-grid/column-gap.png
  articles/css-flexbox-vs-css-grid/extra-content.png
  articles/css-flexbox-vs-css-grid/flex-content-first.png
  articles/css-flexbox-vs-css-grid/flex-header-nav.png
  articles/css-flexbox-vs-css-grid/flex-horizontal-or-vertical.jpg
  articles/css-flexbox-vs-css-grid/gap-with-margin-wrapped.png
  articles/css-flexbox-vs-css-grid/gap-with-margin.png
  articles/css-flexbox-vs-css-grid/gap.png
  articles/css-flexbox-vs-css-grid/grid-and-flexible-wrapped.png
  articles/css-flexbox-vs-css-grid/grid-and-flexible.jpg
  articles/css-flexbox-vs-css-grid/grid-example.jpg
  articles/css-flexbox-vs-css-grid/grid-header-nav-layout-first-under-the-hood.png
  articles/css-flexbox-vs-css-grid/grid-header-nav-layout-first.png
  articles/css-flexbox-vs-css-grid/grid-header-nav.png
  articles/css-flexbox-vs-css-grid/grid-header-under-the-hood.png
  articles/css-flexbox-vs-css-grid/grid.png
  articles/css-flexbox-vs-css-grid/header-and-logo.jpg
  articles/css-flexbox-vs-css-grid/header-content.png
  articles/css-flexbox-vs-css-grid/hero.png
  articles/css-flexbox-vs-css-grid/horizontal.png
  articles/css-flexbox-vs-css-grid/images-section.png
  articles/css-flexbox-vs-css-grid/index.md
  articles/css-flexbox-vs-css-grid/nav-header-content.png
  articles/css-flexbox-vs-css-grid/subscribe-form.jpg
  articles/css-flexbox-vs-css-grid/subscribe.gif
  articles/css-flexbox-vs-css-grid/vertical.png
  articles/css-flexbox-vs-css-grid/web-design-implemented.png
  articles/css-flexbox-vs-css-grid/web-page-design-and-content-alignment.png
  articles/css-flexbox-vs-css-grid/web-page-under-the-hood.png
Labels: duplicate, ready for final review

#1329 Parametric versus Non-Parametric Models
  articles/parametric-vs-nonparametric/fit.png
  articles/parametric-vs-nonparametric/hero.jpg
  articles/parametric-vs-nonparametric/index.md
Labels: article, revisions needed

#1544 How to implement motion layout animation in android studio
  articles/how-to-implement-dark-mode-in-android-studio/index.md
  articles/how-to-implement-motion-layout-animation-in-android-studio/convert.png
  articles/how-to-implement-motion-layout-animation-in-android-studio/demo.gif
  articles/how-to-implement-motion-layout-animation-in-android-studio/design.png
  articles/how-to-implement-motion-layout-animation-in-android-studio/hero.jpg
  articles/how-to-implement-motion-layout-animation-in-android-studio/index.md
Labels: ready for final review

#1541 Understanding systemd
  articles/understanding-systemd/figure-1.png
  articles/understanding-systemd/figure-2.png
  articles/understanding-systemd/figure-3.png
  articles/understanding-systemd/figure-4.png
  articles/understanding-systemd/figure-5.png
  articles/understanding-systemd/figure-6.png
  articles/understanding-systemd/figure-7.png
  articles/understanding-systemd/hero.jpg
  articles/understanding-systemd/index.md
  authors/emmanuel-bashorun/avatar.jpg
  authors/emmanuel-bashorun/index.md
Labels: assigned for review, ready for final review

#1450 Laravel 8 Email Verification
  articles/laravel-8-email-verification/hero.jpg
  articles/laravel-8-email-verification/index.md
Labels: enhancement, ready for final review, tiered payout

#1426 The Development of 5G protocol standardization
  articles/the-development-of-5g-protocol-standardization/hero.jpg
  articles/the-development-of-5g-protocol-standardization/index.md
  authors/ruth-mare/avatar.JPG
  authors/ruth-mare/index.md
Labels: article, good first article, needs front matter, ready for final review

#1473 Getting started with game development using windows forms
  articles/getting-started-with-game-development-using-windows-forms/hero.jpg
  articles/getting-started-with-game-development-using-windows-forms/index.md
  articles/getting-started-with-game-development-using-windows-forms/mastermind_form.png
Labels: assigned for review, preliminary revision in progress, ready for final review

#1520 Understanding static and dynamic routing
  articles/understanding-static-dynamic-routing/bandwidth.jpg
  articles/understanding-static-dynamic-routing/default-route.jpg
  articles/understanding-static-dynamic-routing/float.JPG
  articles/understanding-static-dynamic-routing/hero.jpg
  articles/understanding-static-dynamic-routing/hop.jpg
  articles/understanding-static-dynamic-routing/index.md
  articles/understanding-static-dynamic-routing/load.jpg
  articles/understanding-static-dynamic-routing/static-route.jpg
  articles/understanding-static-dynamic-routing/summary-route.jpg
Labels: assigned for review, enhancement, ready for final review, tiered payout

#1543 How To Implement a custom scrollbar on a web page using CSS
  articles/custom-scroll-bar/hero.jpg
  articles/custom-scroll-bar/img_1.png
  articles/custom-scroll-bar/img_2.png
  articles/custom-scroll-bar/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1551 Introduction to Adafruit IO
  articles/introduction-to-adafruit-io/cloud-computing-features.jpg
  articles/introduction-to-adafruit-io/hero.jpg
  articles/introduction-to-adafruit-io/index.md
  articles/introduction-to-adafruit-io/result.gif
  articles/introduction-to-adafruit-io/uploading.png
Labels: ready for final review, tech tutorial

#1496 Editing Video with Python + MoviePy (tutorial) (non-conflict PR)
  articles/constraint-satisfaction-minizinc-gecode/United_States_Public_Domain_Map.jpg
  articles/constraint-satisfaction-minizinc-gecode/hero.jpg
  articles/constraint-satisfaction-minizinc-gecode/img1.png
  articles/constraint-satisfaction-minizinc-gecode/img2.png
  articles/constraint-satisfaction-minizinc-gecode/tsp.gif
  articles/video-editing-python-moviepy/hero.jpg
  articles/video-editing-python-moviepy/index.md
Labels: assigned for review, ready for final review, tech tutorial
