Repository section-engineering-education/engineering-education, pull requests merged in 2021-01, with the labels that each got.

#835 Stock price prediction using Python
  articles/stock-price-prediction-using-python/first.png
  articles/stock-price-prediction-using-python/hero.png
  articles/stock-price-prediction-using-python/index.md
  articles/stock-price-prediction-using-python/second.png
  articles/stock-price-prediction-using-python/third.png
Labels: assigned for review, preliminary revision in progress, ready for final review

#847 Understanding the LAMP Stack
  articles/lamp-stack/flowchart.png
  articles/lamp-stack/hero.jpg
  articles/lamp-stack/index.md
  articles/lamp-stack/lampstack.png
Labels: ready for final review

#935 Implementing Firebase's Realtime Database in a Flutter Application
  articles/implementing-firebase-in-flutter/add-app.png
  articles/implementing-firebase-in-flutter/console.png
  articles/implementing-firebase-in-flutter/create-database.png
  articles/implementing-firebase-in-flutter/find-package.png
  articles/implementing-firebase-in-flutter/firebaseresults.png
  articles/implementing-firebase-in-flutter/getting-started.png
  articles/implementing-firebase-in-flutter/hero.png
  articles/implementing-firebase-in-flutter/index.md
  articles/implementing-firebase-in-flutter/package-name.png
  articles/implementing-firebase-in-flutter/paste-json.png
  articles/implementing-firebase-in-flutter/project-name.png
  articles/implementing-firebase-in-flutter/ui.jpeg
Labels: assigned for review, ready for final review

#858 React Native Razorpay Integration
  articles/react-native-razorpay/alert_modal.jpeg
  articles/react-native-razorpay/checkout_form.jpeg
  articles/react-native-razorpay/create_order_request.png
  articles/react-native-razorpay/hero.jpg
  articles/react-native-razorpay/index.md
  articles/react-native-razorpay/payment_states.png
  articles/react-native-razorpay/razorpay_apikeys.png
  articles/react-native-razorpay/razorpay_dashboard.png
  articles/react-native-razorpay/razorpay_newkey.png
  articles/react-native-razorpay/razorpay_payment_flow.png
  articles/react-native-razorpay/razorpay_payments.png
  articles/react-native-razorpay/razorpay_settings.png
  articles/react-native-razorpay/signup-page.png
  articles/react-native-razorpay/starter_page.jpeg
  articles/react-native-razorpay/test_page.jpeg
Labels: enhancement

#849 Google Sheet Advanced Feature
  articles/google-sheet-advanced-features/collaboration-share.png
  articles/google-sheet-advanced-features/deploy-web-app.png
  articles/google-sheet-advanced-features/dev-addons.png
  articles/google-sheet-advanced-features/hero.png
  articles/google-sheet-advanced-features/index.md
  articles/google-sheet-advanced-features/link-form.png
  articles/google-sheet-advanced-features/mobile-app.png
  articles/google-sheet-advanced-features/offline-access.png
  authors/peter-ndegwa/avatar.png
  authors/peter-ndegwa/index.md
Labels: good first article, needs author page, ready for final review

#965 TensorFlow vs PyTorch: Which one to pick?
  articles/tensorflow-vs-pytorch/hero.png
  articles/tensorflow-vs-pytorch/index.md
Labels: ready for final review

#928 10 Powerful Business Intelligence Tools for Data Analysts
  articles/ten-powerful-bi-tools-for-data-analysts/bi-architecture.jpg
  articles/ten-powerful-bi-tools-for-data-analysts/clear-analytics.png
  articles/ten-powerful-bi-tools-for-data-analysts/domo-bi.png
  articles/ten-powerful-bi-tools-for-data-analysts/hero.jpg
  articles/ten-powerful-bi-tools-for-data-analysts/ibm-cognos-analytics.jpg
  articles/ten-powerful-bi-tools-for-data-analysts/index.md
  articles/ten-powerful-bi-tools-for-data-analysts/microstrategy.jpg
  articles/ten-powerful-bi-tools-for-data-analysts/power-bi.png
  articles/ten-powerful-bi-tools-for-data-analysts/qlikview.jpg
  articles/ten-powerful-bi-tools-for-data-analysts/sap.png
  articles/ten-powerful-bi-tools-for-data-analysts/sisense.png
  articles/ten-powerful-bi-tools-for-data-analysts/yellow-fin-bi.png
  articles/ten-powerful-bi-tools-for-data-analysts/zoho-analytics.jpg
Labels: assigned for review, ready for final review

#932 Introduction to theory of computation
  articles/introduction-to-theory-of-computation/hero.jpg
  articles/introduction-to-theory-of-computation/index.md
  authors/elly-omondi/avatar.jpg
  authors/elly-omondi/index.md
Labels: assigned for review, good first article, help wanted, ready for final review

#944 Working with forms in Django
  articles/working-with-forms-in-django/hero.jpg
  articles/working-with-forms-in-django/index.md
  articles/working-with-forms-in-django/register1.png
  articles/working-with-forms-in-django/register2.png
  articles/working-with-forms-in-django/register4.png
  articles/working-with-forms-in-django/settings.png
  authors/anita-achu/avatar.png
  authors/anita-achu/index.md
Labels: good first article

#967 Threading in workmanager
  articles/threading-workmanager/demo.png
  articles/threading-workmanager/hero.png
  articles/threading-workmanager/index.md
Labels: ready for final review

#948 Understand Hashing in Cryptography
  articles/understand-hashing-in-cryptography/hero.jpg
  articles/understand-hashing-in-cryptography/index.md
Labels: ready for final review

#949 Using Picasso in Android
  articles/using-picasso-in-android/app.gif
  articles/using-picasso-in-android/hero.jpg
  articles/using-picasso-in-android/index.md
  articles/using-picasso-in-android/name.jpg
Labels: assigned for review, ready for final review

#1005 All about fragments in android applications
  articles/all-about-fragments-in-android-applications/final-graph.png
  articles/all-about-fragments-in-android-applications/fragment-view-lifecycle.png
  articles/all-about-fragments-in-android-applications/hero.png
  articles/all-about-fragments-in-android-applications/index.md
  articles/all-about-fragments-in-android-applications/launch-project.png
  articles/all-about-fragments-in-android-applications/navigation-graph.png
Labels: needs front matter, ready for final review

#989 Making a simple GET request using Retrofit in Android
  articles/making-api-requests-using-retrofit-android/app.jpg
  articles/making-api-requests-using-retrofit-android/hero.jpg
  articles/making-api-requests-using-retrofit-android/index.md
  articles/making-api-requests-using-retrofit-android/name.jpg
Labels: needs front matter, ready for final review

#994 Firebase email and password authentication in Android using Kotlin
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/android-studio-config-project.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/android-studio-select-type.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/android-studio-welcome-screen.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/app-three-in-one.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-connect-to-firebase1.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-connected-fb-add-auth1.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-connected-fb-and-auth.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-firebase-assistant1.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-firebase-auth1.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-project-home-screen.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-sign-in-choose-account.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-sign-in-icon.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-sign-in-permission.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/as-sign-in-success.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-authenticated-users.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-choose-project-to-connect.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-connect-project2.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-console1.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-create-project-finish-up1.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-create-project-finish-up2.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-create-project-step0.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-create-project-step1.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-create-project-step2.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-enable-auth1.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-enable-auth2.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/firebase-project-connected-to-as.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/hero.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/index.md
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/org-complete.png
  articles/firebase-email-and-password-authentication-in-android-using-kotlin/org-packages.png
  authors/eric-gacoki/avatar.png
  authors/eric-gacoki/index.md
Labels: good first article, ready for final review

#1194 How to build a UI for your model using Streamlit
  articles/streamlit-ui-tutorial/hero.jpg
  articles/streamlit-ui-tutorial/index.md
  articles/streamlit-ui-tutorial/performance.png
  articles/streamlit-ui-tutorial/predict.png
  articles/streamlit-ui-tutorial/screencast.gif
  articles/streamlit-ui-tutorial/title.png
  authors/rahul-banerjee/avatar.jpg
  authors/rahul-banerjee/index.md
Labels: duplicate, good first article, ready for final review

#939 Building an Express Server for Agora Cloud Recording
  articles/agora-cloud-recording/cr_enabled.png
  articles/agora-cloud-recording/customer_secret.png
  articles/agora-cloud-recording/enable_cr.png
  articles/agora-cloud-recording/hero.jpg
  articles/agora-cloud-recording/index.md
  articles/agora-cloud-recording/max_concurrent_channels.png
  articles/agora-cloud-recording/postman_acquire.png
  articles/agora-cloud-recording/postman_start.png
  articles/agora-cloud-recording/restful_api.png
  articles/agora-cloud-recording/usage_button.png
Labels: ready for final review

#960 Build an Express Server to Query & Update Agora Cloud Recording Session
  articles/agora-cloud-recording-part-2/hero.jpg
  articles/agora-cloud-recording-part-2/index.md
Labels: tech review

#920 How to setup ci/cd to react with circle ci, aws s3, and aws cloud front
  1.png
  articles/ci-cd-setup-react/1-create-new-github-repo.png
  articles/ci-cd-setup-react/10-enable-the-static-hosting.png
  articles/ci-cd-setup-react/11-test-run-react-result.png
  articles/ci-cd-setup-react/12-circlecI-dashboard.png
  articles/ci-cd-setup-react/13-configuration-process-on-circleci.png
  articles/ci-cd-setup-react/14-work-on-deployment-branch.png
  articles/ci-cd-setup-react/15-setting-up-environment-variables.png
  articles/ci-cd-setup-react/16-click-on-project-settings.png
  articles/ci-cd-setup-react/17-add-environment-variable.png
  articles/ci-cd-setup-react/18-add-the-correct-variables.png
  articles/ci-cd-setup-react/19-setting-up-aws-cloudfront.png
  articles/ci-cd-setup-react/2-create-a-new-s3-bucket.png
  articles/ci-cd-setup-react/20-origin-domain-name.png
  articles/ci-cd-setup-react/21-in-progress-status.png
  articles/ci-cd-setup-react/22-final-result.png
  articles/ci-cd-setup-react/3-enter-the-bucket-name-and-choose-the-server-region.png
  articles/ci-cd-setup-react/4-make-the-bucket-mode-public.png
  articles/ci-cd-setup-react/5-select-the-permissions-tab.png
  articles/ci-cd-setup-react/6-turn-off-block-public-access.png
  articles/ci-cd-setup-react/7-go-to-my-security-credential.png
  articles/ci-cd-setup-react/8-create-a-new-access-key-and-download-the-key-file.png
  articles/ci-cd-setup-react/9-navigate-to-static-web-hosting.png
  articles/ci-cd-setup-react/hero.jpg
  articles/ci-cd-setup-react/index.md
Labels: revisions needed

#951 Implementing Lipa na Mpesa online using Node.js
  articles/lipa-na-mpesa-online/hero.jpg
  articles/lipa-na-mpesa-online/index.md
Labels: assigned for review, ready for final review

#1020 Is Node.js a good choice to create an App based on Micro-services?
  articles/microservices-and-nodejs/hero.jpg
  articles/microservices-and-nodejs/index.md
Labels: assigned for review, needs front matter, ready for final review

#899 Replication of PostgreSQL database
  articles/how-to-replicate-postgresql-database/hero.jpg
  articles/how-to-replicate-postgresql-database/index.md
  articles/how-to-replicate-postgresql-database/internet-network.png
  articles/how-to-replicate-postgresql-database/local-network.png
  articles/how-to-replicate-postgresql-database/pg_hba-edit.png
  articles/how-to-replicate-postgresql-database/postgres-login.png
  articles/how-to-replicate-postgresql-database/slavepg_hbaedit.png
  authors/sylvester-tamba/avatar.jpg
  authors/sylvester-tamba/index.md
Labels: assigned for review, good first article, ready for final review

#914 Getting Started with AWS DynamoDB
  articles/getting-started-with-aws-dynamodb/aws-adding-iam-user.jpg
  articles/getting-started-with-aws-dynamodb/aws-cli-configure.jpg
  articles/getting-started-with-aws-dynamodb/aws-console-dynamodb-query.jpg
  articles/getting-started-with-aws-dynamodb/hero.jpg
  articles/getting-started-with-aws-dynamodb/index.md
Labels: ready for final review

#1202 Update Cloud Recording with Agora Article
  articles/agora-cloud-recording-part-2/hero.jpg
  articles/agora-cloud-recording/index.md
  articles/react-native-agora-livestreaming-app/env_setup.png
  articles/react-native-agora-livestreaming-app/index.md
  articles/react-native-agora-video-conference-app/env_setup.png
  articles/react-native-agora-video-conference-app/index.md
  articles/react-native-razorpay/env_setup.png
  articles/react-native-razorpay/index.md
Labels: article update

#954 Aggregation in Database Management Systems (DBMS)
  articles/aggregation-in-dbms/example-of-aggregation.jpg
  articles/aggregation-in-dbms/hero.jpg
  articles/aggregation-in-dbms/index.md
  articles/aggregation-in-dbms/process-flow-for-aggregation.jpg
Labels: assigned for review, ready for final review

#934 Introduction to Android Views and Viewgroups
  articles/introduction-to-android-views-and-view-groups/hero.png
  articles/introduction-to-android-views-and-view-groups/index.md
  articles/introduction-to-android-views-and-view-groups/screenshot-button.png
  articles/introduction-to-android-views-and-view-groups/screenshot-constraint-layout.png
  articles/introduction-to-android-views-and-view-groups/screenshot-edit-text.png
  articles/introduction-to-android-views-and-view-groups/screenshot-frame-layout.png
  articles/introduction-to-android-views-and-view-groups/screenshot-image-view.png
  articles/introduction-to-android-views-and-view-groups/screenshot-linear-layout.png
  articles/introduction-to-android-views-and-view-groups/screenshot-relative-layout.png
  articles/introduction-to-android-views-and-view-groups/screenshot-text-view.png
Labels: needs front matter, ready for final review

#966 Introduction To Solid Principle
  articles/introduction-to-solid-principle/hero.jpg
  articles/introduction-to-solid-principle/index.md
Labels: ready for final review, tiered payout

#985 Introduction to friend functions in C++
  articles/introduction-to-friend-functions-in-c++/hero.jpg
  articles/introduction-to-friend-functions-in-c++/index.md
Labels: assigned for review, ready for final review

#1045 How and when to apply session storage with JavaScript
  articles/how-and-when-to-apply-session-storage-with-JavaScript/hero.jpg
  articles/how-and-when-to-apply-session-storage-with-JavaScript/index.md
Labels: needs front matter, ready for final review

#1006 How to Protect your System against Ransomware as a Service (RaaS)
  articles/how-to-protect-your-system-against-ransomware-as-a-service-raas/hero.jpg
  articles/how-to-protect-your-system-against-ransomware-as-a-service-raas/index.md
Labels: ready for final review

#1016 MySQL with Node.js
  articles/mysql-with-node-js/add-more-rows.jpg
  articles/mysql-with-node-js/connection-established.png
  articles/mysql-with-node-js/custom-server.png
  articles/mysql-with-node-js/database-created.jpg
  articles/mysql-with-node-js/db-created.png
  articles/mysql-with-node-js/error.jpg
  articles/mysql-with-node-js/fields-updated.jpg
  articles/mysql-with-node-js/finish-installation.jpg
  articles/mysql-with-node-js/hero.png
  articles/mysql-with-node-js/index.md
  articles/mysql-with-node-js/install-setups.jpg
  articles/mysql-with-node-js/office-deleted.jpg
  articles/mysql-with-node-js/open-table.jpg
  articles/mysql-with-node-js/password.jpg
  articles/mysql-with-node-js/password.png
  articles/mysql-with-node-js/refresh.jpg
  articles/mysql-with-node-js/server-ready.png
  articles/mysql-with-node-js/server-running.jpg
  articles/mysql-with-node-js/server-test.jpg
  articles/mysql-with-node-js/start-installation.jpg
  articles/mysql-with-node-js/start-mysql-workbench.png
  articles/mysql-with-node-js/table-and-rows-created.jpg
  articles/mysql-with-node-js/view-table-rows.jpg
Labels: assigned for review, ready for final review

#1036 Understanding Variables In JavaScript
  articles/variables-in-js/hero.jpg
  articles/variables-in-js/index.md
  authors/caroline-gatwiri/avatar.jpg
  authors/caroline-gatwiri/index.md
Labels: assigned for review, good first article, ready for final review

#1024 Building local unit tests in android-kotlin
  articles/building-local-unit-tests-in-android-kotlin/app-name.png
  articles/building-local-unit-tests-in-android-kotlin/class-name.png
  articles/building-local-unit-tests-in-android-kotlin/hero.jpg
  articles/building-local-unit-tests-in-android-kotlin/index.md
  articles/building-local-unit-tests-in-android-kotlin/output.png
  articles/building-local-unit-tests-in-android-kotlin/test-source.png
  articles/building-local-unit-tests-in-android-kotlin/test.png
Labels: ready for final review

#1108 Introduction to Tailwind CSS
  articles/introduction-to-tailwind-css/hero.jpg
  articles/introduction-to-tailwind-css/index.md
  articles/introduction-to-tailwind-css/result.png
Labels: assigned for review, ready for final review

#1025 How to use local storage with JavaScript
  articles/how-to-use-local-storage-with-JavaScript/hero.jpg
  articles/how-to-use-local-storage-with-JavaScript/index.md
Labels: assigned for review, ready for final review

#975 How AIOps is transforming IT operations
  articles/how-aiops-is-transforming-it-operations/gartner-guide-for-aiops-platforms.jpg
  articles/how-aiops-is-transforming-it-operations/hero.jpg
  articles/how-aiops-is-transforming-it-operations/index.md
Labels: enhancement

#1246 Fix Image Links in React Native Articles
  articles/react-native-agora-video-conference-app/index.md
  articles/react-native-razorpay/index.md
Labels: article update

#1126 Speech Recognition using the Web Speech API in JavaScript
  articles/speech-recognition-in-javascript/final.gif
  articles/speech-recognition-in-javascript/hero.jpg
  articles/speech-recognition-in-javascript/index.md
  articles/speech-recognition-in-javascript/start_screen.png
Labels: assigned for review, needs plagiarism check, ready for final review

#1026 Creating a Django Hello World App Using PostgreSQL Database
  articles/django-app-using-postgresql-database/access_psql.png
  articles/django-app-using-postgresql-database/django_webpage.jpg
  articles/django-app-using-postgresql-database/hero.jpg
  articles/django-app-using-postgresql-database/homepage.png
  articles/django-app-using-postgresql-database/index.md
  articles/django-app-using-postgresql-database/postgresql_database.jpg
  articles/django-app-using-postgresql-database/psql_shell.png
  authors/adeyemi-atoyegbe/avatar.jpeg
  authors/adeyemi-atoyegbe/index.md
Labels: assigned for review, good first article, ready for final review

#1029 Mathematics for Machine Learning (ML)
  articles/mathematics-for-machine-learning/hero.jpg
  articles/mathematics-for-machine-learning/index.md
  articles/mathematics-for-machine-learning/math-topics.png
Labels: article, ready for final review

#1030 Reproducibility to Improve Machine Learning
  articles/reproducibility-machine-learning/hero.jpg
  articles/reproducibility-machine-learning/index.md
Labels: ready for final review

#1033 How to create CRUD API using Spring Boot
  articles/spring-boot-crud-api/create-todo.png
  articles/spring-boot-crud-api/delete-todo.png
  articles/spring-boot-crud-api/generate-project.png
  articles/spring-boot-crud-api/get-todo-by-id.png
  articles/spring-boot-crud-api/get-todos.png
  articles/spring-boot-crud-api/hero.jpg
  articles/spring-boot-crud-api/index.md
  articles/spring-boot-crud-api/project-structure.png
  articles/spring-boot-crud-api/update-todo.png
Labels: assigned for review, ready for final review

#1173 Getting started with NodeMCU
  articles/getting-started-with-nodemcu/hero.jpg
  articles/getting-started-with-nodemcu/index.md
  articles/getting-started-with-nodemcu/nodemcu.png
  articles/getting-started-with-nodemcu/pin-diagram.png
  articles/getting-started-with-nodemcu/result.gif
  articles/getting-started-with-nodemcu/uploading.png
Labels: assigned for review, ready for final review

#1034 Big O notation with Python
  articles/big-o-notation/hero.jpg
  articles/big-o-notation/index.md
  articles/big-o-notation/log-2-n.png
  articles/big-o-notation/n-square.png
  articles/big-o-notation/o-1.png
  articles/big-o-notation/o-n.png
Labels: assigned for review, good first article, ready for final review

#1038 Minimizing Data Leakage in Machine Learning
  articles/data-leakage/hero.jpg
  articles/data-leakage/index.md
Labels: article, needs front matter, ready for final review

#1054 How to execute Linux commands in python
  articles/how-to-execute-linux-commands-in-python/hero.jpeg
  articles/how-to-execute-linux-commands-in-python/index.md
  articles/how-to-execute-linux-commands-in-python/output.png
  articles/how-to-execute-linux-commands-in-python/servers.png
Labels: assigned for review, ready for final review

#1048 An Overview of Meta-Learning
  articles/meta-learning/hero.jpg
  articles/meta-learning/index.md
  articles/meta-learning/maml.png
Labels: article, ready for final review

#993 Getting started with Yii 2 PHP Framework
  articles/php-yii2-framework/1.png
  articles/php-yii2-framework/congratulations.png
  articles/php-yii2-framework/hero.jpg
  articles/php-yii2-framework/index.md
  articles/php-yii2-framework/web.png
  authors/erastus-muriithi/avatar.jpeg
  authors/erastus-muriithi/index.md
Labels: ready for final review

#1056 How AI predicted the coronavirus outbreak
  articles/how-ai-predicted-the-coronavirus-outbreak/hero.jpg
  articles/how-ai-predicted-the-coronavirus-outbreak/index.md
  articles/how-ai-predicted-the-coronavirus-outbreak/international-passengers-from-china.PNG
Labels: article, ready for final review

#1090 How to Generate Random Numbers in Python
  articles/random-number-genrator-python/hero.jpg
  articles/random-number-genrator-python/index.md
  articles/random-number-genrator-python/middle_squares.png
Labels: ready for final review, tech tutorial

#1058 How Artificial Intelligence has transformed the sports industry
  articles/how-artificial-intelligence-has-transformed-the-sports-industry/hero.jpg
  articles/how-artificial-intelligence-has-transformed-the-sports-industry/index.md
Labels: article, needs front matter, ready for final review

#1068 React Progressive Web App
  articles/react-progressive-web-application/hero.jpg
  articles/react-progressive-web-application/index.md
  articles/react-progressive-web-application/install.png
  articles/react-progressive-web-application/pwa-performance.png
  articles/react-progressive-web-application/react-pwa1.png
  articles/react-progressive-web-application/react-pwa2.png
  articles/react-progressive-web-application/requirements.png
  authors/wilson-gichuhi/avatar.jpeg
  authors/wilson-gichuhi/index.md
Labels: assigned for review, ready for final review

#1070 Choosing between Modern Data Warehouses: BigQuery vs Redshift vs Snowflake
  articles/choosing-between-modern-data-warehouses-bigquery-vs-redshift-vs-snowflake/hero.jpg
  articles/choosing-between-modern-data-warehouses-bigquery-vs-redshift-vs-snowflake/index.md
Labels: article, needs front matter, ready for final review

#1002 internationalization in django
  articles/internationalization-in-django/hero.jpg
  articles/internationalization-in-django/index.md
  authors/ifenna-okoye/avatar.jpg
  authors/ifenna-okoye/index.md
Labels: good first article, needs author page, needs hero image, ready for final review, tech tutorial

#1074 How to create CRUD API in flask
  articles/flask-crud-api/create-todo.png
  articles/flask-crud-api/database.png
  articles/flask-crud-api/delete-todo.png
  articles/flask-crud-api/get-todo-by-id.png
  articles/flask-crud-api/get-todos.png
  articles/flask-crud-api/hero.jpg
  articles/flask-crud-api/index.md
  articles/flask-crud-api/update-todo.png
Labels: assigned for review, ready for final review, tech review, tiered payout

#1111 Article Update: Getting to Grips with APIs - API Depreciation Notice
  articles/simple-guide-to-using-apis-nodejs/index.md
Labels: article update, assigned for review

#1075 Deploying Machine Learning models using Flask
  articles/deploying-machine-learning-models-using-flask/Dataset.PNG
  articles/deploying-machine-learning-models-using-flask/Input.PNG
  articles/deploying-machine-learning-models-using-flask/Output.PNG
  articles/deploying-machine-learning-models-using-flask/hero.png
  articles/deploying-machine-learning-models-using-flask/index.md
Labels: ready for final review, tech tutorial, tiered payout

#1076 Dark Mode for React Application using Context API and Hooks
  articles/react-dark-mode-with-context-api-and-hooks/hero.jpg
  articles/react-dark-mode-with-context-api-and-hooks/index.md
  articles/react-dark-mode-with-context-api-and-hooks/lightmode.png
  articles/react-dark-mode-with-context-api-and-hooks/toggle.gif
Labels: ready for final review, tech tutorial

#1089 Introduction to recursion
  articles/introduction-to-recursion/hero.jpg
  articles/introduction-to-recursion/index.md
Labels: assigned for review, ready for final review

#1113 Introduction to dynamic programming
  articles/introduction-to-dynamic-programming/fibonacci.png
  articles/introduction-to-dynamic-programming/hero.jpg
  articles/introduction-to-dynamic-programming/index.md
Labels: needs front matter, ready for final review, tech tutorial

#1135 Basic Setup for Data Science
  articles/data-science-setup/1.png
  articles/data-science-setup/2.png
  articles/data-science-setup/3.png
  articles/data-science-setup/hero.jpg
  articles/data-science-setup/index.md
  articles/data-science-setup/pytorch.png
  articles/data-science-setup/scikit-learn.png
Labels: assigned for review, ready for final review

#1106 5 Real Life Use Cases of 5G Ultra-Reliable Low-Latency Communication (URLLC)
  articles/five-real-life-use-cases-of-5g-ultra-reliable-low-latency-communication-urllc/hero.jpg
  articles/five-real-life-use-cases-of-5g-ultra-reliable-low-latency-communication-urllc/index.md
Labels: article, ready for final review

#1119 Develop Google add-on
  articles/develop-google-add-on/access-published.png
  articles/develop-google-add-on/allow-permission.png
  articles/develop-google-add-on/apps-script-access.png
  articles/develop-google-add-on/apps-script-editor.png
  articles/develop-google-add-on/choose-account.png
  articles/develop-google-add-on/debugging.png
  articles/develop-google-add-on/deployment.png
  articles/develop-google-add-on/helper-function.png
  articles/develop-google-add-on/hero.png
  articles/develop-google-add-on/index.md
  articles/develop-google-add-on/menu.png
  articles/develop-google-add-on/published.png
  articles/develop-google-add-on/review-permissions.png
  articles/develop-google-add-on/scopes.png
  articles/develop-google-add-on/side-bar.png
  articles/develop-google-add-on/triggers.png
Labels: ready for final review

#1141 Guide to Open Source Licenses
  articles/open-source-licenses/hero.jpg
  articles/open-source-licenses/index.md
Labels: assigned for review, ready for final review

#1167 Hypothesis Testing in Data Science
  articles/hypothesis-testing-data-science/hero.jpg
  articles/hypothesis-testing-data-science/index.md
  articles/hypothesis-testing-data-science/nullatlernative.png
  articles/hypothesis-testing-data-science/significancelevel.png
Labels: article, ready for final review

#1168 Text to Speech using Web Speech API in JavaScript
  articles/text-to-speech-in-javascript/hero.jpg
  articles/text-to-speech-in-javascript/index.md
  articles/text-to-speech-in-javascript/start_screen.png
Labels: assigned for review, ready for final review, tech tutorial

#1019 How to Use Kanban to Manage your Next Project
  articles/how-to-use-kanban-to-manage-your-next-project/hero.jpg
  articles/how-to-use-kanban-to-manage-your-next-project/index.md
  articles/how-to-use-kanban-to-manage-your-next-project/kanban-board-components.jpg
  articles/how-to-use-kanban-to-manage-your-next-project/simple-kanban-board.jpg
Labels: article, assigned for review, needs front matter, preliminary revision in progress

#1416 Added NodeMCU article again
  articles/getting-started-with-nodemcu/hero.jpg
  articles/getting-started-with-nodemcu/index.md
  articles/getting-started-with-nodemcu/nodemcu.png
  articles/getting-started-with-nodemcu/pin-diagram.png
  articles/getting-started-with-nodemcu/result.gif
  articles/getting-started-with-nodemcu/uploading.png
Labels: article update

#1133 Uploading Multipart/Form-data using Multer in a node.js application.
  articles/uploading-files-using-multer-nodejs/appjs.png
  articles/uploading-files-using-multer-nodejs/appjs2.png
  articles/uploading-files-using-multer-nodejs/appjs3.png
  articles/uploading-files-using-multer-nodejs/atlas.png
  articles/uploading-files-using-multer-nodejs/hero.jpg
  articles/uploading-files-using-multer-nodejs/index.md
  articles/uploading-files-using-multer-nodejs/json.png
Labels: ready for final review

#1009 The Evolution Of Resource Sharing Technologies Over The Internet
  articles/the-evolution-of-resource-sharing-technologies-over-the-internet/hero.jpg
  articles/the-evolution-of-resource-sharing-technologies-over-the-internet/index.md
Labels: article, enhancement

#1059 JavaScript Arrow Function ( => ) Explained
  articles/how-to-use-javascript-arrow-functions-and-this-keyword/error.jpg
  articles/how-to-use-javascript-arrow-functions-and-this-keyword/hero.jpg
  articles/how-to-use-javascript-arrow-functions-and-this-keyword/index.md
  articles/how-to-use-javascript-arrow-functions-and-this-keyword/this-execution-context.jpg
  articles/how-to-use-javascript-arrow-functions-and-this-keyword/this-inside-arrow-function.jpg
  articles/how-to-use-javascript-arrow-functions-and-this-keyword/window-objects.jpg
Labels: ready for final review, tech tutorial

#1115 Functional Programming with Haskell
  articles/intro-to-haskell/hero.jpg
  articles/intro-to-haskell/index.md
Labels: ready for final review, tech tutorial

#1103 Variables, Data Types and Control Statements in C#
  articles/variables-data-types-and-control-statements-in-csharp/hero.jpg
  articles/variables-data-types-and-control-statements-in-csharp/index.md
Labels: assigned for review, ready for final review

#1131 NPM vs NPX
  articles/npm-vs-npx-what-is-the-difference/execute-gist-code-with-npx.jpg
  articles/npm-vs-npx-what-is-the-difference/hero.jpg
  articles/npm-vs-npx-what-is-the-difference/index.md
Labels: article, assigned for review, ready for final review, tiered payout

#1170 Introduction to InfluxDB
  articles/introduction-to-influxdb/download.png
  articles/introduction-to-influxdb/hero.jpg
  articles/introduction-to-influxdb/index.md
  articles/introduction-to-influxdb/influx.png
  articles/introduction-to-influxdb/influxd.png
  articles/introduction-to-influxdb/select.png
  articles/introduction-to-influxdb/select_temperature.png
  articles/introduction-to-influxdb/show_databases.png
Labels: ready for final review, tech tutorial

#1184 Automating UI Tests in Android Using Espresso
  articles/automating-ui-tests-in-android-using-espresso/hero.jpg
  articles/automating-ui-tests-in-android-using-espresso/index.md
  articles/automating-ui-tests-in-android-using-espresso/result.gif
  false
Labels: assigned for review, ready for final review

#1305 Text Recognition using Firebase ML in a Non-Expo React Native Application
  articles/react-native-firebase-text-recognition/api_services.png
  articles/react-native-firebase-text-recognition/buttons_ui.jpg
  articles/react-native-firebase-text-recognition/cloud_dashboard.png
  articles/react-native-firebase-text-recognition/cloud_vision_dashboard.png
  articles/react-native-firebase-text-recognition/download_services.json.png
  articles/react-native-firebase-text-recognition/enable_cloud_vision.png
  articles/react-native-firebase-text-recognition/env_setup.png
  articles/react-native-firebase-text-recognition/final_result.jpg
  articles/react-native-firebase-text-recognition/firebase_new.png
  articles/react-native-firebase-text-recognition/hero.jpg
  articles/react-native-firebase-text-recognition/index.md
  articles/react-native-firebase-text-recognition/new_dashboard.png
  articles/react-native-firebase-text-recognition/package_name.png
  articles/react-native-firebase-text-recognition/register_app.png
  articles/react-native-firebase-text-recognition/search_libraries.png
  articles/react-native-firebase-text-recognition/with_image.jpg
Labels: ready for final review, tech tutorial

#1175 Effect of Ensemble Learning on Bias and Variance
  articles/ensemble-bias-var/bias.png
  articles/ensemble-bias-var/biasvariancetrade.png
  articles/ensemble-bias-var/boosting.jpg
  articles/ensemble-bias-var/hero.jpg
  articles/ensemble-bias-var/index.md
  articles/ensemble-bias-var/modelcomplexity.png
  articles/ensemble-bias-var/variance.png
Labels: article, ready for final review

#1410 Updated tsParticles Article
  articles/javascript-particles-effect-with-tsparticles/index.md
Labels: article update

#1171 Theoretical Introduction to Linear Regression
  articles/linear-regression-introduction/hero.jpg
  articles/linear-regression-introduction/index.md
Labels: ready for final review

#1185 Getting started with MATLAB
  articles/getting-started-with-matlab/1.PNG
  articles/getting-started-with-matlab/2.PNG
  articles/getting-started-with-matlab/hero.png
  articles/getting-started-with-matlab/index.md
  articles/getting-started-with-matlab/sin-cos.jpg
Labels: ready for final review, tech tutorial

#1104 How to consume data from an API using react
  articles/how-to-consume-data-from-an-API-using-react/app.gif
  articles/how-to-consume-data-from-an-API-using-react/email.png
  articles/how-to-consume-data-from-an-API-using-react/hero.png
  articles/how-to-consume-data-from-an-API-using-react/index.md
  articles/how-to-consume-data-from-an-API-using-react/signup.png
  articles/how-to-consume-data-from-an-API-using-react/structure.png
Labels: assigned for review, ready for final review

#1190 Popular Machine Learning (ML) Datasets
  articles/popular-machine-learning-datasets/cifar-10-dataset.PNG
  articles/popular-machine-learning-datasets/fashion-mnist-dataset.PNG
  articles/popular-machine-learning-datasets/hero.jpg
  articles/popular-machine-learning-datasets/index.md
  articles/popular-machine-learning-datasets/mnist-dataset.PNG
  articles/popular-machine-learning-datasets/sentiment140.PNG
Labels: article, ready for final review

#1191 Batch Processing vs Stream Processing
  articles/batch-processing-vs-stream-processing/hero.jpg
  articles/batch-processing-vs-stream-processing/index.md
Labels: article, ready for final review

#1198 Getting started with UI layouts in android
  articles/getting-started-with-ui-layouts-in-android/anatomy.jpg
  articles/getting-started-with-ui-layouts-in-android/constraint.jpg
  articles/getting-started-with-ui-layouts-in-android/frame.jpg
  articles/getting-started-with-ui-layouts-in-android/hero.jpg
  articles/getting-started-with-ui-layouts-in-android/index.md
  articles/getting-started-with-ui-layouts-in-android/linear.jpg
  articles/getting-started-with-ui-layouts-in-android/relative.png
  authors/briana-nzivu/avatar.jpg
  authors/briana-nzivu/avatar.png
  authors/briana-nzivu/index.md
Labels: ready for final review

#1229 An Overview of Teradata RDBMS
  articles/an-overview-of-teradata-rdbms/hero.jpg
  articles/an-overview-of-teradata-rdbms/index.md
  articles/an-overview-of-teradata-rdbms/retrieval-architecture.png
  articles/an-overview-of-teradata-rdbms/storage-architecture.png
  articles/an-overview-of-teradata-rdbms/teradata-architecture.png
Labels: article, ready for final review

#1399 How to use intertersection observer API by building a simple image lazy loading website
  articles/intersection-observer/hero.jpg
  articles/intersection-observer/index.md
Labels: ready for final review

#1031 Integrating Django with TinyMCE
  articles/integrating-django-with-tinymce/hero.jpg
  articles/integrating-django-with-tinymce/index.md
  articles/integrating-django-with-tinymce/tinymce-the-final-results.jpg
  authors/samuel-mwangi/avatar.jpg
  authors/samuel-mwangi/index.md
Labels: good first article, needs author page

#1178 React Native Firebase Storage for Non-Expo Workflow
  articles/react-native-firebase-storage/app_ui.jpg
  articles/react-native-firebase-storage/bucket_location.png
  articles/react-native-firebase-storage/default_rules.png
  articles/react-native-firebase-storage/download_services.json.png
  articles/react-native-firebase-storage/enable_storage.png
  articles/react-native-firebase-storage/env_setup.png
  articles/react-native-firebase-storage/firebase_new.png
  articles/react-native-firebase-storage/hero.jpg
  articles/react-native-firebase-storage/index.md
  articles/react-native-firebase-storage/new_dashboard.png
  articles/react-native-firebase-storage/package_name.png
  articles/react-native-firebase-storage/pause.gif
  articles/react-native-firebase-storage/register_app.png
  articles/react-native-firebase-storage/resume.jpg
  articles/react-native-firebase-storage/storage_default_rules.png
  articles/react-native-firebase-storage/storage_setup_done.png
  articles/react-native-firebase-storage/upload_progress.gif
  articles/react-native-firebase-storage/uploaded_media.png
  articles/react-native-firebase-storage/view_media.jpg
Labels: ready for final review, tech tutorial

#1110 How to create Django Docker images
  articles/django-docker/docker_create.png
  articles/django-docker/docker_get.png
  articles/django-docker/hero.jpg
  articles/django-docker/index.md
Labels: assigned for review, ready for final review

#1125 Creating and Connecting Maria Database to a PHP registration form
  articles/maria-data-base/database.png
  articles/maria-data-base/database2.png
  articles/maria-data-base/form.png
  articles/maria-data-base/hero.jpg
  articles/maria-data-base/img1.png
  articles/maria-data-base/img2.png
  articles/maria-data-base/img3.png
  articles/maria-data-base/img4.png
  articles/maria-data-base/img5.png
  articles/maria-data-base/index.md
  articles/maria-data-base/maria.png
  articles/maria-data-base/phpmyadmin.png
Labels: ready for final review

#1176 Constraint-Satisfaction Problems with MiniZinc + Gecode
  articles/constraint-satisfaction-minizinc-gecode/United_States_Public_Domain_Map.jpg
  articles/constraint-satisfaction-minizinc-gecode/hero.jpg
  articles/constraint-satisfaction-minizinc-gecode/img1.png
  articles/constraint-satisfaction-minizinc-gecode/img2.png
  articles/constraint-satisfaction-minizinc-gecode/index.md
  articles/constraint-satisfaction-minizinc-gecode/tsp.gif
  authors/nicholas-kross/avatar.jpg
  authors/nicholas-kross/index.md
Labels: assigned for review, good first article, ready for final review

#1071 What it Takes to be a Flutter Developer.
  articles/becoming-a-flutter-developer/hero.jpg
  articles/becoming-a-flutter-developer/index.md
Labels: ready for final review

#1469 Password Strength Checker using JavaScript Regex
  articles/password-strength-checker-javascript/hero.jpg
  articles/password-strength-checker-javascript/index.md
  articles/password-strength-checker-javascript/medium-password.png
  articles/password-strength-checker-javascript/strong-password.png
  articles/password-strength-checker-javascript/weak-password.png
Labels: ready for final review, tech tutorial

#1240 Understanding Design Patterns in Java
  articles/design-patterns/hero.jpg
  articles/design-patterns/index.md
  authors/kiplangat-erick/avatar.jpg
  authors/kiplangat-erick/index.md
Labels: assigned for review, good first article, ready for final review

#1117 Node.js vs. Django
  articles/node-vs-django/hero.jpg
  articles/node-vs-django/index.md
Labels: ready for final review

#1172 Implementing Linear Regression Using Gradient Descent in Python
  articles/linear-regression-code/hero.jpg
  articles/linear-regression-code/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1211 MOLAP vs ROLAP vs HOLAP in Online Analytical Processing (OLAP)
  articles/molap-vs-rolap-vs-holap/hero.jpg
  articles/molap-vs-rolap-vs-holap/holap-architecture.png
  articles/molap-vs-rolap-vs-holap/index.md
  articles/molap-vs-rolap-vs-holap/molap-architecture.png
  articles/molap-vs-rolap-vs-holap/olap-architecture.png
  articles/molap-vs-rolap-vs-holap/rolap-architecture.jpg
Labels: article, ready for final review

#1250 Getting started with classes and objects in C++
  articles/getting-started-with-classes-and-objects-in-c++/console.png
  articles/getting-started-with-classes-and-objects-in-c++/hero.jpg
  articles/getting-started-with-classes-and-objects-in-c++/index.md
Labels: ready for final review, tech tutorial

#1335 Introduction to Kotlin Coroutines
  articles/introduction-to-kotlin-coroutines/hero.jpg
  articles/introduction-to-kotlin-coroutines/index.md
  articles/introduction-to-kotlin-coroutines/new-project.png
Labels: assigned for review, ready for final review

#1136 Deploying your Android App to Play Store
  articles/deploying-your-android-app-to-google-play-store/android_app_bundle.png
  articles/deploying-your-android-app-to-google-play-store/confirm.png
  articles/deploying-your-android-app-to-google-play-store/create_new.png
  articles/deploying-your-android-app-to-google-play-store/generate_app_bundle.png
  articles/deploying-your-android-app-to-google-play-store/hero.jpg
  articles/deploying-your-android-app-to-google-play-store/index.md
  articles/deploying-your-android-app-to-google-play-store/key_store.png
  articles/deploying-your-android-app-to-google-play-store/message.png
  articles/deploying-your-android-app-to-google-play-store/minify.png
  articles/deploying-your-android-app-to-google-play-store/release.png
  articles/deploying-your-android-app-to-google-play-store/version_code_name.png
  authors/christine-wasike/avatar.jpg
  authors/christine-wasike/index.md
Labels: good first article, needs author page, ready for final review

#1215 Getting started with Constraint Layout design in Android
  articles/getting-started-with-constraint-layout-in-android/adding-view.png
  articles/getting-started-with-constraint-layout-in-android/barrier.png
  articles/getting-started-with-constraint-layout-in-android/baseline.png
  articles/getting-started-with-constraint-layout-in-android/chain-styles.png
  articles/getting-started-with-constraint-layout-in-android/circular-alignment.png
  articles/getting-started-with-constraint-layout-in-android/constrained-view.png
  articles/getting-started-with-constraint-layout-in-android/constraining-view.png
  articles/getting-started-with-constraint-layout-in-android/flow.png
  articles/getting-started-with-constraint-layout-in-android/guideline.png
  articles/getting-started-with-constraint-layout-in-android/helpers-icon.png
  articles/getting-started-with-constraint-layout-in-android/hero.png
  articles/getting-started-with-constraint-layout-in-android/horizontal-chain.png
  articles/getting-started-with-constraint-layout-in-android/horizontal-constraint.png
  articles/getting-started-with-constraint-layout-in-android/index.md
  articles/getting-started-with-constraint-layout-in-android/match-height-dark.png
  articles/getting-started-with-constraint-layout-in-android/match-height.png
  articles/getting-started-with-constraint-layout-in-android/match-width.png
  articles/getting-started-with-constraint-layout-in-android/select-baseline.png
  articles/getting-started-with-constraint-layout-in-android/vertical-chain.png
  articles/getting-started-with-constraint-layout-in-android/vertical-constraint.png
Labels: assigned for review, ready for final review

#1242 Intro to Scikit Learn in Python
  articles/introduction-to-scikit-learn-in-python/hero.png
  articles/introduction-to-scikit-learn-in-python/index.md
  articles/introduction-to-scikit-learn-in-python/normalization-formula.png
  articles/introduction-to-scikit-learn-in-python/standardization-formula.png
Labels: ready for final review, tech tutorial

#1235 How to upload files to Amazon S3 in Spring Boot
  articles/spring-boot-amazon-s3/amazon-console-uploaded-image.png
  articles/spring-boot-amazon-s3/amazon-s3-create-bucket.png
  articles/spring-boot-amazon-s3/amazon-search-s3.png
  articles/spring-boot-amazon-s3/amazon-security-key.png
  articles/spring-boot-amazon-s3/amazon-spring-boot-project.png
  articles/spring-boot-amazon-s3/amazon-upload-image.png
  articles/spring-boot-amazon-s3/hero.jpg
  articles/spring-boot-amazon-s3/index.md
Labels: ready for final review

#1290 Introduction to time series
  articles/Introduction-to-time-series/hero.jpg
  articles/Introduction-to-time-series/img.jpg
  articles/Introduction-to-time-series/index.md
Labels: article, duplicate, ready for final review, tiered payout

#1275 Implementing public key cryptography in JavaScript.
  articles/implementing-public-key-cryptography-in-js/hero.jpg
  articles/implementing-public-key-cryptography-in-js/index.md
Labels: duplicate, ready for final review

#1123 How to build a simple Angular SPA from scratch
  articles/building-a-simple-angular-app/hero.png
  articles/building-a-simple-angular-app/index.md
  articles/building-a-simple-angular-app/my-app-anime-akira.png
  articles/building-a-simple-angular-app/my-app-home.png
  authors/mahantesh-r/avatar.jpeg
  authors/mahantesh-r/index.md
Labels: assigned for review, ready for final review

#1083 Introduction to Fuzzy Operations
  articles/fuzzy-logic-operations/L-function.png
  articles/fuzzy-logic-operations/gamma-correct.png
  articles/fuzzy-logic-operations/gamma.png
  articles/fuzzy-logic-operations/gaussian.png
  articles/fuzzy-logic-operations/graphical_rep_1.png
  articles/fuzzy-logic-operations/graphical_rep_2.png
  articles/fuzzy-logic-operations/hero.jpg
  articles/fuzzy-logic-operations/index.md
  articles/fuzzy-logic-operations/pi_function.png
  articles/fuzzy-logic-operations/triangular_function.png
Labels: article, assigned for review, preliminary revision in progress

#1187 Getting Started with Selenium Automation Testing
  articles/getting-started-with-selenium-automation-testing/chrome-driver.png
  articles/getting-started-with-selenium-automation-testing/downloading-selenium-client.jpg
  articles/getting-started-with-selenium-automation-testing/eclipse-ide.jpg
  articles/getting-started-with-selenium-automation-testing/eclipse-installer.jpg
  articles/getting-started-with-selenium-automation-testing/hero.jpg
  articles/getting-started-with-selenium-automation-testing/index.md
  articles/getting-started-with-selenium-automation-testing/installing-eclipse-ide.png
  articles/getting-started-with-selenium-automation-testing/java-command-prompt.png
  articles/getting-started-with-selenium-automation-testing/step-1.jpg
  articles/getting-started-with-selenium-automation-testing/step-10.jpg
  articles/getting-started-with-selenium-automation-testing/step-2-1.jpg
  articles/getting-started-with-selenium-automation-testing/step-2-2.png
  articles/getting-started-with-selenium-automation-testing/step-3-1.jpg
  articles/getting-started-with-selenium-automation-testing/step-3-2.jpg
  articles/getting-started-with-selenium-automation-testing/step-4.jpg
  articles/getting-started-with-selenium-automation-testing/step-5-1.jpg
  articles/getting-started-with-selenium-automation-testing/step-5-2.png
  articles/getting-started-with-selenium-automation-testing/step-6-1.jpg
  articles/getting-started-with-selenium-automation-testing/step-6-2.jpg
  articles/getting-started-with-selenium-automation-testing/step-7.jpg
  articles/getting-started-with-selenium-automation-testing/step-8-1.jpg
  articles/getting-started-with-selenium-automation-testing/step-8-2.png
  articles/getting-started-with-selenium-automation-testing/step-9.jpg
Labels: assigned for review, ready for final review, tech tutorial, tiered payout

#1225 Introduction to C++ operators
  articles/introduction-to-c++-operators/hero.jpg
  articles/introduction-to-c++-operators/index.md
Labels: article, assigned for review, ready for final review, tiered payout

#1245 Image Labeling using Firebase ML in a Non-Expo React Native Application
  articles/react-native-firebase-image-labeling/api_services.png
  articles/react-native-firebase-image-labeling/buttons_ui.jpg
  articles/react-native-firebase-image-labeling/cloud_dashboard.png
  articles/react-native-firebase-image-labeling/cloud_vision_dashboard.png
  articles/react-native-firebase-image-labeling/download_services.json.png
  articles/react-native-firebase-image-labeling/enable_cloud_vision.png
  articles/react-native-firebase-image-labeling/env_setup.png
  articles/react-native-firebase-image-labeling/final_result.jpg
  articles/react-native-firebase-image-labeling/firebase_new.png
  articles/react-native-firebase-image-labeling/hero.jpg
  articles/react-native-firebase-image-labeling/index.md
  articles/react-native-firebase-image-labeling/new_dashboard.png
  articles/react-native-firebase-image-labeling/package_name.png
  articles/react-native-firebase-image-labeling/register_app.png
  articles/react-native-firebase-image-labeling/search_libraries.png
  articles/react-native-firebase-image-labeling/with_image.jpg
Labels: ready for final review, tech tutorial

#1259 Figma For Web Design: A Beginner's Guide
  articles/using-figma-for-web-design/blue-polygon.png
  articles/using-figma-for-web-design/canvas.jpg
  articles/using-figma-for-web-design/changing-color.png
  articles/using-figma-for-web-design/changing-frame-name.jpg
  articles/using-figma-for-web-design/choose-plan.jpg
  articles/using-figma-for-web-design/comments.jpg
  articles/using-figma-for-web-design/constraints.jpg
  articles/using-figma-for-web-design/create-account.jpg
  articles/using-figma-for-web-design/creating-a-polygon.png
  articles/using-figma-for-web-design/creating-a-rectangle.png
  articles/using-figma-for-web-design/creating-shapes.jpg
  articles/using-figma-for-web-design/design-team-name.jpg
  articles/using-figma-for-web-design/email-and-password.jpg
  articles/using-figma-for-web-design/figma-desktop-app.jpg
  articles/using-figma-for-web-design/figma-downloads.jpg
  articles/using-figma-for-web-design/figma-user-interface.png
  articles/using-figma-for-web-design/frame-output.png
  articles/using-figma-for-web-design/frame.jpg
  articles/using-figma-for-web-design/hero.jpg
  articles/using-figma-for-web-design/index.md
  articles/using-figma-for-web-design/introductory-message.png
  articles/using-figma-for-web-design/invite-collaborators.png
  articles/using-figma-for-web-design/iphone-11-frame.png
  articles/using-figma-for-web-design/layers.jpg
  articles/using-figma-for-web-design/menu.jpg
  articles/using-figma-for-web-design/preset-frame.jpg
  articles/using-figma-for-web-design/properties-panel.jpg
  articles/using-figma-for-web-design/share-icon.jpg
  articles/using-figma-for-web-design/sign-up.jpg
  articles/using-figma-for-web-design/team-library.jpg
  articles/using-figma-for-web-design/text-tool.jpg
  articles/using-figma-for-web-design/vector-networks.jpg
  articles/using-figma-for-web-design/writing-text.png
Labels: ready for final review

#1492 Update articles
  articles/agora-cloud-recording-part-2/index.md
  articles/agora-cloud-recording/index.md
  articles/agora-express-token-server/hero.jpg
  articles/dark-mode-for-react-app-using-context-api-and-hooks/hero.jpg
  articles/dark-mode-for-react-app-using-context-api-and-hooks/index.md
  articles/dark-mode-for-react-app-using-context-api-and-hooks/lightmode.png
  articles/dark-mode-for-react-app-using-context-api-and-hooks/toggle.gif
  articles/react-native-firebase-text-recognition/index.md
  articles/react-native-razorpay/hero.jpg
Labels: article update

#1159 build-a-websocket-powered-tic-tac-toe-with-adonisjs
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/adonis-logo.png
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/client-to-server.png
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/generate-game-code.gif
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/hero.png
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/index.md
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/joining-game-with-code.gif
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/nodejs-logo.png
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/redis.png
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/security-implications.jpg
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/server-to-multiple-clients.png
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/set-username.gif
  articles/build-a-websockets-powered-tic-tac-toe-with-adonisjs/winning-sequence-iteration.png
  authors/osinachi-chukwujama/index.md
  authors/osinachi-chukwujama/osi-headshot.png
Labels: assigned for review, ready for final review, tech review

#1043 Spotify API with Spotipy Part 1
  articles/spotify-python-part-1/hero.jpg
  articles/spotify-python-part-1/index.md
  authors/joshua-welsh/avatar.png
  authors/joshua-welsh/index.md
Labels: good first article, needs front matter, ready for final review, tech tutorial

#1227 An Overview of Blockchain Consensus Protocols
  articles/blockchain-consensus-protocols/hero.jpg
  articles/blockchain-consensus-protocols/index.md
Labels: article, assigned for review, ready for final review

#1239 Implementing sorting algorithms in JavaScript
  articles/sorting-algorithms-in-js/bubble-sort.png
  articles/sorting-algorithms-in-js/hero.jpg
  articles/sorting-algorithms-in-js/index.md
  articles/sorting-algorithms-in-js/insertion-sort.png
  articles/sorting-algorithms-in-js/merge_sort.png
  articles/sorting-algorithms-in-js/quick-sort.png
  articles/sorting-algorithms-in-js/selection-sort.png
Labels: assigned for review, ready for final review, tech tutorial

#1278 How to implement dark mode in Android Studio
  articles/how-to-implement-dark-mode-in-android-studio/demo.gif
  articles/how-to-implement-dark-mode-in-android-studio/hero.jpg
  articles/how-to-implement-dark-mode-in-android-studio/index.md
Labels: ready for final review

#1281 Seaborn Tutorial
  articles/seaborn-tutorial/countplot1.png
  articles/seaborn-tutorial/countplot2.png
  articles/seaborn-tutorial/distplot1.png
  articles/seaborn-tutorial/distplot2.png
  articles/seaborn-tutorial/heatmap1.png
  articles/seaborn-tutorial/heatmap2.png
  articles/seaborn-tutorial/hero.jpg
  articles/seaborn-tutorial/index.md
  articles/seaborn-tutorial/jointplot.png
  articles/seaborn-tutorial/kdeplot.png
  articles/seaborn-tutorial/pairplot.jpg
  articles/seaborn-tutorial/pokemon1.png
  articles/seaborn-tutorial/pokemon2.jpg
  articles/seaborn-tutorial/pokemon3.png
  articles/seaborn-tutorial/scatterplot.png
Labels: ready for final review, tech tutorial
