Repository section-engineering-education/engineering-education, pull requests merged in 2021-10, with the labels that each got.

#4076 Searching and sorting techniques
  content/articles/searching-and-sorting-techniques/index.md
Labels: duplicate

#3752 How to secure your Firebase App with Firebase Security Rules
  content/articles/how-to-secure-your-firebase-app-with-firebase-security-rules/chatapp.jpg
  content/articles/how-to-secure-your-firebase-app-with-firebase-security-rules/cloud-firestone-policy-config.jpg
  content/articles/how-to-secure-your-firebase-app-with-firebase-security-rules/create-db.jpg
  content/articles/how-to-secure-your-firebase-app-with-firebase-security-rules/edit-rules.jpg
  content/articles/how-to-secure-your-firebase-app-with-firebase-security-rules/firebase.jpg
  content/articles/how-to-secure-your-firebase-app-with-firebase-security-rules/hero.jpg
  content/articles/how-to-secure-your-firebase-app-with-firebase-security-rules/index.md
Labels: assigned for review, ready for final review

#3880 Implementing Flask API using Linked list Data Structure
  content/articles/implementing-flask-api-using-linked-list/create-user.jpg
  content/articles/implementing-flask-api-using-linked-list/hero.jpg
  content/articles/implementing-flask-api-using-linked-list/index.md
  content/articles/implementing-flask-api-using-linked-list/linked-list.jpg
Labels: assigned for review, ready for final review

#3820 Design a sign up and login gui using javafx
  content/articles/design-a-sign-up-and-login-gui-using-javafx/delete-v-box.png
  content/articles/design-a-sign-up-and-login-gui-using-javafx/download-screen-builder.png
  content/articles/design-a-sign-up-and-login-gui-using-javafx/final-program.png
  content/articles/design-a-sign-up-and-login-gui-using-javafx/hello-java-fx.png
  content/articles/design-a-sign-up-and-login-gui-using-javafx/hero.png
  content/articles/design-a-sign-up-and-login-gui-using-javafx/index.md
  content/articles/design-a-sign-up-and-login-gui-using-javafx/java-fx-dependencies.png
  content/articles/design-a-sign-up-and-login-gui-using-javafx/java-fx-new-project.png
  content/articles/design-a-sign-up-and-login-gui-using-javafx/java-fx-scene-builder.png
Labels: duplicate, assigned for review, ready for final review

#3882 How to Auto Log Off Users Due to Inactivity Using Angular 12
  content/articles/auto-logout-angular/hero.png
  content/articles/auto-logout-angular/index.md
  content/articles/auto-logout-angular/register.png
Labels: enhancement, tech tutorial

#4125 Added Myself to Developer List
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#3636 HTML Client for Web Services Using DHTML Behavior
  content/articles/html-client-for-web-services-using-dhtml-behavior/addnew.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/appcode.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/delete.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/employeeid.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/explorer.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/hero.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/http.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/index.md
  content/articles/html-client-for-web-services-using-dhtml-behavior/invalid.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/postmethod.jpg
  content/articles/html-client-for-web-services-using-dhtml-behavior/webservice.jpg
  content/authors/stephen-boro/avatar.jpg
  content/authors/stephen-boro/index.md
Labels: assigned for review, ready for final review

#3749 lru cache implementation writeup completed
  content/articles/lru-cache-implementation-in-javascript/ddl_hash.png
  content/articles/lru-cache-implementation-in-javascript/hero.jpg
  content/articles/lru-cache-implementation-in-javascript/index.md
  content/articles/lru-cache-implementation-in-javascript/result.PNG
Labels: ready for final review

#3790 Intent Classification with Rasa and Spacy
  content/articles/intent-classification-with-rasa-and-spacy/dataset-used.jpg
  content/articles/intent-classification-with-rasa-and-spacy/hero.jpg
  content/articles/intent-classification-with-rasa-and-spacy/index.md
  content/articles/intent-classification-with-rasa-and-spacy/nlp-vs-nlp.png
  content/authors/kelvin-kimani-ngure/avatar.png
  content/authors/kelvin-kimani-ngure/index.md
Labels: assigned for review, ready for final review, needs front matter, tech tutorial, test reviewer assigned

#3808 Java Program to Store Unicode Characters using Character Literals
  content/articles/storing-unicode-characters-using-character-literals-in-java/hero.jpg
  content/articles/storing-unicode-characters-using-character-literals-in-java/index.md
  content/authors/diana-peter/avatar.jpg
  content/authors/diana-peter/index.md
Labels: good first article, assigned for review, ready for final review, needs front matter, test reviewer assigned

#3835 How to build a simple router using window event listeners in JavaScript
  content/articles/how-to-build-a-simple-router-in-javascript/hero.png
  content/articles/how-to-build-a-simple-router-in-javascript/index.md
Labels: ready for final review

#4052 Getting started with Bootstrap
  content/articles/a-look-at-some-bootstrap-examples/hero.png
  content/articles/a-look-at-some-bootstrap-examples/index.md
  content/authors/erastus-muriithi/avatar.jpeg
  content/authors/erastus-muriithi/avatar.png
  content/authors/erastus-muriithi/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#3753 How to choose the appropriate microservices framework for your project?
  content/articles/choosing-a-microservice-framework-for-your-project/hero.jpeg
  content/articles/choosing-a-microservice-framework-for-your-project/index.md
Labels: assigned for review, ready for final review

#3819 Geofencing in Android with Kotlin
  content/articles/geofencing-in-android-with-kotlin/hero.png
  content/articles/geofencing-in-android-with-kotlin/index.md
  content/articles/geofencing-in-android-with-kotlin/new_project.png
Labels: assigned for review, ready for final review

#3859 Implementation of fuzzy logics in Matlab
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_eight.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_eleven.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_five.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_four.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_nine.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_one.png
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_seven.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_six.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_ten.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_three.jpeg
  content/articles/implementation-of-fuzzy-logic-in-matlab/fuzzy_two.png
  content/articles/implementation-of-fuzzy-logic-in-matlab/hero.jpg
  content/articles/implementation-of-fuzzy-logic-in-matlab/index.md
  content/authors/collince-odhiambo/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3894 Handling Memory Leaks In Android Using LeakCanary
  content/articles/handling-memory-leaks-in-android-using-leakcanary/analyzing_leak.png
  content/articles/handling-memory-leaks-in-android-using-leakcanary/detecting_leak.jpg
  content/articles/handling-memory-leaks-in-android-using-leakcanary/dumping_leak.jpg
  content/articles/handling-memory-leaks-in-android-using-leakcanary/hero.png
  content/articles/handling-memory-leaks-in-android-using-leakcanary/index.md
  content/articles/handling-memory-leaks-in-android-using-leakcanary/leak_category.jpg
  content/articles/handling-memory-leaks-in-android-using-leakcanary/leaks.jpg
Labels: assigned for review, ready for final review

#3828 Writing a Flutter Web Plugin
  content/articles/writing-a-flutter-web-plugin/hero.png
  content/articles/writing-a-flutter-web-plugin/index.md
  content/authors/faith-zawadi/avatar.jpg
  content/authors/faith-zawadi/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, tech tutorial

#3897 Data visualization with tables in React
  content/articles/data-visualization-with-tables-in-react/hero.jpeg
  content/articles/data-visualization-with-tables-in-react/index.md
  content/articles/data-visualization-with-tables-in-react/react-table.gif
Labels: assigned for review, ready for final review, tech tutorial

#3904 Manipulating object states using Finite State Machine using Django - (Duplicate of #3623)
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/hero.jpg
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/image-one.jpg
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/index.md
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/new-five.jpg
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/new-one.jpg
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/new-six.jpg
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/new-three.jpg
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/new-two.jpg
  content/articles/manipulating-object-states-in-django-using-finite-state-machine/run-server.jpg
  content/authors/ayemobola-tolulope/avatar.jpg
  content/authors/ayemobola-tolulope/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#3876 Building Spotify Recommendation Engine
  content/articles/building-spotify-recommendation-engine/album-cover-art.png
  content/articles/building-spotify-recommendation-engine/collaborative-filtering.JPG
  content/articles/building-spotify-recommendation-engine/cosine-similarity.png
  content/articles/building-spotify-recommendation-engine/dashboard.png
  content/articles/building-spotify-recommendation-engine/equation.jpg
  content/articles/building-spotify-recommendation-engine/feature-matrix.JPG
  content/articles/building-spotify-recommendation-engine/hero.png
  content/articles/building-spotify-recommendation-engine/index.md
  content/articles/building-spotify-recommendation-engine/normalization-equation.jpg
  content/articles/building-spotify-recommendation-engine/recommendation.png
  content/articles/building-spotify-recommendation-engine/snapshot-1.JPG
  content/articles/building-spotify-recommendation-engine/snapshot-2.JPG
  content/articles/building-spotify-recommendation-engine/snapshot-3.JPG
  content/articles/building-spotify-recommendation-engine/snapshot-4.JPG
  content/articles/building-spotify-recommendation-engine/snapshot-5.JPG
  content/articles/building-spotify-recommendation-engine/snapshot-6.JPG
  content/articles/building-spotify-recommendation-engine/spotify-api.png
  content/articles/building-spotify-recommendation-engine/web-api.JPG
  content/authors/tanmoy-ghosh/avatar.jpg
  content/authors/tanmoy-ghosh/index.md
Labels: good first article, assigned for review, ready for final review

#3926 Setting up a Private DNS server with Raspberry Pi
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/adpater-settings.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/control.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/edit-cache.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/edit-conf-file.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/hero.jpg
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/index.md
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/install-dnsmasq.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/ipaddress.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/network-adapter.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/network-and-internet.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/network-status.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/properties-1.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/properties-2.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/responsetime1.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/responsetime2.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/set-dns.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/status.png
  content/articles/setting-up-a-private-dns-server-with-raspberry-pi/update.png
Labels: assigned for review, ready for final review, tech tutorial

#3944 Linear and Binary Search In Java Data Structures and Algorithms
  content/articles/linear-and-binary-search-algorithms-in-java/hero.jpg
  content/articles/linear-and-binary-search-algorithms-in-java/index.md
Labels: assigned for review, ready for final review, test reviewer assigned

#4243 Update Area of Expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#3802 Integrate airtable with Next.js
  content/articles/integrate-airtable-with-nextjs/create-req.png
  content/articles/integrate-airtable-with-nextjs/delete-req.png
  content/articles/integrate-airtable-with-nextjs/final.png
  content/articles/integrate-airtable-with-nextjs/hero.png
  content/articles/integrate-airtable-with-nextjs/index.md
  content/articles/integrate-airtable-with-nextjs/update-req.png
  content/authors/giridhar-talla/avatar.jpg
  content/authors/giridhar-talla/index.md
Labels: good first article, ready for final review

#3807 Adding custom methods for LINQ queries
  content/articles/adding-custom-methods-for-linq-queries/hero.jpg
  content/articles/adding-custom-methods-for-linq-queries/index.md
Labels: assigned for review, ready for final review

#3951 Integrating firebase database in django
  content/articles/integrating-firebase-database-in-django/appname.png
  content/articles/integrating-firebase-database-in-django/choose.png
  content/articles/integrating-firebase-database-in-django/create-database.png
  content/articles/integrating-firebase-database-in-django/created.png
  content/articles/integrating-firebase-database-in-django/database.png
  content/articles/integrating-firebase-database-in-django/hero.png
  content/articles/integrating-firebase-database-in-django/index.md
  content/articles/integrating-firebase-database-in-django/new-project.png
  content/articles/integrating-firebase-database-in-django/project-name.png
  content/articles/integrating-firebase-database-in-django/refresh.png
  content/articles/integrating-firebase-database-in-django/result.png
  content/articles/integrating-firebase-database-in-django/setup.png
  content/articles/integrating-firebase-database-in-django/test-mode.png
Labels: assigned for review, ready for final review, tech tutorial

#4017 Setting up a Wi-Fi extender using a raspberry pi
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/dnsmasq.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/hero.jpg
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/hostapd-config.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/hostapd.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/index.md
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/restartservice.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/step10.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/step12.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/step12b.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/step4.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/step5.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/step7a.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/step7b.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/step9.png
  content/articles/setting-up-a-wifi-extender-using-a-raspberry-pi/updating_packages.png
Labels: assigned for review, ready for final review, tech tutorial

#4001 Making predictions using monte carlo simulation
  content/articles/making-predictions-using-monte-carlo-simulation/hero.jpg
  content/articles/making-predictions-using-monte-carlo-simulation/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4044 Creating movies and animations using matlab
  content/articles/creating-movies-and-animations-using-matlab/animation_one.png
  content/articles/creating-movies-and-animations-using-matlab/animation_three.png
  content/articles/creating-movies-and-animations-using-matlab/animation_two.png
  content/articles/creating-movies-and-animations-using-matlab/hero.jpg
  content/articles/creating-movies-and-animations-using-matlab/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4251 Update My Article On Spring Security
  content/articles/an-all-in-one-spring-security-crash-course-for-java-developers/index.md
Labels: article update

#3948 How to set up and Build a Vue app with a Flask backend using Docker
  content/articles/how-to-build-a-vue-app-with-flask-sqlite-backend-using-docker/add-todos-page.PNG
  content/articles/how-to-build-a-vue-app-with-flask-sqlite-backend-using-docker/flask-console-output.PNG
  content/articles/how-to-build-a-vue-app-with-flask-sqlite-backend-using-docker/hero.png
  content/articles/how-to-build-a-vue-app-with-flask-sqlite-backend-using-docker/index.md
  content/articles/how-to-build-a-vue-app-with-flask-sqlite-backend-using-docker/todos-page.PNG
Labels: ready for final review

#4086 Introduction to Netcat
  content/articles/Introduction-to-Netcat/help.png
  content/articles/Introduction-to-Netcat/hero.jpg
  content/articles/Introduction-to-Netcat/index.md
Labels: assigned for review, ready for final review

#4051 Added image field to RSS feed
  layouts/articles/rss.xml
Labels: enhancement, feature request

#3957 Getting started with Decision Trees in python
  content/articles/decision-tree-in-python/data-image.png
  content/articles/decision-tree-in-python/encoded.png
  content/articles/decision-tree-in-python/hero.png
  content/articles/decision-tree-in-python/index.md
  content/articles/decision-tree-in-python/our-data.drop.png
  content/articles/decision-tree-in-python/our-data.png
  content/articles/decision-tree-in-python/tree-structure.png
  content/articles/decision-tree-in-python/weather.png
Labels: assigned for review, ready for final review, tech tutorial

#3975 How to Use a Local DNS Resolver to Redirect All DNS Requests
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/hero.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/image-01.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/image-02.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/image-03.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/image-04.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/image-05.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/image-06.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/image-07.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/image-08.png
  content/articles/local-dns-resolver-to-redirect-all-dns-requests/index.md
  content/authors/daniel-muriithi/avatar.jpg
  content/authors/daniel-muriithi/index.md
Labels: good first article, ready for final review
