Repository section-engineering-education/engineering-education, pull requests merged in 2021-12, with the labels that each got.

#5002 How to control a Servo Motor using a Raspberry Pi 3
  content/articles/how-to-control-a-servo-motor-using-a-raspberry-pi-3/hero.jpg
  content/articles/how-to-control-a-servo-motor-using-a-raspberry-pi-3/index.md
  content/articles/how-to-control-a-servo-motor-using-a-raspberry-pi-3/jumper-cable.png
  content/articles/how-to-control-a-servo-motor-using-a-raspberry-pi-3/pi-pin-numbering.jpg
  content/articles/how-to-control-a-servo-motor-using-a-raspberry-pi-3/servo-motor.png
  content/articles/how-to-control-a-servo-motor-using-a-raspberry-pi-3/servo.png
Labels: assigned for review, ready for final review, tech tutorial

#4888 Understanding Diffie Helman and Elgamal Asymmetric Encryption
  content/articles/diffie-hellman-elgamal/hero.png
  content/articles/diffie-hellman-elgamal/index.md
  content/authors/gitahi-philomena/avatar.jpg
  content/authors/gitahi-philomena/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#4706 How to ground truth label your datasets
  content/articles/how-to-ground-truth-label-your-datasets/ground1.png
  content/articles/how-to-ground-truth-label-your-datasets/ground10.png
  content/articles/how-to-ground-truth-label-your-datasets/ground11.png
  content/articles/how-to-ground-truth-label-your-datasets/ground12.png
  content/articles/how-to-ground-truth-label-your-datasets/ground12a.png
  content/articles/how-to-ground-truth-label-your-datasets/ground13.png
  content/articles/how-to-ground-truth-label-your-datasets/ground14.png
  content/articles/how-to-ground-truth-label-your-datasets/ground15.png
  content/articles/how-to-ground-truth-label-your-datasets/ground16.png
  content/articles/how-to-ground-truth-label-your-datasets/ground2.png
  content/articles/how-to-ground-truth-label-your-datasets/ground3.png
  content/articles/how-to-ground-truth-label-your-datasets/ground4.png
  content/articles/how-to-ground-truth-label-your-datasets/ground5.png
  content/articles/how-to-ground-truth-label-your-datasets/ground6.png
  content/articles/how-to-ground-truth-label-your-datasets/ground7.png
  content/articles/how-to-ground-truth-label-your-datasets/ground8.png
  content/articles/how-to-ground-truth-label-your-datasets/ground9.png
  content/articles/how-to-ground-truth-label-your-datasets/hero.jpg
  content/articles/how-to-ground-truth-label-your-datasets/index.md
Labels: assigned for review, ready for final review

#4902 Working with coroutine in python
  content/articles/working-with-coroutine-in-python/hero.jpg
  content/articles/working-with-coroutine-in-python/index.md
  content/authors/stanley-nganga/avatar.jpg
  content/authors/stanley-nganga/index.md
Labels: good first article, ready for final review, tech tutorial

#4922 Working with CSV files in Python
  content/articles/working-with-csv-files-in-python/hero.png
  content/articles/working-with-csv-files-in-python/image1.png
  content/articles/working-with-csv-files-in-python/image2.png
  content/articles/working-with-csv-files-in-python/image3.png
  content/articles/working-with-csv-files-in-python/image4.png
  content/articles/working-with-csv-files-in-python/index.md
Labels: assigned for review, ready for final review

#4816 An Introduction to PyTorch Lightning
  content/articles/an-introduction-to-pytorch-lightning/hero.png
  content/articles/an-introduction-to-pytorch-lightning/index.md
Labels: ready for final review, tech tutorial

#4921 How to build a task manager with angular
  content/articles/how-to-build-a-task-manager-with-angular/formgroup1.png
  content/articles/how-to-build-a-task-manager-with-angular/hero.jpg
  content/articles/how-to-build-a-task-manager-with-angular/index.md
  content/articles/how-to-build-a-task-manager-with-angular/todo-list.png
Labels: ready for final review, tech tutorial

#5099 How to detect stop traffic using deep R-CNN in both real time and offline mode in Matlab
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/hero.jpg
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/index.md
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopEight.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopEleven.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopFive.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopFour.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopNine.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopOne.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopSeven.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopSix.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopTen.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopThree.png
  content/articles/detect-stop-traffic-deep-rcnn-in-matlab/stopTwo.png
Labels: ready for final review, tech tutorial

#5092 Using JavaScript's mathematical functions to create animations
  content/articles/javascript-math-animations/circle.png
  content/articles/javascript-math-animations/hero.jpg
  content/articles/javascript-math-animations/index.md
  content/articles/javascript-math-animations/triangle.png
Labels: assigned for review, ready for final review, tech tutorial

#5224 How to Create a Collapsible Bottom Navigation Bar using Android Jetpack Compose Navigation
  content/articles/collapsible-bottom-navigation-bar-using-jetpack-compose-navigation/empty-compose-activity.png
  content/articles/collapsible-bottom-navigation-bar-using-jetpack-compose-navigation/hero.png
  content/articles/collapsible-bottom-navigation-bar-using-jetpack-compose-navigation/index.md
  content/articles/collapsible-bottom-navigation-bar-using-jetpack-compose-navigation/kotlin-class.png
  content/articles/collapsible-bottom-navigation-bar-using-jetpack-compose-navigation/kotlin-sealed-class.png
Labels: duplicate, ready for final review, tech tutorial

#4871 How to set up a Simple Python WebSocket with AioHTTP
  content/articles/how-to-set-up-a-python-web-socket-with-aiohttp/hero.png
  content/articles/how-to-set-up-a-python-web-socket-with-aiohttp/index.md
  content/authors/carol-wanjiru/avatar.jpg
  content/authors/carol-wanjiru/index.md
Labels: good first article, assigned for review, ready for final review

#4879 Getting Started with DBSCAN Clustering in Python
  content/articles/dbscan-clustering-in-python/clusters-plot.png
  content/articles/dbscan-clustering-in-python/data-head.png
  content/articles/dbscan-clustering-in-python/distances-plot.png
  content/articles/dbscan-clustering-in-python/hero.png
  content/articles/dbscan-clustering-in-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#4985 Implementing a custom zoom in and zoom out imageview in android with kotlin
  content/articles/implementing-a-custom-zoom-in-and-zoom-out-imageview-in-android-with-kotlin/demo1.png
  content/articles/implementing-a-custom-zoom-in-and-zoom-out-imageview-in-android-with-kotlin/demo2.png
  content/articles/implementing-a-custom-zoom-in-and-zoom-out-imageview-in-android-with-kotlin/hero.png
  content/articles/implementing-a-custom-zoom-in-and-zoom-out-imageview-in-android-with-kotlin/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5010 Cancer Cell Classification using Scikit-Learn
  content/articles/cancer-cell-classification-using-scikit-learn/hero.jpg
  content/articles/cancer-cell-classification-using-scikit-learn/index.md
  content/authors/meshack-john/avatar.jpg
  content/authors/meshack-john/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#5348 Article Update: Integrating django with tinymce
  content/articles/integrating-django-with-tinymce/homepage_Test.jpg
  content/articles/integrating-django-with-tinymce/index.md
  content/articles/integrating-django-with-tinymce/tinymceTest.jpg
Labels: article update

#5019 How to develop an API architecture(Duplicate PR of #4875)
  content/articles/how-to-develop-api-architecture/hero.jpg
  content/articles/how-to-develop-api-architecture/index.md
Labels: assigned for review, ready for final review

#5005 Implementing Frontend Pagination in React
  content/articles/frontend-pagination-react/hero.jpg
  content/articles/frontend-pagination-react/index.md
  content/authors/kevin-murimi/avatar.png
Labels: assigned for review, ready for final review

#5027 Devops test automation strategy for a successful CI/CD adoption
  content/articles/devops-test-automation-strategy-for-a-successful-ci-cd-adoption/devops-automation-model.png
  content/articles/devops-test-automation-strategy-for-a-successful-ci-cd-adoption/hero.jpg
  content/articles/devops-test-automation-strategy-for-a-successful-ci-cd-adoption/index.md
  content/articles/devops-test-automation-strategy-for-a-successful-ci-cd-adoption/pyramid.png
  content/authors/johnson-kamau/avatar.jpg
  content/authors/johnson-kamau/index.md
Labels: good first article, assigned for review, ready for final review, article

#5035 Creating a one to one video call Android app with Agora SDK using Kotlin
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/android_studio_project.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/demo1.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/demo2.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/demo3.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/generate_token.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/generated_token.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/hero.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/index.md
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/new_agora_project.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/temp_token.png
  content/articles/creating-a-one-to-one-video-call-android-app-with-agora-sdk-with-kotlin/welcome_edit.png
Labels: ready for final review, tech tutorial

#5049 Getting Started With Elarian
  content/articles/elarian-javascript-demo/api-key.png
  content/articles/elarian-javascript-demo/channel-app-code.png
  content/articles/elarian-javascript-demo/channel.png
  content/articles/elarian-javascript-demo/create-org.png
  content/articles/elarian-javascript-demo/elarian-signup.png
  content/articles/elarian-javascript-demo/final-screen_.png
  content/articles/elarian-javascript-demo/hero.png
  content/articles/elarian-javascript-demo/index.md
  content/articles/elarian-javascript-demo/initial-screen.png
  content/articles/elarian-javascript-demo/new-app.png
  content/articles/elarian-javascript-demo/org-explorer.png
Labels: assigned for review, ready for final review, tech tutorial

#5059 Running Laravel migrations on an existing database.
  content/articles/laravel-existing-database-migrations/hero.jpg
  content/articles/laravel-existing-database-migrations/index.md
  content/articles/laravel-existing-database-migrations/migration-three.png
  content/articles/laravel-existing-database-migrations/migration-two.png
  content/articles/laravel-existing-database-migrations/screen-final.png
  content/articles/laravel-existing-database-migrations/screen-one.png
  content/articles/laravel-existing-database-migrations/screen-three.png
  content/articles/laravel-existing-database-migrations/screen-two.png
Labels: assigned for review, tech review, ready for final review

#5016 Create a Java getter-setter generator using Python
  content/articles/create-a-java-getter-setter-generator-using-python/hero.png
  content/articles/create-a-java-getter-setter-generator-using-python/index.md
Labels: assigned for review, ready for final review

#5135 [Duplicate of #4991]: Building Autocorrect Feature Using NLP with Python
  content/articles/building-autocorrect-feature-using-nlp-with-python/hero.jpg
  content/articles/building-autocorrect-feature-using-nlp-with-python/index.md
  content/articles/building-autocorrect-feature-using-nlp-with-python/output.jpg
  content/authors/antony-lia/avatar.jpeg
  content/authors/antony-lia/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5120 The Basics of Fraud Detection Analytics
  content/articles/basics-of-fraud-detection-analytics/hero.jpg
  content/articles/basics-of-fraud-detection-analytics/index.md
Labels: assigned for review, ready for final review

#5126 [Languages] OOP Concept: Understanding Inheritance and Polymorphism in Java
  content/articles/understanding-java-inheritance-and-polymorphism/hero.jpg
  content/articles/understanding-java-inheritance-and-polymorphism/index.md
  content/authors/frank-joseph/avatar.jpg
  content/authors/frank-joseph/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5133 Getting Started with Recoil as a State Management Library for React Applications
  content/articles/react-recoil-state-management/hero.jpg
  content/articles/react-recoil-state-management/index.md
  content/authors/anne-mwangi/avatar.jpg
  content/authors/anne-mwangi/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5137 Introduction Firebase 9 and above with React Native
  content/articles/firebase-nine-and-above-with-react-native/add-a-new-project.png
  content/articles/firebase-nine-and-above-with-react-native/application-registration.png
  content/articles/firebase-nine-and-above-with-react-native/cloud-firestore.png
  content/articles/firebase-nine-and-above-with-react-native/hero.jpg
  content/articles/firebase-nine-and-above-with-react-native/home-page-todos-delete.jpg
  content/articles/firebase-nine-and-above-with-react-native/home-page-with-todos.jpg
  content/articles/firebase-nine-and-above-with-react-native/home-page.jpg
  content/articles/firebase-nine-and-above-with-react-native/index.md
Labels: assigned for review, ready for final review

#5158 Create a Next.js Blog App with TypeScript, Apollo Server and FaunaDB
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/add-article-response.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/add-article.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/apollo-gui-playground.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/apollo-launch-server.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/article-spec-page.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/articles-home.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/create-fauna-db.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/hero.jpg
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/index.md
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/initial-server-log.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/new-collection-page.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/new-collection.png
  content/articles/nextjs-blog-faunadb-typescript-apollo-server/security-section.png
Labels: assigned for review, ready for final review, tech tutorial

#5177 Working with Gridbag layout in Java
  content/articles/working-with-gridbag-layout-in-java/1-layout-sketch.jpg
  content/articles/working-with-gridbag-layout-in-java/2-final.jpg
  content/articles/working-with-gridbag-layout-in-java/3-gui-title.jpg
  content/articles/working-with-gridbag-layout-in-java/4-close-button.jpg
  content/articles/working-with-gridbag-layout-in-java/hero.png
  content/articles/working-with-gridbag-layout-in-java/index.md
  content/authors/suleiman-ibrahim/avatar.png
  content/authors/suleiman-ibrahim/index.md
Labels: assigned for review, ready for final review

#5197 [Duplicate of #5078]: Building Scalable Multi-Module Projects in Spring Boot
  content/articles/multi-module-architecture-with-spring-boot-and-maven/bonus.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/controller.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/data.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/datatwo.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/hero.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/index.md
  content/articles/multi-module-architecture-with-spring-boot-and-maven/landing.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/packaging.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/parentpom.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/payment.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/picone.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/service.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/settingup.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/springstart.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/startproject.jpg
  content/articles/multi-module-architecture-with-spring-boot-and-maven/startproject1.jpg
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#4827 Implementation of linear quadratic regulator (lqr) control for the inverted pendulum on a cart using Matlab
  content/articles/implementation-of-linear-quadratic-regulator-control-for-the-inverted-pendulum/hero.jpg
  content/articles/implementation-of-linear-quadratic-regulator-control-for-the-inverted-pendulum/index.md
  content/articles/implementation-of-linear-quadratic-regulator-control-for-the-inverted-pendulum/pendulum-four.png
  content/articles/implementation-of-linear-quadratic-regulator-control-for-the-inverted-pendulum/pendulum-one.png
  content/articles/implementation-of-linear-quadratic-regulator-control-for-the-inverted-pendulum/pendulum-three.png
  content/articles/implementation-of-linear-quadratic-regulator-control-for-the-inverted-pendulum/pendulum-two.png
Labels: enhancement, assigned for review

#5183 Dockerizing an ASP.NET Core Web API app and SQL Server
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/add-new-movie.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/asp-sql.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/aspproj-name.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/aspsql-cont.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/container-orchestrator.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/delete-movie.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/disable-docker.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/docker-compose.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/edit-movie-btn.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/hero.jpg
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/index.md
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/modify-movie.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/new-asp-proj.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/new-movie.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/ssms-connect.png
  content/articles/dockerizing-an-aspnet-core-web-api-app-and-sql-server/target-os.png
Labels: assigned for review, ready for final review, tech tutorial

#5213 [Duplicate of #5054]: Mock a Datasource for react using json-server
  content/articles/mock-a-datasource-for-react-using-json-server/Homepage.png
  content/articles/mock-a-datasource-for-react-using-json-server/about-page.png
  content/articles/mock-a-datasource-for-react-using-json-server/add-items.png
  content/articles/mock-a-datasource-for-react-using-json-server/final-server-product-image.png
  content/articles/mock-a-datasource-for-react-using-json-server/hero.png
  content/articles/mock-a-datasource-for-react-using-json-server/index.md
  content/articles/mock-a-datasource-for-react-using-json-server/querying.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5018 A Gentle Introduction to the Python Binance API
  content/articles/a-gentle-introduction-to-the-python-binance-api/api.png
  content/articles/a-gentle-introduction-to-the-python-binance-api/column-converted.png
  content/articles/a-gentle-introduction-to-the-python-binance-api/hero.png
  content/articles/a-gentle-introduction-to-the-python-binance-api/index.md
  content/articles/a-gentle-introduction-to-the-python-binance-api/number-column.png
  content/articles/a-gentle-introduction-to-the-python-binance-api/numerical-columns.png
  content/articles/a-gentle-introduction-to-the-python-binance-api/plot.png
Labels: ready for final review, tech tutorial

#5037 How To Build GraphQL APIs with ExpressJS and Typescript
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/add-update-book-mutation.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/all-books-query-mongo.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/books-book-query-mongo.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/books-query.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/build-schema-docs.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/delete-book-mutation.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/graphql-query.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/graphql-server.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/hero.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/index.md
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/multiple-addbook-mutation-mongo.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/multiple-queries.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/project-structure.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/sample-gql-mutation.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/sample-gql-query.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/sample-gql-schema.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/sample-gql-subscription.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/single-book-query.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/ts-project-structure.png
  content/articles/how-to-build-graphql-apis-with-expressjs-and-typescript/update-and-delete-book-mutations-mongo.png
Labels: assigned for review, ready for final review, tech tutorial

#5151 [Duplicate of #4236]: How to create a responsive React navigation bar using PrimeReact
  content/articles/using-prime-react-in-react-applications/app.png
  content/articles/using-prime-react-in-react-applications/code.png
  content/articles/using-prime-react-in-react-applications/hero.png
  content/articles/using-prime-react-in-react-applications/index.md
  content/authors/gerald-ezenagu/avatar.jpg
  content/authors/gerald-ezenagu/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, tech tutorial

#5261 Implementing a Generic Singly linked list Data Structure in Java
  content/articles/generic-singly-linked-list-data-structure-java/hero.jpg
  content/articles/generic-singly-linked-list-data-structure-java/index.md
  content/authors/lynn-mumo/avatar.jpg
  content/authors/lynn-mumo/index.md
Labels: duplicate, assigned for review, ready for final review

#5418 [Article Update]Spring Boot Rest template
  content/articles/spring-boot-rest-template/create-todo.png
  content/articles/spring-boot-rest-template/delete.png
  content/articles/spring-boot-rest-template/get-todo-by-id.png
  content/articles/spring-boot-rest-template/get-todos.png
  content/articles/spring-boot-rest-template/get.png
  content/articles/spring-boot-rest-template/index.md
  content/articles/spring-boot-rest-template/post.png
  content/articles/spring-boot-rest-template/put.png
  content/articles/spring-boot-rest-template/update-todo.png
Labels: article update

#5167 Advanced form operations In Jetpack compose
  content/articles/jetpack-compose-forms/hero.jpg
  content/articles/jetpack-compose-forms/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5178 Understanding Server-side request forgery attacks
  content/articles/server-side-request-forgery-attacks/adminpageinspect.png
  content/articles/server-side-request-forgery-attacks/deleteuserrequest.png
  content/articles/server-side-request-forgery-attacks/hero.png
  content/articles/server-side-request-forgery-attacks/index.md
  content/articles/server-side-request-forgery-attacks/lab1capture.png
  content/articles/server-side-request-forgery-attacks/lab1capture2.png
  content/articles/server-side-request-forgery-attacks/lab1capture3.png
  content/articles/server-side-request-forgery-attacks/lab1cspture .png
  content/articles/server-side-request-forgery-attacks/redirect.png
  content/authors/felix-vaati/index.md
Labels: ready for final review

#5193 How To Add Pure CSS Waves To Your Website
  content/articles/pure-css-wave-animations-website/hero.jpg
  content/articles/pure-css-wave-animations-website/index.md
  content/authors/linchez-maina/avatar.jpeg
  content/authors/linchez-maina/index.md
Labels: good first article, ready for final review

#5366 Creating Responsive Line and Bar charts with React and Semantic-UI
  content/articles/responsive-charts-with-semantic-ui-and-react/hero.jpg
  content/articles/responsive-charts-with-semantic-ui-and-react/index.md
  content/authors/fred-benson/avatar.jpg
  content/authors/fred-benson/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5215 Solving a one way ANOVA with Excel and testing for normality and homogeneity using Python
  content/articles/one-way-anova-excel-testing-normality-homogeneity-using-python/bartlett.jpg
  content/articles/one-way-anova-excel-testing-normality-homogeneity-using-python/boxplot.jpg
  content/articles/one-way-anova-excel-testing-normality-homogeneity-using-python/data-set.jpg
  content/articles/one-way-anova-excel-testing-normality-homogeneity-using-python/hero.jpg
  content/articles/one-way-anova-excel-testing-normality-homogeneity-using-python/index.md
  content/articles/one-way-anova-excel-testing-normality-homogeneity-using-python/input-range.jpg
  content/articles/one-way-anova-excel-testing-normality-homogeneity-using-python/result.jpg
  content/articles/one-way-anova-excel-testing-normality-homogeneity-using-python/unicode-error.jpg
  content/authors/kuteyi-victor-toluwase/avatar.jpg
  content/authors/kuteyi-victor-toluwase/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#5221 [duplicate of #5200]: The complete roadmap to blockchain development
  content/articles/the-complete-roadmap-to-blockchain-development/hero.jpg
  content/articles/the-complete-roadmap-to-blockchain-development/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5153 Understanding Ethereum and smart contracts
  content/articles/ethereum-and-smart-contracts/data-transaction-healthcare.png
  content/articles/ethereum-and-smart-contracts/hero.jpeg
  content/articles/ethereum-and-smart-contracts/index.md
  content/articles/ethereum-and-smart-contracts/smartcontracts.jpg
Labels: assigned for review, ready for final review

#5473 Enged article banner
  assets/scss/components/_all.scss
  assets/scss/components/_engEd-banner.scss
  layouts/articles/single.html
  layouts/partials/engineering-education/eng-ed-banner.html
Labels: enhancement

#5055 [Android]Authentication using facebook in android studio
  content/articles/authentication-using-facebook-in-android-studio/creating_project.png
  content/articles/authentication-using-facebook-in-android-studio/facebook_for_developers.png
  content/articles/authentication-using-facebook-in-android-studio/hero.jpg
  content/articles/authentication-using-facebook-in-android-studio/index.md
Labels: ready for final review

#5129 A General Purpose Intelligence System
  content/articles/general-purpose-intelligence-system/hero.png
  content/articles/general-purpose-intelligence-system/index.md
  content/authors/monica-dalmas/avatar.png
  content/authors/monica-dalmas/index.md
Labels: good first article, assigned for review, ready for final review, article

#5170 Understanding Cross-Site Scripting Attacks
  content/articles/understanding-cross-site-scripting-attacks/acunetix.png
  content/articles/understanding-cross-site-scripting-attacks/alert.png
  content/articles/understanding-cross-site-scripting-attacks/hero.png
  content/articles/understanding-cross-site-scripting-attacks/in.png
  content/articles/understanding-cross-site-scripting-attacks/index.md
  content/articles/understanding-cross-site-scripting-attacks/profile-login.png
  content/articles/understanding-cross-site-scripting-attacks/stored.png
  content/articles/understanding-cross-site-scripting-attacks/test1.png
  content/articles/understanding-cross-site-scripting-attacks/u.png
  content/articles/understanding-cross-site-scripting-attacks/xss.png
  content/authors/shuaib-oseni/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5182 Imbalanced-Learn Python Package for Machine Learning
  content/articles/imbalanced-learn-python-package-for-machine-learning/accuracy-score.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/accuracy-score1.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/class-distribution.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/class-distribution1.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/class-distribution2.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/class-distribution3.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/dataset-columns.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/hero.jpg
  content/articles/imbalanced-learn-python-package-for-machine-learning/index.md
  content/articles/imbalanced-learn-python-package-for-machine-learning/pie-chart-train-set.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/pie-chart.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/random-oversampling.png
  content/articles/imbalanced-learn-python-package-for-machine-learning/random-undersampling.png
Labels: assigned for review, ready for final review, tech tutorial

#5242 [Duplicate of #5147]: Saving and Loading Stacked Ensemble Classifiers in ONNX format in Python
  content/articles/save-and-load-stacked-ensembles-in-onnx/df1.png
  content/articles/save-and-load-stacked-ensembles-in-onnx/hero.jpg
  content/articles/save-and-load-stacked-ensembles-in-onnx/index.md
  content/authors/ian-njari/avatar.jpg
  content/authors/ian-njari/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5042 Effects and Side Effects handling in Jetpack Compose
  content/articles/side-effects-and-effects-handling-in-jetpack-compose/hero.png
  content/articles/side-effects-and-effects-handling-in-jetpack-compose/index.md
  content/authors/samantha-namenya/avatar.jpg
  content/authors/samantha-namenya/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5163 Hyperparameter Tuning of Machine Learning Model in Python
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/best-parameters.png
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/grid-search-technique.png
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/hero.jpg
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/index.md
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/model-training.png
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/n-estimators-range.png
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/optimized-model.png
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/prediction-results.png
  content/articles/hyperparameter-tuning-of-machine-learning-model-in-python/random-search-technique.png
Labels: assigned for review, ready for final review, tech tutorial

#5034 Understanding mobile databases in networking
  content/articles/mobile-databases-in-networking/hero.jpg
  content/articles/mobile-databases-in-networking/index.md
Labels: assigned for review, ready for final review, article

#5198 How Intelligent Automation is Powering Machine Vision
  content/articles/how-intelligent-automation-is-powering-machine-vision/hero.jpg
  content/articles/how-intelligent-automation-is-powering-machine-vision/index.md
Labels: assigned for review, ready for final review

#5085 How to Pick PDF Files and Images from Phone Storage in Android Using Kotlin
  content/articles/picking-pdf-and-image-from-phone-storage/alert-dialog.png
  content/articles/picking-pdf-and-image-from-phone-storage/hero.png
  content/articles/picking-pdf-and-image-from-phone-storage/index.md
  content/articles/picking-pdf-and-image-from-phone-storage/screenshot.png
  content/authors/hepatrique-okeyo/avatar.jpeg
  content/authors/hepatrique-okeyo/index.md
Labels: assigned for review, ready for final review, test reviewer assigned

#5284 Stateful vs Stateless Architectures
  content/articles/stateful-vs-stateless-architectures/hero.png
  content/articles/stateful-vs-stateless-architectures/index.md
Labels: duplicate, assigned for review, ready for final review, test reviewer assigned

#5155 Flutter Authentication Using Flask API
  content/articles/flutter-authentication-using-flask-api/dashboard.jpeg
  content/articles/flutter-authentication-using-flask-api/demo.gif
  content/articles/flutter-authentication-using-flask-api/hero.jpg
  content/articles/flutter-authentication-using-flask-api/index.md
  content/articles/flutter-authentication-using-flask-api/login-success.jpeg
  content/articles/flutter-authentication-using-flask-api/login.jpeg
  content/articles/flutter-authentication-using-flask-api/register-success.jpeg
  content/articles/flutter-authentication-using-flask-api/register.jpeg
  content/articles/flutter-authentication-using-flask-api/user-exist.jpeg
  content/articles/flutter-authentication-using-flask-api/welcome.jpeg
  content/articles/flutter-authentication-using-flask-api/wrong-credentials.jpeg
Labels: assigned for review, ready for final review, tech tutorial

#5226 Implementing Authentication And Authaurization in Server Side Blazor
  content/articles/authorization-and-authentication-in-server-side-blazor/blazorserver.jpg
  content/articles/authorization-and-authentication-in-server-side-blazor/framework.jpg
  content/articles/authorization-and-authentication-in-server-side-blazor/hero.jpg
  content/articles/authorization-and-authentication-in-server-side-blazor/index.md
  content/articles/authorization-and-authentication-in-server-side-blazor/nameapp.jpg
  content/articles/authorization-and-authentication-in-server-side-blazor/newproject.jpg
Labels: duplicate, assigned for review, ready for final review

#5075 Getting Started with Hierarchical Clustering in Python
  content/articles/hierarchical-clustering-in-python/agglomerative-clutsering.png
  content/articles/hierarchical-clustering-in-python/centroid.png
  content/articles/hierarchical-clustering-in-python/complete-linkage.png
  content/articles/hierarchical-clustering-in-python/customer-clusters.png
  content/articles/hierarchical-clustering-in-python/data-head.png
  content/articles/hierarchical-clustering-in-python/dendogram.png
  content/articles/hierarchical-clustering-in-python/euclidean-distance.png
  content/articles/hierarchical-clustering-in-python/hero.png
  content/articles/hierarchical-clustering-in-python/index.md
  content/articles/hierarchical-clustering-in-python/single-linkage.png
  content/authors/dennis-kimutai-koech/avatar.png
  content/authors/dennis-kimutai-koech/index.md
Labels: assigned for review, ready for final review

#5204 Is a Knowledge Graph Just Another Means of Knowledge Visualization?
  content/articles/is-knowledge-graph-just-another-means-of-knowledge-visualization/hero.jpg
  content/articles/is-knowledge-graph-just-another-means-of-knowledge-visualization/index.md
Labels: assigned for review, ready for final review

#5201 [API] Building a CRUD API with the Dapper ORM in ASP.NET Core
  content/articles/building-a-crud-api-dapper-aspnet-core/create-todo.png
  content/articles/building-a-crud-api-dapper-aspnet-core/delete-todo.png
  content/articles/building-a-crud-api-dapper-aspnet-core/get-after-delete.png
  content/articles/building-a-crud-api-dapper-aspnet-core/get-after-update.png
  content/articles/building-a-crud-api-dapper-aspnet-core/get-todo.png
  content/articles/building-a-crud-api-dapper-aspnet-core/get-todos-user.png
  content/articles/building-a-crud-api-dapper-aspnet-core/get-todos.png
  content/articles/building-a-crud-api-dapper-aspnet-core/get-user.png
  content/articles/building-a-crud-api-dapper-aspnet-core/get-users.png
  content/articles/building-a-crud-api-dapper-aspnet-core/hero.png
  content/articles/building-a-crud-api-dapper-aspnet-core/index.md
  content/articles/building-a-crud-api-dapper-aspnet-core/swagger.png
  content/articles/building-a-crud-api-dapper-aspnet-core/update-todo.png
  content/authors/olumide-nwosu/avatar.jpg
  content/authors/olumide-nwosu/index.md
Labels: good first article, assigned for review, ready for final review

#5205 How to build a GlassBox Model using InterpretML Python
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/categorical-encoding.png
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/dataset-datatypes.png
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/dataset-snip.png
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/dataset-structure.png
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/glass-box-model.png
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/global-explanation.png
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/hero.jpg
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/index.md
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/local-explanation.png
  content/articles/how-to-build-a-glass-box-model-using-interpretml-python/methods-and-attributes.png
  content/authors/charles-ndirutu/avatar.jpg
  content/authors/charles-ndirutu/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#5330 A Look at C# Coding Conventions - (Duplicate of #4659)
  content/articles/a-look-at-csharp-coding-conventions/hero.jpg
  content/articles/a-look-at-csharp-coding-conventions/index.md
Labels: duplicate, assigned for review, ready for final review, article

#5217 Get started with a Lexical Analyzer
  content/articles/getting-started-with-a-lexical-analyzer/code-structure.png
  content/articles/getting-started-with-a-lexical-analyzer/compiler-construction-steps.png
  content/articles/getting-started-with-a-lexical-analyzer/hero.png
  content/articles/getting-started-with-a-lexical-analyzer/index.md
  content/articles/getting-started-with-a-lexical-analyzer/lex-analyzer-process.png
  content/articles/getting-started-with-a-lexical-analyzer/path.png
  content/articles/getting-started-with-a-lexical-analyzer/second-program-output.png
  content/articles/getting-started-with-a-lexical-analyzer/terminal-output.png
  content/articles/getting-started-with-a-lexical-analyzer/token-count.png
  content/articles/getting-started-with-a-lexical-analyzer/verbs-l-run.png
Labels: assigned for review, ready for final review, tech tutorial

#5245 Build a Static Next.js Markdown Files Blog with Typescript, MDX and Tailwind CSS
  content/articles/static-nextjs-markdown-blog-typescript-mdx-tailwindcss/hero.jpg
  content/articles/static-nextjs-markdown-blog-typescript-mdx-tailwindcss/home-page.PNG
  content/articles/static-nextjs-markdown-blog-typescript-mdx-tailwindcss/hosted-blog-application.PNG
  content/articles/static-nextjs-markdown-blog-typescript-mdx-tailwindcss/index.md
  content/articles/static-nextjs-markdown-blog-typescript-mdx-tailwindcss/specific-article-page.PNG
  content/articles/static-nextjs-markdown-blog-typescript-mdx-tailwindcss/vercel-deployment-conf.PNG
Labels: assigned for review, ready for final review, tech tutorial

#5251 Understanding the 51% attack on blockchain
  content/articles/understanding-the-51-attack-on-blockchain/hero.jpeg
  content/articles/understanding-the-51-attack-on-blockchain/index.md
Labels: assigned for review, ready for final review, article

#5211 Building a Sheep - Wolves - Grass Agent-Based Model from scratch using p5.js
  content/articles/building-a-sheep-wolves-grass-agent-based-model-from-scratch/hero.jpg
  content/articles/building-a-sheep-wolves-grass-agent-based-model-from-scratch/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5230 Accelerating Automation with Hyperautomation
  content/articles/accelerating-automation-with-hyper-automation/hero.jpg
  content/articles/accelerating-automation-with-hyper-automation/index.md
Labels: assigned for review, ready for final review

#5231 Working with Ktor-Client: How to Build and Make HTTP Requests With Ktor-Client in Android Jetpack Compose
  content/articles/http-requests-with-ktor-client-in-android-jetpack-compose/compose-activity.png
  content/articles/http-requests-with-ktor-client-in-android-jetpack-compose/hero.jpg
  content/articles/http-requests-with-ktor-client-in-android-jetpack-compose/index.md
  content/articles/http-requests-with-ktor-client-in-android-jetpack-compose/ktor-client.png
Labels: assigned for review, ready for final review, tech tutorial

#5237 Understanding Search Algorithms in AI
  content/articles/understanding-search-algorithms-in-ai/hero.jpg
  content/articles/understanding-search-algorithms-in-ai/index.md
  content/articles/understanding-search-algorithms-in-ai/search-algorithms.png
Labels: assigned for review, ready for final review

#5397 [Duplicate of #5124]: Dealing with pythons missing values: A complete guide
  content/articles/complete-guide-to-dealing-with-missing-values-in-python/hero.jpg
  content/articles/complete-guide-to-dealing-with-missing-values-in-python/index.md
  content/authors/jackline-gesare/avatar.jpg
  content/authors/jackline-gesare/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5407 [Duplicate of #5038]: Object detection with YOLOv5 and PyTorch
  content/articles/object-detection-with-yolov5-and-pytorch/boda.jpg
  content/articles/object-detection-with-yolov5-and-pytorch/boda1.jpg
  content/articles/object-detection-with-yolov5-and-pytorch/evaluation.JPG
  content/articles/object-detection-with-yolov5-and-pytorch/hero.jpg
  content/articles/object-detection-with-yolov5-and-pytorch/index.md
  content/articles/object-detection-with-yolov5-and-pytorch/inference.JPG
  content/articles/object-detection-with-yolov5-and-pytorch/object1.png
  content/articles/object-detection-with-yolov5-and-pytorch/requirements.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5222 How to classify ECG signals using continuous wavelet transform and AlexNet via transfer learning
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-eight.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-five.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-four.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-nine.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-one.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-seven.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-six.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-ten.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-three.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/class-two.png
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/hero.jpg
  content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5389 Getting Started With .NET MAUI To Build Cross-Platform Apps In Visual Studio
  content/articles/getting-started-with-dot-net-maui-for-cross-platform-apps/hero.png
  content/articles/getting-started-with-dot-net-maui-for-cross-platform-apps/index.md
  content/articles/getting-started-with-dot-net-maui-for-cross-platform-apps/maui.png
  content/articles/getting-started-with-dot-net-maui-for-cross-platform-apps/workloads.png
Labels: assigned for review, ready for final review

#5241 Creating a Pie Chart from scratch using JavaScript, HTML Canvas, and CSS
  content/articles/javascript-canvas-piechart/hero.jpg
  content/articles/javascript-canvas-piechart/index.md
  content/articles/javascript-canvas-piechart/pie-one.png
  content/articles/javascript-canvas-piechart/pie-three.png
  content/articles/javascript-canvas-piechart/pie-two.png
Labels: assigned for review, ready for final review, tech tutorial

#5289 How to build a Currency Converter with React and its Material UI
  content/articles/how-to-build-a-currency-converter-with-react-and-its-material-ui/currency-converter.jpg
  content/articles/how-to-build-a-currency-converter-with-react-and-its-material-ui/hero.jpg
  content/articles/how-to-build-a-currency-converter-with-react-and-its-material-ui/index.md
  content/articles/how-to-build-a-currency-converter-with-react-and-its-material-ui/package-json.png
Labels: assigned for review, ready for final review, tech tutorial

#5229 Deserialization in c#
  content/articles/deserialization-in-csharp/hero.png
  content/articles/deserialization-in-csharp/index.md
  content/authors/stanley-kuria/avatar.jpg
  content/authors/stanley-kuria/index.md
Labels: ready for final review

#5302 Understanding the Resilient Packet Ring Technology
  content/articles/understanding-the-resilient-packet-ring-technology/hero.jpg
  content/articles/understanding-the-resilient-packet-ring-technology/index.md
Labels: assigned for review, ready for final review

#5020 Servlet: Filter API
  content/articles/servlet-filter-api/autodemoservlet.jpg
  content/articles/servlet-filter-api/checkpasswordlenght.jpg
  content/articles/servlet-filter-api/hero.jpg
  content/articles/servlet-filter-api/index.md
  content/articles/servlet-filter-api/loginhtml.jpg
  content/articles/servlet-filter-api/projectname.jpg
  content/articles/servlet-filter-api/servletfilterprocess.jpg
  content/authors/benson-sapan/avatar.jpg
  content/authors/benson-sapan/index.md
Labels: duplicate, ready for final review

#5315 Deploying a serverless Django application with Zappa on AWS
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/admin.PNG
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/architecture.png
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/hero.png
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/index.md
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/meme.jpg
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/newadmin.PNG
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/zappa2.PNG
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/zappa3.PNG
  content/articles/deploying-a-serverless-django-restapi-with-zappa-on-aws/zappainit.PNG
Labels: assigned for review, ready for final review, tech tutorial

#5429 Beginners intro to Generative Modeling
  content/articles/beginners-intro-to-generative-modeling/autoencoder-architecture.png
  content/articles/beginners-intro-to-generative-modeling/discriminative-vs-generative.png
  content/articles/beginners-intro-to-generative-modeling/gan-architecture.png
  content/articles/beginners-intro-to-generative-modeling/generated-data.png
  content/articles/beginners-intro-to-generative-modeling/hero.jpg
  content/articles/beginners-intro-to-generative-modeling/index.md
  content/articles/beginners-intro-to-generative-modeling/latent-distribution.png
  content/articles/beginners-intro-to-generative-modeling/mnist-data.png
  content/articles/beginners-intro-to-generative-modeling/model-summary.png
  content/articles/beginners-intro-to-generative-modeling/portrait.png
  content/articles/beginners-intro-to-generative-modeling/vae-architecture.png
Labels: duplicate, ready for final review

#5268 Using kotlinx coroutines in firebase authentication and realtime database in android
  content/articles/using-kotlinx-coroutines-in-firebase-authentication-and-realtime-database-in-android/demo1.png
  content/articles/using-kotlinx-coroutines-in-firebase-authentication-and-realtime-database-in-android/demo2.png
  content/articles/using-kotlinx-coroutines-in-firebase-authentication-and-realtime-database-in-android/hero.png
  content/articles/using-kotlinx-coroutines-in-firebase-authentication-and-realtime-database-in-android/index.md
  content/articles/using-kotlinx-coroutines-in-firebase-authentication-and-realtime-database-in-android/main.png
Labels: assigned for review, ready for final review, tech tutorial

#5278 [Duplicate of #5243] React components instantiation
  content/articles/react-components-instantiation/hero.jpeg
  content/articles/react-components-instantiation/index.md
Labels: duplicate, ready for final review, tech tutorial

#5307 A 3D Object Detection Solution for Everyday Objects
  content/articles/a-3d-object-detection-solution-for-everyday-objects/annotated-image.png
  content/articles/a-3d-object-detection-solution-for-everyday-objects/hero.png
  content/articles/a-3d-object-detection-solution-for-everyday-objects/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5320 Building Web Applications With Devextreme
  content/articles/building-web-applications-with-devextreme/hero.png
  content/articles/building-web-applications-with-devextreme/image1.png
  content/articles/building-web-applications-with-devextreme/image2.png
  content/articles/building-web-applications-with-devextreme/index.md
  content/authors/abimbola-taofeek/index.md
Labels: assigned for review, ready for final review

#5606 Implementing an auto-logout feature for Android(Kotlin)
  content/articles/android-autologout-kotlin/hero.jpg
  content/articles/android-autologout-kotlin/index.md
Labels: assigned for review, ready for final review, reviewer-tryout

#5332 Android security rules
  content/articles/android-security-rules/hero.png
  content/articles/android-security-rules/index.md
Labels: assigned for review, ready for final review, article

#5392 Convert HTML to PDF with Docraptor
  content/articles/convert-html-to-pdf-with-docraptor/converted-pdf-with-docraptor.png
  content/articles/convert-html-to-pdf-with-docraptor/hero.jpg
  content/articles/convert-html-to-pdf-with-docraptor/index.md
  content/authors/kennedy-ndutha/avatar.jpg
  content/authors/kennedy-ndutha/index.md
Labels: duplicate, ready for final review, tech tutorial

#5352 How to build a Text Classification model Using BERT and Tensorflow
  content/articles/classification-model-using-bert-and-tensorflow/dataset-structure.png
  content/articles/classification-model-using-bert-and-tensorflow/hero.jpg
  content/articles/classification-model-using-bert-and-tensorflow/index.md
  content/articles/classification-model-using-bert-and-tensorflow/labeled-dataset.png
  content/articles/classification-model-using-bert-and-tensorflow/model-prediction.png
  content/articles/classification-model-using-bert-and-tensorflow/model-summary.png
  content/articles/classification-model-using-bert-and-tensorflow/model-training.png
  content/articles/classification-model-using-bert-and-tensorflow/value-count.png
Labels: assigned for review, ready for final review, tech tutorial, reviewer-tryout

#5437 How to set up Go API with the Prisma ORM
  content/articles/how-to-set-up-golong-api-with-the-prisma-orm/get-todos.png
  content/articles/how-to-set-up-golong-api-with-the-prisma-orm/go-server-with-echo.png
  content/articles/how-to-set-up-golong-api-with-the-prisma-orm/hero.jpg
  content/articles/how-to-set-up-golong-api-with-the-prisma-orm/index.md
  content/articles/how-to-set-up-golong-api-with-the-prisma-orm/logs.png
  content/articles/how-to-set-up-golong-api-with-the-prisma-orm/post-method.png
  content/articles/how-to-set-up-golong-api-with-the-prisma-orm/post-todo.png
  content/articles/how-to-set-up-golong-api-with-the-prisma-orm/sqlite-table.png
Labels: assigned for review, ready for final review, tech tutorial

#5288 Understanding the downsides of load balancing
  content/articles/understanding-the-downsides-of-load-balancing/hero.jpg
  content/articles/understanding-the-downsides-of-load-balancing/index.md
Labels: ready for final review, article

#5304 Effects of Feature Scaling on a Machine Learning Model
  content/articles/feature-scaling-effects-machine-learning-model/accuracy.jpg
  content/articles/feature-scaling-effects-machine-learning-model/df-head.jpg
  content/articles/feature-scaling-effects-machine-learning-model/df-info.jpg
  content/articles/feature-scaling-effects-machine-learning-model/df1-head-after.jpg
  content/articles/feature-scaling-effects-machine-learning-model/df2-after.jpg
  content/articles/feature-scaling-effects-machine-learning-model/df2-before.jpg
  content/articles/feature-scaling-effects-machine-learning-model/hero.jpg
  content/articles/feature-scaling-effects-machine-learning-model/index.md
  content/articles/feature-scaling-effects-machine-learning-model/print-y.jpg
  content/articles/feature-scaling-effects-machine-learning-model/y-predict.jpg
  content/articles/feature-scaling-effects-machine-learning-model/y-test.jpg
Labels: assigned for review, ready for final review, tech tutorial, reviewer-tryout

#5404 How to integrate PHP emails using Mailtrap
  content/articles/php-mailtrap/configs.png
  content/articles/php-mailtrap/hero.png
  content/articles/php-mailtrap/inbox.png
  content/articles/php-mailtrap/index.md
  content/articles/php-mailtrap/output.png
Labels: ready for final review, tech tutorial

#5442 DevOps Pipelines Automation with Cloud Build and Triggers
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/automate.png
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/dashboard.png
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/hero.jpg
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/index.md
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/pipeline.png
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/result1.png
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/shell.png
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/sourcerepo.png
  content/articles/devops-pipelines-automation-with-cloud-build-and-triggers/stages.png
Labels: assigned for review, ready for final review, tech tutorial

#5312 Data Classification with Kernel SVM in Scikit-learn
  content/articles/data-classification-with-kernel-svm-in-scikit-learn/hard-margin.png
  content/articles/data-classification-with-kernel-svm-in-scikit-learn/hero.png
  content/articles/data-classification-with-kernel-svm-in-scikit-learn/index.md
  content/articles/data-classification-with-kernel-svm-in-scikit-learn/non-linear.png
  content/articles/data-classification-with-kernel-svm-in-scikit-learn/soft-margin.png
  content/articles/data-classification-with-kernel-svm-in-scikit-learn/transformed-data.png
Labels: ready for final review, tech tutorial

#5318 Getting Started with ECLAT Algorithm in Association Rule Mining
  content/articles/eclat-algorithm-in-python/hero.png
  content/articles/eclat-algorithm-in-python/horizontal.png
  content/articles/eclat-algorithm-in-python/index.md
  content/articles/eclat-algorithm-in-python/supports.png
  content/articles/eclat-algorithm-in-python/tid-set.png
  content/articles/eclat-algorithm-in-python/verticle-format.png
Labels: assigned for review, ready for final review, tech tutorial

#5369 [Duplicate] How to deploy machine learning model as an app in Python using Gradio
  content/articles/deploying-machine-learning-model-as-an-app-in-python-using-gradio/gradio-ui.png
  content/articles/deploying-machine-learning-model-as-an-app-in-python-using-gradio/hero.png
  content/articles/deploying-machine-learning-model-as-an-app-in-python-using-gradio/image-classification-user-interface.png
  content/articles/deploying-machine-learning-model-as-an-app-in-python-using-gradio/index.md
  content/articles/deploying-machine-learning-model-as-an-app-in-python-using-gradio/multiple-inputs-output1.png
  content/articles/deploying-machine-learning-model-as-an-app-in-python-using-gradio/multiple-inputs-output2.png
  content/articles/deploying-machine-learning-model-as-an-app-in-python-using-gradio/prediction-results.png
Labels: duplicate, assigned for review, preliminary revision in progress, ready for final review

#5115 Video player in flutter using chewie and getx
  content/articles/video-player-in-flutter-using-chewie-and-getx/hero.png
  content/articles/video-player-in-flutter-using-chewie-and-getx/index.md
  content/authors/naomi-kanoi/avatar.jpg
  content/authors/naomi-kanoi/index.md
Labels: enhancement, ready for final review

#5357 Animations in Jetpack Compose [duplicate of #5316]
  content/articles/animations-in-jetpack-compose/hero.png
  content/articles/animations-in-jetpack-compose/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5383 Getting started with nltk wordnet in python
  content/articles/getting-started-with-nltk-wordnet-in-python/hero.jpg
  content/articles/getting-started-with-nltk-wordnet-in-python/index.md
  content/authors/jacinta-kyulu/avatar.jpg
  content/authors/jacinta-kyulu/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#5181 [Duplicate of #4238]: Track users using google analytics
  content/articles/track-users-using-google-analytics/account-detail.png
  content/articles/track-users-using-google-analytics/achieving-goals.png
  content/articles/track-users-using-google-analytics/age.png
  content/articles/track-users-using-google-analytics/analytics-custom-dimension.png
  content/articles/track-users-using-google-analytics/analytics-view-with-userid.png
  content/articles/track-users-using-google-analytics/automatic-data-collection.png
  content/articles/track-users-using-google-analytics/device.png
  content/articles/track-users-using-google-analytics/gender.png
  content/articles/track-users-using-google-analytics/google-analytics-admin.png
  content/articles/track-users-using-google-analytics/google-analytics-custom-dimension-user-type.png
  content/articles/track-users-using-google-analytics/google-analytics-custom-report-with-user-type.png
  content/articles/track-users-using-google-analytics/google-analytics-custom-report.png
  content/articles/track-users-using-google-analytics/google-analytics-user-explorer.png
  content/articles/track-users-using-google-analytics/hero.png
  content/articles/track-users-using-google-analytics/index.md
  content/articles/track-users-using-google-analytics/interests.png
  content/articles/track-users-using-google-analytics/internal-site-search.png
  content/articles/track-users-using-google-analytics/language.png
  content/articles/track-users-using-google-analytics/location.png
  content/articles/track-users-using-google-analytics/mobile-device-info.png
  content/articles/track-users-using-google-analytics/target-social-platforms.png
  content/authors/nancy-muthoni/avatar.jpg
  content/authors/nancy-muthoni/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, tech tutorial

#5726 Momentum based gradient optimizer and optimization techniques for gradient descent
  content/articles/gradient-descent-based-optimization-techniques/hero.jpg
  content/articles/gradient-descent-based-optimization-techniques/index.md
Labels: duplicate, ready for final review

#5411 Machine Learning image classification with Javascript and Nyckel
  content/articles/machine-learning-image-classification-with-javascript-and-nyckel/hero.png
  content/articles/machine-learning-image-classification-with-javascript-and-nyckel/htmlResult.png
  content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
  content/articles/machine-learning-image-classification-with-javascript-and-nyckel/styled.png
  content/articles/machine-learning-image-classification-with-javascript-and-nyckel/withmask.png
  content/articles/machine-learning-image-classification-with-javascript-and-nyckel/withoutmask.png
  content/authors/kamau-victor/index.md
Labels: duplicate, ready for final review, tech tutorial

#5501 How to use text databases in Python
  content/articles/using-text-databases-in-python/hero.jpg
  content/articles/using-text-databases-in-python/index.md
Labels: ready for final review, tech tutorial

#5344 Getting started with nuxt 3
  content/articles/getting-started-with-nuxt-3/comparison.jpg
  content/articles/getting-started-with-nuxt-3/hero.jpg
  content/articles/getting-started-with-nuxt-3/index.md
  content/articles/getting-started-with-nuxt-3/install-nuxt3.jpg
  content/articles/getting-started-with-nuxt-3/nuxt3-project.jpg
  content/articles/getting-started-with-nuxt-3/start-project.jpg
Labels: revisions needed, ready for final review, test reviewer assigned

#5489 Overview of developing serverless applications in C#
  content/articles/serverless-applications-in-csharp/aws-project1.png
  content/articles/serverless-applications-in-csharp/aws-publish1.png
  content/articles/serverless-applications-in-csharp/aws-window1.png
  content/articles/serverless-applications-in-csharp/azure-extensions1.png
  content/articles/serverless-applications-in-csharp/getting-started-with-aws1.png
  content/articles/serverless-applications-in-csharp/hero.jpeg
  content/articles/serverless-applications-in-csharp/index.md
  content/articles/serverless-applications-in-csharp/json-file1.png
Labels: assigned for review, ready for final review, article

#5493 Flutter timeline in action
  content/articles/flutter-timelines-progress-indicators/hero.jpg
  content/articles/flutter-timelines-progress-indicators/index.md
  content/articles/flutter-timelines-progress-indicators/timeline-one.jpg
  content/articles/flutter-timelines-progress-indicators/timeline-two.jpg
Labels: assigned for review, ready for final review, tech tutorial

#5510 Cycle Detection in a Graph in C#
  content/articles/graph-cycle-detection-csharp/Cyclegraph.png
  content/articles/graph-cycle-detection-csharp/dfs.png
  content/articles/graph-cycle-detection-csharp/directed-graph.png
  content/articles/graph-cycle-detection-csharp/graphexample.png
  content/articles/graph-cycle-detection-csharp/hero.jpg
  content/articles/graph-cycle-detection-csharp/index.md
  content/articles/graph-cycle-detection-csharp/output1.png
  content/articles/graph-cycle-detection-csharp/unidirected-1.png
  content/articles/graph-cycle-detection-csharp/unidirected.png
  content/articles/graph-cycle-detection-csharp/weightedgraph.png
Labels: duplicate, ready for final review

#5465 Building and run unikernels with OPS
  content/articles/build-and-run-unikernel-with-ops/hero.jpg
  content/articles/build-and-run-unikernel-with-ops/index.md
  content/authors/judith-nyakundi/avatar.jpeg
  content/authors/judith-nyakundi/index.md
Labels: duplicate, ready for final review

#5517 Getting Started with Singular Value Decomposition(SVD) in Python
  content/articles/singular-value-decomposition-in-python/hero.jpg
  content/articles/singular-value-decomposition-in-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5488 Exception and Error Handling in Python
  content/articles/exceptions-and-error/except.png
  content/articles/exceptions-and-error/exception_hierarchy.png
  content/articles/exceptions-and-error/hero.jpg
  content/articles/exceptions-and-error/index.jpg
  content/articles/exceptions-and-error/index.md
  content/articles/exceptions-and-error/key.jpg
  content/articles/exceptions-and-error/local.jpg
  content/articles/exceptions-and-error/nameerror.jpg
  content/articles/exceptions-and-error/try.png
  content/articles/exceptions-and-error/type.jpg
  content/articles/exceptions-and-error/zero.jpg
Labels: assigned for review, ready for final review, tech tutorial

#5323 Solving Database Re-Platforming Challenge with Adaptive Data Virtualization
  content/articles/solving-database-re-platforming-challenge-with-adaptive-data-virtualization/hero.jpg
  content/articles/solving-database-re-platforming-challenge-with-adaptive-data-virtualization/index.md
  content/authors/gregory-munene/avatar.jpg
  content/authors/gregory-munene/index.md
Labels: assigned for review, ready for final review

#5364 Signal Handling in Cpp
  content/articles/signal-handling-in-cpp/hero.jpg
  content/articles/signal-handling-in-cpp/index.md
Labels: ready for final review

#5419 Django application deployment with Ansible
  content/articles/django-ansible-deployment/hero.png
  content/articles/django-ansible-deployment/index.md
Labels: assigned for review, ready for final review

#5543 [Duplicate of #5387] searching-and-sorting-techniques
  content/articles/searching-and-sorting-techniques/hero.jpg
  content/articles/searching-and-sorting-techniques/index.md
Labels: duplicate, ready for final review, test reviewer assigned

#5513 How to build discord bot with JavaScript
  content/articles/how-to-build-discord-bot-with-javascript/Token.PNG
  content/articles/how-to-build-discord-bot-with-javascript/authorize.PNG
  content/articles/how-to-build-discord-bot-with-javascript/bot.PNG
  content/articles/how-to-build-discord-bot-with-javascript/botonline.PNG
  content/articles/how-to-build-discord-bot-with-javascript/dialog.PNG
  content/articles/how-to-build-discord-bot-with-javascript/hero.png
  content/articles/how-to-build-discord-bot-with-javascript/index.md
  content/articles/how-to-build-discord-bot-with-javascript/link.PNG
  content/articles/how-to-build-discord-bot-with-javascript/new.PNG
  content/articles/how-to-build-discord-bot-with-javascript/permission.PNG
  content/articles/how-to-build-discord-bot-with-javascript/reply.PNG
  content/articles/how-to-build-discord-bot-with-javascript/yes.PNG
  content/authors/kamau-wambui/avatar.jpg
  content/authors/kamau-wambui/index.md
Labels: ready for final review

#5504 How to build a client server application using Rust
  content/articles/how-to-build-a-client-server-application-using-rust/cargo-run.png
  content/articles/how-to-build-a-client-server-application-using-rust/client-messages.png
  content/articles/how-to-build-a-client-server-application-using-rust/client.png
  content/articles/how-to-build-a-client-server-application-using-rust/hero.png
  content/articles/how-to-build-a-client-server-application-using-rust/index.md
  content/articles/how-to-build-a-client-server-application-using-rust/rust-installation.png
  content/articles/how-to-build-a-client-server-application-using-rust/server-messages.png
  content/articles/how-to-build-a-client-server-application-using-rust/server.png
  content/articles/how-to-build-a-client-server-application-using-rust/setup.png
Labels: assigned for review, ready for final review, test reviewer assigned

#5548 [Duplicate of #5335]: Build a weather forecast app with nextjs
  content/articles/build-a-weather-forecast-app-with-next-js/api-key.png
  content/articles/build-a-weather-forecast-app-with-next-js/final-result.jpg
  content/articles/build-a-weather-forecast-app-with-next-js/first-pic.jpg
  content/articles/build-a-weather-forecast-app-with-next-js/front-end.jpg
  content/articles/build-a-weather-forecast-app-with-next-js/hero.jpg
  content/articles/build-a-weather-forecast-app-with-next-js/index.md
  content/authors/oyedele-temitope/avatar.jpg
  content/authors/oyedele-temitope/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, tech tutorial

#5586 What makes automation smart?
  content/articles/what-makes-automation-smart/hero.jpg
  content/articles/what-makes-automation-smart/index.md
Labels: assigned for review, ready for final review, article

#5557 [Machine Learning] Dropout Regularization to handle overfitting in deep learning models.
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/converted-column.png
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/dataset-structure.png
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/dropout-regularization-working.png
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/dropout-regularization.png
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/hero.jpg
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/index.md
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/model-training.png
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/sequential-model.jpeg
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/testing-phase.png
  content/articles/dropout-regularization-to-handle-overfitting-in-deep-learning-models/testing-score.png
Labels: assigned for review, ready for final review, tech tutorial

#5598 [Duplicate of #5512]: runtime-update-of-multiple-fields-in-django-using-the-f-function-the-most-efficient-way-to-go
  content/articles/runtime-updation-using-f-function-in-django/allmeterslist.jpg
  content/articles/runtime-updation-using-f-function-in-django/create-reading-act.jpg
  content/articles/runtime-updation-using-f-function-in-django/create-reading-act1.jpg
  content/articles/runtime-updation-using-f-function-in-django/create-reading-act2.jpg
  content/articles/runtime-updation-using-f-function-in-django/create-reading-act3.jpg
  content/articles/runtime-updation-using-f-function-in-django/create-reading-act4.jpg
  content/articles/runtime-updation-using-f-function-in-django/create-reading-act5.jpg
  content/articles/runtime-updation-using-f-function-in-django/defmeterusage.jpg
  content/articles/runtime-updation-using-f-function-in-django/hero.jpg
  content/articles/runtime-updation-using-f-function-in-django/index.md
  content/articles/runtime-updation-using-f-function-in-django/wecreatedmeter.jpg
  content/articles/runtime-updation-using-f-function-in-django/wecreatemeter.jpg
Labels: duplicate, ready for final review, tech tutorial

#5546 How to Build a FullStack Reactive Svelte application with MongoDB
  content/articles/how-to-build-a-fullstack-svelte-application-with-mongodb/adding-todos-response.png
  content/articles/how-to-build-a-fullstack-svelte-application-with-mongodb/default-svelte-landing-page.png
  content/articles/how-to-build-a-fullstack-svelte-application-with-mongodb/getting-todos-response.png
  content/articles/how-to-build-a-fullstack-svelte-application-with-mongodb/hero.jpg
  content/articles/how-to-build-a-fullstack-svelte-application-with-mongodb/index.md
  content/articles/how-to-build-a-fullstack-svelte-application-with-mongodb/todos-homepage.png
Labels: assigned for review, ready for final review, tech tutorial, test reviewer assigned, reviewer-tryout

#5692 Handling Angular base64 images in a RESTFul API with Laravel
  content/articles/upload-images-angular-laravel/hero.png
  content/articles/upload-images-angular-laravel/index.md
Labels: ready for final review, tech tutorial

#5558 [Duplicate of #4815]File handling in Java and C#
  content/articles/file-handling-in-java-and-csharp/hero.jpg
  content/articles/file-handling-in-java-and-csharp/index.md
Labels: ready for final review

#5596 Task Tracker Application with React Hooks
  content/articles/task-tracker-app-with-react-hooks/Remove.jpg
  content/articles/task-tracker-app-with-react-hooks/hero.jpg
  content/articles/task-tracker-app-with-react-hooks/index.md
Labels: duplicate, ready for final review
