Repository section-engineering-education/engineering-education, pull requests merged in 2021-09, with the labels that each got.

#3260 Data Access With ADO.NET In Micro Focus Visual COBOL
  content/articles/data-access-with-ado-dotnet-in-micro-focus-visual-cobol/hero.png
  content/articles/data-access-with-ado-dotnet-in-micro-focus-visual-cobol/index.md
  content/articles/data-access-with-ado-dotnet-in-micro-focus-visual-cobol/output.png
  content/articles/data-access-with-ado-dotnet-in-micro-focus-visual-cobol/storage-section.png
  content/authors/amos-magu/avatar.jpeg
  content/authors/amos-magu/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3191 Planting Timber Logs the Right Way
  content/articles/planting-timber-logs-the-right-way/add_dependency.png
  content/articles/planting-timber-logs-the-right-way/creating_a_class_java.png
  content/articles/planting-timber-logs-the-right-way/creating_a_class_kotlin.png
  content/articles/planting-timber-logs-the-right-way/creating_project2.png
  content/articles/planting-timber-logs-the-right-way/hero.png
  content/articles/planting-timber-logs-the-right-way/index.md
  content/articles/planting-timber-logs-the-right-way/manifest.png
  content/articles/planting-timber-logs-the-right-way/timber_log_java.png
  content/articles/planting-timber-logs-the-right-way/timber_log_kotlin.png
  content/authors/michael-johnson-owallah/avatar.jpg
  content/authors/michael-johnson-owallah/index.md
Labels: good first article, assigned for review, ready for final review

#3347 Form Validation in Vue.js using VeeValidate
  content/articles/form-validation-in-vue.js-using-veevalidate/hero.jpg
  content/articles/form-validation-in-vue.js-using-veevalidate/index.md
Labels: assigned for review, ready for final review

#3410 PHP Exception Handling
  content/articles/php-exception-handling/Flowfile.png
  content/articles/php-exception-handling/hero.jpg
  content/articles/php-exception-handling/index.md
  content/authors/mackrine-awino/index.md
Labels: ready for final review, tech tutorial

#3356 IoT Development with Rust vs. C++
  content/articles/iot-development-with-rust-vs-c++/hero.jpg
  content/articles/iot-development-with-rust-vs-c++/index.md
  content/authors/steve-nzovi/avatar.jpg
  content/authors/steve-nzovi/index.md
Labels: good first article, ready for final review, article

#3528 C# or C++ for game development?
  content/articles/c-sharp-or-c++-for-game-development/hero.jpg
  content/articles/c-sharp-or-c++-for-game-development/index.md
  content/authors/victor-kamau/avatar.jpg
  content/authors/victor-kamau/index.md
Labels: good first article, assigned for review, ready for final review

#3371 Build a contact form with PHP
  content/articles/build-a-contact-form-with-php/google-less-secure.jpg
  content/articles/build-a-contact-form-with-php/hero.jpg
  content/articles/build-a-contact-form-with-php/index.md
  content/articles/build-a-contact-form-with-php/project.png
  content/articles/build-a-contact-form-with-php/xampp-server-homepage.png
  content/articles/build-a-contact-form-with-php/xampp-settings.png
Labels: ready for final review, test reviewer assigned

#3379 Building simple and interactive maps using leaflet.js
  content/articles/building-simple-maps-using-leaflet-js/hero.jpg
  content/articles/building-simple-maps-using-leaflet-js/index.md
  content/articles/building-simple-maps-using-leaflet-js/mapimage.PNG
  content/authors/femi-ige-muyiwa/avatar.jpg
  content/authors/femi-ige-muyiwa/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3387 How to develop a Business Directory using CodeIgniter and MySQL?
  content/articles/how-to-develop-a-business-directory-using-codeigniter-and-mysql/biz-dir.PNG
  content/articles/how-to-develop-a-business-directory-using-codeigniter-and-mysql/codeigniter-start-page.PNG
  content/articles/how-to-develop-a-business-directory-using-codeigniter-and-mysql/hero.png
  content/articles/how-to-develop-a-business-directory-using-codeigniter-and-mysql/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3438 Displaying images with fresco library in android
  content/articles/displaying-images-with-fresco-library-in-android/demo.gif
  content/articles/displaying-images-with-fresco-library-in-android/hero.png
  content/articles/displaying-images-with-fresco-library-in-android/index.md
  content/articles/displaying-images-with-fresco-library-in-android/new_project.png
  content/authors/brandy-odhiambo/avatar.jpg
  content/authors/brandy-odhiambo/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3401 Classless Routing Using OSPF Protocol
  content/articles/classless-routing-using-ospf-protocol/hero.jpg
  content/articles/classless-routing-using-ospf-protocol/index.md
  content/articles/classless-routing-using-ospf-protocol/multiarea.jpg
  content/articles/classless-routing-using-ospf-protocol/ospf-configuration.jpg
  content/articles/classless-routing-using-ospf-protocol/ping_ospf.jpg
  content/articles/classless-routing-using-ospf-protocol/singlearea.jpg
Labels: assigned for review, ready for final review, tech tutorial

#3421 What is MVC Architecture and how does it work?
  content/articles/what-is-mvc-and-how-does-it-work/hero.png
  content/articles/what-is-mvc-and-how-does-it-work/index.md
  content/articles/what-is-mvc-and-how-does-it-work/mvc.png
  content/authors/esther-mwangi/avatar.jpg
  content/authors/esther-mwangi/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3425 Using realm database in android
  content/articles/using-realm-database-in-android/addnote.png
  content/articles/using-realm-database-in-android/allnotes.png
  content/articles/using-realm-database-in-android/hero.png
  content/articles/using-realm-database-in-android/index.md
  content/articles/using-realm-database-in-android/updatenote.png
Labels: assigned for review, ready for final review, tech tutorial

#3439 Recovering deleted files using Foremost
  content/articles/recover-deleted-files-with-foremost/all.png
  content/articles/recover-deleted-files-with-foremost/disk.png
  content/articles/recover-deleted-files-with-foremost/drive.png
  content/articles/recover-deleted-files-with-foremost/drives.jpg
  content/articles/recover-deleted-files-with-foremost/hero.jpg
  content/articles/recover-deleted-files-with-foremost/index.md
  content/articles/recover-deleted-files-with-foremost/output.png
  content/articles/recover-deleted-files-with-foremost/recover.png
  content/articles/recover-deleted-files-with-foremost/tools.png
  content/authors/denis-kuria/avatar.jpg
  content/authors/denis-kuria/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3411 Different Techniques of Encoding Data for Transmission
  content/articles/different-techniques-of-encoding-data-for-transmission/differential.png
  content/articles/different-techniques-of-encoding-data-for-transmission/hero.jpg
  content/articles/different-techniques-of-encoding-data-for-transmission/index.md
  content/articles/different-techniques-of-encoding-data-for-transmission/manchester.png
  content/articles/different-techniques-of-encoding-data-for-transmission/nrz-i.png
  content/articles/different-techniques-of-encoding-data-for-transmission/nrz-l.png
  content/authors/geoffrey-omukuba/avatar.jpg
  content/authors/geoffrey-omukuba/index.md
Labels: enhancement, test reviewer assigned

#3448 Creating a Shopping Cart using Arrays and Objects using vanilla JavaScript
  content/articles/JavaSript-Shopping-Cart/hero.jpg
  content/articles/JavaSript-Shopping-Cart/index.md
Labels: assigned for review, ready for final review

#3363 Introduction to Cloud Management
  content/articles/introduction-to-cloud-management/hero.jpg
  content/articles/introduction-to-cloud-management/index.md
Labels: assigned for review, ready for final review, article

#3364 Implementing Google reCAPTCHA in a SpringBoot application
  content/articles/spring-boot-recaptcha/hero.jpg
  content/articles/spring-boot-recaptcha/index.md
  content/articles/spring-boot-recaptcha/larger-score-image.png
  content/articles/spring-boot-recaptcha/login-image.png
  content/articles/spring-boot-recaptcha/otp-image.png
  content/articles/spring-boot-recaptcha/plagarism-check.png
  content/articles/spring-boot-recaptcha/spring-initializr.png
  content/articles/spring-boot-recaptcha/success-page-image.png
Labels: assigned for review, ready for final review

#3344 Using Azure Functions and C# to Create Serverless APIs
  content/articles/using-azure-functions-and-csharp-to-create-serverless-apis/app.jpg
  content/articles/using-azure-functions-and-csharp-to-create-serverless-apis/b13.png
  content/articles/using-azure-functions-and-csharp-to-create-serverless-apis/configure.jpg
  content/articles/using-azure-functions-and-csharp-to-create-serverless-apis/core.jpg
  content/articles/using-azure-functions-and-csharp-to-create-serverless-apis/create.jpg
  content/articles/using-azure-functions-and-csharp-to-create-serverless-apis/hero.png
  content/articles/using-azure-functions-and-csharp-to-create-serverless-apis/index.md
  content/articles/using-azure-functions-and-csharp-to-create-serverless-apis/manage.png
  content/authors/dennis-mwangi/avatar.png
  content/authors/dennis-mwangi/index.md
Labels: assigned for review, ready for final review

#3413 Webscraping with Javascript
  content/articles/introduction-to-web-scraping-with-javascript-and-puppeteer/hero.jpg
  content/articles/introduction-to-web-scraping-with-javascript-and-puppeteer/index.md
  content/authors/kevin-murimi/avatar.png
  content/authors/kevin-murimi/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3377 Build RESTful Services in Go with an idiomatic Approach
  content/articles/build-restful-services-in-go-with-an-idiomatic-approach/get-first.png
  content/articles/build-restful-services-in-go-with-an-idiomatic-approach/get-second.png
  content/articles/build-restful-services-in-go-with-an-idiomatic-approach/hero.png
  content/articles/build-restful-services-in-go-with-an-idiomatic-approach/index.md
  content/articles/build-restful-services-in-go-with-an-idiomatic-approach/post-first.png
Labels: ready for final review, test reviewer assigned

#3408 10 of the most annoying UI/UX mistakes to avoid
  content/articles/ten-ui-ux-mistakes/form-validation.png
  content/articles/ten-ui-ux-mistakes/hero.png
  content/articles/ten-ui-ux-mistakes/inconsistent-design.png
  content/articles/ten-ui-ux-mistakes/index.md
  content/articles/ten-ui-ux-mistakes/paragraphs.png
  content/articles/ten-ui-ux-mistakes/reading-paragraphs.png
  content/authors/wanjiru-alice/avatar.jpeg
  content/authors/wanjiru-alice/index.md
Labels: good first article, ready for final review

#3390 What is NetDevOps? Top NetDevOps Tools for your Windows Operating System
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/ci-cd-devnet-sandbox.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/cisco-iox-ci-cd-lab-model.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/cisco-network-culture-change.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/cisco-sanbox-lab-with-ci-cd-kubernetes.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/devops-diagram.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/hero.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/index.md
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/iox-workflow.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/netdevops-survey-env-language-stack.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/netdevops-survey-operation-automated-tool.png
  content/articles/what-is-netdevops-top-netdevops-tools-for-your-windows-operating-system/netdevops.jpg
Labels: ready for final review, article

#3483 Local GitLab Repository Mirroring to an External GitLab Repository
  content/articles/local-gitlab-repository-mirroring-to-an-external-gitlab-repository/hero.png
  content/articles/local-gitlab-repository-mirroring-to-an-external-gitlab-repository/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3412 Building A React App With TypeScript
  content/articles/building-a-react-app-with-typescript/app1.png
  content/articles/building-a-react-app-with-typescript/app_demo.gif
  content/articles/building-a-react-app-with-typescript/filestructure.png
  content/articles/building-a-react-app-with-typescript/hero.png
  content/articles/building-a-react-app-with-typescript/index.md
  content/authors/babatunde-koiki/avatar.jpg
  content/authors/babatunde-koiki/index.md
Labels: ready for final review, test reviewer assigned

#3472 PHPUnit, The Bigger Picture
  content/articles/phpunit-bigger-picture/folder-structure.png
  content/articles/phpunit-bigger-picture/hero.png
  content/articles/phpunit-bigger-picture/index.md
Labels: ready for final review, tech tutorial

#3465 How Edge Artificial Intelligence is Revolutionizing Mobile Application Development
  content/articles/edge-artificial-intelligence-and-mobile-development/hero.jpg
  content/articles/edge-artificial-intelligence-and-mobile-development/index.md
Labels: ready for final review, test reviewer assigned

#3485 Building Scrollable and Lazy Components in Jetpack Compose
  content/articles/scrollable-components-in-jetpack-compose/create-compose-project.png
  content/articles/scrollable-components-in-jetpack-compose/hero.png
  content/articles/scrollable-components-in-jetpack-compose/index.md
  content/articles/scrollable-components-in-jetpack-compose/sample-item.png
  content/articles/scrollable-components-in-jetpack-compose/sticky-headers.png
  content/articles/scrollable-components-in-jetpack-compose/vertical-list.png
  content/authors/jane-njoki/avatar.jpg
  content/authors/jane-njoki/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3394 Continuous Integration with Jenkins
  content/articles/Continuous-Integration-with-Jenkins/hero.jpg
  content/articles/Continuous-Integration-with-Jenkins/index.md
  content/authors/ruth-wambui/avatar.jpg
  content/authors/ruth-wambui/index.md
Labels: ready for final review

#3422 Curve fitting using matlab
  content/articles/curve-fitting-using-matlab/curve_eight.png
  content/articles/curve-fitting-using-matlab/curve_eleven.png
  content/articles/curve-fitting-using-matlab/curve_five.png
  content/articles/curve-fitting-using-matlab/curve_four.png
  content/articles/curve-fitting-using-matlab/curve_nine.png
  content/articles/curve-fitting-using-matlab/curve_one.png
  content/articles/curve-fitting-using-matlab/curve_seven.png
  content/articles/curve-fitting-using-matlab/curve_six.png
  content/articles/curve-fitting-using-matlab/curve_ten.png
  content/articles/curve-fitting-using-matlab/curve_three.png
  content/articles/curve-fitting-using-matlab/curve_twelve.png
  content/articles/curve-fitting-using-matlab/curve_two.png
  content/articles/curve-fitting-using-matlab/hero.jpg
  content/articles/curve-fitting-using-matlab/index.md
Labels: assigned for review, ready for final review

#3473 Multi-Class Text Classification with PySpark
  content/articles/multiclass-text-classification-with-pyspark/components-of-spark.jpg
  content/articles/multiclass-text-classification-with-pyspark/dataset-columns.jpg
  content/articles/multiclass-text-classification-with-pyspark/dataset-structure.jpg
  content/articles/multiclass-text-classification-with-pyspark/dataset.jpg
  content/articles/multiclass-text-classification-with-pyspark/hero.png
  content/articles/multiclass-text-classification-with-pyspark/index.md
  content/articles/multiclass-text-classification-with-pyspark/output.jpg
  content/articles/multiclass-text-classification-with-pyspark/pipeline-stages.jpg
  content/articles/multiclass-text-classification-with-pyspark/prediction-output.jpg
  content/articles/multiclass-text-classification-with-pyspark/pyspark-ui.jpg
  content/articles/multiclass-text-classification-with-pyspark/spark-streaming.png
  content/articles/multiclass-text-classification-with-pyspark/sparkcontext-ui-1.jpg
  content/articles/multiclass-text-classification-with-pyspark/sparkcontext-ui-2.jpg
  content/authors/james-omina/avatar.jpg
  content/authors/james-omina/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3503 Getting started with Visual Basic .NET
  content/articles/getting-started-with-visual-basic-net/hero.png
  content/articles/getting-started-with-visual-basic-net/index.md
  content/articles/getting-started-with-visual-basic-net/newproject.png
  content/articles/getting-started-with-visual-basic-net/newproject1.png
  content/articles/getting-started-with-visual-basic-net/newproject2.png
  content/articles/getting-started-with-visual-basic-net/newproject3.png
  content/articles/getting-started-with-visual-basic-net/visualstudio1.jpg
  content/articles/getting-started-with-visual-basic-net/visualstudio2.png
  content/authors/felix-vaati/index.md
Labels: assigned for review, ready for final review

#3479 Creating Serverless Functions ( Faas ) with AWS Lambda and Golang #3236
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/aws-create-lambda-setting.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/aws-lambda-dashboard.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/aws-lambda-edit-handler.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/aws-lambda-function-dashboard.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/aws-lambda-runtime-settings.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/aws-lambda-test-prompt.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/aws-lambda-test-result.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/aws-lambda-test.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/hero.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/index.md
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/sample-env-file.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/sample-program-output.png
  content/articles/serverless-functions-faas-with-aws-lambda-and-golang/search-aws-dashboard.png
Labels: assigned for review, ready for final review, tech tutorial

#3513 Extracting Colors from Images using Palette API in Android
  content/articles/extracting-colors-from-image-using-palette-API-in-android/create_project.png
  content/articles/extracting-colors-from-image-using-palette-API-in-android/hero.png
  content/articles/extracting-colors-from-image-using-palette-API-in-android/index.md
  content/articles/extracting-colors-from-image-using-palette-API-in-android/screen_one.png
  content/articles/extracting-colors-from-image-using-palette-API-in-android/screen_two.png
  content/authors/robert-muriithi/avatar.jpg
  content/authors/robert-muriithi/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3458 Getting Started with PHP 7+ without using a framework
  content/articles/getting-started-with-php7-without-using-a-framework/app-test.PNG
  content/articles/getting-started-with-php7-without-using-a-framework/folder-structure.PNG
  content/articles/getting-started-with-php7-without-using-a-framework/hero.jpg
  content/articles/getting-started-with-php7-without-using-a-framework/index.md
Labels: ready for final review

#3498 Java Swing Components Set and Get Methods
  content/articles/java-swing-setter-and-getters/guidesign.png
  content/articles/java-swing-setter-and-getters/hero.png
  content/articles/java-swing-setter-and-getters/index.md
  content/articles/java-swing-setter-and-getters/output.png
  content/authors/ayoma-joseph/avatar.jpg
Labels: assigned for review, ready for final review

#3519 Why Backup won't work for Stateful containers?
  content/articles/why-backup-wont-work-for-stateful-containers/docker-image-pull.PNG
  content/articles/why-backup-wont-work-for-stateful-containers/docker-ps-all.PNG
  content/articles/why-backup-wont-work-for-stateful-containers/hero.png
  content/articles/why-backup-wont-work-for-stateful-containers/index.md
Labels: assigned for review, ready for final review

#3514 Transitioning from Bootstrap to Semantic-UI React
  content/articles/transitioning-from-bootstrap-to-semantic-ui-react/hero.jpg
  content/articles/transitioning-from-bootstrap-to-semantic-ui-react/index.md
  content/authors/toro-nyong/avatar.jpg
  content/authors/toro-nyong/index.md
Labels: good first article, assigned for review, ready for final review

#3577 How to solve discrete logistic equation in matlab
  content/articles/how-to-solve-discrete-logistic-equation-in-matlab/hero.jpg
  content/articles/how-to-solve-discrete-logistic-equation-in-matlab/index.md
  content/articles/how-to-solve-discrete-logistic-equation-in-matlab/logistic_one.png
  content/authors/peter-adongo/avatar.jpeg
  content/authors/peter-adongo/index.md
Labels: good first article, assigned for review, ready for final review

#3586 Core Concepts Of Redux Store Management
  content/articles/core-concepts-of-redux-store-management/hero.png
  content/articles/core-concepts-of-redux-store-management/index.md
  content/articles/hero.png
  content/articles/index.md
Labels: assigned for review, ready for final review

#3533 Hapi validation bcrypt hashing and jwt
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/access-denied.png
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/email-check.png
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/folders.png
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/hero.jpg
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/index.md
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/password-check.png
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/user-auth-token.png
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/user-saved.png
  content/articles/hapi-validation-bcrypt-hashing-and-jwt/view-protected-route.png
Labels: assigned for review, ready for final review, tech tutorial

#3600 Data Encryption with Quick Response (QR) Codes in Android
  content/articles/data-encryption-with-qr-codes-in-android/code-scanner-preview.png
  content/articles/data-encryption-with-qr-codes-in-android/create-new-project.png
  content/articles/data-encryption-with-qr-codes-in-android/generate-qr-code-example.jpg
  content/articles/data-encryption-with-qr-codes-in-android/generate-qr-code-preview.png
  content/articles/data-encryption-with-qr-codes-in-android/hero.png
  content/articles/data-encryption-with-qr-codes-in-android/index.md
  content/articles/data-encryption-with-qr-codes-in-android/scan-qr-code-1.jpg
  content/articles/data-encryption-with-qr-codes-in-android/scan-qr-code-2.jpg
Labels: assigned for review, ready for final review, tech tutorial

#3566 Controlling Android Phone Using SRCPY
  content/articles/controlling-android-phone-using-scrcpy/hero.png
  content/articles/controlling-android-phone-using-scrcpy/image1.png
  content/articles/controlling-android-phone-using-scrcpy/image2.png
  content/articles/controlling-android-phone-using-scrcpy/index.md
  content/authors/nancy-mumbi/avatar.jpg
  content/authors/nancy-mumbi/index.md
Labels: enhancement, good first article, assigned for review

#3687 How to create an Android Wear OS app
  content/articles/how-to-create-an-android-wear-os-app/box-inset-layout.png
  content/articles/how-to-create-an-android-wear-os-app/drawer.png
  content/articles/how-to-create-an-android-wear-os-app/hero.png
  content/articles/how-to-create-an-android-wear-os-app/index.md
  content/articles/how-to-create-an-android-wear-os-app/swipe-dismiss-frame-layout.png
  content/authors/antony-muriuki/avatar.jpg
  content/authors/antony-muriuki/index.md
Labels: enhancement, assigned for review, tech tutorial

#3736 How to solve linear equations using matlab
  content/articles/solving-linear-equations-using-matlab/hero.jpg
  content/articles/solving-linear-equations-using-matlab/index.md
  content/articles/solving-linear-equations-using-matlab/linear_eight.png
  content/articles/solving-linear-equations-using-matlab/linear_eleven.png
  content/articles/solving-linear-equations-using-matlab/linear_fifteen.png
  content/articles/solving-linear-equations-using-matlab/linear_five.png
  content/articles/solving-linear-equations-using-matlab/linear_four.png
  content/articles/solving-linear-equations-using-matlab/linear_fourteen.png
  content/articles/solving-linear-equations-using-matlab/linear_nine.png
  content/articles/solving-linear-equations-using-matlab/linear_one.png
  content/articles/solving-linear-equations-using-matlab/linear_seven.png
  content/articles/solving-linear-equations-using-matlab/linear_seventeen.png
  content/articles/solving-linear-equations-using-matlab/linear_six.png
  content/articles/solving-linear-equations-using-matlab/linear_sixteen.png
  content/articles/solving-linear-equations-using-matlab/linear_ten.png
  content/articles/solving-linear-equations-using-matlab/linear_thirteen.png
  content/articles/solving-linear-equations-using-matlab/linear_three.png
  content/articles/solving-linear-equations-using-matlab/linear_twelve.png
  content/articles/solving-linear-equations-using-matlab/linear_two.png
Labels: revisions needed, duplicate, assigned for review, ready for final review, test reviewer assigned

#3826 Deploy flutter to gce
  content/articles/deploy-flutter-to-google-computer-engine/app-live.png
  content/articles/deploy-flutter-to-google-computer-engine/console.png
  content/articles/deploy-flutter-to-google-computer-engine/hero.png
  content/articles/deploy-flutter-to-google-computer-engine/index.md
  content/articles/deploy-flutter-to-google-computer-engine/running-instance.png
  content/articles/deploy-flutter-to-google-computer-engine/select-web.png
  content/articles/deploy-flutter-to-google-computer-engine/upload-file.png
  content/articles/deploy-flutter-to-google-computer-engine/upload.png
  content/authors/paul-romans/index.md
Labels: duplicate, assigned for review, ready for final review

#3466 Statistics hypothesis testing - (Duplicate of #2800)
  content/articles/statistical-hypothesis-testing-python-implementation/chi-square-calculation.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/chi-square.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/dataset_head.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/dataset_sample.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/df_isnull.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/df_new.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/dfsample5.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/hero.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/index.md
  content/articles/statistical-hypothesis-testing-python-implementation/one-sample-t-test.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/paired-t-test.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/two-sample-t-test.PNG
  content/articles/statistical-hypothesis-testing-python-implementation/twowayanova.PNG
Labels: duplicate, assigned for review, ready for final review, test reviewer assigned

#3581 Creating a Simple Python Note App with Flask and MongoDB database
  content/articles/building-a-simple-python-note-app-with-flask-and-mongodb/hero.jpg
  content/articles/building-a-simple-python-note-app-with-flask-and-mongodb/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3523 Monitoring a Microsoft SQL Server database using Solar Winds Database Performance Analyzer - (Duplicate of #3471)
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/accept-license.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/change-directory.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/confirmation.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/connection-to-sql-details.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/db-details.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/dpa-finish.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/file-extraction.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/hero.jpg
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/index.md
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/installation.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/monitoring-user.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/no-configuration.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/notifications.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/optimization.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/query_advisor.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/reports.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/repository-admin-user.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/repository-creation.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/resources.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/select-register-instance.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/sql-selection.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/sql-self-managed.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/success-message.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/summary.png
  content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/urls.png
Labels: duplicate, assigned for review, ready for final review, article

#3648 Implementing shooting method in Matlab
  content/articles/implementing-shooting-method-in-matlab/hero.jpg
  content/articles/implementing-shooting-method-in-matlab/index.md
  content/articles/implementing-shooting-method-in-matlab/shooting_five.png
  content/articles/implementing-shooting-method-in-matlab/shooting_four.png
  content/articles/implementing-shooting-method-in-matlab/shooting_one.png
  content/articles/implementing-shooting-method-in-matlab/shooting_three.png
  content/articles/implementing-shooting-method-in-matlab/shooting_two.png
Labels: ready for final review, tech tutorial

#3585 Getting Started With Dependency Injection in Angular 12+
  content/articles/angular-12-dependency-injection/hero.png
  content/articles/angular-12-dependency-injection/index.md
  content/articles/angular-12-dependency-injection/output.png
  content/authors/naomi-seint/avatar.jpeg
  content/authors/naomi-seint/index.md
Labels: ready for final review, tech tutorial

#3339 Getting started with Spring Boot Webflux
  content/articles/spring-webflux/delete.png
  content/articles/spring-webflux/get_all.png
  content/articles/spring-webflux/get_by_id.png
  content/articles/spring-webflux/get_by_name.png
  content/articles/spring-webflux/hero.png
  content/articles/spring-webflux/index.md
  content/articles/spring-webflux/update.png
  content/authors/sumba-elvis/avatar.jpeg
  content/authors/sumba-elvis/index.md
Labels: good first article, assigned for review, ready for final review, needs front matter, tech tutorial

#3592 How to Create a Web Component with Vanilla JavaScript
  content/articles/how-to-create-a-web-component-with-vanilla-javascript/browser-support.jpg
  content/articles/how-to-create-a-web-component-with-vanilla-javascript/employee-card.jpg
  content/articles/how-to-create-a-web-component-with-vanilla-javascript/hero.jpg
  content/articles/how-to-create-a-web-component-with-vanilla-javascript/image.png
  content/articles/how-to-create-a-web-component-with-vanilla-javascript/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3831 Java singleton design pattern
  content/articles/java-singleton-design-pattern/hero.jpg
  content/articles/java-singleton-design-pattern/index.md
  content/authors/caroline-wanjiku/avatar.jpg
  content/authors/caroline-wanjiku/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#3609 Watching for System Dark Mode changes using JavaScript and CSS
  content/articles/watch-dark-mode-js-css/hero.png
  content/articles/watch-dark-mode-js-css/index.md
Labels: ready for final review

#3572 How to create a headless CMS website using WordPress, Next.js and GraphQL Queries (WPGraphQL)
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/add-post-category.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/add-post-form.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/default-next-js-page.PNG
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/hero.jpg
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/index.md
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/plugins-search-bar.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/post-category-selection.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/post-excerpt.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/post-page.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/post-publish-button.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/posts-page.PNG
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/wp-graphql-playbutton.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/wp-graphql-plugin.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/wpgraphql-activate.png
  content/articles/create-a-headless-cms-website-using-wordpress-nextjs-and-graphql/wpgraphql-endpoint.png
Labels: assigned for review, ready for final review, tech tutorial

#3767 Building A Personality Test App with Java
  content/articles/building-a-personality-test-app-with-java/hero.jpeg
  content/articles/building-a-personality-test-app-with-java/index.md
  content/authors/badmus-kola/avatar.jpg
  content/authors/badmus-kola/index.md
Labels: duplicate, enhancement, assigned for review, ready for final review

#3579 Online Machine Learning with River Python
  content/articles/online-machine-learning-with-river-python/hero.jpg
  content/articles/online-machine-learning-with-river-python/index.md
  content/articles/online-machine-learning-with-river-python/methods-and-attributes-1.jpg
  content/articles/online-machine-learning-with-river-python/methods-and-attributes-2.jpg
  content/articles/online-machine-learning-with-river-python/offline-vs-online-machine-learning.jpg
  content/articles/online-machine-learning-with-river-python/pipeline-visualization.jpg
Labels: assigned for review, ready for final review, tech tutorial

#3637 Setup & run Docker containers on computer engine
  content/articles/docker-containers-on-compute-engine/app-running.jpg
  content/articles/docker-containers-on-compute-engine/app-running.png
  content/articles/docker-containers-on-compute-engine/authorize-api-key.png
  content/articles/docker-containers-on-compute-engine/creating image.png
  content/articles/docker-containers-on-compute-engine/creating-vm-instance.png
  content/articles/docker-containers-on-compute-engine/hero.png
  content/articles/docker-containers-on-compute-engine/image-build.png
  content/articles/docker-containers-on-compute-engine/image-created.png
  content/articles/docker-containers-on-compute-engine/index.md
  content/articles/docker-containers-on-compute-engine/running-intances.png
  content/articles/docker-containers-on-compute-engine/select-firewall.png
Labels: assigned for review, ready for final review, tech tutorial

#3619 Spring Boot Configuration Basics
  content/articles/spring-boot-configuration/hero.png
  content/articles/spring-boot-configuration/index.md
  content/articles/spring-boot-configuration/run-config.png
Labels: assigned for review, ready for final review, tech tutorial

#3599 Connect flash express sessions and boostrap
  content/articles/connect-flash-express-sessions-and-boostrap/connect-flash-errors.png
  content/articles/connect-flash-express-sessions-and-boostrap/hero.png
  content/articles/connect-flash-express-sessions-and-boostrap/homepage.png
  content/articles/connect-flash-express-sessions-and-boostrap/index.md
  content/articles/connect-flash-express-sessions-and-boostrap/login-form-validation.png
  content/articles/connect-flash-express-sessions-and-boostrap/login-page-redirect.png
  content/articles/connect-flash-express-sessions-and-boostrap/logout.png
Labels: assigned for review, ready for final review, tech tutorial

#3548 Drug Label Extraction Using Deep Learning
  content/articles/drug-labels-extraction-using-deep-learning/drug1.png
  content/articles/drug-labels-extraction-using-deep-learning/drug2.png
  content/articles/drug-labels-extraction-using-deep-learning/hero.png
  content/articles/drug-labels-extraction-using-deep-learning/index.md
  content/articles/drug-labels-extraction-using-deep-learning/output.png
Labels: ready for final review, tech tutorial

#3597 Author RSS Feeds
  content/authors/louise-findlay/index.md
  layouts/articles/rss.xml
Labels: enhancement, feature request

#3657 Kivy python first app
  content/articles/kivy-python-first-app/app.png
  content/articles/kivy-python-first-app/hero.png
  content/articles/kivy-python-first-app/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3695 How to Build a digital Clock with only HTML, CSS, and JavaScript #3536
  content/articles/build-digital-clock-using-javascript/hero.jpg
  content/articles/build-digital-clock-using-javascript/index.md
Labels: assigned for review, ready for final review

#3696 Integrating Hover SDK for offline Mpesa payments in Android with Kotlin
  content/articles/integrating-hover-sdk-in-android/add_steps.png
  content/articles/integrating-hover-sdk-in-android/created_action.png
  content/articles/integrating-hover-sdk-in-android/hero.png
  content/articles/integrating-hover-sdk-in-android/hover_app.png
  content/articles/integrating-hover-sdk-in-android/index.md
  content/articles/integrating-hover-sdk-in-android/new_action.png
  content/articles/integrating-hover-sdk-in-android/new_project.png
Labels: assigned for review, ready for final review, tech tutorial

#3718 How password hashing occurs
  content/articles/how-password-hashing-occurs/crack.png
  content/articles/how-password-hashing-occurs/hero.jpg
  content/articles/how-password-hashing-occurs/index.md
  content/articles/how-password-hashing-occurs/script.png
Labels: assigned for review, ready for final review

#3454 How to Lookup Ip Addresses in Java
  content/articles/how-to-lookup-ip-addresses-in-java/hero.jpg
  content/articles/how-to-lookup-ip-addresses-in-java/index.md
Labels: assigned for review, ready for final review

#3666 Understanding concurrency in Go
  content/articles/concurrency-in-go/goroutine.png
  content/articles/concurrency-in-go/hero.png
  content/articles/concurrency-in-go/index.md
  content/articles/concurrency-in-go/noconcurrency.png
  content/articles/concurrency-in-go/waitgroup.png
Labels: ready for final review

#3720 Exception handling in windows forms
  content/articles/exception-handling-in-windows-forms/date-normal.png
  content/articles/exception-handling-in-windows-forms/date-tool.png
  content/articles/exception-handling-in-windows-forms/error-output.png
  content/articles/exception-handling-in-windows-forms/exception-form.png
  content/articles/exception-handling-in-windows-forms/hero.png
  content/articles/exception-handling-in-windows-forms/index.md
Labels: assigned for review, ready for final review

#3651 Abstractive Summarization using Deep Learning
  content/articles/abstractive-summarization-using-deep-learning/hero.png
  content/articles/abstractive-summarization-using-deep-learning/index.md
Labels: ready for final review, tech tutorial

#3709 Multi-Label Classification with Scikit-MultiLearn
  content/articles/multi-label-classification-with-scikit-multilearn/binary-relevance.png
  content/articles/multi-label-classification-with-scikit-multilearn/chain-sequence.png
  content/articles/multi-label-classification-with-scikit-multilearn/classifier-chains.png
  content/articles/multi-label-classification-with-scikit-multilearn/dataset-snip.jpg
  content/articles/multi-label-classification-with-scikit-multilearn/dataset-structure.jpg
  content/articles/multi-label-classification-with-scikit-multilearn/hero.png
  content/articles/multi-label-classification-with-scikit-multilearn/index.md
  content/articles/multi-label-classification-with-scikit-multilearn/label-powerset.png
  content/authors/charles-kariuki/avatar.jpg
  content/authors/charles-kariuki/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3797 How to obtain bloodvessel segmentation in retinal images using Matlab
  content/articles/how-to-obtain-blood-vessel-segmentation-in-retinal-images-using-matlab/hero.jpg
  content/articles/how-to-obtain-blood-vessel-segmentation-in-retinal-images-using-matlab/index.md
  content/articles/how-to-obtain-blood-vessel-segmentation-in-retinal-images-using-matlab/retinal-four.png
  content/articles/how-to-obtain-blood-vessel-segmentation-in-retinal-images-using-matlab/retinal-one.png
  content/articles/how-to-obtain-blood-vessel-segmentation-in-retinal-images-using-matlab/retinal-three.png
  content/articles/how-to-obtain-blood-vessel-segmentation-in-retinal-images-using-matlab/retinal-two.png
Labels: assigned for review, ready for final review

#3641 Is Java the Best Language for Artificial Intelligence Projects?
  content/articles/java-for-artificial-intelligence-projects/hero.jpg
  content/articles/java-for-artificial-intelligence-projects/index.md
Labels: preliminary revision in progress, ready for final review, needs front matter, test reviewer assigned

#3622 Setting Up Hotspot On Kali Linux
  content/articles/setting-up-hotspot-on-kali-linux/connection.png
  content/articles/setting-up-hotspot-on-kali-linux/drivers.png
  content/articles/setting-up-hotspot-on-kali-linux/hero.jpg
  content/articles/setting-up-hotspot-on-kali-linux/index.md
  content/articles/setting-up-hotspot-on-kali-linux/installations.png
  content/articles/setting-up-hotspot-on-kali-linux/security.png
  content/articles/setting-up-hotspot-on-kali-linux/settings.png
  content/authors/jacob-muganda/avatar.jpg
  content/authors/jacob-muganda/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3988 Fixing migration
  content/articles/laravel-sanctum-api-auth/index.md
Labels: article update

#3675 how to troubleshoot and monitor a database
  content/articles/how-to-troubleshoot-and-monitor-a-database/hero.jpg
  content/articles/how-to-troubleshoot-and-monitor-a-database/index.md
  content/authors/extravaganza-77/avatar.jpg
  content/authors/extravaganza-77/index.md
Labels: good first article, assigned for review, ready for final review, article

#3676 Building a Responsive and Collapsible Sidebar with Ant Design Library and React
  content/articles/collapsible-sidebar-with-react-and-ant-design-library/hero.png
  content/articles/collapsible-sidebar-with-react-and-ant-design-library/index.md
  content/authors/tio-umoh/avatar.jpg
  content/authors/tio-umoh/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3730 Firestore data modeling and query customization in Android
  content/articles/firestore-data-modeling-and-query-customization-in-android/custom-query-greater-than.png
  content/articles/firestore-data-modeling-and-query-customization-in-android/database-design.png
  content/articles/firestore-data-modeling-and-query-customization-in-android/hero.png
  content/articles/firestore-data-modeling-and-query-customization-in-android/index.md
  content/articles/firestore-data-modeling-and-query-customization-in-android/saved-data.png
Labels: assigned for review, ready for final review

#3733 Null Safety Support for Flutter and Dart
  content/articles/null-safety-support-for-flutter-and-dart/hero.jpg
  content/articles/null-safety-support-for-flutter-and-dart/index.md
  content/authors/francisca-ngodu/avatar.jpg
  content/authors/francisca-ngodu/index.md.md
Labels: good first article, assigned for review, ready for final review, article

#3634 Machine Learning for Audio Classification
  content/articles/machine-learning-for-audio-classification/hero.png
  content/articles/machine-learning-for-audio-classification/index.md
  content/articles/machine-learning-for-audio-classification/spectrogram.png
Labels: ready for final review, tech tutorial

#3693 Getting started with React Cosmos
  content/articles/getting-started-with-react-cosmos/cosmos-app-cart.png
  content/articles/getting-started-with-react-cosmos/cosmos-app.png
  content/articles/getting-started-with-react-cosmos/cosmos-btn.png
  content/articles/getting-started-with-react-cosmos/cosmos-starter.png
  content/articles/getting-started-with-react-cosmos/cosmos-variants.gif
  content/articles/getting-started-with-react-cosmos/hero.jpg
  content/articles/getting-started-with-react-cosmos/index.md
Labels: assigned for review, ready for final review

#3740 Using Django in Kivy applications
  content/articles/using-django-in-kivy-application/create_task_page.png
  content/articles/using-django-in-kivy-application/creating_a_task.png
  content/articles/using-django-in-kivy-application/creating_the_action_bar.png
  content/articles/using-django-in-kivy-application/displaying_tasks_from_server.png
  content/articles/using-django-in-kivy-application/hero.jpg
  content/articles/using-django-in-kivy-application/index.md
  content/articles/using-django-in-kivy-application/original_kivy_app.png
  content/articles/using-django-in-kivy-application/task_created.png
  content/articles/using-django-in-kivy-application/task_submitted_successfully.png
  content/articles/using-django-in-kivy-application/tasks_home_page.png
Labels: assigned for review, ready for final review, tech tutorial

#3744 Java native interface
  content/articles/java-native-interface/hero.jpg
  content/articles/java-native-interface/index.md
  content/authors/mary-wanjiku/avator.jpg
  content/authors/mary-wanjiku/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3751 BigDecimal and Primitive Data Type Arithmetic Program in Java
  content/articles/bigdecimal-and-primitive-data-type-arithmetic-program-in-java/hero.jpg
  content/articles/bigdecimal-and-primitive-data-type-arithmetic-program-in-java/index.md
Labels: assigned for review, ready for final review

#3759 Integrate Machine Learning Model into a Flask REST API and Deploying to Heroku
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/get_request_local.PNG
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/get_request_to_deployed_heroku_api.PNG
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/hero.png
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/index.md
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/pip-install-virtualenv.PNG
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/post_request_to_deployed_api.PNG
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/post_request_to_local_api.PNG
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/post_wrong_request_to_deployed_api.PNG
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/post_wrong_request_to_local_server.PNG
  content/articles/integrate-ml-to-flask-api-and-deploy-to-heroku/push_to_heroku.PNG
Labels: assigned for review, ready for final review

#3858 How Java Virtual Machine Works
  content/articles/how-java-virtual-machine-works/hero.jpg
  content/articles/how-java-virtual-machine-works/index.md
  content/authors/geofrey-mwangi/avatar.jpg
  content/authors/geofrey-mwangi/index.md
Labels: duplicate, ready for final review

#3837 Integrating YouTube videos into a Django app
  content/articles/integrating-youtube-videos-into-a-django-application/admin.jpg
  content/articles/integrating-youtube-videos-into-a-django-application/blog-detail.jpg
  content/articles/integrating-youtube-videos-into-a-django-application/blog.jpg
  content/articles/integrating-youtube-videos-into-a-django-application/hero.png
  content/articles/integrating-youtube-videos-into-a-django-application/index.md
  content/authors/samuel-mwangi/index.md
Labels: assigned for review, ready for final review

#3689 How to solve initial value problem using ode45 in Matlab
  content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/hero.jpg
  content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/index.md
  content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/ode-one.png
  content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/ode-three.png
  content/articles/how-to-solve-initial-value-problem-using-ode45-in-matlab/ode-two.png
  content/authors/joseph-odhiambo/avatar.jpeg
  content/authors/joseph-odhiambo/index.md
Labels: enhancement, assigned for review
