Repository section-engineering-education/engineering-education, pull requests merged in 2021-07, with the labels that each got.

#2610 Integrating Instagram basic display API on a Node.js GraphQL API
  content/articles/integrating-instagram-basic-display-api/credentials.png
  content/articles/integrating-instagram-basic-display-api/env-with-llat.png
  content/articles/integrating-instagram-basic-display-api/env-with-sat.png
  content/articles/integrating-instagram-basic-display-api/hero.jpg
  content/articles/integrating-instagram-basic-display-api/index.md
  content/articles/integrating-instagram-basic-display-api/long-lived-at-response.png
  content/articles/integrating-instagram-basic-display-api/media-data-response.png
  content/articles/integrating-instagram-basic-display-api/new-env.png
  content/articles/integrating-instagram-basic-display-api/profile-data-response.png
  content/articles/integrating-instagram-basic-display-api/project-structure.png
  content/articles/integrating-instagram-basic-display-api/scripts-section.png
  content/articles/integrating-instagram-basic-display-api/short-lived-at-response.png
  content/articles/integrating-instagram-basic-display-api/tester-invites.png
  content/articles/integrating-instagram-basic-display-api/url-code.png
  content/articles/integrating-instagram-basic-display-api/urls-insta-display-app.png
Labels: ready for final review

#2601 Integrating Cloud Firestore database in Android-Kotlin
  content/articles/integrating-firestore-in-android-kotlin/add-app-details.png
  content/articles/integrating-firestore-in-android-kotlin/create-cloud-database.png
  content/articles/integrating-firestore-in-android-kotlin/download-config-file.png
  content/articles/integrating-firestore-in-android-kotlin/firebase-project-example.png
  content/articles/integrating-firestore-in-android-kotlin/hero.png
  content/articles/integrating-firestore-in-android-kotlin/index.md
  content/articles/integrating-firestore-in-android-kotlin/logs.png
  content/articles/integrating-firestore-in-android-kotlin/my-firebase-projects.png
  content/articles/integrating-firestore-in-android-kotlin/saved-data.png
  content/authors/noni-diana/avatar.jpg
  content/authors/noni-diana/index.md
Labels: assigned for review, good first article, ready for final review

#2596 How to Containerize an Angular Application Featuring Nginx Using Docker Containers
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/docker-build.png
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/docker-compose-up.png
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/docker-compose.png
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/docker-images.png
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/docker-version.png
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/dockerfile.png
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/dockerized-angular-app.png
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/hero.png
  content/articles/containerizing-an-angular-app-featuring-nginx-web-server-using-docker/index.md
Labels: ready for final review, tech tutorial

#2660 Getting started with Jetpack Compose in Android
  content/articles/getting-started-with-jetpack-compose-in-android/hero.png
  content/articles/getting-started-with-jetpack-compose-in-android/index.md
  content/articles/getting-started-with-jetpack-compose-in-android/new-compose-project.png
  content/authors/maurine-muthoki/avatar.jpg
  content/authors/maurine-muthoki/index.md
Labels: assigned for review, ready for final review

#2532 Operators In C#
  content/articles/operators-in-csharp/hero.png
  content/articles/operators-in-csharp/index.md
  content/authors/lewis-macharia/avatar.png
  content/authors/lewis-macharia/index.md
Labels: good first article, ready for final review

#2615 Compile your Node.js application into a .exe file
  content/articles/compile-your-nodejs-application-into-a-exe-file/hero.jpg
  content/articles/compile-your-nodejs-application-into-a-exe-file/index.md
  content/articles/compile-your-nodejs-application-into-a-exe-file/nexe.png
  content/articles/compile-your-nodejs-application-into-a-exe-file/pkg.png
Labels: assigned for review, ready for final review

#2623 The Evolution of Computing to Edge Computing
  content/articles/what-is-edge-computing/cloud-computing.PNG
  content/articles/what-is-edge-computing/edge-computing.PNG
  content/articles/what-is-edge-computing/hero.png
  content/articles/what-is-edge-computing/index.md
Labels: article, ready for final review

#2642 The Overview of Container Technology
  content/articles/overview-of-container-technology/containers-vs-virtual-machines.jpg
  content/articles/overview-of-container-technology/hero.jpg
  content/articles/overview-of-container-technology/index.md
  content/authors/julie-ruguru/avatar.jpg
  content/authors/julie-ruguru/index.md
Labels: assigned for review, good first article, ready for final review

#2682 Entropy and Information Gain to Build Decision Trees in Machine Learning
  content/articles/entropy/hero.jpg
  content/articles/entropy/index.md
  content/articles/entropy/mytree.png
  content/articles/entropy/purity.png
  content/articles/entropy/tree.png
Labels: assigned for review, ready for final review, tech tutorial

#2656 Wavelet Transform Based Denoising of images using Matlab
  content/articles/wavelet-transform-based-denoising-of-images-using-matlab/hero.jpg
  content/articles/wavelet-transform-based-denoising-of-images-using-matlab/image1.png
  content/articles/wavelet-transform-based-denoising-of-images-using-matlab/image2.png
  content/articles/wavelet-transform-based-denoising-of-images-using-matlab/image3.png
  content/articles/wavelet-transform-based-denoising-of-images-using-matlab/image4.png
  content/articles/wavelet-transform-based-denoising-of-images-using-matlab/image5.png
  content/articles/wavelet-transform-based-denoising-of-images-using-matlab/image6.png
  content/articles/wavelet-transform-based-denoising-of-images-using-matlab/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2676 Difference Between a Website and a Web Application
  content/articles/website-vs-web-app/hero.png
  content/articles/website-vs-web-app/index.md
Labels: article, assigned for review, ready for final review

#2560 Comparison between the HTTP/3 and HTTP/2 Protocols
  content/articles/http3-vs-http2/TCP-QUIC-latency.png
  content/articles/http3-vs-http2/hero.jpg
  content/articles/http3-vs-http2/http2-http3.png
  content/articles/http3-vs-http2/index.md
Labels: article, assigned for review, ready for final review

#2677 Boosting Algorithms in Python
  content/articles/boosting-algorithms-python/adaboost.PNG
  content/articles/boosting-algorithms-python/bagging.PNG
  content/articles/boosting-algorithms-python/boosting.PNG
  content/articles/boosting-algorithms-python/datahead.PNG
  content/articles/boosting-algorithms-python/decisionstumps.PNG
  content/articles/boosting-algorithms-python/hero.png
  content/articles/boosting-algorithms-python/index.md
  content/articles/boosting-algorithms-python/performance.PNG
  content/articles/boosting-algorithms-python/quotes.PNG
Labels: assigned for review, ready for final review, tech tutorial

#2649 Getting started with Python input function and loops
  content/articles/user-input-and-while-loops-in-python/hero.png
  content/articles/user-input-and-while-loops-in-python/index.md
  content/authors/bonface-muriithi/avatar.jpg
  content/authors/bonface-muriithi/index.md
Labels: assigned for review, good first article, ready for final review

#2764 Building a Loader Using Animations in Tailwind CSS
  content/articles/building-a-loader-using-animations-in-tailwind-css/hero.jpg
  content/articles/building-a-loader-using-animations-in-tailwind-css/img1.png
  content/articles/building-a-loader-using-animations-in-tailwind-css/img2.png
  content/articles/building-a-loader-using-animations-in-tailwind-css/index.md
  content/articles/building-a-loader-using-animations-in-tailwind-css/loader.gif
Labels: assigned for review, ready for final review

#2570 Understanding Docker Networking
  content/articles/understanding-docker-networking/hero.jpg
  content/articles/understanding-docker-networking/index.md
Labels: article, ready for final review

#2661 Storing Data in Python Using the JSON Module
  content/articles/storing-data-in-python-using-json-module/hero.jpg
  content/articles/storing-data-in-python-using-json-module/index.md
  content/authors/felix-maina/avatar.jpg
  content/authors/felix-maina/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2694 Getting started with Spring boot Batch processing
  content/articles/spring-boot-batch/batch-cmd.png
  content/articles/spring-boot-batch/batch-running.png
  content/articles/spring-boot-batch/hero.jpg
  content/articles/spring-boot-batch/index.md
Labels: assigned for review, ready for final review

#2703 DOM manipulation with JavaScript
  content/articles/dom-manipulation-with-javascript/dom-example.png
  content/articles/dom-manipulation-with-javascript/hero.jpg
  content/articles/dom-manipulation-with-javascript/home-page-screenshot.jpg
  content/articles/dom-manipulation-with-javascript/index.md
Labels: assigned for review, ready for final review

#2665 Understanding @Input and @Output Decorators in Angular
  content/articles/angular-output-and-input-decorator/added-artist.png
  content/articles/angular-output-and-input-decorator/hero.png
  content/articles/angular-output-and-input-decorator/index.md
  content/articles/angular-output-and-input-decorator/input.png
  content/articles/angular-output-and-input-decorator/original-output.png
Labels: ready for final review

#2753 Creating a Responsive Navigation Bar using Tailwind CSS and JavaScript
  content/articles/creating-a-responsive-navigation-bar-using-tailwind-css-and-javascript/hero.jpg
  content/articles/creating-a-responsive-navigation-bar-using-tailwind-css-and-javascript/img-desktop-view.png
  content/articles/creating-a-responsive-navigation-bar-using-tailwind-css-and-javascript/img-medium-view.png
  content/articles/creating-a-responsive-navigation-bar-using-tailwind-css-and-javascript/img-mobile-view.png
  content/articles/creating-a-responsive-navigation-bar-using-tailwind-css-and-javascript/index.md
  content/authors/ian-masae/avatar.jpg
  content/authors/ian-masae/index.md
Labels: assigned for review, good first article, ready for final review

#2704 Audio signals processing using matlab
  content/articles/audio-signals-processing-using-matlab/hero.jpg
  content/articles/audio-signals-processing-using-matlab/index.md
  content/articles/audio-signals-processing-using-matlab/signal.png
  content/articles/audio-signals-processing-using-matlab/signal2.png
Labels: assigned for review, ready for final review

#2733 Why Unikernels may soon replace Docker?
  content/articles/why-unikernels-may-soon-replace-docker/hero.jpg
  content/articles/why-unikernels-may-soon-replace-docker/index.md
  content/authors/lilian-ogoti/avatar.jpg
  content/authors/lilian-ogoti/index.md
Labels: assigned for review, good first article, ready for final review

#2692 Learn How to Implement Queues in Laravel 8
  content/articles/implementing-laravel-queues/hero.png
  content/articles/implementing-laravel-queues/index.md
Labels: ready for final review, tech tutorial

#2681 Implementation of ci and cd in java application(linux) using shell and docker executor on git lab
  content/articles/ci-cd-java-application-using-shell-docker-executor-gitlab/hero.png
  content/articles/ci-cd-java-application-using-shell-docker-executor-gitlab/index.md
  content/authors/James-Bundi/avatar.png
  content/authors/James-Bundi/index.md
Labels: assigned for review, needs plagiarism check, ready for final review

#2713 How to setup, containerize and test a single Hadoop cluster using Docker and docker-compose
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/check-ip-address.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/docker-architecture.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/docker-compose-version-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/docker-container-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/docker-container.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/docker-images-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/docker-ps-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/docker-version-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/hadoop-ecosystem.jpg
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/hadoop-running-containers-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/hadoop-ui.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/hdfsarchitecture.gif
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/hdfsdatanodes.gif
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/hero.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/index.md
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/ip-address-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/jps-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/map-reduce-architecture.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/mapreduce-flow-diagram.jpg
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/output-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/running-containers-response.png
  content/articles/set-up-containerize-and-test-a-single-hadoop-cluster-using-docker-and-docker-compose/yarn-architecture.gif
Labels: assigned for review, ready for final review, tech tutorial

#2785 A Pure MLP Architecture for Computer Vision
  content/articles/pure-mlp-architecture-for-computer-vision/hero.png
  content/articles/pure-mlp-architecture-for-computer-vision/index.md
  content/articles/pure-mlp-architecture-for-computer-vision/mlp-architecture.PNG
  content/articles/pure-mlp-architecture-for-computer-vision/mlp-mixer-architecture.PNG
Labels: article, ready for final review

#2721 Building Telegram Bot using Python
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/add.png
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/bot-father.png
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/botname.png
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/create.png
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/hero.png
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/index.md
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/json.png
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/message.png
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/random.png
  content/articles/building-a-telegram-bot-with-python-to-generate-quotes/start-bot-father.png
Labels: assigned for review, enhancement, ready for final review, tech tutorial

#2776 Introduction to Linux Shell and Shell Scripting
  content/articles/introduction-to-linux-shell-and-shell-scripting/bash_script.png
  content/articles/introduction-to-linux-shell-and-shell-scripting/hero.png
  content/articles/introduction-to-linux-shell-and-shell-scripting/index.md
  content/articles/introduction-to-linux-shell-and-shell-scripting/ubuntu_GUI.png
  content/articles/introduction-to-linux-shell-and-shell-scripting/ubuntu_terminal.png
  content/authors/Dennis-Kariuki/avatar.jpeg
  content/authors/Dennis-Kariuki/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2905 Structuring Large Applications with Blueprint and Application Factory…
  content/articles/structuring-large-applications-with-blueprints-and-application-factory-in-flask/hero.jpg
  content/articles/structuring-large-applications-with-blueprints-and-application-factory-in-flask/index.md
Labels: assigned for review, duplicate, ready for final review, tech tutorial

#2904 Sending WhatsApp Messages with Serverless Python Applications using AWS Chalice
  content/articles/aws-chalice-twilio-whatsapp/hero.jpg
  content/articles/aws-chalice-twilio-whatsapp/index.md
  content/articles/aws-chalice-twilio-whatsapp/message-received.png
  content/articles/aws-chalice-twilio-whatsapp/postman-example.JPG
  content/articles/aws-chalice-twilio-whatsapp/sandbox-activate-message.jpg
  content/articles/aws-chalice-twilio-whatsapp/sent-message.jpg
Labels: duplicate, ready for final review, tech tutorial

#2757 Creating an API using Prisma, Node.js and Postresql
  content/articles/api-with-prisma-and-nodejs/hero.png
  content/articles/api-with-prisma-and-nodejs/index.md
Labels: assigned for review, ready for final review

#2763 Build a Twitch Chatbot in Node.js
  content/articles/build-a-twitch-chatbot-in-nodejs/channel.png
  content/articles/build-a-twitch-chatbot-in-nodejs/hero.jpg
  content/articles/build-a-twitch-chatbot-in-nodejs/index.md
  content/articles/build-a-twitch-chatbot-in-nodejs/live-demo.png
  content/articles/build-a-twitch-chatbot-in-nodejs/streamyard.png
  content/authors/justus-mbuvi/avatar.jpg
  content/authors/justus-mbuvi/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2699 Understanding polymorphism & abstract classes using C#
  content/articles/understanding-polymorphism-abstract-classes-using-c-/hero.png
  content/articles/understanding-polymorphism-abstract-classes-using-c-/index.md
Labels: assigned for review, ready for final review

#2775 Understanding C++ storage class
  content/articles/storage-class-in-cplusplus/hero.jpg
  content/articles/storage-class-in-cplusplus/index.md
Labels: assigned for review, ready for final review

#2922 Updating my PR title (Understanding Polymorphism using Abstract Classes in C#)
  content/articles/understanding-polymorphism-abstract-classes-using-c-/index.md
Labels: article update

#2797 Why and How Microservice messaging works in Kubernetes?
  content/articles/why-and-how-microservice-messaging-works-in-kubernetes/hero.jpg
  content/articles/why-and-how-microservice-messaging-works-in-kubernetes/index.md
  content/articles/why-and-how-microservice-messaging-works-in-kubernetes/many-services.png
  content/articles/why-and-how-microservice-messaging-works-in-kubernetes/service-five.png
  content/articles/why-and-how-microservice-messaging-works-in-kubernetes/service-three.png
Labels: article, assigned for review, ready for final review, ready for review

#2741 Create API Authentication With Laravel 8 Passport
  content/articles/laravel-passport/hero.png
  content/articles/laravel-passport/index.md
  content/articles/laravel-passport/token.png
Labels: assigned for review, ready for final review

#2806 Applying AI and ML to predict consumer behavior
  content/articles/applying-ai-and-ml-to-predict-consumer-behavior/clusters-line-graph.png
  content/articles/applying-ai-and-ml-to-predict-consumer-behavior/dataset.png
  content/articles/applying-ai-and-ml-to-predict-consumer-behavior/distribution-plots.png
  content/articles/applying-ai-and-ml-to-predict-consumer-behavior/gender-count-plot.png
  content/articles/applying-ai-and-ml-to-predict-consumer-behavior/hero.jpg
  content/articles/applying-ai-and-ml-to-predict-consumer-behavior/index.md
  content/articles/applying-ai-and-ml-to-predict-consumer-behavior/kmeans-cluster-4.png
  content/authors/skay-ai/avatar.png
  content/authors/skay-ai/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2784 Why Kubernetes is the best technology for running Cloud-Native Database
  content/articles/kubernetes-best-technology-running-cloud-native-database/hero.jpg
  content/articles/kubernetes-best-technology-running-cloud-native-database/index.md
  content/authors/ephraim-gathoni/avatar.jpg
  content/authors/ephraim-gathoni/index.md
Labels: assigned for review, good first article, ready for final review

#2781 How to containerize a MySQL based server and PHPMyAdmin/Adminer with docker and run SQL queries
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/a-linked-docker-mysql-server-and-phpmyadmin.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/a-localhost-dockerized-adminer.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/a-localhost-dockerized-phpmyadmin.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/adminer.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/bash-shell.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/create-database.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/docker-images.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/docker-pull-mysql-latest.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/docker-show-databases.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/hero.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/index.md
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/mysql-server-docker-queries.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/mysql-server.png
  content/articles/containerizing-mysql-server-phpmyadmin-with-docker/mysqldb-container.png
Labels: assigned for review, ready for final review, tech tutorial

#2790 Getting started with Django Unit testing
  content/articles/django-unit-testing/hero.png
  content/articles/django-unit-testing/index.md
Labels: assigned for review, ready for final review

#2769 Inversion of control principle
  content/articles/ioc_principle/dependecy_inversion_principle_image_1.png
  content/articles/ioc_principle/dependecy_inversion_principle_image_2.png
  content/articles/ioc_principle/dependency_injection.png
  content/articles/ioc_principle/dry_algorithm_family.png
  content/articles/ioc_principle/hero.png
  content/articles/ioc_principle/index.md
  content/articles/ioc_principle/wash_algorithm_family.png
  content/authors/love-otudor/avatar.jpeg
  content/authors/love-otudor/index.md
Labels: article, assigned for review, good first article, ready for final review, ready for review

#2730 Django custom templates tags and filters
  content/articles/django-custom-template-tags-and-filters/contact_page_with_filters.png
  content/articles/django-custom-template-tags-and-filters/contact_page_with_inclusion_tags.png
  content/articles/django-custom-template-tags-and-filters/contact_page_with_simple_tags.png
  content/articles/django-custom-template-tags-and-filters/hero.jpg
  content/articles/django-custom-template-tags-and-filters/index.md
  content/articles/django-custom-template-tags-and-filters/initial_contacts_page.png
  content/authors/john-kiguru/avatar.jpeg
  content/authors/john-kiguru/index.md
Labels: good first article, ready for final review

#2937 Understanding Facial Recognition using Local Binary Pattern Histogram (LBPH) Algorithm
  content/articles/understanding-facial-recognition-using-local-binary-pattern-histogram-(lbph)-algorithm/extracting_histograms.jpg
  content/articles/understanding-facial-recognition-using-local-binary-pattern-histogram-(lbph)-algorithm/hero.jpg
  content/articles/understanding-facial-recognition-using-local-binary-pattern-histogram-(lbph)-algorithm/index.md
  content/articles/understanding-facial-recognition-using-local-binary-pattern-histogram-(lbph)-algorithm/lbp_operation.png
Labels: article, duplicate, ready for final review

#2801 Bing Maps With Angular in a Spring Boot Application
  content/articles/angular-springboot-bing-maps/forms.png
  content/articles/angular-springboot-bing-maps/full-app.png
  content/articles/angular-springboot-bing-maps/hero.jpg
  content/articles/angular-springboot-bing-maps/index.md
Labels: assigned for review, ready for final review

#2796 Differences between a Hub, Switch, and Router
  content/articles/switch-vs-router-vs-hub/hero.jpg
  content/articles/switch-vs-router-vs-hub/index.md
  content/authors/jedidah-mwangi/avatar.jpeg
  content/authors/jedidah-mwangi/index.md
Labels: article, assigned for review, good first article, ready for final review

#2791 Handling JSON in MongoDB
  content/articles/handling-json-in-mongodb/hero.png
  content/articles/handling-json-in-mongodb/index.md
  content/authors/simon-salva/avatar.png
  content/authors/simon-salva/index.md
Labels: assigned for review, preliminary revision in progress, tech review

#2833 How to work with Docker containers using VS Code
  content/articles/docker-in-vscode/docker-add-files.png
  content/articles/docker-in-vscode/docker-commands.png
  content/articles/docker-in-vscode/docker-extension.png
  content/articles/docker-in-vscode/hero.png
  content/articles/docker-in-vscode/index.md
  content/authors/magdaline-kariuki/avatar.png
  content/authors/magdaline-kariuki/index.md
Labels: good first article, ready for final review

#2807 Improving App performance with `DiffUtil` in Android-Kotlin
  content/articles/angular-springboot-bing-maps/forms.png
  content/articles/angular-springboot-bing-maps/full-app.png
  content/articles/angular-springboot-bing-maps/hero.jpg
  content/articles/improving-app-performance-with-diffutil/app-testing.gif
  content/articles/improving-app-performance-with-diffutil/hero.png
  content/articles/improving-app-performance-with-diffutil/index.md
Labels: assigned for review, ready for final review

#2762 Building an Artificial Neural Network with Keras
  content/articles/build-ann-with-keras/NN-SVG-architecture.PNG
  content/articles/build-ann-with-keras/actual-vs-predicted-values.PNG
  content/articles/build-ann-with-keras/dataset.PNG
  content/articles/build-ann-with-keras/feature-scaling.PNG
  content/articles/build-ann-with-keras/features.PNG
  content/articles/build-ann-with-keras/hero.png
  content/articles/build-ann-with-keras/index.md
  content/articles/build-ann-with-keras/label-encoding.PNG
  content/articles/build-ann-with-keras/labels.PNG
  content/articles/build-ann-with-keras/last-eleven-epochs-of-training.PNG
  content/articles/build-ann-with-keras/onehot-encoding.PNG
  content/articles/build-ann-with-keras/plot-model.PNG
  content/articles/build-ann-with-keras/select-dataset.PNG
  content/articles/build-ann-with-keras/upload-data.PNG
  content/articles/build-ann-with-keras/upload-dataset.PNG
  content/articles/build-ann-with-keras/uploaded-dataset.PNG
Labels: ready for final review, tech tutorial

#2747 Creating an auto-typing feature in JavaScript
  content/articles/auto-typing-js/hero.jpg
  content/articles/auto-typing-js/index.md
Labels: revisions needed, tech tutorial

#2824 Documenting JavaScript Code with JSDocs
  content/articles/jsdoc-documentation/class-members.png
  content/articles/jsdoc-documentation/class-methods.png
  content/articles/jsdoc-documentation/functions-module.png
  content/articles/jsdoc-documentation/hero.png
  content/articles/jsdoc-documentation/index.md
  content/articles/jsdoc-documentation/initial-page.png
  content/authors/phina-kersly/index.md
Labels: assigned for review, ready for final review

#2755 Understanding Closures in Ruby
  content/articles/understanding-closures-in-ruby/hero.jpg
  content/articles/understanding-closures-in-ruby/index.md
Labels: ready for final review, tech tutorial

#2803 Getting Started with Fastify Node.js and Svelte
  content/articles/getting-started-with-fastify-and-svelte/complete.png
  content/articles/getting-started-with-fastify-and-svelte/hero.jpg
  content/articles/getting-started-with-fastify-and-svelte/index.md
  content/authors/kevin-kimani/avatar.jpeg
  content/authors/kevin-kimani/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3004 Creating an audiobook with Pyttxs3, PyPDF3 and Tkinter
  content/articles/creating-an-audiobook-with-pyttxs3-pypdf3-and-tkinter/dialog.png
  content/articles/creating-an-audiobook-with-pyttxs3-pypdf3-and-tkinter/hero.jpg
  content/articles/creating-an-audiobook-with-pyttxs3-pypdf3-and-tkinter/index.md
Labels: duplicate, ready for final review, tech tutorial

#3020 Google Authentication using Firebase in a Quasar Vue.js Application
  content/articles/quasar-googleauth-with-firebase/domain.png
  content/articles/quasar-googleauth-with-firebase/emailpasswordprovider.png
  content/articles/quasar-googleauth-with-firebase/googleprovider.png
  content/articles/quasar-googleauth-with-firebase/hero.jpg
  content/articles/quasar-googleauth-with-firebase/index.md
  content/articles/quasar-googleauth-with-firebase/siginmethods.png
Labels: assigned for review, duplicate, ready for final review

#2795 Docker Images with Google Cloud
  content/articles/docker-images-on-google-cloud/confirm-upload.png
  content/articles/docker-images-on-google-cloud/deployed.png
  content/articles/docker-images-on-google-cloud/deploying.png
  content/articles/docker-images-on-google-cloud/hero.png
  content/articles/docker-images-on-google-cloud/index.md
  content/articles/docker-images-on-google-cloud/private.png
  content/articles/docker-images-on-google-cloud/shell.png
  content/articles/docker-images-on-google-cloud/storage.png
  content/authors/dolores-merceline/avater.jpg
  content/authors/dolores-merceline/index.md
Labels: assigned for review, ready for final review

#2850 Image processing with Coil in Android
  content/articles/image-processing-with-coil-in-android/design-preview.png
  content/articles/image-processing-with-coil-in-android/hero.png
  content/articles/image-processing-with-coil-in-android/index.md
Labels: ready for final review, tech tutorial

#2720 Filter Machine with Vanilla JavaScript
  content/articles/filter-machine-with-vanilla-javascript/hero.png
  content/articles/filter-machine-with-vanilla-javascript/index.md
  content/articles/filter-machine-with-vanilla-javascript/page.gif
  content/authors/mudasiru-rasheed/avatar.jpg
  content/authors/mudasiru-rasheed/index.md
Labels: good first article, ready for final review

#2916 Guide to Spring Cloud Kubernetes
  content/articles/spring-cloud-k8/dashboard.png
  content/articles/spring-cloud-k8/hero.png
  content/articles/spring-cloud-k8/index.md
  content/authors/odiwuor-amos/avatar.jpeg
Labels: ready for final review

#2980 Packet Filtering Using Access Control Lists
  content/articles/packet-filtering-using-acls/acl.jpg
  content/articles/packet-filtering-using-acls/hero.jpg
  content/articles/packet-filtering-using-acls/index.md
Labels: ready for final review

#2810 Building a Hangman Game with Vanilla JavaScript
  content/articles/creating-a-hangman-game-with-vanilla-javascript/hero.jpg
  content/articles/creating-a-hangman-game-with-vanilla-javascript/index.md
  content/articles/creating-a-hangman-game-with-vanilla-javascript/the-game-buttons.jpg
  content/articles/creating-a-hangman-game-with-vanilla-javascript/the-game-image.jpg
Labels: ready for final review

#2831 Introduction to Application Performance Management
  content/articles/introduction-to-application-performance-management/hero.jpg
  content/articles/introduction-to-application-performance-management/index.md
Labels: article, ready for final review

#2834 What is Kafka? How to Build and Dockerize a Kafka Application using Docker Containers
  content/articles/what-is-kafka-how-to-build-and-dockerize-a-kafka-cluster-using-docker-containers/apache-kafka-diagram.png
  content/articles/what-is-kafka-how-to-build-and-dockerize-a-kafka-cluster-using-docker-containers/apache-kafka-partitions.png
  content/articles/what-is-kafka-how-to-build-and-dockerize-a-kafka-cluster-using-docker-containers/hero.png
  content/articles/what-is-kafka-how-to-build-and-dockerize-a-kafka-cluster-using-docker-containers/index.md
  content/articles/what-is-kafka-how-to-build-and-dockerize-a-kafka-cluster-using-docker-containers/kafka-broker.png
  content/articles/what-is-kafka-how-to-build-and-dockerize-a-kafka-cluster-using-docker-containers/running-containers.png
Labels: ready for final review

#2870 The Case for Blockchain for Machine Learning
  content/articles/can-blockchain-improve-machine-learning-privacy/blockchain-structure.png
  content/articles/can-blockchain-improve-machine-learning-privacy/hero.png
  content/articles/can-blockchain-improve-machine-learning-privacy/index.md
Labels: article, ready for final review

#2739 Decision making and branching in java
  content/articles/decision-making-and-branching-in-java/hero.jpg
  content/articles/decision-making-and-branching-in-java/index.md
  content/authors/george-wamama/Avatar.jpg
  content/authors/george-wamama/index.md
Labels: enhancement, tech tutorial

#2815 Getting started with Spring Boot caching
  content/articles/spring-boot-caching/hero.jpg
  content/articles/spring-boot-caching/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2744 How to Make a Discord Bot using Python
  content/articles/how-to-make-a-discord-bot-using-python/hero.jpg
  content/articles/how-to-make-a-discord-bot-using-python/img1.png
  content/articles/how-to-make-a-discord-bot-using-python/img2.png
  content/articles/how-to-make-a-discord-bot-using-python/img3.png
  content/articles/how-to-make-a-discord-bot-using-python/img4.png
  content/articles/how-to-make-a-discord-bot-using-python/img5.png
  content/articles/how-to-make-a-discord-bot-using-python/img6.png
  content/articles/how-to-make-a-discord-bot-using-python/img7.png
  content/articles/how-to-make-a-discord-bot-using-python/img8.png
  content/articles/how-to-make-a-discord-bot-using-python/index.md
  content/authors/harshita-bansal/avatar.jpeg
  content/authors/harshita-bansal/index.md
Labels: ready for final review

#2706 Working with Styled-components in React
  content/articles/working-with-styled-components-in-react/App.js.png
  content/articles/working-with-styled-components-in-react/Landing-page.png
  content/articles/working-with-styled-components-in-react/LogoOne.png
  content/articles/working-with-styled-components-in-react/LogoTwo.png
  content/articles/working-with-styled-components-in-react/back-ground.jpg
  content/articles/working-with-styled-components-in-react/component.png
  content/articles/working-with-styled-components-in-react/hero.jpg
  content/articles/working-with-styled-components-in-react/index.md
  content/articles/working-with-styled-components-in-react/server-start-up.png
  content/articles/working-with-styled-components-in-react/structure.png
  content/articles/working-with-styled-components-in-react/unstyled.png
Labels: ready for final review

#2840 Understanding how Kubernetes Networking Works
  content/articles/understanding-how-kubernetes-networking-works/hero.jpg
  content/articles/understanding-how-kubernetes-networking-works/index.md
Labels: assigned for review, ready for final review

#2761 Why and when you should use kubernetes
  content/articles/why-and-when-you-should-use-kubernetes/hero.jpg
  content/articles/why-and-when-you-should-use-kubernetes/index.md
  content/authors/erick-wekesa/avatar.jpg
  content/authors/erick-wekesa/index.md
Labels: assigned for review, duplicate, good first article, ready for final review

#2630 Handling RecyclerView Clicks the Right Way
  content/articles/handling-recyclerview-clicks-the-right-way/create_project.png
  content/articles/handling-recyclerview-clicks-the-right-way/hero.jpg
  content/articles/handling-recyclerview-clicks-the-right-way/index.md
  content/articles/handling-recyclerview-clicks-the-right-way/recyclerview.jpg
  content/articles/handling-recyclerview-clicks-the-right-way/recyclerview_clicked.jpg
  content/authors/joel-kanyi/avatar.jpg
  content/authors/joel-kanyi/index.md
Labels: assigned for review, good first article, ready for final review

#2896 Face recognition using principal component analysis (pca) in Matlab
  content/articles/face-recognition-using-principal-component-analysis-in-matlab/hero.jpg
  content/articles/face-recognition-using-principal-component-analysis-in-matlab/image1.png
  content/articles/face-recognition-using-principal-component-analysis-in-matlab/image2.png
  content/articles/face-recognition-using-principal-component-analysis-in-matlab/index.md
Labels: assigned for review, ready for final review

#2880 How to Build Apps with Serverless Architecture?
  content/articles/how-to-build-apps-with-serverless-architecture/hero.jpg
  content/articles/how-to-build-apps-with-serverless-architecture/index.md
  content/authors/lilian-kerubo/avatar.jpg
  content/authors/lilian-kerubo/index.md
Labels: assigned for review, good first article, ready for final review

#2812 How KubeMQ users build scalable messaging platforms with Kubernetes Operators?
  content/articles/kubemq-scalable-messaging-platforms-kubernetes-operators/hero.jpg
  content/articles/kubemq-scalable-messaging-platforms-kubernetes-operators/index.md
Labels: assigned for review, ready for final review

#2851 How to Set up and Configure Redis Caching for WordPress
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/aws-key-pair.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/aws-marketplace.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/choose-aws-instance-type.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/enable-object-cache.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/get-system-log.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/hero.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/index.md
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/key-prefix-enabled.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/launch-instances.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/load-ppk.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/login-terminal.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/ppk.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/putty-ip-address-session.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/query-monitor-dashboard.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/query-monitor-dashboard2.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/query-monitor-menu.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/query-monitor.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/redis-empty-key-list.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/redis-object-cache-plugin.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/redis-object-cache-set.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/redis-wp-keys.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/running-wordpress-instances.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/sudo-systemctl-status-redis.png
  content/articles/how-to-set-up-and-configure-redis-caching-for-wordpress/wp-login-details.png
Labels: ready for final review

#2983 Introduction to PHP Operators
  content/articles/introduction-to-php-operators/hero.png
  content/articles/introduction-to-php-operators/image1.png
  content/articles/introduction-to-php-operators/image2.png
  content/articles/introduction-to-php-operators/image3.png
  content/articles/introduction-to-php-operators/image4.png
  content/articles/introduction-to-php-operators/index.md
  content/authors/serah-muthoni/avatar.jpg
  content/authors/serah-muthoni/index.md
Labels: duplicate, enhancement

#2783 Getting started with PHP Sessions
  content/articles/getting-started-with-php-sessions/hero.jpg
  content/articles/getting-started-with-php-sessions/image1.png
  content/articles/getting-started-with-php-sessions/image2.png
  content/articles/getting-started-with-php-sessions/image3.png
  content/articles/getting-started-with-php-sessions/image4.png
  content/articles/getting-started-with-php-sessions/index.md
  content/authors/neema-muganga/avatar.jpg
  content/authors/neema-muganga/index.md
Labels: ready for final review, tech tutorial

#2813 Transaction and transaction management in SQL
  content/articles/transaction-management-in-database/hero.jpg
  content/articles/transaction-management-in-database/index.md
Labels: assigned for review, ready for final review

#2981 added how-to-handle-file-upload-in-flask folder
  content/articles/how-to-handle-file-uploads-with-flask/hero.jpg
  content/articles/how-to-handle-file-uploads-with-flask/image1.PNG
  content/articles/how-to-handle-file-uploads-with-flask/image2.PNG
  content/articles/how-to-handle-file-uploads-with-flask/image3.PNG
  content/articles/how-to-handle-file-uploads-with-flask/image4.PNG
  content/articles/how-to-handle-file-uploads-with-flask/image5.PNG
  content/articles/how-to-handle-file-uploads-with-flask/index.md
Labels: ready for final review, tech tutorial

#2860 How to share data between a docker container and the host computer
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/bind-mount-containers.png
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/bind-mount-default.png
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/containers.png
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/default-nginx-page.png
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/hero.jpg
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/index.md
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/ip-address.png
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/nginx-docker-image.png
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/updated-nginx-page.png
  content/articles/how-to-share-data-between-a-docker-container-and-the-host-computer/volumes.png
  content/authors/joakim-gakure/avatar.png
  content/authors/joakim-gakure/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2794 A dive into python strings
  content/articles/python-strings/hero.png
  content/articles/python-strings/index.md
  content/authors/dianne-sandra/avatar.jpg
  content/authors/dianne-sandra/index.md
Labels: ready for final review, tech tutorial

#2818 Getting Started with Polynomial Regression in R
  content/articles/polynomial-regression/Salaryplot.png
  content/articles/polynomial-regression/dataset.png
  content/articles/polynomial-regression/hero.jpg
  content/articles/polynomial-regression/index.md
  content/articles/polynomial-regression/newdataset.png
  content/articles/polynomial-regression/newdatasetlevels.png
  content/articles/polynomial-regression/summary.png
  content/articles/polynomial-regression/visualpoly.png
  content/authors/lawrence-mbici/avatar.jpg
  content/authors/lawrence-mbici/index.md
Labels: ready for final review, tech tutorial

#2826 How to start up with Socket Programming with Java
  content/articles/socket-programming-in-java/hero.png
  content/articles/socket-programming-in-java/index.md
  content/authors/Apondi-Ashley/avatar.jpeg
  content/authors/Apondi-Ashley/index.md
Labels: ready for final review, tech tutorial

#2913 Understanding AES and RSA encryption algorithms
  content/articles/aes-rsa-encryption/RSA.png
  content/articles/aes-rsa-encryption/aes-flow.png
  content/articles/aes-rsa-encryption/hero.jpg
  content/articles/aes-rsa-encryption/index.md
  content/articles/aes-rsa-encryption/mixcolumn.png
  content/articles/aes-rsa-encryption/round.png
  content/articles/aes-rsa-encryption/shift.png
  content/articles/aes-rsa-encryption/sub.png
Labels: article, ready for final review

#2920 Building a Kubernetes-based solution in a Hybrid Environment by using KubeMQ
  content/articles/kubernetes-based-platform-solution-in-a-hybrid-environment-using-kubemq/hero.jpg
  content/articles/kubernetes-based-platform-solution-in-a-hybrid-environment-using-kubemq/index.md
  content/authors/lewel-murithi/avatar.jpg
  content/authors/lewel-murithi/index.md
Labels: assigned for review, ready for final review

#2933 Docker Push for Publishing Images to Docker Hub
  content/articles/docker-push-for-publishing-images-to-docker-hub/hero.jpg
  content/articles/docker-push-for-publishing-images-to-docker-hub/index.md
  content/articles/docker-push-for-publishing-images-to-docker-hub/repo.jpg
Labels: assigned for review, ready for final review, tech tutorial

#2912 Using Multiple SSH Keys for Multiple GitHub Accounts
  content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/add-sshkey.jpg
  content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/config.jpg
  content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/hero.jpg
  content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/index.md
  content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/ls-ssh.jpg
  content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/personal.jpg
  content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/ssh-copy-key.jpg
  content/articles/using-multiple-ssh-keys-for-multiple-github-accounts/work.jpg
  content/authors/wangui-leah/avatar.jpg
  content/authors/wangui-leah/index.md
Labels: assigned for review, enhancement, tech tutorial
