Repository section-engineering-education/engineering-education, pull requests merged in 2021-06, with the labels that each got.

#2255 Getting Started With HTTP/2 and Server Push in Node.js
  content/articles/http2-in-nodejs/hero.jpg
  content/articles/http2-in-nodejs/http2support.png
  content/articles/http2-in-nodejs/httppush.png
  content/articles/http2-in-nodejs/index.md
  content/authors/bradley-biketi/avatar.jpg
  content/authors/bradley-biketi/index.md
Labels: assigned for review, ready for final review

#2293 Creating dynamic web content with createjs
  content/articles/createJS-guide/frame-indexing-example.png
  content/articles/createJS-guide/hero.png
  content/articles/createJS-guide/index.md
  content/articles/createJS-guide/sprite-sheet.png
  content/articles/createJS-guide/successful-asset-loading.png
Labels: assigned for review, ready for final review

#2307 how to handle navigation in flutter
  content/articles/how-to-handle-navigation-in-flutter/hero.jpg
  content/articles/how-to-handle-navigation-in-flutter/image1.PNG
  content/articles/how-to-handle-navigation-in-flutter/image2.png
  content/articles/how-to-handle-navigation-in-flutter/image3.png
  content/articles/how-to-handle-navigation-in-flutter/image4.png
  content/articles/how-to-handle-navigation-in-flutter/index.md
Labels: duplicate, ready for final review

#2198 Getting started with Spring Boot REST Template
  content/articles/spring-boot-rest-template/create-todo.png
  content/articles/spring-boot-rest-template/get-todo-by-id.png
  content/articles/spring-boot-rest-template/get-todos.png
  content/articles/spring-boot-rest-template/hero.jpg
  content/articles/spring-boot-rest-template/index.md
  content/articles/spring-boot-rest-template/update-todo.png
  content/authors/elizabeth-akinyi/avatar.jpeg
  content/authors/elizabeth-akinyi/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2464 Integrating Tailwindcss into you Flask apps.
  content/articles/integrate-tailwindcss-into-flask/demo1.JPG
  content/articles/integrate-tailwindcss-into-flask/demo2.JPG
  content/articles/integrate-tailwindcss-into-flask/hero.png
  content/articles/integrate-tailwindcss-into-flask/index.md
  content/authors/paul-asalu/avatar.jpg
  content/authors/paul-asalu/index.md
Labels: ready for final review

#2150 Angular 11 Popup Notification with SweetAlert2 Example
  content/articles/angular-11-notifications/error-alert.png
  content/articles/angular-11-notifications/hero.jpg
  content/articles/angular-11-notifications/index.md
  content/articles/angular-11-notifications/question-alert.png
  content/articles/angular-11-notifications/success-sweetalert.png
  content/articles/angular-11-notifications/warning-alert.png
Labels: assigned for review, ready for final review, tech tutorial

#2207 Getting started with Kubernetes Clusters
  content/articles/kubernetes-clusters-intro/hero.jpg
  content/articles/kubernetes-clusters-intro/index.md
  content/articles/kubernetes-clusters-intro/shell.png
Labels: assigned for review, ready for final review

#2197 Routing with Angular 11 Router: Full-Tutorial
  content/articles/angular-11-routing/hero.jpg
  content/articles/angular-11-routing/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1996 Email authentication and verification Node.js and Firebase
  content/articles/email-authentication-and-verification-nodejs-firebase/account-verified.png
  content/articles/email-authentication-and-verification-nodejs-firebase/hero.jpg
  content/articles/email-authentication-and-verification-nodejs-firebase/homepage.png
  content/articles/email-authentication-and-verification-nodejs-firebase/inbox.png
  content/articles/email-authentication-and-verification-nodejs-firebase/index.md
  content/articles/email-authentication-and-verification-nodejs-firebase/link-in-mail.png
  content/articles/email-authentication-and-verification-nodejs-firebase/link-redirect.png
  content/articles/email-authentication-and-verification-nodejs-firebase/login.png
  content/articles/email-authentication-and-verification-nodejs-firebase/register.png
Labels: assigned for review, ready for final review, tech tutorial

#2485 How to set up User Authentification from Scratch with Rails 6
  content/articles/how-to-setup-user-authentication-from-scratch-with-rails-6/hero.jpeg
  content/articles/how-to-setup-user-authentication-from-scratch-with-rails-6/index.md
  content/articles/how-to-setup-user-authentication-from-scratch-with-rails-6/localhost.png
  content/articles/how-to-setup-user-authentication-from-scratch-with-rails-6/pass_reset_mail.png
  content/articles/how-to-setup-user-authentication-from-scratch-with-rails-6/railsconsole.png
  content/articles/how-to-setup-user-authentication-from-scratch-with-rails-6/sign_up.png
  content/articles/how-to-setup-user-authentication-from-scratch-with-rails-6/welcome_mailer.png
  content/authors/njunu-simon/avatar.jpg
  content/authors/njunu-simon/index.md
Labels: assigned for review, duplicate, ready for final review

#2240 How to connect MongoDB to Node.js using Mongoose.
  content/articles/nodejs-mongoosejs-mongodb/add_user.png
  content/articles/nodejs-mongoosejs-mongodb/clusters.png
  content/articles/nodejs-mongoosejs-mongodb/connect_to_db.png
  content/articles/nodejs-mongoosejs-mongodb/get_users.png
  content/articles/nodejs-mongoosejs-mongodb/hero.jpg
  content/articles/nodejs-mongoosejs-mongodb/index.md
  content/authors/nancy-maina/avatar.jpg
  content/authors/nancy-maina/index.md
Labels: good first article, ready for final review

#2234 Getting started with graphical user interface in Matlab
  content/articles/matlab-graphical-user-interface/hero.jpg
  content/articles/matlab-graphical-user-interface/image1.png
  content/articles/matlab-graphical-user-interface/image10.png
  content/articles/matlab-graphical-user-interface/image11.png
  content/articles/matlab-graphical-user-interface/image12.png
  content/articles/matlab-graphical-user-interface/image2.png
  content/articles/matlab-graphical-user-interface/image3.png
  content/articles/matlab-graphical-user-interface/image4.png
  content/articles/matlab-graphical-user-interface/image5.png
  content/articles/matlab-graphical-user-interface/image6.png
  content/articles/matlab-graphical-user-interface/image7.png
  content/articles/matlab-graphical-user-interface/image8.png
  content/articles/matlab-graphical-user-interface/image9.png
  content/articles/matlab-graphical-user-interface/index.md
  content/authors/linet-achieng/avatar.jpg
  content/authors/linet-achieng/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2296 Sharing Data between Docker Containers
  content/articles/sharing-data-between-docker-containers/hero.jpg
  content/articles/sharing-data-between-docker-containers/index.md
Labels: ready for final review, tech tutorial

#2267 Getting started with Google sheets API in Node.js
  content/articles/google-sheets-api-in-nodejs/form.png
  content/articles/google-sheets-api-in-nodejs/hero.jpg
  content/articles/google-sheets-api-in-nodejs/index.md
  content/articles/google-sheets-api-in-nodejs/sheet-file.png
  content/articles/google-sheets-api-in-nodejs/success.png
  content/authors/mia-roberts/avatar.jpeg
  content/authors/mia-roberts/index.md
Labels: assigned for review, ready for final review

#2342 How To Build A Random Password Generator App With HTML, CSS And JAVASCRIPT
  content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/ascii-table.png
  content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/hero.jpg
  content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/index.md
  content/articles/how-to-build-a-random-password-generator-app-with-html-css-javascript/password-generator-app.png
  content/authors/Destiny-Etinagbedia/avatar.jpg
  content/authors/Destiny-Etinagbedia/index.md
Labels: assigned for review, duplicate, ready for final review

#2305 Applet programming in java
  content/articles/applet-programming-in-java/hero.jpg
  content/articles/applet-programming-in-java/index.md
  content/authors/paul-mwangi/avatar.jpg
  content/authors/paul-mwangi/index.md
Labels: ready for final review

#2289 How to Setup Dynamic Cron Job(Task Scheduling) in Laravel?
  content/articles/laravel-cron-jobs/hero.png
  content/articles/laravel-cron-jobs/index.md
Labels: assigned for review, ready for final review

#2227 Deploying Docker Containers to Kubernetes Cluster
  content/articles/deploy-docker-container-to-kubernetes-cluster/app-deployed.png
  content/articles/deploy-docker-container-to-kubernetes-cluster/creating-image.png
  content/articles/deploy-docker-container-to-kubernetes-cluster/dashboard.png
  content/articles/deploy-docker-container-to-kubernetes-cluster/deployment.png
  content/articles/deploy-docker-container-to-kubernetes-cluster/hero.jpg
  content/articles/deploy-docker-container-to-kubernetes-cluster/index.md
  content/authors/samuel-zabastian/avatar.jpg
  content/authors/samuel-zabastian/index.md
Labels: assigned for review, ready for final review

#2325 Building a Java Application with Jenkins in Docker
  content/articles/building-a-java-application-with-jenkins-in-docker/build-now.png
  content/articles/building-a-java-application-with-jenkins-in-docker/build-trigger.png
  content/articles/building-a-java-application-with-jenkins-in-docker/check-docker-build-step.png
  content/articles/building-a-java-application-with-jenkins-in-docker/console-output.png
  content/articles/building-a-java-application-with-jenkins-in-docker/create-item.png
  content/articles/building-a-java-application-with-jenkins-in-docker/docker-build-step.png
  content/articles/building-a-java-application-with-jenkins-in-docker/docker-hub-login.png
  content/articles/building-a-java-application-with-jenkins-in-docker/docker-image-push.png
  content/articles/building-a-java-application-with-jenkins-in-docker/docker-plugins.png
  content/articles/building-a-java-application-with-jenkins-in-docker/freestyle-project.png
  content/articles/building-a-java-application-with-jenkins-in-docker/github-url.png
  content/articles/building-a-java-application-with-jenkins-in-docker/hero.png
  content/articles/building-a-java-application-with-jenkins-in-docker/index.md
  content/articles/building-a-java-application-with-jenkins-in-docker/initial-admin-password.png
  content/articles/building-a-java-application-with-jenkins-in-docker/intellij-settings.png
  content/articles/building-a-java-application-with-jenkins-in-docker/jdk-config.png
  content/articles/building-a-java-application-with-jenkins-in-docker/jenkins-configuration.png
  content/articles/building-a-java-application-with-jenkins-in-docker/jenkins-getting-started.png
  content/articles/building-a-java-application-with-jenkins-in-docker/jenkins-home.png
  content/articles/building-a-java-application-with-jenkins-in-docker/maven-build-step.png
  content/articles/building-a-java-application-with-jenkins-in-docker/maven-config.png
  content/articles/building-a-java-application-with-jenkins-in-docker/maven-test-failure.png
  content/articles/building-a-java-application-with-jenkins-in-docker/maven-test-pass.png
  content/articles/building-a-java-application-with-jenkins-in-docker/plugins-installation.png
  content/articles/building-a-java-application-with-jenkins-in-docker/see-console-output.png
  content/articles/building-a-java-application-with-jenkins-in-docker/source-code-management.png
  content/authors/divine-odazie/avatar.jpeg
  content/authors/divine-odazie/index.md
Labels: ready for final review, tech tutorial

#2281 Getting Started With Custom Pipes in Angular 11
  content/articles/angular11-custom-pipes/angular-homepage.png
  content/articles/angular11-custom-pipes/currency.png
  content/articles/angular11-custom-pipes/custom.png
  content/articles/angular11-custom-pipes/hero.jpg
  content/articles/angular11-custom-pipes/index.md
  content/articles/angular11-custom-pipes/text-case.png
  content/authors/bhanji-brilliant/avatar.png
  content/authors/bhanji-brilliant/index.md
Labels: assigned for review, ready for final review

#2312 getting-started-with-css
  content/articles/getting-started-with-css/hero.jpg
  content/articles/getting-started-with-css/index.md
  content/authors/lucy-maina/avatar.jpg
  content/authors/lucy-maina/index.md
Labels: good first article, ready for final review

#2438 Node.js Network Requests Using Axios
  content/articles/nodejs-network-requests-using-axios/hero.jpg
  content/articles/nodejs-network-requests-using-axios/index.md
Labels: assigned for review, ready for final review

#2357 Getting Started With MariaDB Using Docker and Node.js
  content/articles/getting-started-with-mariadb-using-docker-and-nodejs/hero.jpg
  content/articles/getting-started-with-mariadb-using-docker-and-nodejs/index.md
  content/articles/getting-started-with-mariadb-using-docker-and-nodejs/maria-db-root.PNG
  content/articles/getting-started-with-mariadb-using-docker-and-nodejs/persons-route.PNG
Labels: ready for final review

#2324 Email/Password Authentication Using Firebase in React Native
  content/articles/react-native-firebase-email-authentication/auth_get_starterd.png
  content/articles/react-native-firebase-email-authentication/download_services.json.png
  content/articles/react-native-firebase-email-authentication/enabled_email.png
  content/articles/react-native-firebase-email-authentication/env_setup.png
  content/articles/react-native-firebase-email-authentication/firebase_new.png
  content/articles/react-native-firebase-email-authentication/folder_structure.png
  content/articles/react-native-firebase-email-authentication/hero.jpeg
  content/articles/react-native-firebase-email-authentication/index.md
  content/articles/react-native-firebase-email-authentication/new_dashboard.png
  content/articles/react-native-firebase-email-authentication/package_name.png
  content/articles/react-native-firebase-email-authentication/register_app.png
  content/articles/react-native-firebase-email-authentication/screens.jpg
  content/articles/react-native-firebase-email-authentication/signin.gif
  content/articles/react-native-firebase-email-authentication/signout.gif
Labels: assigned for review, ready for final review, tech tutorial

#2353 A step by step guide on how to use Typescript with Node.js
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/compiled-javascript.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/generateing-tsconfig-file.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/hero.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/index.md
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/nodemon.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/npm-types-declarations.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/package-json-file.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/sum-results.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/ts-node-compiler.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/ts-node-dev.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/tsc-version.png
  content/articles/a-step-by-step-guide-on-how-to-use-typescript-with-nodejs/tsconfig-file.png
  content/authors/faith-musyoka/avatar.PNG
  content/authors/faith-musyoka/index.md
Labels: assigned for review, good first article, ready for final review

#2317 Using Modern CSS Features in Old Browsers using @supports
  content/articles/articles/nodejs-vs-python/hero.png
  content/articles/articles/nodejs-vs-python/index.md
  content/articles/css-supports-query/hero.jpg
  content/articles/css-supports-query/index.md
  content/articles/css-supports-query/sticky-firefox.jpg
  content/articles/css-supports-query/sticky.jpg
Labels: ready for final review, tech tutorial

#2363 How to Build Authentication Api with Jwt Token in Nodejs
  content/articles/how-to-build-authentication-api-with-jwt-token-in-nodejs/error-response.png
  content/articles/how-to-build-authentication-api-with-jwt-token-in-nodejs/folder-struc.png
  content/articles/how-to-build-authentication-api-with-jwt-token-in-nodejs/hero.png
  content/articles/how-to-build-authentication-api-with-jwt-token-in-nodejs/index.md
  content/articles/how-to-build-authentication-api-with-jwt-token-in-nodejs/login.png
  content/articles/how-to-build-authentication-api-with-jwt-token-in-nodejs/register.png
  content/articles/how-to-build-authentication-api-with-jwt-token-in-nodejs/success-response.png
  content/authors/idris-olubisi/index.md
Labels: ready for final review

#2355 Type Casting in Java
  content/articles/type-casting-in-java/hero.jpg
  content/articles/type-casting-in-java/index.md
  content/authors/terrypha-wamaitha/Avatar.jpeg
  content/authors/terrypha-wamaitha/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2361 Top Container Orchestration Tools
  content/articles/top-container-orchestration-tools/apache-mesos.jpg
  content/articles/top-container-orchestration-tools/docker-swarm.jpg
  content/articles/top-container-orchestration-tools/hero.jpg
  content/articles/top-container-orchestration-tools/index.md
  content/articles/top-container-orchestration-tools/kubernetes-architecture.jpg
  content/authors/esther-waithera/avatar.jpg
  content/authors/esther-waithera/index.md
Labels: article, assigned for review, good first article, ready for final review

#2378 Pointers In C#
  content/articles/pointers-in-csharp/activating_unsafe_code.png
  content/articles/pointers-in-csharp/hero.png
  content/articles/pointers-in-csharp/index.md
  content/authors/kelvin-munene/avatar.jpeg
  content/authors/kelvin-munene/index.md
Labels: ready for final review, tech tutorial

#2367 Fundamentals of container security
  content/articles/fundamentals-of-container-security/hero.jpg
  content/articles/fundamentals-of-container-security/index.md
Labels: article, assigned for review, ready for final review

#2444 Making cURL requests in Node.js
  content/articles/node-curl/hero.jpg
  content/articles/node-curl/index.md
  content/authors/vincent-ngunzulu/avatar.jpg
  content/authors/vincent-ngunzulu/index.md
Labels: assigned for review, good first article, ready for final review

#2389 How sweet is kubernetes?
  content/articles/how-sweet-is-kubernetes/fleetman.png
  content/articles/how-sweet-is-kubernetes/hero.jpeg
  content/articles/how-sweet-is-kubernetes/index.md
  content/articles/how-sweet-is-kubernetes/ingress.png
  content/articles/how-sweet-is-kubernetes/node.png
  content/authors/qoyum-yusuf/avatar.jpg
  content/authors/qoyum-yusuf/index.md
Labels: article, assigned for review, duplicate, good first article, ready for final review

#2402 Working with Google Translate API
  content/articles/working-with-translate-api-in-nodejs/after-translation.png
  content/articles/working-with-translate-api-in-nodejs/choose-language.png
  content/articles/working-with-translate-api-in-nodejs/hero.png
  content/articles/working-with-translate-api-in-nodejs/index.md
  content/articles/working-with-translate-api-in-nodejs/user-interface.png
Labels: assigned for review, needs plagiarism check, ready for final review

#2395 Flutter Social Authentication
  content/articles/flutter-social-authentication/access.png
  content/articles/flutter-social-authentication/android.png
  content/articles/flutter-social-authentication/app-id.png
  content/articles/flutter-social-authentication/auth-redirect.png
  content/articles/flutter-social-authentication/chooseaccount.jpg
  content/articles/flutter-social-authentication/facebook.jpg
  content/articles/flutter-social-authentication/hero.jpg
  content/articles/flutter-social-authentication/homescreen.jpg
  content/articles/flutter-social-authentication/index.md
  content/articles/flutter-social-authentication/loginscreen.jpg
  content/articles/flutter-social-authentication/package.png
  content/articles/flutter-social-authentication/setuplogin.png
  content/articles/flutter-social-authentication/users.png
Labels: assigned for review, ready for final review

#2488 What are Cookies, How Cookies Work, and How to use them in Node.js
  content/articles/what-are-cookies-nodejs/a-running-server.png
  content/articles/what-are-cookies-nodejs/accept-cookies-website-popup.png
  content/articles/what-are-cookies-nodejs/bob-login-cookie.png
  content/articles/what-are-cookies-nodejs/browser-console.png
  content/articles/what-are-cookies-nodejs/cookie-deleted.png
  content/articles/what-are-cookies-nodejs/cookie-not-accessed-with-javascript.png
  content/articles/what-are-cookies-nodejs/cookie-saved-console-log.png
  content/articles/what-are-cookies-nodejs/cookie-saved.png
  content/articles/what-are-cookies-nodejs/cookies-updated-security-values.png
  content/articles/what-are-cookies-nodejs/hero.png
  content/articles/what-are-cookies-nodejs/home-page.png
  content/articles/what-are-cookies-nodejs/index.md
  content/articles/what-are-cookies-nodejs/login-page.png
  content/articles/what-are-cookies-nodejs/login-server-running.png
  content/articles/what-are-cookies-nodejs/logout-clear-cookies.png
  content/articles/what-are-cookies-nodejs/saved-cookie.png
  content/articles/what-are-cookies-nodejs/welcome-page.png
Labels: ready for final review, tech tutorial

#2636 [Author Update] Update Louise Findlay Author Bio
  content/authors/louise-findlay/index.md
Labels: author update

#2420 Using machine learning to translate brain signals to text
  content/articles/using-machine-learning-to-translate-brain-signals-to-text/electrode-implants.PNG
  content/articles/using-machine-learning-to-translate-brain-signals-to-text/hero.jpg
  content/articles/using-machine-learning-to-translate-brain-signals-to-text/index.md
  content/articles/using-machine-learning-to-translate-brain-signals-to-text/interpretation.PNG
  content/articles/using-machine-learning-to-translate-brain-signals-to-text/online-offline-system.PNG
  content/articles/using-machine-learning-to-translate-brain-signals-to-text/pca.PNG
  content/articles/using-machine-learning-to-translate-brain-signals-to-text/t-sne.PNG
Labels: article, ready for final review

#2201 Getting started with Data Preprocessing in R
  content/articles/data-preprocessing/Dataset.png
  content/articles/data-preprocessing/dataset1.png
  content/articles/data-preprocessing/dataset2.png
  content/articles/data-preprocessing/encode1.png
  content/articles/data-preprocessing/encode_Purchased.png
  content/articles/data-preprocessing/hero.jpg
  content/articles/data-preprocessing/index.md
  content/articles/data-preprocessing/one.png
  content/articles/data-preprocessing/scaled_test_set.png.png
  content/articles/data-preprocessing/scaled_training_set.png
  content/articles/data-preprocessing/test_set.png
  content/articles/data-preprocessing/training_set.png
  content/authors/stanley-juma/avatar.png
  content/authors/stanley-juma/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2404 Introduction to WLAN frequency bands
  content/articles/introduction-to-wlan-frequency-bands/hero.jpg
  content/articles/introduction-to-wlan-frequency-bands/index.md
Labels: article, duplicate, ready for final review

#2631 Flutter social auth
  content/articles/flutter-social-authentication/auth-redirect-url.png
  content/articles/flutter-social-authentication/index.md
Labels: article update

#2448 CRUD Operations with YII2 Framework Using GII
  content/articles/crud-operations-with-yii2-framework-using-gii/create.png
  content/articles/crud-operations-with-yii2-framework-using-gii/crud_generator.png
  content/articles/crud-operations-with-yii2-framework-using-gii/crud_project_verification.png
  content/articles/crud-operations-with-yii2-framework-using-gii/database_record.png
  content/articles/crud-operations-with-yii2-framework-using-gii/delete.png
  content/articles/crud-operations-with-yii2-framework-using-gii/generate.png
  content/articles/crud-operations-with-yii2-framework-using-gii/gii_welcome_page.png
  content/articles/crud-operations-with-yii2-framework-using-gii/hero.png
  content/articles/crud-operations-with-yii2-framework-using-gii/index.md
  content/articles/crud-operations-with-yii2-framework-using-gii/main_local.png
  content/articles/crud-operations-with-yii2-framework-using-gii/model_generator.png
  content/articles/crud-operations-with-yii2-framework-using-gii/read.png
  content/articles/crud-operations-with-yii2-framework-using-gii/update.png
  content/authors/beatrice-muriithi/avatar.png
  content/authors/beatrice-muriithi/index.md
Labels: assigned for review, good first article, ready for final review

#2410 How to Setup and run PHP Websites using Docker Containers with PHP Apache and MySQL
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/apache-server-running.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/db-inserted-records.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/docker-compose-up.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/docker-engine-container-running.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/docker-engine.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/docker-error.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/docker-version.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/dockerized-php-website.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/hero.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/index.md
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/mysql-connected-successfully.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/mysql-image.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/mysql-select-results.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/no-running-docker-container.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/php-docker-container-folder.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/php-my-admin-login.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/phpmyadmin.png
  content/articles/dockerized-php-apache-and-mysql-container-development-environment/solve-docker-error.png
Labels: assigned for review, ready for final review, tech tutorial

#2425 PID controllers using Matlab
  content/articles/pid-controllers-using-matlab/PID1.png
  content/articles/pid-controllers-using-matlab/PID10.png
  content/articles/pid-controllers-using-matlab/PID11.png
  content/articles/pid-controllers-using-matlab/PID12.png
  content/articles/pid-controllers-using-matlab/PID2.png
  content/articles/pid-controllers-using-matlab/PID3.png
  content/articles/pid-controllers-using-matlab/PID4.png
  content/articles/pid-controllers-using-matlab/PID5.png
  content/articles/pid-controllers-using-matlab/PID6.png
  content/articles/pid-controllers-using-matlab/PID7.png
  content/articles/pid-controllers-using-matlab/PID8.png
  content/articles/pid-controllers-using-matlab/PID9.png
  content/articles/pid-controllers-using-matlab/hero.jpeg
  content/articles/pid-controllers-using-matlab/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2655 [Duplicate] How to Interact with an API from a Vue.js Application
  content/articles/how-to-interact-with-an-api-from-a-vuejs-application/hero.png
  content/articles/how-to-interact-with-an-api-from-a-vuejs-application/index.md
  content/authors/edidiong-etok/avatar.jpeg
  content/authors/edidiong-etok/index.md
Labels: assigned for review, duplicate, ready for final review

#2652 How to Interact with an API from a Vue.js Application
  content/articles/how-to-interact-with-an-api-from-a-vuejs-application/hero.png
  content/articles/how-to-interact-with-an-api-from-a-vuejs-application/index.md
  content/authors/edidiong-etok/avatar.jpeg
  content/authors/edidiong-etok/index.md
Labels: assigned for review, duplicate, ready for final review

#2669 [Duplicate] Hashing In Data Structure
  content/articles/hashing-in-data-structures/hash-intro.png
  content/articles/hashing-in-data-structures/hash-map.png
  content/articles/hashing-in-data-structures/hash-map2.png
  content/articles/hashing-in-data-structures/hero.jpg
  content/articles/hashing-in-data-structures/index.md
  content/articles/hashing-in-data-structures/output.png
  content/authors/anubhav-bansal/avatar.jpg
  content/authors/anubhav-bansal/index.md
Labels: assigned for review, duplicate, ready for final review

#2445 Using Formidable for parsing form data in Node.js application.
  content/articles/upload-files-using-formidable-nodejs/appjs.png
  content/articles/upload-files-using-formidable-nodejs/appjs2.png
  content/articles/upload-files-using-formidable-nodejs/hero.png
  content/articles/upload-files-using-formidable-nodejs/index.md
Labels: assigned for review, ready for final review

#2474 How to write efficient python code
  content/articles/how-to-write-efficient-python-code/hero.jpg
  content/articles/how-to-write-efficient-python-code/index.md
  content/authors/samuel-torimiro/avatar.jpg
  content/authors/samuel-torimiro/index.md
Labels: assigned for review, good first article, ready for final review

#2489 Concept of first hop redundancy protocol
  content/articles/concept-of-first-hop-redundancy-protocol/active.JPG
  content/articles/concept-of-first-hop-redundancy-protocol/hero.jpg
  content/articles/concept-of-first-hop-redundancy-protocol/index.md
  content/articles/concept-of-first-hop-redundancy-protocol/standby.JPG
  content/articles/concept-of-first-hop-redundancy-protocol/topo.JPG
  content/authors/rabo-james-bature/avatar.jpg
Labels: assigned for review, duplicate, ready for final review

#2526 Breaking Down Docker Containers vs. Virtual Machines (VMs)
  content/articles/breaking-down-docker-containers-vs-virtual-machines/hero.jpg
  content/articles/breaking-down-docker-containers-vs-virtual-machines/index.md
  content/authors/nelly-atieno/avatar.jpg
  content/authors/nelly-atieno/index.md
Labels: duplicate, ready for final review

#2399 Comparing Serverless Computing Vs Containers
  content/articles/comparing-serverless-computing-vs-containers/hero.png
  content/articles/comparing-serverless-computing-vs-containers/index.md
  content/authors/jayden-kiprotich/avatar.jpg
  content/authors/jayden-kiprotich/index.md
Labels: article, assigned for review, good first article, ready for final review

#2483 Files and Exceptions in Python
  content/articles/files-and-exceptions-in-python/hero.jpg
  content/articles/files-and-exceptions-in-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2297 Introduction to Internet Protocol and Subnetting
  content/articles/introduction-to-subnetting/classes-ip.jpeg
  content/articles/introduction-to-subnetting/diagram-of-IPV4.jpeg
  content/articles/introduction-to-subnetting/hero.jpg
  content/articles/introduction-to-subnetting/index.md
  content/articles/introduction-to-subnetting/network-host-id.gif
  content/articles/introduction-to-subnetting/routing.jpg
  content/articles/introduction-to-subnetting/types-of-routing.jpeg
  content/authors/anyebe-blessing-ene/avatar.jpg
  content/authors/anyebe-blessing-ene/index.md
Labels: article, good first article, ready for final review

#2457 Linux container (LXC ) vs. Docker container , what's the difference and why Docker is better
  content/articles/lxc-vs-docker-what-is-the-difference-and-why-docker-is-better/a-docker-container.png
  content/articles/lxc-vs-docker-what-is-the-difference-and-why-docker-is-better/hero.png
  content/articles/lxc-vs-docker-what-is-the-difference-and-why-docker-is-better/index.md
  content/articles/lxc-vs-docker-what-is-the-difference-and-why-docker-is-better/lxc-container.png
  content/articles/lxc-vs-docker-what-is-the-difference-and-why-docker-is-better/virtual-machine-vm-architecture.jpeg
  content/authors/julius-gikonyo/avatar.jpg
  content/authors/julius-gikonyo/index.md
Labels: assigned for review, good first article, ready for final review

#2481 Network Management Using CDP and LLDP Layer 2 Protocols
  content/articles/network-management-with-cdp-lldp/hero.jpg
  content/articles/network-management-with-cdp-lldp/index.md
  content/articles/network-management-with-cdp-lldp/network.jpg
  content/authors/atonya-dennis/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2492 pm2-with-nodejs
  content/articles/pm2-with-nodejs/hero.jpg
  content/articles/pm2-with-nodejs/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2498 Different ways of creating Objects in Java
  content/articles/different-ways-to-create-objects-in-java/hero.jpg
  content/articles/different-ways-to-create-objects-in-java/index.md
  content/authors/moses-mwangi/avatar.jpeg
  content/authors/moses-mwangi/index.md
Labels: ready for final review, tech tutorial

#2505 Data Encryption and Decryption in Node.js using Crypto
  content/articles/data-encryption-and-decryption-in-node-js-using-crypto/encrypt-decrypt.jpg
  content/articles/data-encryption-and-decryption-in-node-js-using-crypto/encrypt.jpg
  content/articles/data-encryption-and-decryption-in-node-js-using-crypto/hero.jpg
  content/articles/data-encryption-and-decryption-in-node-js-using-crypto/index.md
Labels: assigned for review, ready for final review

#2504 h2o security implementation
  content/articles/securing-data-with-h2o/false.jpg
  content/articles/securing-data-with-h2o/hero.jpg
  content/articles/securing-data-with-h2o/index.md
  content/articles/securing-data-with-h2o/true.jpg
Labels: ready for final review

#2515 Getting Started With Kali Linux
  content/articles/getting-started-with-kali-linux/cat.png
  content/articles/getting-started-with-kali-linux/cd.png
  content/articles/getting-started-with-kali-linux/cd1.png
  content/articles/getting-started-with-kali-linux/echo.png
  content/articles/getting-started-with-kali-linux/firefox.png
  content/articles/getting-started-with-kali-linux/hero.jpg
  content/articles/getting-started-with-kali-linux/index.md
  content/articles/getting-started-with-kali-linux/login.png
  content/articles/getting-started-with-kali-linux/ls-la.png
  content/articles/getting-started-with-kali-linux/ls.png
  content/articles/getting-started-with-kali-linux/mkdir.png
  content/articles/getting-started-with-kali-linux/msfconsole.png
  content/articles/getting-started-with-kali-linux/passwd.png
  content/articles/getting-started-with-kali-linux/pwd.png
  content/articles/getting-started-with-kali-linux/rmdir.png
  content/authors/meshack-kimosop/avatar.jpg
  content/authors/meshack-kimosop/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2500 How to Containerize a Python Application
  content/articles/how-to-containerize-a-python-application/hero.jpg
  content/articles/how-to-containerize-a-python-application/index.md
  content/authors/emmanuel-alege/avatar.jpg
  content/authors/emmanuel-alege/index.md
Labels: ready for final review, tech tutorial

#2507 Using ECS to deploy a docker app to AWS
  content/articles/using-ecs-to-deploy-docker-app-to-aws/app-running.png
  content/articles/using-ecs-to-deploy-docker-app-to-aws/build-app.png
  content/articles/using-ecs-to-deploy-docker-app-to-aws/creating-cluster.png
  content/articles/using-ecs-to-deploy-docker-app-to-aws/creating-task.png
  content/articles/using-ecs-to-deploy-docker-app-to-aws/edit-inbound-rules.png
  content/articles/using-ecs-to-deploy-docker-app-to-aws/hero.jpg
  content/articles/using-ecs-to-deploy-docker-app-to-aws/index.md
  content/articles/using-ecs-to-deploy-docker-app-to-aws/repository-created.png
  content/articles/using-ecs-to-deploy-docker-app-to-aws/task-running.png
  content/articles/using-ecs-to-deploy-docker-app-to-aws/upload-to-repository.png
  content/authors/victor-elvis/avatar.jpeg
  content/authors/victor-elvis/index.md
Labels: assigned for review, duplicate, good first article, ready for final review, tech tutorial

#2517 What is AWS, why is AWS popular?
  content/articles/what-is-aws-and-why-is-aws-so-popular/aws-global-infrastructure.png
  content/articles/what-is-aws-and-why-is-aws-so-popular/cloud-service-providers.png
  content/articles/what-is-aws-and-why-is-aws-so-popular/hero.png
  content/articles/what-is-aws-and-why-is-aws-so-popular/index.md
  content/articles/what-is-aws-and-why-is-aws-so-popular/most-loved-platform.png
  content/articles/what-is-aws-and-why-is-aws-so-popular/most-wanted-platform.png
  content/articles/what-is-aws-and-why-is-aws-so-popular/popular-platforms.png
Labels: article, ready for final review

#2524 Create php superglobals
  content/articles/php-superglobals/hero.jpg
  content/articles/php-superglobals/index.md
Labels: ready for final review

#2547 Sharing data using SafeArgs in Android-Kotlin
  content/articles/safe-args-in-android/accept-dependencies.png
  content/articles/safe-args-in-android/add-custom-argument.png
  content/articles/safe-args-in-android/add-int-argument.png
  content/articles/safe-args-in-android/hero.png
  content/articles/safe-args-in-android/index.md
  content/articles/safe-args-in-android/new-project.png
Labels: assigned for review, ready for final review

#2600 C# Enumerations (Enum)
  content/articles/c-sharp-enums/hero.jpg
  content/articles/c-sharp-enums/index.md
Labels: assigned for review, ready for final review

#2599 Working with cypress in Nodejs
  content/articles/node-cypress-testing/cypress-binary.png
  content/articles/node-cypress-testing/hero.jpg
  content/articles/node-cypress-testing/index.md
  content/articles/node-cypress-testing/test-result.png
Labels: assigned for review, ready for final review, tech tutorial

#2684 Working with Images in a Spring Boot Backend (Kotlin)
  content/articles/working-with-images-in-spring-boot/hero.png
  content/articles/working-with-images-in-spring-boot/index.md
  content/articles/working-with-images-in-spring-boot/sample-cors-error.png
Labels: assigned for review, ready for final review

#2618 Understanding Quality of Service (QoS)
  content/articles/understanding-quality-of-service/hero.png
  content/articles/understanding-quality-of-service/index.md
Labels: article, duplicate, ready for final review

#2750 Update list-of-software-peer-reviewers.md
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#2421 Why you should use Wakanda JavaScript framework
  content/articles/why-you-should-use-wakanda/hero.jpg
  content/articles/why-you-should-use-wakanda/index.md
  content/authors/ann-michubu/avatar.jpg
  content/authors/ann-michubu/index.md
Labels: article, good first article, ready for final review

#2508 Creating a Custom Data Transformer using Scikit-Learn
  content/articles/custom-transformer/hero.jpg
  content/articles/custom-transformer/index.md
Labels: ready for final review

#2256 Getting Started With Fastify Node.js framework and Faunadb
  content/articles/fastify-fauna-nodejs/Usersmembercoll.png
  content/articles/fastify-fauna-nodejs/create-user.png
  content/articles/fastify-fauna-nodejs/db-name2.png
  content/articles/fastify-fauna-nodejs/get-user.png
  content/articles/fastify-fauna-nodejs/hero.jpg
  content/articles/fastify-fauna-nodejs/index.md
  content/articles/fastify-fauna-nodejs/newdatabase1.png
  content/articles/fastify-fauna-nodejs/read-privileges.png
  content/articles/fastify-fauna-nodejs/role-server3.png
  content/articles/fastify-fauna-nodejs/shell-create-collection.png
Labels: assigned for review, ready for final review, tech tutorial

#2502 Introduction to GUI using Tkinter in Python
  content/articles/introduction-to-gui-using-tkinter-in-python/hero.jpg
  content/articles/introduction-to-gui-using-tkinter-in-python/index.md
  content/articles/introduction-to-gui-using-tkinter-in-python/passsword.png
Labels: ready for final review, tech tutorial

#2767 Update Content Moderators Docs
  content-moderators/cheat-sheet.md
  content-moderators/content-moderators.md
  content-moderators/final-front-matter-review.md
  content-moderators/how-to-preview-hugo.md
Labels: documentation

#2314 Creating Node Application Using Express Generator
  content/articles/nodejs-app-express-generator/hero.jpg
  content/articles/nodejs-app-express-generator/home.png
  content/articles/nodejs-app-express-generator/index.md
Labels: assigned for review, question, ready for final review

#2315 Deploying RESTful APIs using Node, Express 4 to Kubernetes clusters
  content/articles/restful-node-deployment-using-docker/hero.jpg
  content/articles/restful-node-deployment-using-docker/index.md
  content/authors/jared-phelix/avatar.png
  content/authors/jared-phelix/index.md
Labels: assigned for review, ready for final review

#2566 Top 5 Docker Logging Best Practices
  content/articles/top-5-docker-logging-practices/hero.png
  content/articles/top-5-docker-logging-practices/index.md
Labels: article, assigned for review, good first article, ready for final review

#2477 PostgreSQL vs MySQL
  content/articles/postgresql-vs-mysql/hero.jpg
  content/articles/postgresql-vs-mysql/index.md
  content/articles/postgresql-vs-mysql/postgresql-vs-mysql.png
  content/authors/amos-muriithi/avatar.jpg
  content/authors/amos-muriithi/index.md
Labels: article, assigned for review, good first article, ready for final review

#2447 How to implement Caching in AdonisJS 5
  content/articles/how-to-implement-caching-in-adonisjs-5/forum_cache.png
  content/articles/how-to-implement-caching-in-adonisjs-5/forum_nocache.png
  content/articles/how-to-implement-caching-in-adonisjs-5/hero.png
  content/articles/how-to-implement-caching-in-adonisjs-5/index.md
Labels: ready for final review, tech tutorial

#2585 How To Deploy A Streamlit App With Docker
  content/articles/how-to-deploy-streamlit-app-with-docker/data.png
  content/articles/how-to-deploy-streamlit-app-with-docker/female-prediction.png
  content/articles/how-to-deploy-streamlit-app-with-docker/hero.png
  content/articles/how-to-deploy-streamlit-app-with-docker/index.md
  content/articles/how-to-deploy-streamlit-app-with-docker/male-prediction.png
  content/authors/bravin-wasike/avatar.jpg
  content/authors/bravin-wasike/index.md
Labels: assigned for review, good first article, ready for final review

#2571 A beginners guide on how to become a blockchain developer
  content/articles/a-beginners-guide-on-how-to-become-a-blockchain-developer/hero.jpg
  content/articles/a-beginners-guide-on-how-to-become-a-blockchain-developer/index.md
Labels: article, ready for final review

#2568 Java vs C#
  content/articles/java-vs-csharp/hero.jpg
  content/articles/java-vs-csharp/index.md
  content/authors/alice-wangari/avatar.jpeg
  content/authors/alice-wangari/index.md
Labels: good first article, ready for final review
