Repository section-engineering-education/engineering-education, pull requests merged in 2021-04, with the labels that each got.

#1758 Implementing Rate Limiting in Flask APIs
  articles/implementing-rate-limiting-in-flask/hero.jpg
  articles/implementing-rate-limiting-in-flask/index.md
  articles/implementing-rate-limiting-in-flask/nulbeq2kwcnmek9ucrn2.png
  articles/implementing-rate-limiting-in-flask/oqahhiaqcfeigq1urdwe.png
  articles/implementing-rate-limiting-in-flask/osw9-4n2ilprrg2m_i9g.png
  authors/solomon-esenyi/avatar.jpg
Labels: assigned for review, ready for final review

#1921 Areas of Expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#1918 Update Author Page
  authors/saiharsha-balasubramaniam/index.md
Labels: documentation

#1908 Areas of Expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#1912 Areas of expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#1798 How to Build a Clock with JavaScript and SVG
  articles/how-to-build-a-clock-with-javascript-and-svg/hero.png
  articles/how-to-build-a-clock-with-javascript-and-svg/index.md
  articles/how-to-build-a-clock-with-javascript-and-svg/result.png
Labels: ready for final review, tech tutorial

#1925 Add areas of expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#1782 How to Create an Automatic Slider in Android Studio
  articles/how-to-create-an-automatic-slider-in-android-studio/automatic-slider-timer.gif
  articles/how-to-create-an-automatic-slider-in-android-studio/hero.jpg
  articles/how-to-create-an-automatic-slider-in-android-studio/index.md
  articles/how-to-create-an-automatic-slider-in-android-studio/sliders.gif
Labels: enhancement, ready for final review, tech tutorial

#1688 Django API documentation
  articles/django-api-documentation/coreapi.png
  articles/django-api-documentation/hero.jpg
  articles/django-api-documentation/index.md
  articles/django-api-documentation/redoc.png
  articles/django-api-documentation/swagger.png
  authors/okelo-violet/avatar.jpeg
  authors/okelo-violet/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1951 Fixes to my author page
  authors/terrence-aluda/index.md
Labels: documentation

#1948 Update areas of expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#1946 Update list-of-software-peer-reviewers.md
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#1945 Added area of expertise
  authors/peter-kayere/avatar.jpg
  authors/peter-kayere/avatar.png
  authors/peter-kayere/index.md
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#1803 Face detection using Viola-Jones algorithm in Matlab
  articles/face-detection-matlab/building.png
  articles/face-detection-matlab/engineers.png
  articles/face-detection-matlab/hero.jpg
  articles/face-detection-matlab/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1808 Getting started with quasar framework
  articles/getting-started-with-quasar-framework/hero.jpg
  articles/getting-started-with-quasar-framework/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1809 Biometric 2FA in a Django Application with TypingDNA
  articles/biometric-2fa-in-a-django-application-with-typingdna/add-video.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/added-video.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/application-running.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/autocomplete-disabler.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/check-user-endpoint.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/dashboard.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/email-verification.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/enrollment-page.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/hero.jpg
  articles/biometric-2fa-in-a-django-application-with-typingdna/import.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/index.md
  articles/biometric-2fa-in-a-django-application-with-typingdna/invalid-token.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/link-sent.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/login.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/migrations.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/project-structure.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/project_structure.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/sign-in-page.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/verification-token.png
  articles/biometric-2fa-in-a-django-application-with-typingdna/verify-page.png
  authors/doro-onome/avatar.jpg
  authors/doro-onome/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1965 Added missing image for article
  articles/biometric-2fa-in-a-django-application-with-typingdna/signup-page.png
Labels: article update

#1771 Building web server with vlang
  articles/building-your-web-server-with-vlang/hero.jpg
  articles/building-your-web-server-with-vlang/index.md
  authors/samuel-umoren/avatar.jpg
  authors/samuel-umoren/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1814 Developing a one-to-one mapping application leveraging hibernate
  articles/hibernate-one-to-one-mapping/create-customer.png
  articles/hibernate-one-to-one-mapping/customer-subscription.png
  articles/hibernate-one-to-one-mapping/deleting-subscription.png
  articles/hibernate-one-to-one-mapping/hero.jpg
  articles/hibernate-one-to-one-mapping/index.md
  articles/hibernate-one-to-one-mapping/maven-structure.png
  articles/hibernate-one-to-one-mapping/mysql-login.png
  articles/hibernate-one-to-one-mapping/plagiarism-check.png
  articles/hibernate-one-to-one-mapping/updating-customer.png
  authors/david-mbochi/avatar.jpg
  authors/david-mbochi/index.md
Labels: assigned for review, good first article, needs front matter, ready for final review

#1821 Comparing Graphical User Interface (GUI) and Command Line Interface (CLI)
  articles/comparing-graphical-user-interface-gui-and-command-line-interface-cli/hero.jpg
  articles/comparing-graphical-user-interface-gui-and-command-line-interface-cli/index.md
  authors/bridget-mwikali/avatar.jpg
  authors/bridget-mwikali/index.md
Labels: article, good first article, ready for final review

#1888 How To Build A Custom URL Shortener Using Node.js, Express and MongoDB
  articles/nodejs-url-shortener/hero.jpg
  articles/nodejs-url-shortener/index.md
  articles/nodejs-url-shortener/postman.gif
  authors/mary-njeri/avatar.jpg
  authors/mary-njeri/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1850 How to implement SearchView in Android
  articles/implementing-search-view-in-android/directories-collapsed.png
  articles/implementing-search-view-in-android/hero.png
  articles/implementing-search-view-in-android/index.md
  articles/implementing-search-view-in-android/main-ui.png
  articles/implementing-search-view-in-android/results.png
  articles/implementing-search-view-in-android/row-item.png
  authors/eric-gacoki/avatar.jpg
  authors/eric-gacoki/avatar.png
  authors/eric-gacoki/index.md
Labels: assigned for review, ready for final review

#1826 The Basics of Means End Analysis in AI
  articles/basics-of-means-end-analysis-in-ai/delete-operator.png
  articles/basics-of-means-end-analysis-in-ai/expand-operator.png
  articles/basics-of-means-end-analysis-in-ai/hero.jpg
  articles/basics-of-means-end-analysis-in-ai/index.md
  articles/basics-of-means-end-analysis-in-ai/initial-and-target-states.png
  articles/basics-of-means-end-analysis-in-ai/initial-state.png
  articles/basics-of-means-end-analysis-in-ai/mea-processes.jpg
  articles/basics-of-means-end-analysis-in-ai/move-operator.png
  authors/grace-nkurikiyinka/avatar.jpg
  authors/grace-nkurikiyinka/index.md
Labels: assigned for review, good first article, ready for final review

#1832 What is Self-Supervised Learning?
  articles/what-is-self-supervised-learning/hero.jpg
  articles/what-is-self-supervised-learning/index.md
Labels: article, ready for final review

#1837 Introduction to Dynamic Host Configuration Protocol (DHCP)
  articles/introduction-to-dynamic-host-configuration/dora.jpg
  articles/introduction-to-dynamic-host-configuration/download.jpg
  articles/introduction-to-dynamic-host-configuration/hero.jpg
  articles/introduction-to-dynamic-host-configuration/index.md
Labels: article, assigned for review, ready for final review

#1847 Getting Started With Node.js OS Module
  articles/nodejs-os-module/hero.jpg
  articles/nodejs-os-module/index.md
Labels: article, assigned for review, ready for final review

#1840 User groups and permissions - Linux
  articles/user-groups-and-permissions-Linux/1.png
  articles/user-groups-and-permissions-Linux/2.png
  articles/user-groups-and-permissions-Linux/3.png
  articles/user-groups-and-permissions-Linux/hero.png
  articles/user-groups-and-permissions-Linux/index.md
Labels: article, assigned for review, ready for final review

#1855 JavaScript vs. TypeScript
  articles/javascript-vs-typescript/function-error-detected.jpg
  articles/javascript-vs-typescript/function-error.jpg
  articles/javascript-vs-typescript/hero.jpg
  articles/javascript-vs-typescript/index.md
  articles/javascript-vs-typescript/most-loved-language.jpg
  articles/javascript-vs-typescript/most-popular-language-red-monk.jpg
  articles/javascript-vs-typescript/most-popular-language-stack-overflow.jpg
  articles/javascript-vs-typescript/static-typing-error.jpg
  articles/javascript-vs-typescript/static-typing.jpg
  articles/javascript-vs-typescript/typescript-api-documentation-highlights.png
  articles/javascript-vs-typescript/typescript-hotkeys.jpg
  articles/javascript-vs-typescript/typescript-trend.jpg
  authors/catherine-macharia/avatar.jpeg
  authors/catherine-macharia/index.md
Labels: ready for final review, tech tutorial

#1856 Managing File uploads in HTML forms using PHP
  articles/managing-file-uploads-in-html-forms-using-php/Phpmyadmin.jpg
  articles/managing-file-uploads-in-html-forms-using-php/apachestart.jpg
  articles/managing-file-uploads-in-html-forms-using-php/apachesuccess.jpg
  articles/managing-file-uploads-in-html-forms-using-php/formlayout.jpg
  articles/managing-file-uploads-in-html-forms-using-php/hero.jpg
  articles/managing-file-uploads-in-html-forms-using-php/index.md
  articles/managing-file-uploads-in-html-forms-using-php/mysqlbutton.jpg
  authors/felix-vaati/avatar.png
  authors/felix-vaati/index.md
Labels: assigned for review, good first article, ready for final review

#1933 Building your first telegram bot in Node.js
  articles/telegram-bot-in-nodejs/hero.jpg
  articles/telegram-bot-in-nodejs/image1.jpg
  articles/telegram-bot-in-nodejs/image2.jpg
  articles/telegram-bot-in-nodejs/image3.jpg
  articles/telegram-bot-in-nodejs/image4.jpg
  articles/telegram-bot-in-nodejs/image5.jpg
  articles/telegram-bot-in-nodejs/index.md
  authors/ck-muithi/avatar.jpg
  authors/ck-muithi/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1859 Build a Tasks iOS Application using Swift
  articles/ios-tasks-app-using-swift/app-settings.png
  articles/ios-tasks-app-using-swift/create-new-project.png
  articles/ios-tasks-app-using-swift/hero.jpg
  articles/ios-tasks-app-using-swift/index.md
  articles/ios-tasks-app-using-swift/template.png
  articles/ios-tasks-app-using-swift/xcode-main-window.png
Labels: ready for final review, tech tutorial

#1862 Consuming APIs in flutter
  articles/consuming-apis-in-flutter/hero.jpg
  articles/consuming-apis-in-flutter/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1863 Docker & WordPress – Containerizing WordPress with Docker-Compose
  articles/docker-wordpress-containerizing-wordpress-with-docker-compose/docker-installation-error.jpg
  articles/docker-wordpress-containerizing-wordpress-with-docker-compose/docker-wordpress-files.jpg
  articles/docker-wordpress-containerizing-wordpress-with-docker-compose/hero.png
  articles/docker-wordpress-containerizing-wordpress-with-docker-compose/index.md
  articles/docker-wordpress-containerizing-wordpress-with-docker-compose/wordpress-installation.jpg
  articles/docker-wordpress-containerizing-wordpress-with-docker-compose/wordpress-php-my-admin.jpg
  articles/docker-wordpress-containerizing-wordpress-with-docker-compose/wp-admin-backend.jpg
  articles/docker-wordpress-containerizing-wordpress-with-docker-compose/wp-admin-config-information.jpg
  authors/rose-waitherero/avatar.jpeg
  authors/rose-waitherero/index.md
Labels: ready for final review

#1930 Sending SMS in Nodejs using vonage's SMS API
  articles/send-sms-in-nodejs-using-vonage-api/dashboard.png
  articles/send-sms-in-nodejs-using-vonage-api/hero.png
  articles/send-sms-in-nodejs-using-vonage-api/index.md
  articles/send-sms-in-nodejs-using-vonage-api/success-message.png
  articles/send-sms-in-nodejs-using-vonage-api/text-before-sending.png
  articles/send-sms-in-nodejs-using-vonage-api/text-in-sms-app.png
  authors/mercy-meave/hero.jpeg
  authors/mercy-meave/index.md
Labels: ready for final review, tech tutorial

#1897 Sealed Classes in Kotlin
  articles/sealed-classes-in-kotlin/hero.jpg
  articles/sealed-classes-in-kotlin/index.md
Labels: assigned for review, ready for final review

#1877 Uploading images to cloudinary from django application
  articles/uploading-images-to-cloudinary-from-django-application/add-photo.png
  articles/uploading-images-to-cloudinary-from-django-application/admin.png
  articles/uploading-images-to-cloudinary-from-django-application/dash.png
  articles/uploading-images-to-cloudinary-from-django-application/django-admin.png
  articles/uploading-images-to-cloudinary-from-django-application/fish-local.png
  articles/uploading-images-to-cloudinary-from-django-application/hero.png
  articles/uploading-images-to-cloudinary-from-django-application/index.md
  articles/uploading-images-to-cloudinary-from-django-application/photo-added.png
  authors/shuaib-oseni/Avatar.jpg
  authors/shuaib-oseni/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1894 Nodejs child processes
  articles/nodejs-child-processes/hero.jpg
  articles/nodejs-child-processes/index.md
Labels: assigned for review, ready for final review

#1885 Hash Tables in JavaScript
  articles/hash-tables-in-javascript/hero.jpg
  articles/hash-tables-in-javascript/index.md
  articles/hash-tables-in-javascript/linear-probing.jpg
  articles/hash-tables-in-javascript/separate-chaining.jpg
Labels: assigned for review, ready for final review

#1903 How to buid a TODO app
  articles/how-to-build-a-flutter-todo-app/appbar.jpg
  articles/how-to-build-a-flutter-todo-app/default.jpg
  articles/how-to-build-a-flutter-todo-app/final.jpg
  articles/how-to-build-a-flutter-todo-app/hero.jpg
  articles/how-to-build-a-flutter-todo-app/index.md
  authors/nathaniel-dauda-wobin/author.jpg
  authors/nathaniel-dauda-wobin/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1902 How to upload files to AWS S3 using Django Rest Framework
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/access_key_generated.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/add_user_screen.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/app_structure.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/assign_username.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/aws_sucessful_upload.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/click_create_bucket.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/finish_bucket_creation.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/globally_name_bucket.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/hero.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/iam_sidemenu.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/index.md
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/media_included_structure.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/new_user.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/sample_upload.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/search_iam.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/search_s3.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/set_permission.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/set_permission_boundary.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/successful_bucket_creation.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/uploaded_big_o.png
  articles/how-to-upload-files-to-aws-s3-using-django-rest-framework/user_summary.png
Labels: duplicate, ready for final review

#1913 Introduction to YOLO algorithm for Object Detection
  articles/introduction-to-yolo-algorithm-for-object-detection/bounding-box.png
  articles/introduction-to-yolo-algorithm-for-object-detection/grids.png
  articles/introduction-to-yolo-algorithm-for-object-detection/hero.jpg
  articles/introduction-to-yolo-algorithm-for-object-detection/how-yolo-algorithm-works.jpg
  articles/introduction-to-yolo-algorithm-for-object-detection/index.md
  articles/introduction-to-yolo-algorithm-for-object-detection/iou.jpeg
  authors/grace-karimi/avatar.jpg
  authors/grace-karimi/index.md
Labels: assigned for review, good first article, ready for final review

#1917 How to set up a Node.js Express server for React
  articles/how-to-setup-nodejs-express-for-react/folder-structure.PNG
  articles/how-to-setup-nodejs-express-for-react/get-route-success.PNG
  articles/how-to-setup-nodejs-express-for-react/hero.jpg
  articles/how-to-setup-nodejs-express-for-react/index.md
  articles/how-to-setup-nodejs-express-for-react/react-app-success.PNG
  authors/verah-ombui/avatar.jpg
  authors/verah-ombui/index.md
Labels: assigned for review, ready for final review

#1815 Cryptography In Computer Networking
  articles/cryptography-in-computer-networking/hero.jpg
  articles/cryptography-in-computer-networking/index.md
  authors/mackrine-awino/avatar.jpeg
  authors/mackrine-awino/index.md
Labels: assigned for review, enhancement

#1828 Building an Appointment Scheduling Telegram Bot with Python and Fauna
  articles/building-an-appointment-scheduling-telegram-bot/add_appointment.png
  articles/building-an-appointment-scheduling-telegram-bot/bot_father_COMMAND.png
  articles/building-an-appointment-scheduling-telegram-bot/bot_father_convo.png
  articles/building-an-appointment-scheduling-telegram-bot/create_collection.png
  articles/building-an-appointment-scheduling-telegram-bot/create_index.png
  articles/building-an-appointment-scheduling-telegram-bot/database_dashboard.png
  articles/building-an-appointment-scheduling-telegram-bot/delete_appintment.png
  articles/building-an-appointment-scheduling-telegram-bot/hero.jpg
  articles/building-an-appointment-scheduling-telegram-bot/index.md
  articles/building-an-appointment-scheduling-telegram-bot/indexes.png
  articles/building-an-appointment-scheduling-telegram-bot/key.png
  articles/building-an-appointment-scheduling-telegram-bot/list_appointment.png
  articles/building-an-appointment-scheduling-telegram-bot/list_today_appointment.png
  articles/building-an-appointment-scheduling-telegram-bot/new_key.png
  articles/building-an-appointment-scheduling-telegram-bot/run_result.png
  articles/building-an-appointment-scheduling-telegram-bot/search_bot.png
  articles/building-an-appointment-scheduling-telegram-bot/search_bot_father.png
  articles/building-an-appointment-scheduling-telegram-bot/start_bot.png
  articles/building-an-appointment-scheduling-telegram-bot/start_bot_father.png
  articles/building-an-appointment-scheduling-telegram-bot/update_appointment.png
  authors/onojakpor-ochuko/index.md
Labels: tech tutorial

#2076 changed image name on article
  articles/building-an-appointment-scheduling-telegram-bot/delete_appointment.png
  authors/onojakpor-ochuko/index.md
Labels: article update

#1873 Getting started with Nodejs EJS templating engine
  articles/nodejs-ejs/hero.png
  articles/nodejs-ejs/index.md
  articles/nodejs-ejs/project-structure.png
  articles/nodejs-ejs/running-site.png
Labels: assigned for review, ready for final review, tech tutorial

#1914 Network troubleshooting using traceroute
  articles/network-troubleshooting-using-traceroute/hero.png
  articles/network-troubleshooting-using-traceroute/index.md
  articles/network-troubleshooting-using-traceroute/picture-five.png
  articles/network-troubleshooting-using-traceroute/picture-four.png
  articles/network-troubleshooting-using-traceroute/picture-one.png
  articles/network-troubleshooting-using-traceroute/picture-seven.png
  articles/network-troubleshooting-using-traceroute/picture-six.png
  articles/network-troubleshooting-using-traceroute/picture-three.png
  articles/network-troubleshooting-using-traceroute/picture-two.png
  authors/sudi-david/avatar.jpeg
  authors/sudi-david/index.md
Labels: article, good first article, needs front matter, ready for final review

#1954 Documenting a Node.js REST API using swagger
  articles/documenting-node-js-rest-api-using-swagger/create-todo-screenshot.png
  articles/documenting-node-js-rest-api-using-swagger/delete-todo-screenshot.png
  articles/documenting-node-js-rest-api-using-swagger/general-info-screenshot.png
  articles/documenting-node-js-rest-api-using-swagger/get-todo-screenshot.png
  articles/documenting-node-js-rest-api-using-swagger/get-todos-screenshot.png
  articles/documenting-node-js-rest-api-using-swagger/hero.jpg
  articles/documenting-node-js-rest-api-using-swagger/index.md
  articles/documenting-node-js-rest-api-using-swagger/schemas-screenshot.png
  articles/documenting-node-js-rest-api-using-swagger/servers-screenshot.png
  articles/documenting-node-js-rest-api-using-swagger/tags-screenshot.png
  articles/documenting-node-js-rest-api-using-swagger/update-todo-screenshot.png
Labels: assigned for review, ready for final review, tech tutorial

#1982 How to perform custom ranking for records from a MongoDB database in Node.js
  articles/nodejs-mongodb-custom-ranking/hero.jpg
  articles/nodejs-mongodb-custom-ranking/index.md
  articles/nodejs-mongodb-custom-ranking/screen.png
Labels: assigned for review, duplicate, ready for final review, tech tutorial

#1924 Declarative vs Imperative UI in Android
  articles/declarative-vs-imperative-ui-android/complex.jpg
  articles/declarative-vs-imperative-ui-android/component.png
  articles/declarative-vs-imperative-ui-android/composable.png
  articles/declarative-vs-imperative-ui-android/hero.jpg
  articles/declarative-vs-imperative-ui-android/index.md
  articles/declarative-vs-imperative-ui-android/layout.jpg
  authors/linus-muema/index.md
Labels: ready for final review

#1956 Introduction to Sequalize ORM for Node.js
  articles/introduction-to-sequalize-orm-for-nodejs/hero.jpg
  articles/introduction-to-sequalize-orm-for-nodejs/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1938 Getting Started With Spring WebSockets in Java
  articles/getting-started-with-spring-websockets/hero.jpg
  articles/getting-started-with-spring-websockets/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1970 Consuming the TinEye Reverse Image Search API in Node.js
  articles/nodejs-tineye-api/hero.jpg
  articles/nodejs-tineye-api/index.md
  articles/nodejs-tineye-api/meloncat.jpg
  articles/nodejs-tineye-api/screen1.png
  articles/nodejs-tineye-api/screen2.png
  authors/sandra-moringa/avatar.jpeg
  authors/sandra-moringa/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1923 Android Application Widgets Tutorial in Java
  articles/android-application-widgets-tutorial-in-java/android-app-widget.gif
  articles/android-application-widgets-tutorial-in-java/android-studio-configure-app-widget.jpg
  articles/android-application-widgets-tutorial-in-java/android-studio-create-new-widget.jpg
  articles/android-application-widgets-tutorial-in-java/demo-widget-screenshot.jpg
  articles/android-application-widgets-tutorial-in-java/hero.jpg
  articles/android-application-widgets-tutorial-in-java/home-screen-demo-widget.jpg
  articles/android-application-widgets-tutorial-in-java/index.md
  articles/android-application-widgets-tutorial-in-java/manifest-code.png
  articles/android-application-widgets-tutorial-in-java/widget-class-code.png
  authors/moses-chege/avatar.jpg
  authors/moses-chege/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1939 Introduction to UiPath in Robotic Process Automation (RPA)
  articles/introduction-to-uipath-in-rpa/hero.jpg
  articles/introduction-to-uipath-in-rpa/index.md
  articles/introduction-to-uipath-in-rpa/uipath-architecture.jpg
Labels: article, assigned for review, ready for final review

#2103 Area of expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#1991 Building a simple cryptocurrency blockchain in Nodejs
  articles/building-a-simple-cryptocurrency-blockchain/bitcoin.jpg
  articles/building-a-simple-cryptocurrency-blockchain/ethereum.jpg
  articles/building-a-simple-cryptocurrency-blockchain/hero.jpg
  articles/building-a-simple-cryptocurrency-blockchain/index.md
  articles/building-a-simple-cryptocurrency-blockchain/output.jpg
  authors/yitzack-rabin/avatar.jpg
  authors/yitzack-rabin/index.md
  hero.jpg
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1949 An Introduction to K-Nearest Neighbors (KNN) Algorithm
  articles/introduction-to-knn-algorithm/dataset.PNG
  articles/introduction-to-knn-algorithm/euclidean-distance.PNG
  articles/introduction-to-knn-algorithm/hero.jpg
  articles/introduction-to-knn-algorithm/index.md
  articles/introduction-to-knn-algorithm/knn.png
Labels: assigned for review, ready for final review, tech tutorial

#1942 Getting started with linear regression in R
  articles/linear-regression-r/head_output.png
  articles/linear-regression-r/hero.jpg
  articles/linear-regression-r/image-one.png
  articles/linear-regression-r/index.md
  articles/linear-regression-r/plot-one.png
  articles/linear-regression-r/plot.png
  articles/linear-regression-r/prediction-plot.png
  articles/linear-regression-r/summary-output.png
  articles/linear-regression-r/summary.png
  authors/daniel-mwanthi/avatar.jpg
  authors/daniel-mwanthi/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1953 How to get SSL/HTTPS for localhost
  articles/how-to-get-ssl-https-for-localhost/firefox-not-secure.PNG
  articles/how-to-get-ssl-https-for-localhost/firefox-privacy-settings.PNG
  articles/how-to-get-ssl-https-for-localhost/firefox-secure.PNG
  articles/how-to-get-ssl-https-for-localhost/hero.jpg
  articles/how-to-get-ssl-https-for-localhost/index.md
  articles/how-to-get-ssl-https-for-localhost/postman-error.PNG
  articles/how-to-get-ssl-https-for-localhost/postman-red-security-error.png
  articles/how-to-get-ssl-https-for-localhost/postman-ssl-off.PNG
  articles/how-to-get-ssl-https-for-localhost/postman-success-cert.png
  articles/how-to-get-ssl-https-for-localhost/postman-success.PNG
  authors/lewel-murithi/avatar.jpg
  authors/lewel-murithi/index.md
Labels: good first article, ready for final review, tech tutorial

#1957 from theory to practice implementing totp 2fa in python and flask
  articles/implementing-totp-2fa-using-flask/generating-otp.png
  articles/implementing-totp-2fa-using-flask/hello-world.png
  articles/implementing-totp-2fa-using-flask/hero.jpg
  articles/implementing-totp-2fa-using-flask/index.md
  articles/implementing-totp-2fa-using-flask/invalid-login.png
  articles/implementing-totp-2fa-using-flask/invalid-otp.png
  articles/implementing-totp-2fa-using-flask/login.png
  articles/implementing-totp-2fa-using-flask/valid-login.png
  articles/implementing-totp-2fa-using-flask/valid-otp.png
  authors/prince-joel/avatar.jpg
  authors/prince-joel/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#1955 feat: Pushing why you should use celery with rabbitmq
  articles/why-you-should-use-celery-with-rabbitmq/gendog1.png
  articles/why-you-should-use-celery-with-rabbitmq/gendog2.png
  articles/why-you-should-use-celery-with-rabbitmq/hero.jpg
  articles/why-you-should-use-celery-with-rabbitmq/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1973 Build a Ticketing App with AdonisJS and VueJS #1630
  articles/build-a-ticketing-app-with-adonisjs-and-vuejs/buildpreview.png
  articles/build-a-ticketing-app-with-adonisjs-and-vuejs/hero.png
  articles/build-a-ticketing-app-with-adonisjs-and-vuejs/index.md
Labels: assigned for review, ready for final review, tech tutorial

#1969 An Overview of IoT Technology
  articles/an-overview-of-iot-technology/hero.jpg
  articles/an-overview-of-iot-technology/index.md
  articles/introduction-to-elastic-stack/index.md
Labels: article, ready for final review

#1947 Concepts and Configuration of the Spanning Tree Protocol
  articles/concepts-and-configuration-of-stp/Single-point-of-failure.jpg
  articles/concepts-and-configuration-of-stp/hero.jpg
  articles/concepts-and-configuration-of-stp/index.md
  articles/concepts-and-configuration-of-stp/interface-states.jpg
  articles/concepts-and-configuration-of-stp/spanning-tree.jpg
Labels: assigned for review, ready for final review, tech tutorial
