Repository section-engineering-education/engineering-education, pull requests merged in 2021-08, with the labels that each got.

#2939 Building a Machine Learning Classification Model with PyCaret
  content/articles/building-a-machine-learning-classification-model-with-pycaret/best-model.png
  content/articles/building-a-machine-learning-classification-model-with-pycaret/hero.png
  content/articles/building-a-machine-learning-classification-model-with-pycaret/index.md
  content/articles/building-a-machine-learning-classification-model-with-pycaret/loaded-dataset.png
  content/articles/building-a-machine-learning-classification-model-with-pycaret/predict-model-best.png
  content/articles/building-a-machine-learning-classification-model-with-pycaret/prediction-dataset.png
  content/articles/building-a-machine-learning-classification-model-with-pycaret/saved-model-results.png
  content/articles/building-a-machine-learning-classification-model-with-pycaret/setup-function-results.png
Labels: ready for final review, tech tutorial

#2926 Understanding DHCP Server Router Configuration
  content/articles/dhcp-server-router-configuration/dhcp-server-connection.jpg
  content/articles/dhcp-server-router-configuration/fail-dhcp.jpg
  content/articles/dhcp-server-router-configuration/hero.jpg
  content/articles/dhcp-server-router-configuration/index.md
  content/articles/dhcp-server-router-configuration/ping-dhcp.jpg
  content/articles/dhcp-server-router-configuration/success-dhcp.jpg
  content/authors/samuel-otieno/avatar.png
  content/authors/samuel-otieno/index.md
Labels: good first article, ready for final review, tech tutorial

#2854 Couchbase Cluster Using Docker Compose
  content/articles/couchbase-cluster-docker/default.png
  content/articles/couchbase-cluster-docker/hero.png
  content/articles/couchbase-cluster-docker/home.png
  content/articles/couchbase-cluster-docker/index.md
  content/articles/couchbase-cluster-docker/rebalance.png
  content/articles/couchbase-cluster-docker/settings.png
Labels: assigned for review, ready for final review

#2915 data abstraction in c#
  content/articles/data-abstraction-in-c-sharp/hero.png
  content/articles/data-abstraction-in-c-sharp/index.md
  content/authors/dickson-gitau/avatar.JPG
  content/authors/dickson-gitau/index.md
Labels: assigned for review, good first article, ready for final review

#3080 Broadcasting a private FM radio station using a Raspberry Pi
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/SSH_enabled.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/configuration.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/gcc_install.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/gitclone.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/hero.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/index.md
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/mkdir.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/os.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/play_audio.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/putty.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/puttylogin.jpg
  content/articles/broadcasting-a-pirate-fm-radio-station-using-a-raspberry-pi/sudomake.jpg
  content/authors/ruphus-muita/avatar.jpg
  content/authors/ruphus-muita/index.md
Labels: assigned for review, duplicate, good first article, ready for final review

#2936 How to Send an Email with Django
  content/articles/how-to-send-email-in-django/django-homepage.jpg
  content/articles/how-to-send-email-in-django/google-less-secure.jpg
  content/articles/how-to-send-email-in-django/hero.jpg
  content/articles/how-to-send-email-in-django/homepage.jpg
  content/articles/how-to-send-email-in-django/index.md
  content/articles/how-to-send-email-in-django/success-page.jpg
Labels: assigned for review, ready for final review

#2917 Building a Simple Nest.js Microservice Application using Redis as the Transporter
  content/articles/building-nest-js-application-using-redis/hero.jpg
  content/articles/building-nest-js-application-using-redis/index.md
  content/articles/building-nest-js-application-using-redis/page-content.png
Labels: assigned for review, ready for final review, tech tutorial

#2752 Getting started with data preprocessing in Python
  content/articles/data-preprocessing-python/Dataframe.png
  content/articles/data-preprocessing-python/hero.png
  content/articles/data-preprocessing-python/index.md
  content/articles/data-preprocessing-python/paste_link.png
Labels: ready for final review

#2977 How to create a user login page using java gui - Duplicate of #2814
  content/articles/how-to-create-a-user-login-page-using-java-gui/hero.jpg
  content/articles/how-to-create-a-user-login-page-using-java-gui/index.md
  content/articles/how-to-create-a-user-login-page-using-java-gui/login-page.png
  content/articles/how-to-create-a-user-login-page-using-java-gui/structure.png
  content/authors/abdulazeez-saidu/avatar.jpg
  content/authors/abdulazeez-saidu/index.md
Labels: assigned for review, duplicate, good first article, ready for final review, tech tutorial

#3036 Introduction to Java Swing Desktop Application Using NetBeans IDE
  content/articles/introduction-to-java-swing/hero.jpg
  content/articles/introduction-to-java-swing/index.md
  content/articles/introduction-to-java-swing/jbutton.png
  content/articles/introduction-to-java-swing/jlabel.png
  content/articles/introduction-to-java-swing/jtext.png
  content/articles/introduction-to-java-swing/netbeans-add.png
  content/articles/introduction-to-java-swing/netbeans-desktopapp.png
  content/articles/introduction-to-java-swing/netbeans-jform.png
  content/articles/introduction-to-java-swing/netbeans-jframe.png
  content/articles/introduction-to-java-swing/netbeans-jframename.png
  content/articles/introduction-to-java-swing/netbeans-project.png
  content/articles/introduction-to-java-swing/netbeans-run.png
  content/articles/introduction-to-java-swing/netbeans-startpage.png
  content/authors/ayoma-joseph/avatar.jpg
  content/authors/ayoma-joseph/index.md
Labels: assigned for review, ready for final review

#3021 Running a Multi-container (Spring Boot and PostgreSQL) Application with Docker Compose
  content/articles/running-a-multi-container-springboot-postgresql-application-with-docker-compose/directory-structure.png
  content/articles/running-a-multi-container-springboot-postgresql-application-with-docker-compose/get-request.png
  content/articles/running-a-multi-container-springboot-postgresql-application-with-docker-compose/hero.jpg
  content/articles/running-a-multi-container-springboot-postgresql-application-with-docker-compose/index.md
  content/articles/running-a-multi-container-springboot-postgresql-application-with-docker-compose/post-request.png
Labels: assigned for review, ready for final review, tech tutorial

#3069 A practical approach to Date and Time in JavaScript
  content/articles/practical-approach-to-date-and-time-in-javascript/hero.png
  content/articles/practical-approach-to-date-and-time-in-javascript/index.md
Labels: assigned for review, ready for final review, tech review

#3153 Update UPLOAD_INSTRUCTIONS.md
  new_contributors/UPLOAD_INSTRUCTIONS.md
Labels: documentation

#2987 Password cracking with john the ripper
  content/articles/password-cracking-with-john-the-ripper/clone.png
  content/articles/password-cracking-with-john-the-ripper/configure.png
  content/articles/password-cracking-with-john-the-ripper/hero.jpg
  content/articles/password-cracking-with-john-the-ripper/index.md
  content/articles/password-cracking-with-john-the-ripper/installing.png
  content/articles/password-cracking-with-john-the-ripper/make_install.png
  content/articles/password-cracking-with-john-the-ripper/run.png
  content/articles/password-cracking-with-john-the-ripper/user_add.png
  content/authors/koros-wkd/avatar.jpg
  content/authors/koros-wkd/index.md
Labels: assigned for review, good first article, ready for final review, tech tutorial

#2872 Semantic HTML for beginners
  content/articles/semantic-html-for-beginners/hero.jpg
  content/articles/semantic-html-for-beginners/html-layout.jpg
  content/articles/semantic-html-for-beginners/index.md
  content/authors/tella-joshua/avatar.jpg
  content/authors/tella-joshua/index.md
Labels: article, assigned for review, good first article, ready for final review, ready for review

#3053 How to use CSS Selectors
  content/articles/how-to-use-css-selectors/hero.png
  content/articles/how-to-use-css-selectors/index.md
Labels: assigned for review, ready for final review, tech tutorial

#2878 Generic programming in c#
  content/articles/generic-programming-in-csharp/hero.jpg
  content/articles/generic-programming-in-csharp/index.md
  content/authors/elijah-ndungu/avatar.jpg
  content/authors/elijah-ndungu/index.md
Labels: ready for final review, tech tutorial

#2899 How to deploy Spring Boot application to Kubernetes
  content/articles/spring-boot-kubernetes/hero.png
  content/articles/spring-boot-kubernetes/index.md
  content/articles/spring-boot-kubernetes/kubernetes-dashboard.png
Labels: assigned for review, ready for final review

#2670 Getting started with Django and Celery
  content/articles/django-celery-tasks/celery-generate.png
  content/articles/django-celery-tasks/celery-success.png
  content/articles/django-celery-tasks/celery-users.png
  content/articles/django-celery-tasks/celery.png
  content/articles/django-celery-tasks/hero.png
  content/articles/django-celery-tasks/index.md
  content/authors/njeri-karen/avatar.jpeg
  content/authors/njeri-karen/index.md
Labels: assigned for review, ready for final review, needs front matter, tech tutorial

#2885 API Authentication using Laravel Sanctum — Laravel 8
  content/articles/laravel-sanctum-api-auth/account.png
  content/articles/laravel-sanctum-api-auth/hero.jpg
  content/articles/laravel-sanctum-api-auth/index.md
  content/articles/laravel-sanctum-api-auth/register.png
Labels: assigned for review, ready for final review

#2993 understanding and working with javascript cookies
  content/articles/understanding-and-working-javascript-cookies/hero.png
  content/articles/understanding-and-working-javascript-cookies/index.md
  content/authors/bernard-mburu/avatar.jpg
  content/authors/bernard-mburu/index.md
Labels: good first article, ready for final review

#2817 Arrays in java
  content/articles/arrays-in-java/hero.png
  content/articles/arrays-in-java/index.md
  content/authors/Catherine-Njoki/avatar.jpg
  content/authors/Catherine-Njoki/index.md
Labels: good first article, assigned for review, ready for final review, article

#2931 Parsing emails in Python
  content/articles/email-parser-python/hero.jpg
  content/articles/email-parser-python/index.md
Labels: assigned for review, ready for final review

#2874 How to configure a Relational Database Server on AWS #2662
  content/articles/configuring-a-relational-database-server-on-aws/aws_create_database.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_create_security_group.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_firewall_rules.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_rds_configuration_page_1.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_rds_configuration_page_2.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_rds_configuration_setting.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_rds_connecting_params.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_rds_create_database_button.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_rds_create_db_credentials.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_rds_search_vpc.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_rds_select_vpc.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_save_security_group.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_search_rds.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_security_group_detail.png
  content/articles/configuring-a-relational-database-server-on-aws/aws_signin_page.png
  content/articles/configuring-a-relational-database-server-on-aws/database_name.png
  content/articles/configuring-a-relational-database-server-on-aws/hero.png
  content/articles/configuring-a-relational-database-server-on-aws/index.md
  content/articles/configuring-a-relational-database-server-on-aws/mysql_create_table_query.png
  content/articles/configuring-a-relational-database-server-on-aws/mysql_workbench_1.png
  content/articles/configuring-a-relational-database-server-on-aws/mysql_workbench_2.png
  content/articles/configuring-a-relational-database-server-on-aws/mysql_workbench_3.png
  content/articles/configuring-a-relational-database-server-on-aws/mysql_workbench_password.png
  content/articles/configuring-a-relational-database-server-on-aws/search_security_group.png
  content/authors/oluwatomisin-bamimore/avatar.png
  content/authors/oluwatomisin-bamimore/index.md
Labels: ready for final review

#3085 How to provide backup services with Google Drive in Android-Kotlin
  content/articles/backup-services-with-google-drive-api-in-android/hero.png
  content/articles/backup-services-with-google-drive-api-in-android/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3066 Implementing a GraphQL server using Prisma, SQLite, and Nest.js with Typescript
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/creating-a-post.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/deleting-a-post.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/fetching-posts.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/fetching-single-post.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/graphql-example.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/hero.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/index.md
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/nest-app-scaffolding.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/sqlite-db-migrations.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/start-nestjs-dev-application.png
  content/articles/implementing-a-graphql-server-using-prisma-sqlite-and-nestjs-with-typescript/updating-a-post.png
Labels: assigned for review, ready for final review

#2956 Kubernetes Cost Optimization Using Autoscaling Methods
  content/articles/kubernetes-cost-optimization-using-autoscaling-methods/hero.jpg
  content/articles/kubernetes-cost-optimization-using-autoscaling-methods/index.md
  content/authors/grace-mumbi/avatar.jpg
  content/authors/grace-mumbi/index.md
Labels: good first article, ready for final review, article

#3038 Understanding the CSS Box-Model
  content/articles/understanding-css-box-model/border.png
  content/articles/understanding-css-box-model/css-box-model.png
  content/articles/understanding-css-box-model/div-span.png
  content/articles/understanding-css-box-model/hero.jpg
  content/articles/understanding-css-box-model/index.md
  content/articles/understanding-css-box-model/padding.png
  content/articles/understanding-css-box-model/padding2.png
  content/authors/terrypha-wamaitha/Avatar.jpeg
Labels: assigned for review, ready for final review, test reviewer assigned

#2948 How to create a REST API using Spring Boot, Maven, and MySQL
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/add-employee.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/check-mysql-for-get-employee.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/check-mysql.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/delete-Employee.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/get-employee.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/get-singe-employee.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/hero.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/index.md
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/intellij-spring-initializer.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/project-structure.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/run-app.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/select-dependencies.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/spring-initializer.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/swagger-ui.png
  content/articles/how-to-create-a-rest-api-using-spring-boot-maven-and-mysql/update-mployee.png
  content/authors/eme-lekwa/avatar.jpg
  content/authors/eme-lekwa/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#2961 Laravel 8 Collections: PHP Arrays On Steroids
  content/articles/laravel-8-collections/collection.png
  content/articles/laravel-8-collections/hero.jpg
  content/articles/laravel-8-collections/index.md
  content/authors/odongo-albert/avatar.jpg
  content/authors/odongo-albert/index.md
Labels: ready for final review, tech tutorial

#2974 Build and Dockerize a Full-stack React app with Node.js, MySQL and Nginx for reverse proxy
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/adminer-db-and-table.png
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/adminer.png
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/docker-container-running.png
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/dockerized-nodejs-server.png
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/dockerized-react-application.png
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/hero.png
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/index.md
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/nodejs-server.png
  content/articles/build-and-dockerize-a-full-stack-react-app-with-nodejs-and-nginx/react-application.png
Labels: assigned for review, ready for final review, tech tutorial

#2990 How to Create a WordPress Functionality Plugin
  content/articles/how-to-create-a-functionality-plugin/hero.jpg
  content/articles/how-to-create-a-functionality-plugin/index.md
  content/articles/how-to-create-a-functionality-plugin/php-file.jpg
  content/articles/how-to-create-a-functionality-plugin/plugin-desc.jpg
  content/articles/how-to-create-a-functionality-plugin/plugin.gif
Labels: assigned for review, ready for final review, test reviewer assigned

#2907 Create a weather app in node.js using openweathermap api
  content/articles/create-a-weather-app-in-node.js-using-openweathermap-api/finalImage.png
  content/articles/create-a-weather-app-in-node.js-using-openweathermap-api/hero.jpg
  content/articles/create-a-weather-app-in-node.js-using-openweathermap-api/index.md
  content/articles/create-a-weather-app-in-node.js-using-openweathermap-api/openweathermap_login.png
  content/articles/create-a-weather-app-in-node.js-using-openweathermap-api/other_api_urls.png
  content/authors/roy-kibet/avatar.jpg
  content/authors/roy-kibet/index.md
  peer_reviewers/front-matter-process.md
Labels: good first article, assigned for review, ready for final review

#2998 How to debug a matlab code
  content/articles/how-to-debug-matlab-code/debug-eight.png
  content/articles/how-to-debug-matlab-code/debug-eleven.png
  content/articles/how-to-debug-matlab-code/debug-five.png
  content/articles/how-to-debug-matlab-code/debug-four.png
  content/articles/how-to-debug-matlab-code/debug-fourteen.png
  content/articles/how-to-debug-matlab-code/debug-nine.png
  content/articles/how-to-debug-matlab-code/debug-one.png
  content/articles/how-to-debug-matlab-code/debug-seven.png
  content/articles/how-to-debug-matlab-code/debug-six.png
  content/articles/how-to-debug-matlab-code/debug-ten.png
  content/articles/how-to-debug-matlab-code/debug-thirteen.png
  content/articles/how-to-debug-matlab-code/debug-three.png
  content/articles/how-to-debug-matlab-code/debug-twelve.png
  content/articles/how-to-debug-matlab-code/debug-two.png
  content/articles/how-to-debug-matlab-code/hero.jpg
  content/articles/how-to-debug-matlab-code/index.md
Labels: assigned for review, ready for final review

#3093 Added peer reviewer details
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#3044 Key Differences Between Kotlin and Java
  content/articles/difference-between-kotlin-and-java/hero.jpg
  content/articles/difference-between-kotlin-and-java/index.md
  content/authors/nehemiah-maina/avatar.jpg
  content/authors/nehemiah-maina/index.md
Labels: good first article, assigned for review, ready for final review

#2985 Java Exception Handling
  content/articles/exception-handling-in-java/hero.jpg
  content/articles/exception-handling-in-java/index.md
Labels: assigned for review, ready for final review

#2986 Graphs in Data structure ( Using C++)
  content/articles/graphs-in-data-structure-using-cplusplus/graph_1.png
  content/articles/graphs-in-data-structure-using-cplusplus/graph_3.JPG
  content/articles/graphs-in-data-structure-using-cplusplus/graph_4.JPG
  content/articles/graphs-in-data-structure-using-cplusplus/graph_5.JPG
  content/articles/graphs-in-data-structure-using-cplusplus/graph_6.JPG
  content/articles/graphs-in-data-structure-using-cplusplus/graph_7.JPG
  content/articles/graphs-in-data-structure-using-cplusplus/graph_8.JPG
  content/articles/graphs-in-data-structure-using-cplusplus/graph__2.JPG
  content/articles/graphs-in-data-structure-using-cplusplus/hero.jpg
  content/articles/graphs-in-data-structure-using-cplusplus/index.md
  content/articles/graphs-in-data-structure-using-cplusplus/output.JPG
Labels: assigned for review, ready for final review, test reviewer assigned

#3052 Network Automation and Automation Tools
  content/articles/network-automation/ani.png
  content/articles/network-automation/chef.png
  content/articles/network-automation/hero.jpg
  content/articles/network-automation/index.md
  content/articles/network-automation/puppet.png
  content/articles/network-automation/salt.png
  content/authors/rabo-james-bature/index.md
Labels: assigned for review, ready for final review

#3055 Run Length Encoding Compression Algorithm in Python
  content/articles/run-length-encoding-algorithm-in-python/hero.jpg
  content/articles/run-length-encoding-algorithm-in-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3113 Setting Up Kali Linux for dual boot
  content/articles/setting-up-kali-linux-for-dual-boot/hero.jpg
  content/articles/setting-up-kali-linux-for-dual-boot/index.md
  content/articles/setting-up-kali-linux-for-dual-boot/login.png
  content/articles/setting-up-kali-linux-for-dual-boot/rufus.png
  content/articles/setting-up-kali-linux-for-dual-boot/shrink.png
  content/authors/francisca-jeruto/avatar.jpg
  content/authors/francisca-jeruto/index.md
Labels: assigned for review, ready for final review, article

#3002 Angular 12 Material Table With Pagination, Filtering, Sorting
  content/articles/angular12-material-table/console.png
  content/articles/angular12-material-table/expanded-console.png
  content/articles/angular12-material-table/hero.jpg
  content/articles/angular12-material-table/index.md
  content/articles/angular12-material-table/material-output.png
  content/articles/angular12-material-table/output.png
  content/authors/benard-ogure/avatar.png
  content/authors/benard-ogure/index.md
Labels: good first article, ready for final review

#3079 An Overview of Docker Container Linking
  content/articles/an-overview-of-docker-container-linking/hero.jpg
  content/articles/an-overview-of-docker-container-linking/index.md
Labels: assigned for review, ready for final review

#3068 Getting started with Localization in Flutter
  content/articles/flutter-localization/deutsch.jpg
  content/articles/flutter-localization/english.jpg
  content/articles/flutter-localization/hero.png
  content/articles/flutter-localization/index.md
  content/articles/flutter-localization/spanish.jpg
Labels: assigned for review, ready for final review

#3086 Sending Notifications with Spring Boot, Angular, and Firebase Cloud Messaging
  content/articles/fcm-with-spring-and-angular/firebase-config.png
  content/articles/fcm-with-spring-and-angular/flow-chart.png
  content/articles/fcm-with-spring-and-angular/hero.jpg
  content/articles/fcm-with-spring-and-angular/index.md
  content/articles/fcm-with-spring-and-angular/notification.png
  content/authors/john-amiscaray/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3084 Assertions and Design By Contract in Java
  content/articles/assertion-and-design-by-contract-in-java/hero.jpg
  content/articles/assertion-and-design-by-contract-in-java/index.md
Labels: assigned for review, ready for final review

#3185 Ml with brainjs
  content/articles/ml-with-brainjs/hero.png
  content/articles/ml-with-brainjs/index.md
  content/authors/jamila-laureen/avatar.jpg
  content/authors/jamila-laureen/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3097 Introductory Guide to Building Tensorflow 2.5.0 from Source
  content/articles/build-tensorflow-from-source/hero.jpg
  content/articles/build-tensorflow-from-source/index.md
  content/articles/build-tensorflow-from-source/tensorflow-bazel-compatibility.png
Labels: assigned for review, ready for final review, tech tutorial

#3348 Updated Pull Request Template
  .github/pull_request_template.md
Labels: documentation

#3022 How to design infinite impulse response filters using Matlab
  content/articles/hero.jpg
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/filter_eight.PNG
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/filter_five.PNG
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/filter_four.PNG
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/filter_one.PNG
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/filter_seven.PNG
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/filter_six.PNG
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/filter_three.PNG
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/filter_two.PNG
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/hero.jpg
  content/articles/how-to-design-infinite-impulse-response-filters-using-matlab/index.md
Labels: ready for final review, tech tutorial

#3029 Federated Learning using TensorFlow Federated (TFF)
  content/articles/federated-learning-using-tensorflow-federated/hero.png
  content/articles/federated-learning-using-tensorflow-federated/index.md
Labels: ready for final review, tech tutorial

#3102 Introduction to java servlets
  content/articles/introduction-to-java-servlets/architecture_of_java_servlets.png
  content/articles/introduction-to-java-servlets/hero.png
  content/articles/introduction-to-java-servlets/index.md
  ubuntu_GUI.png
Labels: assigned for review, ready for final review

#3175 How to create a Machine Learning App using the FastAPI and deploying it to the Kubernetes cluster
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/all-routes.png
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/bar-graph.png
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/first-route.png
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/hero.png
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/index.md
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/kubernetes-dashboard.png
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/main-doc.png
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/making-predictions.png
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/naive_bayes.pkl
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/snip.png
  content/articles/how-to-create-a-machine-learning-app-using-the-fastapi-and-deploying-it-to-the-kubernetes-cluster/ui-dashboard.png
Labels: duplicate, ready for final review

#3301 Implementing dark mode using Tailwind CSS
  content/articles/implementing-dark-mode-using-tailwind-css/blogpage.jpg
  content/articles/implementing-dark-mode-using-tailwind-css/darkpage.jpg
  content/articles/implementing-dark-mode-using-tailwind-css/hero.jpg
  content/articles/implementing-dark-mode-using-tailwind-css/index.md
  content/articles/implementing-dark-mode-using-tailwind-css/npmresult.jpg
  content/articles/implementing-dark-mode-using-tailwind-css/result.gif
  content/articles/implementing-dark-mode-using-tailwind-css/switch1.jpg
  content/articles/implementing-dark-mode-using-tailwind-css/switch2.jpg
  content/articles/implementing-dark-mode-using-tailwind-css/switch3.gif
Labels: assigned for review, ready for final review

#3045 An Introduction to Blockchain Architecture
  content/articles/an-introduction-to-blockchain-architecture/blockchain.png
  content/articles/an-introduction-to-blockchain-architecture/hash.png
  content/articles/an-introduction-to-blockchain-architecture/hero.png
  content/articles/an-introduction-to-blockchain-architecture/index.md
  content/articles/an-introduction-to-blockchain-architecture/p2p.png
Labels: ready for final review

#3127 Managing Docker Containers using the Command Line Interface
  content/articles/managing-docker-containers-using-command-line-interface/hero.png
  content/articles/managing-docker-containers-using-command-line-interface/index.md
  content/authors/ruth-ngonyo/avatar.png
  content/authors/ruth-ngonyo/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#3138 What are White-Hat and Black-Hat SEO Techniques?
  content/articles/white-hat-seo-black-hat-seo/hero.jpg
  content/articles/white-hat-seo-black-hat-seo/index.md
Labels: duplicate, ready for final review, article

#3105 CSS hacks for Web Developers
  content/articles/css-hacks-for-web-developers/hero.png
  content/articles/css-hacks-for-web-developers/index.md
  content/authors/moses-wachiuri/avatar.png
  content/authors/moses-wachiuri/index.md
Labels: good first article, ready for final review

#3168 Unified Embedding for Face Recognition and Clustering Using FaceNet
  content/articles/facenet-a-unified-embedding-for-face-recognition-and-clustering/facenet-model-architecture.png
  content/articles/facenet-a-unified-embedding-for-face-recognition-and-clustering/hero.png
  content/articles/facenet-a-unified-embedding-for-face-recognition-and-clustering/index.md
  content/articles/facenet-a-unified-embedding-for-face-recognition-and-clustering/triplet-loss.png
Labels: ready for final review, article

#3173 Javascript form events
  content/articles/javascript-form-events/hero.png
  content/articles/javascript-form-events/index.md
  content/authors/samuel-zabastian/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3090 Introduction to Docker Swarm in Container Orchestration
  content/articles/introduction-to-docker-swarm-in-container-orchestration/hero.jpg
  content/articles/introduction-to-docker-swarm-in-container-orchestration/index.md
Labels: assigned for review, ready for final review

#3192 Design Patterns in JavaScript
  content/articles/design-patterns-in-javascript/hero.jpg
  content/articles/design-patterns-in-javascript/index.md
Labels: assigned for review, ready for final review

#3204 Maps api in a webpage
  content/articles/maps-api-in-a-webpage/autocomplete.jpg
  content/articles/maps-api-in-a-webpage/direction.jpg
  content/articles/maps-api-in-a-webpage/hero.jpg
  content/articles/maps-api-in-a-webpage/index.md
  content/articles/maps-api-in-a-webpage/project.jpg
Labels: assigned for review, ready for final review, tech tutorial

#3266 How to turn your photo into cartoon using python
  content/articles/how-to-turn-your-photo-into-cartoon-using-python/Deadpool5.PNG
  content/articles/how-to-turn-your-photo-into-cartoon-using-python/deadpool1.PNG
  content/articles/how-to-turn-your-photo-into-cartoon-using-python/deadpool2.PNG
  content/articles/how-to-turn-your-photo-into-cartoon-using-python/deadpool3.PNG
  content/articles/how-to-turn-your-photo-into-cartoon-using-python/deadpool4.PNG
  content/articles/how-to-turn-your-photo-into-cartoon-using-python/hero.jpg
  content/articles/how-to-turn-your-photo-into-cartoon-using-python/index.md
Labels: tech review, ready for final review, test reviewer assigned

#3189 Loading Image with Glide in Android
  content/articles/loading-image-with-glide-in-android/create-project.png
  content/articles/loading-image-with-glide-in-android/glide-demo.gif
  content/articles/loading-image-with-glide-in-android/hero.png
  content/articles/loading-image-with-glide-in-android/index.md
  content/authors/collince-okeyo/avatar.png
  content/authors/collince-okeyo/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3087 Implementing Video Conferencing with ReactJS, NodeJS, and WebRTC
  content/articles/video-conferencing-app-with-react-node/hero.jpg
  content/articles/video-conferencing-app-with-react-node/index.md
  content/authors/samuel-cletus/avatar.jpg
  content/authors/samuel-cletus/index.md
Labels: assigned for review, ready for final review

#3176 What is RabbitMQ? Dockerize a RabbitMQ Instance using Docker Containers
  content/articles/dockerize-a-rabbitmq-instance/binding.png
  content/articles/dockerize-a-rabbitmq-instance/direct-exchange-queue.png
  content/articles/dockerize-a-rabbitmq-instance/hero.png
  content/articles/dockerize-a-rabbitmq-instance/index.md
  content/articles/dockerize-a-rabbitmq-instance/message-not-routed.png
  content/articles/dockerize-a-rabbitmq-instance/message-routed.png
  content/articles/dockerize-a-rabbitmq-instance/message.png
  content/articles/dockerize-a-rabbitmq-instance/publish-a-message.png
  content/articles/dockerize-a-rabbitmq-instance/queue-binding.png
  content/articles/dockerize-a-rabbitmq-instance/rabbimq-direct-exchange.png
  content/articles/dockerize-a-rabbitmq-instance/rabbit-message-exchange.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-components.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-docker-compose.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-docker-container.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-fanout-exchanges.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-header-exchange.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-instance.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-message-broker.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-message-exchange-example.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq-topic-exchange.png
  content/articles/dockerize-a-rabbitmq-instance/rabbitmq.png
  content/articles/dockerize-a-rabbitmq-instance/test-exchange.png
  content/articles/dockerize-a-rabbitmq-instance/test-exchange2.png
Labels: assigned for review, ready for final review

#3229 Cube.js Analytics Guide
  content/articles/mongo-nodejs-cubejs-dashboard/hero.png
  content/articles/mongo-nodejs-cubejs-dashboard/index.md
Labels: ready for final review, tech tutorial

#3429 Peer reviewer areas of expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#3431 Peer reviwer details
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#3434 adding bio-data
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#3457 Minor change to "Assertions and Design by Contract in Java" article
  content/articles/assertion-and-design-by-contract-in-java/index.md
Labels: article update

#3282 Hosting a Webserver Using a Raspberry Pi
  content/articles/hosting-a-webserver-using-a-raspberry-pi/defaultpage.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/downloaddb.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/hero.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/index.md
  content/articles/hosting-a-webserver-using-a-raspberry-pi/installapache.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/installdb.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/installphp.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/puttylogin.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/reboot.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/renaminghost1.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/renaminghost2.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/restartapache.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/serverrenamed.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/sudoaptupdate.png
  content/articles/hosting-a-webserver-using-a-raspberry-pi/terminal.png
  content/authors/eunice-wanjiku/avatar.png
  content/authors/eunice-wanjiku/index.md
Labels: good first article, assigned for review, ready for final review

#3251 Getting experiential on a Quarkus project
  content/articles/getting-experiential-on-a-quarkus-project/Intellij-profiler-stats.png
  content/articles/getting-experiential-on-a-quarkus-project/Intellij-profiler.png
  content/articles/getting-experiential-on-a-quarkus-project/JConsole-Quarkus-resources.png
  content/articles/getting-experiential-on-a-quarkus-project/JConsole-Quarkus.png
  content/articles/getting-experiential-on-a-quarkus-project/JConsole-VM-Summary.png
  content/articles/getting-experiential-on-a-quarkus-project/Quarkus-IntelliJ-start-extensions.png
  content/articles/getting-experiential-on-a-quarkus-project/Quarkus-IntelliJ-start.png
  content/articles/getting-experiential-on-a-quarkus-project/Quarkus-hero.png
  content/articles/getting-experiential-on-a-quarkus-project/Quarkus_efficiency_image.png
  content/articles/getting-experiential-on-a-quarkus-project/VSCode-Quarkus-extension.png
  content/articles/getting-experiential-on-a-quarkus-project/VSCode-Quarkus-start.png
  content/articles/getting-experiential-on-a-quarkus-project/code.quarkus.io.png
  content/articles/getting-experiential-on-a-quarkus-project/dev-terminal.png
  content/articles/getting-experiential-on-a-quarkus-project/dev-ui.png
  content/articles/getting-experiential-on-a-quarkus-project/hero.png
  content/articles/getting-experiential-on-a-quarkus-project/index.md
  content/articles/getting-experiential-on-a-quarkus-project/template.png
  content/articles/getting-experiential-on-a-quarkus-project/vert.x-worker.png
Labels: assigned for review, ready for final review, tech tutorial

#3430 Peer reviewer areas of expertise
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#3265 How to migrate an on-prem application to serverless?
  content/articles/how-to-migrate-an-on-prem-application-to-serverless/facade.jpg
  content/articles/how-to-migrate-an-on-prem-application-to-serverless/hero.jpg
  content/articles/how-to-migrate-an-on-prem-application-to-serverless/index.md
  content/articles/how-to-migrate-an-on-prem-application-to-serverless/job-mgt.jpg
  content/articles/how-to-migrate-an-on-prem-application-to-serverless/new-system.jpg
  content/articles/how-to-migrate-an-on-prem-application-to-serverless/no-toggler.jpg
  content/articles/how-to-migrate-an-on-prem-application-to-serverless/on-prem.jpg
  content/articles/how-to-migrate-an-on-prem-application-to-serverless/toggler.jpg
Labels: assigned for review, ready for final review, article

#3050 Client side validation with react-alert
  content/articles/client-side-validation-with-react-alert/hero.jpg
  content/articles/client-side-validation-with-react-alert/index.md
Labels: ready for final review, test reviewer assigned

#3203 Cryptanalysis of data after a ransomware attack
  content/articles/cryptanalysis-of-data-after-a-ransomware-attack/hero.jpg
  content/articles/cryptanalysis-of-data-after-a-ransomware-attack/index.md
Labels: assigned for review, ready for final review, test reviewer assigned

#3101 Getting started with optimization in Matlab
  content/articles/getting-started-with-optimization-in-matlab/hero.jpg
  content/articles/getting-started-with-optimization-in-matlab/index.md
  content/articles/getting-started-with-optimization-in-matlab/opt1.png
  content/articles/getting-started-with-optimization-in-matlab/opt2.png
  content/articles/getting-started-with-optimization-in-matlab/opt3.png
  content/articles/getting-started-with-optimization-in-matlab/opt4.png
  content/articles/getting-started-with-optimization-in-matlab/opt5.png
  content/articles/getting-started-with-optimization-in-matlab/opt6.png
  content/authors/florence-atieno/avatar.jpg
  content/authors/florence-atieno/index.md
Labels: good first article, assigned for review, ready for final review

#3215 Why should Healthcare industries adopt cloud computing?
  content/articles/healthcare-and-cloud-computing/hero.jpg
  content/articles/healthcare-and-cloud-computing/index.md
Labels: assigned for review, ready for final review

#3245 Integration of ROS with Arduino
  content/articles/integration-of-ros-with-arduino/hero.png
  content/articles/integration-of-ros-with-arduino/index.md
  content/authors/newton-osage/avatar.png
  content/authors/newton-osage/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#3255 Integrating Chart.js in Django
  content/articles/integrating-chart-js-in-django/add-editor.png
  content/articles/integrating-chart-js-in-django/admin.png
  content/articles/integrating-chart-js-in-django/chart.png
  content/articles/integrating-chart-js-in-django/editors.png
  content/articles/integrating-chart-js-in-django/hero.png
  content/articles/integrating-chart-js-in-django/index.md
  content/articles/integrating-chart-js-in-django/login.png
Labels: assigned for review, ready for final review, tech tutorial

#3037 Getting Started With React Query for data fetching
  content/articles/react-query-data-fetching-and-server-state-management/hero.jpg
  content/articles/react-query-data-fetching-and-server-state-management/img-demo1.png
  content/articles/react-query-data-fetching-and-server-state-management/index.md
  content/articles/react-query-data-fetching-and-server-state-management/react-query-post.png
Labels: assigned for review, ready for final review, tech tutorial

#3165 How to implement object oriented programming Matlab
  content/articles/how-to-implement-object-oriented-programming-in-matlab/hero.jpg
  content/articles/how-to-implement-object-oriented-programming-in-matlab/index.md
  content/articles/how-to-implement-object-oriented-programming-in-matlab/oop_five.png
  content/articles/how-to-implement-object-oriented-programming-in-matlab/oop_four.png
  content/articles/how-to-implement-object-oriented-programming-in-matlab/oop_one.png
  content/articles/how-to-implement-object-oriented-programming-in-matlab/oop_three.png
  content/articles/how-to-implement-object-oriented-programming-in-matlab/oop_two.png
  content/authors/collince-odhiambo/avatar.jpg
  content/authors/collince-odhiambo/index.md
Labels: ready for final review, test reviewer assigned

#3212 Communicating between your Django APIs using RAbbitMQ
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Consumer_command.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Consumer_command_for_Quotes.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Likes_quotes_home_page.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Likes_server_command.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Liking_a_quote.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Liking_a_quote_again.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quote_after_liked_at_Quotes.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quote_also_deleted_at_Likes.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quote_also_edited_at_Likes.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quote_created_at_likes.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quote_deleted_at_Quote.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quote_edited_at_Quotes.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quote_user_home_page.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quotes_home_page.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Quotes_server_command.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/RabbitMQ_start_command.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/Termina_quote_created.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/creating_a_quote.png
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/hero.jpeg
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/index.md
  content/articles/Communicating-between-your-Django-Apis-using-RabbitMQ/users_home_page.png
  content/authors/john-kiguru/avatar.jpeg
Labels: ready for final review, test reviewer assigned

#3315 Unsupervised Machine Learning with PyCaret
  content/articles/unsupervised-machine-learning-with-pycaret/cluster_output.png
  content/articles/unsupervised-machine-learning-with-pycaret/dataset.png
  content/articles/unsupervised-machine-learning-with-pycaret/hero.png
  content/articles/unsupervised-machine-learning-with-pycaret/index.md
  content/articles/unsupervised-machine-learning-with-pycaret/map_overlap.png
  content/articles/unsupervised-machine-learning-with-pycaret/output.png
  content/articles/unsupervised-machine-learning-with-pycaret/plotting_points.png
  content/articles/unsupervised-machine-learning-with-pycaret/prediction_outcome.png
  content/articles/unsupervised-machine-learning-with-pycaret/scatter_plot.png
  content/articles/unsupervised-machine-learning-with-pycaret/setup_completed.png
  content/articles/unsupervised-machine-learning-with-pycaret/word_map.png
  content/authors/francis-ndiritu/avatar.png
  content/authors/francis-ndiritu/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3199 Searching and Sorting in Matlab
  content/articles/searching-and-sorting-in-matlab/hero.jpg
  content/articles/searching-and-sorting-in-matlab/index.md
  content/articles/searching-and-sorting-in-matlab/search_four.png
  content/articles/searching-and-sorting-in-matlab/search_one.png
  content/articles/searching-and-sorting-in-matlab/search_three.png
  content/articles/searching-and-sorting-in-matlab/search_two.png
  content/authors/simon-mwaniki/avatar.png
  content/authors/simon-mwaniki/index.md
Labels: ready for final review, test reviewer assigned

#3257 Introduction to C# Collections
  content/articles/c-sharp-collections/hero.jpg
  content/articles/c-sharp-collections/index.md
Labels: ready for final review, tech tutorial

#3115 Build Next.js with MongoDB and Deploy on Vercel
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/add-a-post.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/add-new-post-form.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/create-a-database-user.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/database-update-post.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/fetch-posts.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/free-mongodb-cluster.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/hero.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/index.md
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/mongodb-atlas-remote-connection.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/mongodb-compass-and-atlas-connection.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/mongodb-saved-post.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/nav-bar-and-the-post-card.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/nextjs-app-scafold.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/the-added-post.png
  content/articles/build-nextjs-with-mongodb-and-deploy-on-vercel/welcome-to-nextjs.png
Labels: ready for final review

#3312 How to Get Started with Docker Machine
  content/articles/docker-machine/hero.png
  content/articles/docker-machine/index.md
  content/authors/vincent-oriyo/avatar.png
  content/authors/vincent-oriyo/index.md
Labels: good first article, ready for final review, tech tutorial

#3372 Understanding Cross Site Request Forgery Attacks
  content/articles/cross-site-request-forgery-attack/hero.jpg
  content/articles/cross-site-request-forgery-attack/index.md
Labels: ready for final review, article

#3588 Updated Louise Findlay Bio
  content/authors/louise-findlay/index.md
Labels: author update

#3589 Updating my info
  content/authors/ahmad-mardeni/index.md
Labels: author update

#3359 Dependency injection in flutter
  content/articles/Dependency-injection-in-flutter/hero.jpg
  content/articles/Dependency-injection-in-flutter/index.md
  content/authors/bonface-ndolo/avatar.jpg
  content/authors/bonface-ndolo/index.md
Labels: revisions needed, good first article, tech tutorial

#3046 How to implement Regular Expressions (Regex) with Java
  content/articles/regex-implementation-with-java/hero.png
  content/articles/regex-implementation-with-java/index.md
  content/authors/damilare-jolayemi/avatar.jpg
  content/authors/damilare-jolayemi/index.md
Labels: assigned for review, ready for final review

#3357 Coming Soon Landing Page Using JavaScript Timers
  content/articles/coming-soon-landing-page-using-javascript-timers/hero.png
  content/articles/coming-soon-landing-page-using-javascript-timers/index.md
  content/articles/coming-soon-landing-page-using-javascript-timers/temp01.jpeg
  content/articles/coming-soon-landing-page-using-javascript-timers/temp02.jpeg
  content/articles/coming-soon-landing-page-using-javascript-timers/temp03.jpeg
  content/authors/esther-maina/avatar.png
  content/authors/esther-maina/index.md
Labels: ready for final review, tech tutorial

#3360 Implementation of CI/CD in .NET application Using Shell Executor on Gitlab
  content/articles/implementation-of-ci-and-cd-in-dot-net-application-using-shell-executor/hero.png
  content/articles/implementation-of-ci-and-cd-in-dot-net-application-using-shell-executor/index.md
Labels: assigned for review, ready for final review, tech tutorial

#3329 Getting hands on on a microprofile project
  content/articles/getting-hands-on-a-microprofile-project/Intellij-Microprofile-start.png
  content/articles/getting-hands-on-a-microprofile-project/Intellij-specifications.png
  content/articles/getting-hands-on-a-microprofile-project/Quarkus-TCK.png
  content/articles/getting-hands-on-a-microprofile-project/VSCode-Generate-microprofile-starter-project.png
  content/articles/getting-hands-on-a-microprofile-project/VSCode-microprofile-extensions.png
  content/articles/getting-hands-on-a-microprofile-project/choose-if-to-add-it-to-your-workspace.png
  content/articles/getting-hands-on-a-microprofile-project/hero.png
  content/articles/getting-hands-on-a-microprofile-project/index.md
  content/articles/getting-hands-on-a-microprofile-project/local-openapi-viewer.png
  content/articles/getting-hands-on-a-microprofile-project/microprofile-4.1-specifications-preview.png
  content/articles/getting-hands-on-a-microprofile-project/microprofile-4.1-specifications.png
  content/articles/getting-hands-on-a-microprofile-project/microprofile-initializer-webpage.png
  content/articles/getting-hands-on-a-microprofile-project/microprofile-runtimes.png
  content/articles/getting-hands-on-a-microprofile-project/select-all-microprofile-specifications.png
  content/articles/getting-hands-on-a-microprofile-project/service-a.png
  content/articles/getting-hands-on-a-microprofile-project/some-microprofile-VSCode-extensions.png
  content/articles/getting-hands-on-a-microprofile-project/swagger-editor.png
Labels: assigned for review, ready for final review

#3267 Image Compression using PCA
  content/articles/image-compression-using-PCA/Capture.JPG
  content/articles/image-compression-using-PCA/face1.png
  content/articles/image-compression-using-PCA/face2.png
  content/articles/image-compression-using-PCA/face3.png
  content/articles/image-compression-using-PCA/face5.png
  content/articles/image-compression-using-PCA/face6.png
  content/articles/image-compression-using-PCA/hero.png
  content/articles/image-compression-using-PCA/image.JPG
  content/articles/image-compression-using-PCA/image2.JPG
  content/articles/image-compression-using-PCA/index.md
  content/articles/image-compression-using-PCA/plot-1.png
  content/articles/image-compression-using-PCA/plot-2.JPG
  content/authors/deewakar-chakraborty/avatar.jpg
  content/authors/deewakar-chakraborty/index.md
Labels: good first article, ready for final review

#3361 Creating a React app using Vite
  content/articles/creating-a-react-app-using-vite/app.PNG
  content/articles/creating-a-react-app-using-vite/finalapp.PNG
  content/articles/creating-a-react-app-using-vite/framework.PNG
  content/articles/creating-a-react-app-using-vite/hero.jpg
  content/articles/creating-a-react-app-using-vite/index.md
  content/articles/creating-a-react-app-using-vite/install.PNG
  content/articles/creating-a-react-app-using-vite/installing.PNG
  content/articles/creating-a-react-app-using-vite/main.PNG
  content/articles/creating-a-react-app-using-vite/package.PNG
  content/articles/creating-a-react-app-using-vite/run.PNG
  content/articles/creating-a-react-app-using-vite/variant.PNG
  content/articles/creating-a-react-app-using-vite/viteTut.PNG
  content/articles/creating-a-react-app-using-vite/viteproject.PNG
Labels: assigned for review, ready for final review

#3285 Create a REST API application using Golang and PostgreSQL database #3099
  content/articles/build-a-rest-api-application-using-golang-and-postgresql-database/go-jetbrain.png
  content/articles/build-a-rest-api-application-using-golang-and-postgresql-database/golang-vscode.png
  content/articles/build-a-rest-api-application-using-golang-and-postgresql-database/hero.jpg
  content/articles/build-a-rest-api-application-using-golang-and-postgresql-database/index.md
  content/articles/build-a-rest-api-application-using-golang-and-postgresql-database/jetbrain-survey.png
  content/articles/build-a-rest-api-application-using-golang-and-postgresql-database/stack-overflow-survey.png
Labels: assigned for review, ready for final review, tech tutorial

#3306 Getting Started with Image Preprocessing in python
  content/articles/image-preprocessing-in-python/contrast.JPG
  content/articles/image-preprocessing-in-python/flip.JPG
  content/articles/image-preprocessing-in-python/gray_scale.JPG
  content/articles/image-preprocessing-in-python/hero.jpg
  content/articles/image-preprocessing-in-python/index.md
  content/articles/image-preprocessing-in-python/norm.JPG
  content/articles/image-preprocessing-in-python/plotted_image.JPG
  content/articles/image-preprocessing-in-python/rgb.JPG
  content/articles/image-preprocessing-in-python/rotate.JPG
  content/articles/image-preprocessing-in-python/shift.JPG
Labels: assigned for review, ready for final review
