Repository section-engineering-education/engineering-education, pull requests merged in 2022-07, with the labels that each got.

#7563 Simple blockchain using flutter
  content/articles/developing-simple-blockchain-app-in-flutter/hero.jpg
  content/articles/developing-simple-blockchain-app-in-flutter/index.md
Labels: duplicate, question, white label, ready for final review

#7630 How to Deploy an NFT with Remix IDE and Opensea
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/compile.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/deploy.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/etherscan.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/hero.jpg
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/index.md
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/ipfs.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/listing.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/metamaskprompt.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/nftart.jpeg
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/opensea.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/rinkeby.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/tokenview.png
  content/articles/how-to-deploy-an-nft-with-remix-ide-and-opensea/wallet.png
Labels: assigned for review, white label, ready for final review, tech tutorial

#7579 Java startup detection of missing modules in a module with examples
  content/articles/java-startup-detection-of-missing-modules/class.PNG
  content/articles/java-startup-detection-of-missing-modules/hero.jpg
  content/articles/java-startup-detection-of-missing-modules/index.md
  content/articles/java-startup-detection-of-missing-modules/module.PNG
  content/articles/java-startup-detection-of-missing-modules/package.PNG
  content/articles/java-startup-detection-of-missing-modules/project.PNG
  content/articles/java-startup-detection-of-missing-modules/project2.PNG
  content/articles/java-startup-detection-of-missing-modules/structure.PNG
  content/authors/mercy-chebet/avatar.jpg
  content/authors/mercy-chebet/index.md
Labels: assigned for review, white label, ready for final review, tech tutorial

#7632 Dynamic Programming In Javascript Using Tabulation
  content/articles/dynamic-programming-in-javascript-using-tabulation/hero.jpg
  content/articles/dynamic-programming-in-javascript-using-tabulation/index.md
  content/articles/dynamic-programming-in-javascript-using-tabulation/iteration-visualization.png
  content/articles/dynamic-programming-in-javascript-using-tabulation/iteration.jpeg
  content/articles/dynamic-programming-in-javascript-using-tabulation/iteration1.jpeg
Labels: assigned for review, white label, preliminary revision in progress, tech tutorial

#7644 [Duplicate] Creating User Authentication UI with Compose for Desktop
  content/articles/creating-user-authentication-ui-with-compose-for-desktop/creating-project1.png
  content/articles/creating-user-authentication-ui-with-compose-for-desktop/creating-project2.jpg
  content/articles/creating-user-authentication-ui-with-compose-for-desktop/hero.jpg
  content/articles/creating-user-authentication-ui-with-compose-for-desktop/index.md
  content/articles/creating-user-authentication-ui-with-compose-for-desktop/login-screen.jpg
  content/articles/creating-user-authentication-ui-with-compose-for-desktop/register-screen.jpg
Labels: duplicate, white label, tech review, ready for final review

#7668 Creating a ScratchPad with Jetpack Compose
  content/articles/creating-a-scratch-pad-with-jetpack-compose/demo.gif
  content/articles/creating-a-scratch-pad-with-jetpack-compose/drawing-tool.png
  content/articles/creating-a-scratch-pad-with-jetpack-compose/hero.jpg
  content/articles/creating-a-scratch-pad-with-jetpack-compose/index.md
  content/articles/creating-a-scratch-pad-with-jetpack-compose/main.png
  content/articles/creating-a-scratch-pad-with-jetpack-compose/new-project.png
  content/articles/creating-a-scratch-pad-with-jetpack-compose/path-state.png
Labels: assigned for review, white label, ready for final review, tech tutorial

#7729 adding more testimonials
  content/authors/peter-kayere/index.md
  data/testimonialsData.yml
Labels: documentation, author update

#7669 Routing with React Navigation and Nesting Navigators in React Native
  content/articles/routing-with-react-navigation-and-nesting-navigators-in-react-native/hero.png
  content/articles/routing-with-react-navigation-and-nesting-navigators-in-react-native/index.md
Labels: assigned for review, white label

#7629 A Beginner Guide on How to Solve a System of Linear Equations using Gaussian Elimination Algorithm
  content/articles/gaussian-elimination-in-r/augmented-matrix.png
  content/articles/gaussian-elimination-in-r/equations.png
  content/articles/gaussian-elimination-in-r/hero.jpg
  content/articles/gaussian-elimination-in-r/image-0.png
  content/articles/gaussian-elimination-in-r/image-1.png
  content/articles/gaussian-elimination-in-r/index.md
  content/articles/gaussian-elimination-in-r/matrix-a.png
  content/articles/gaussian-elimination-in-r/matrix-form.png
  content/articles/gaussian-elimination-in-r/matrix.png
  content/articles/gaussian-elimination-in-r/solution.png
  content/articles/gaussian-elimination-in-r/vector-b.png
  content/articles/gaussian-elimination-in-r/vector-x.png
Labels: assigned for review, white label, needs front matter, needs author page

#7635 Getting started with Kernel PCA algorithm in python
  content/articles/kernel-pca-in-python/colormap0.png
  content/articles/kernel-pca-in-python/colormap1.png
  content/articles/kernel-pca-in-python/head.png
  content/articles/kernel-pca-in-python/hero.jpg
  content/articles/kernel-pca-in-python/index.md
Labels: assigned for review, white label, needs author page

#7696 Working with bash arrays
  content/articles/working-with-bash-arrays/hero.png
  content/articles/working-with-bash-arrays/index.md
Labels: white label, ready for final review, test reviewer assigned

#7636 Creating a Simple Denoising App
  content/articles/creating-simple-denoising-app/App-Interface.png
  content/articles/creating-simple-denoising-app/Application.png
  content/articles/creating-simple-denoising-app/AutoGenerated-code.png
  content/articles/creating-simple-denoising-app/Axes.png
  content/articles/creating-simple-denoising-app/Callback-function.png
  content/articles/creating-simple-denoising-app/Components.png
  content/articles/creating-simple-denoising-app/Design.png
  content/articles/creating-simple-denoising-app/Final-design.png
  content/articles/creating-simple-denoising-app/Output-design.png
  content/articles/creating-simple-denoising-app/hero.jpg
  content/articles/creating-simple-denoising-app/index.md
Labels: assigned for review, white label, preliminary revision in progress

#7726 Custom Decorators in Django
  content/articles/custom-decorators-in-django/authdec.gif
  content/articles/custom-decorators-in-django/hero.jpg
  content/articles/custom-decorators-in-django/index.md
  content/articles/custom-decorators-in-django/pipenv.JPG
  content/articles/custom-decorators-in-django/xhrdec.gif
  content/authors/boluwatife-fayemi/avatar.jpg
  content/authors/boluwatife-fayemi/index.md
Labels: tech review, preliminary revision in progress, ready for final review

#7653 [Duplicate of #7617] - Next.js basics with payroll system
  content/articles/building-a-payroll-system-with-nextjs/Image-three.png
  content/articles/building-a-payroll-system-with-nextjs/demo.png
  content/articles/building-a-payroll-system-with-nextjs/folder-structure.png
  content/articles/building-a-payroll-system-with-nextjs/hero.jpg
  content/articles/building-a-payroll-system-with-nextjs/index.md
  content/authors/eli-musa/avatar.jpg
  content/authors/eli-musa/index.md
Labels: duplicate, good first article, white label, ready for final review, needs front matter
