Repository section-engineering-education/engineering-education, pull requests merged in 2022-01, with the labels that each got.

#5475 Building a Vue.js 3 App with JSON Server and Axios
  content/articles/building-vuejs-app-with-json-server-and-axios/hero.jpg
  content/articles/building-vuejs-app-with-json-server-and-axios/index.md
  content/articles/building-vuejs-app-with-json-server-and-axios/shopping-list.png
  content/articles/building-vuejs-app-with-json-server-and-axios/shopping1.png
Labels: assigned for review, ready for final review, test reviewer assigned

#5481 Working with CSV files in Java
  content/articles/working-with-csv-files-in-java/class.png
  content/articles/working-with-csv-files-in-java/createproject.png
  content/articles/working-with-csv-files-in-java/csvdoc.png
  content/articles/working-with-csv-files-in-java/excel-save.png
  content/articles/working-with-csv-files-in-java/externaljars.png
  content/articles/working-with-csv-files-in-java/hero.png
  content/articles/working-with-csv-files-in-java/index.md
  content/articles/working-with-csv-files-in-java/jars.png
  content/articles/working-with-csv-files-in-java/libraries.png
  content/articles/working-with-csv-files-in-java/microsoftexcelcsv.png
  content/articles/working-with-csv-files-in-java/nameclass.png
  content/articles/working-with-csv-files-in-java/notepad-csv.png
  content/articles/working-with-csv-files-in-java/semi-colon-seperated.png
  content/authors/teresia-wambui/avatar.jpeg
  content/authors/teresia-wambui/index.md
Labels: good first article, assigned for review, ready for final review

#5599 How CART is substantial in speech emotion recognition
  content/articles/cart-algorithms-in-speech-emotion-recognition/hero.jpg
  content/articles/cart-algorithms-in-speech-emotion-recognition/index.md
  content/authors/lynn-njoki/avatar.jpg
  content/authors/lynn-njoki/index.md
Labels: duplicate, good first article, ready for final review, article

#5636 [Duplicate of #5311]: How to implement linear time invariant systems analyzer using matlab graphical user interface
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/hero.jpg
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image1.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image10.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image11.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image12.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image13.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image14.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image2.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image3.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image4.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image5.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image6.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image7.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image8.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/image9.png
  content/articles/linear-time-invariant-systems-analyzer-using-matlab/index.md
Labels: duplicate, ready for final review, tech tutorial

#5396 How to set up Svelte with vite, TypeScript and Tailwind CSS
  content/articles/svelte-with-vite-typescript-and-tailwind-css/default-landing-page.PNG
  content/articles/svelte-with-vite-typescript-and-tailwind-css/hero.jpg
  content/articles/svelte-with-vite-typescript-and-tailwind-css/index.md
  content/articles/svelte-with-vite-typescript-and-tailwind-css/new-landing-page.PNG
  content/articles/svelte-with-vite-typescript-and-tailwind-css/our-services-section.png
  content/articles/svelte-with-vite-typescript-and-tailwind-css/our-team-section.png
  content/articles/svelte-with-vite-typescript-and-tailwind-css/svelte.png
  content/articles/svelte-with-vite-typescript-and-tailwind-css/vite.png
Labels: ready for final review, needs front matter, test reviewer assigned

#5516 Continuous Integration and Deployment with Flask, Docker and Github Actions
  content/articles/continuous-integration-and-deployment-of-pipelines-with-flask-docker-and-github-actions/dockerhub.png
  content/articles/continuous-integration-and-deployment-of-pipelines-with-flask-docker-and-github-actions/hero.png
  content/articles/continuous-integration-and-deployment-of-pipelines-with-flask-docker-and-github-actions/index.md
  content/articles/continuous-integration-and-deployment-of-pipelines-with-flask-docker-and-github-actions/package.png
  content/articles/continuous-integration-and-deployment-of-pipelines-with-flask-docker-and-github-actions/publish.png
  content/articles/continuous-integration-and-deployment-of-pipelines-with-flask-docker-and-github-actions/stages.png
Labels: ready for final review

#5670 Building a dictionary application using Twilio API and WhatsApp
  content/articles/twilio-api-whatsapp-spring-boot/hero.png
  content/articles/twilio-api-whatsapp-spring-boot/index.md
  content/articles/twilio-api-whatsapp-spring-boot/sample.png
Labels: assigned for review, ready for final review

#5487 Introducing Threads in Java Socket Programming
  content/articles/threads-in-java-socket-programming/hero.jpg
  content/articles/threads-in-java-socket-programming/index.md
  content/authors/stephen-mutua/avatar.jpg
  content/authors/stephen-mutua/index.md
Labels: duplicate, assigned for review, ready for final review

#5713 [Duplicate of #5490]: In Page Filtered Search With Vanilla JavaScript
  content/articles/in-page-filtered-search-with-vanilla-javascript/hero.jpg
  content/articles/in-page-filtered-search-with-vanilla-javascript/index.md
  content/authors/cecilia-wanjiru-wairimu/avatar.jpg
  content/authors/cecilia-wanjiru-wairimu/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5714 How to create horizontal scrolling menu using jQuery and php
  content/articles/how-to-create-horizontal-scrolling-menu-using-jQuery-and-php/demo1.png
  content/articles/how-to-create-horizontal-scrolling-menu-using-jQuery-and-php/demo2.png
  content/articles/how-to-create-horizontal-scrolling-menu-using-jQuery-and-php/file-structure.png
  content/articles/how-to-create-horizontal-scrolling-menu-using-jQuery-and-php/hero.png
  content/articles/how-to-create-horizontal-scrolling-menu-using-jQuery-and-php/import-menu2.png
  content/articles/how-to-create-horizontal-scrolling-menu-using-jQuery-and-php/index.md
  content/articles/how-to-create-horizontal-scrolling-menu-using-jQuery-and-php/open_in_browser.png
  content/articles/how-to-create-horizontal-scrolling-menu-using-jQuery-and-php/start_xampp.png
  content/authors/benard-njenga/avatar.png
  content/authors/benard-njenga/index.md
Labels: duplicate, good first article, ready for final review, tech tutorial

#5637 price tracker
  content/articles/price-tracker-with-python-selenium-twilio/build-pack.png
  content/articles/price-tracker-with-python-selenium-twilio/hero.jpg
  content/articles/price-tracker-with-python-selenium-twilio/heroku-job.png
  content/articles/price-tracker-with-python-selenium-twilio/heroku-push.png
  content/articles/price-tracker-with-python-selenium-twilio/index.md
  content/articles/price-tracker-with-python-selenium-twilio/install-scheduler.png
  content/articles/price-tracker-with-python-selenium-twilio/scheduler.png
  content/authors/muhammed-ali/index.md
Labels: ready for final review

#5755 Is Ruby on Rails the Answer to Fintech Woes?
  content/articles/ruby-on-rails-and-fintech/hero.jpg
  content/articles/ruby-on-rails-and-fintech/index.md
Labels: ready for final review, article

#5759 [Duplicate] How to generate reports in a SpringBoot App leveraging Jaspersoft
  content/articles/spring-boot-jaspersoft-reports/all-products.png
  content/articles/spring-boot-jaspersoft-reports/data-source.jpg
  content/articles/spring-boot-jaspersoft-reports/final-design.png
  content/articles/spring-boot-jaspersoft-reports/generated-report.png
  content/articles/spring-boot-jaspersoft-reports/hero.jpg
  content/articles/spring-boot-jaspersoft-reports/index.md
  content/articles/spring-boot-jaspersoft-reports/jaspersoft-connector.jpg
  content/articles/spring-boot-jaspersoft-reports/modify-detail-fields.jpg
  content/articles/spring-boot-jaspersoft-reports/products-page.png
  content/articles/spring-boot-jaspersoft-reports/remove-properties.jpg
  content/articles/spring-boot-jaspersoft-reports/report-fields.jpg
  content/articles/spring-boot-jaspersoft-reports/source-file.png
  content/articles/spring-boot-jaspersoft-reports/spring-initializr.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5554 Localization and internationalization in android
  content/articles/localization-and-internationalization-in-android/create_drawable_file.jpg
  content/articles/localization-and-internationalization-in-android/create_string_file.jpg
  content/articles/localization-and-internationalization-in-android/english.png
  content/articles/localization-and-internationalization-in-android/hero.jpg
  content/articles/localization-and-internationalization-in-android/image_files.jpg
  content/articles/localization-and-internationalization-in-android/index.md
  content/articles/localization-and-internationalization-in-android/swahili.png
  content/authors/vivian-odhiambo/avatar.jpg
  content/authors/vivian-odhiambo/index.md
Labels: enhancement

#5677 Creating an Applet with Threads in Java
  content/articles/creating-applet-with-threads/hero.jpg
  content/articles/creating-applet-with-threads/index.md
  content/authors/andrew-odera/avatar.jpg
  content/authors/andrew-odera/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#5550 Turing Test in AI
  content/articles/turing-test-in-ai/hero.jpg
  content/articles/turing-test-in-ai/index.md
  content/authors/emily-rotich/Index.md
  content/authors/emily-rotich/avatar.jpg
Labels: good first article, assigned for review, ready for final review

#5538 Data Entry Support with HTML
  content/articles/data-entry-support-with-html/hero.jpg
  content/articles/data-entry-support-with-html/image1.png
  content/articles/data-entry-support-with-html/image2.png
  content/articles/data-entry-support-with-html/index.md
  content/authors/jacob-omukaga/avatar.jpeg
  content/authors/jacob-omukaga/index.md
Labels: assigned for review, ready for final review, needs front matter, test reviewer assigned

#5608 Building animated sign-in routes with React.js and bootstrap
  content/articles/building-animated-signin-routes-with-react-and-bootstrap/hero.jpg
  content/articles/building-animated-signin-routes-with-react-and-bootstrap/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5544 Using the Android NDK(C++) to create a simple traffic jam path recommender app
  content/articles/android-jni-cpluplus-dijkstra/full-graph.png
  content/articles/android-jni-cpluplus-dijkstra/graph-one.png
  content/articles/android-jni-cpluplus-dijkstra/hero.jpg
  content/articles/android-jni-cpluplus-dijkstra/index.md
  content/articles/android-jni-cpluplus-dijkstra/shot-five.png
  content/articles/android-jni-cpluplus-dijkstra/shot-four.png
  content/articles/android-jni-cpluplus-dijkstra/shot-one.png
  content/articles/android-jni-cpluplus-dijkstra/shot-six.png
  content/articles/android-jni-cpluplus-dijkstra/shot-three.png
  content/articles/android-jni-cpluplus-dijkstra/shot-two.png
Labels: assigned for review, ready for final review, reviewer-tryout

#5635 [Duplicate] Face Geometry Detection using Python
  content/articles/face-geometry-detection-using-python/avatar.png
  content/articles/face-geometry-detection-using-python/hero.png
  content/articles/face-geometry-detection-using-python/image.png
  content/articles/face-geometry-detection-using-python/index.md
Labels: ready for final review, tech tutorial

#5564 Leveraging GPT-Neo to Generate AI-based Blog Content
  content/articles/leveraging-gptneo-to-generate-ai-based-blog-content/blog-generator.png
  content/articles/leveraging-gptneo-to-generate-ai-based-blog-content/hero.png
  content/articles/leveraging-gptneo-to-generate-ai-based-blog-content/index.md
Labels: ready for final review, tech tutorial

#5886 [Machine Learning] Classification of GitHub Issues Using Machine Learning
  content/articles/classification-of-github-issues-using-machine-learning/bug-label.jpg
  content/articles/classification-of-github-issues-using-machine-learning/concatenated-dataset.jpg
  content/articles/classification-of-github-issues-using-machine-learning/dataset-with-labels.jpg
  content/articles/classification-of-github-issues-using-machine-learning/downloaded-dataset.jpg
  content/articles/classification-of-github-issues-using-machine-learning/enhancement-label.jpg
  content/articles/classification-of-github-issues-using-machine-learning/hero.jpg
  content/articles/classification-of-github-issues-using-machine-learning/index.md
  content/articles/classification-of-github-issues-using-machine-learning/loaded-dataset.jpg
  content/articles/classification-of-github-issues-using-machine-learning/model-output.jpg
  content/articles/classification-of-github-issues-using-machine-learning/new-dataset.jpg
  content/articles/classification-of-github-issues-using-machine-learning/question-label.jpg
Labels: assigned for review, ready for final review, tech tutorial

#5624 [Duplicate of #4271] Introduction to hibernate
  content/articles/introduction-to-hibernate/Detailed.jpg
  content/articles/introduction-to-hibernate/hero.png
  content/articles/introduction-to-hibernate/hibernate1.jpg
  content/articles/introduction-to-hibernate/hibernate2.jpg
  content/articles/introduction-to-hibernate/hibernate3.jpg
  content/articles/introduction-to-hibernate/high.jpg
  content/articles/introduction-to-hibernate/index.md
  content/authors/cosmas-morwabe/avatar.jpg
  content/authors/cosmas-morwabe/index.md
Labels: ready for final review, article

#5661 Using Lottie Animations In Flutter
  content/articles/using-lottie-animations-in-flutter/app.gif
  content/articles/using-lottie-animations-in-flutter/hero.jpg
  content/articles/using-lottie-animations-in-flutter/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5626 Understanding machine learning algorithms and how to Implement them
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/euclidian-distance.png
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/hero.png
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/improvement-graph.png
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/index.md
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/linear-regression.png
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/manhattan-distance.png
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/mse-formula.png
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/negative-linear-relationship.png
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/positive-linear-connection.png
  content/articles/understanding-machine-learning-algorithms-and-how-to-implement-them/weighted-distance.png
Labels: ready for final review, tech tutorial, reviewer-tryout

#5656 How to Recover Data from Digital Storage Media using Autopsy
  content/articles/how-to-recover-data-from-digital-storage-media-using-autopsy/create-new-case.jpg
  content/articles/how-to-recover-data-from-digital-storage-media-using-autopsy/data-recovery.jpg
  content/articles/how-to-recover-data-from-digital-storage-media-using-autopsy/data-source.jpg
  content/articles/how-to-recover-data-from-digital-storage-media-using-autopsy/ftk-imaging.jpg
  content/articles/how-to-recover-data-from-digital-storage-media-using-autopsy/hero.jpg
  content/articles/how-to-recover-data-from-digital-storage-media-using-autopsy/index.md
  content/articles/how-to-recover-data-from-digital-storage-media-using-autopsy/new-case-info.jpg
Labels: ready for final review

#5667 Creating a beeware application
  content/articles/creating-an-application-using-beeware/final.png
  content/articles/creating-an-application-using-beeware/hero.png
  content/articles/creating-an-application-using-beeware/index.md
  content/articles/creating-an-application-using-beeware/starter.png
Labels: assigned for review, ready for final review, tech tutorial

#5685 Getting Started with Time Series Decomposition in python
  content/articles/time-series-decomposition-in-python/additive-time-series-decomposition.png
  content/articles/time-series-decomposition-in-python/additive-time-series.png
  content/articles/time-series-decomposition-in-python/fb-stock-data.png
  content/articles/time-series-decomposition-in-python/hero.png
  content/articles/time-series-decomposition-in-python/high-ts.png
  content/articles/time-series-decomposition-in-python/index.md
  content/articles/time-series-decomposition-in-python/multiplicative-time-series-decomposition.png
  content/articles/time-series-decomposition-in-python/multiplicative-time-series.png
  content/articles/time-series-decomposition-in-python/residual.png
  content/articles/time-series-decomposition-in-python/seasonality.png
  content/articles/time-series-decomposition-in-python/time-series-components.png
  content/articles/time-series-decomposition-in-python/trend.png
Labels: assigned for review, ready for final review, tech tutorial

#5948 [Duplicate of #4590] - Factor affecting the performance of dl
  content/articles/factors-to-consider-for-improving-deeplearning-models-performance/display-rate-charts.png
  content/articles/factors-to-consider-for-improving-deeplearning-models-performance/hero.png
  content/articles/factors-to-consider-for-improving-deeplearning-models-performance/index.md
  content/articles/factors-to-consider-for-improving-deeplearning-models-performance/iteration.png
  content/articles/factors-to-consider-for-improving-deeplearning-models-performance/learning-rate-scale.png
  content/authors/kingsley-tom/avatar.jpg
  content/authors/kingsley-tom/index.md
Labels: duplicate, assigned for review, ready for final review, article

#5909 [Duplicate of #5791] - Creating dummy data in python using faker package
  content/articles/creating-dummy-data-in-python-using-faker-package/hero.jpg
  content/articles/creating-dummy-data-in-python-using-faker-package/index.md
  content/articles/creating-dummy-data-in-python-using-faker-package/profile-data.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5632 how-to-create-a-winforms-io-manager-for-removable-drives-in-c#
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/additional-info.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/both-radiobuttons.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/btn-properties.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/configure.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/create-a-new-project.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/form-border-style.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/form1-bgcolor.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/groupbox1.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/hero.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/index.md
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/initial-window.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/label1.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/renaming-form1.jpg
  content/articles/how-to-create-a-winforms-io-manager-for-removable-drives-in-csharp/with-all-buttons.jpg
  content/authors/donel-mwangi/avatar.jpg
  content/authors/donel-mwangi/index.md
Labels: ready for final review

#5684 Implementing Holistic Tracking using Python
  content/articles/implementing-holistic-tracking-using-python/hero.png
  content/articles/implementing-holistic-tracking-using-python/index.md
  content/articles/implementing-holistic-tracking-using-python/output.png
  content/articles/implementing-holistic-tracking-using-python/workout.jpg
Labels: assigned for review, ready for final review, tech tutorial

#5687 [Languages]: Building a Screen Recording Application Using JavaScript
  content/articles/javascript-screen-recorder/demo1.png
  content/articles/javascript-screen-recorder/demo2.png
  content/articles/javascript-screen-recorder/hero.jpg
  content/articles/javascript-screen-recorder/img1.png
  content/articles/javascript-screen-recorder/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5702 Getting Started with Recursive Feature Elimination in Python
  content/articles/recursive-feature-elimination/data-head.png
  content/articles/recursive-feature-elimination/hero.png
  content/articles/recursive-feature-elimination/index.md
  content/articles/recursive-feature-elimination/object-data-types.png
Labels: assigned for review, ready for final review, tech tutorial

#5649 [Duplicate] The Best Frameworks for Developing Decentralized Applications
  content/articles/best-frameworks-for-developing-dapps/hardhat.jpg
  content/articles/best-frameworks-for-developing-dapps/hero.jpg
  content/articles/best-frameworks-for-developing-dapps/index.md
Labels: assigned for review, ready for final review

#6049 Update list-of-software-peer-reviewers.md
  peer_reviewers/list-of-software-peer-reviewers.md
Labels: documentation

#5633 [Machine Learning] How to Implement K fold Cross-Validation in Scikit-Learn
  content/articles/how-to-implement-k-fold-cross-validation/5-fold-cv.jpeg
  content/articles/how-to-implement-k-fold-cross-validation/accuracy-1.png
  content/articles/how-to-implement-k-fold-cross-validation/accuracy-2.png
  content/articles/how-to-implement-k-fold-cross-validation/dataset-preview.png
  content/articles/how-to-implement-k-fold-cross-validation/f1-score-1.png
  content/articles/how-to-implement-k-fold-cross-validation/f1-score-2.png
  content/articles/how-to-implement-k-fold-cross-validation/hero.png
  content/articles/how-to-implement-k-fold-cross-validation/index.md
  content/articles/how-to-implement-k-fold-cross-validation/precision-1.png
  content/articles/how-to-implement-k-fold-cross-validation/precision-2.png
  content/articles/how-to-implement-k-fold-cross-validation/recall-1.png
  content/articles/how-to-implement-k-fold-cross-validation/recall-2.png
Labels: assigned for review, ready for final review, tech tutorial, test reviewer assigned

#5521 Configuring and unconfiguring a dhcp server
  content/articles/configuring-and-unconfiguring-a-dhcp-server/hero.jpg
  content/articles/configuring-and-unconfiguring-a-dhcp-server/index.md
  content/authors/immah-mulwa/avatar.jpg
  content/authors/immah-mulwa/index.md
Labels: assigned for review, ready for final review

#5858 In-Memory Caching In C#
  content/articles/in-memory-caching-in-c-sharp/blazor.png
  content/articles/in-memory-caching-in-c-sharp/classlibrary.jpg
  content/articles/in-memory-caching-in-c-sharp/framework.png
  content/articles/in-memory-caching-in-c-sharp/hero.jpg
  content/articles/in-memory-caching-in-c-sharp/index.md
  content/articles/in-memory-caching-in-c-sharp/name.jpg
  content/articles/in-memory-caching-in-c-sharp/newproject.png
Labels: assigned for review, ready for final review

#5736 Building a Time Series Weather Forecasting Application in Python
  content/articles/building-a-time-series-weather-forecasting-application-in-python/hero.png
  content/articles/building-a-time-series-weather-forecasting-application-in-python/index.md
  content/articles/building-a-time-series-weather-forecasting-application-in-python/plot.png
  content/articles/building-a-time-series-weather-forecasting-application-in-python/visual.png
Labels: assigned for review, ready for final review, tech tutorial

#5651 Why Move from ETL to ELT for your Fintech Products?
  content/articles/etl-to-elt-for-your-fintech-products/hero.png
  content/articles/etl-to-elt-for-your-fintech-products/index.md
  content/authors/jeska-mweni/avatar.jpg
  content/authors/jeska-mweni/index.md
Labels: good first article, ready for final review, article

#5717 Getting Started with Simplex Method in python
  content/articles/simplex-method-in-python/hero.png
  content/articles/simplex-method-in-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5720 [languages] Caching, Logging and Typography in Flutter resolves issue #4523
  content/articles/caching-logging-typography-in-flutter/hero.jpg
  content/articles/caching-logging-typography-in-flutter/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5693 Mocking with JUnit and Mockito- The Why and How
  content/articles/mocking-with-junit-and-mockito-the-why-and-how/assign-bedspace-to-student.png
  content/articles/mocking-with-junit-and-mockito-the-why-and-how/hero.png
  content/articles/mocking-with-junit-and-mockito-the-why-and-how/hostel-management-system-class-diagram.png
  content/articles/mocking-with-junit-and-mockito-the-why-and-how/index.md
  content/articles/mocking-with-junit-and-mockito-the-why-and-how/register-student-activity.png
  content/articles/mocking-with-junit-and-mockito-the-why-and-how/return-names-of-all-students-in-hostel-diagram.png
  content/authors/ehis-edemakhiota/index.md
Labels: ready for final review, tech tutorial, test reviewer assigned

#5753 Creating A Custom Animated Shimmer Effect with Jetpack Compose
  content/articles/creating-custom-animated-shimmer-effect-with-jetpack-compose/create-project-step-one.png
  content/articles/creating-custom-animated-shimmer-effect-with-jetpack-compose/create-project-step-two.png
  content/articles/creating-custom-animated-shimmer-effect-with-jetpack-compose/hero.png
  content/articles/creating-custom-animated-shimmer-effect-with-jetpack-compose/index.md
  content/articles/creating-custom-animated-shimmer-effect-with-jetpack-compose/shimmer-row.png
  content/authors/Kirwa-Elyjah/avatar.png
  content/authors/Kirwa-Elyjah/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5836 How to work with Observables in Angular 12
  content/articles/angular-observables/hero.png
  content/articles/angular-observables/index.md
  content/articles/angular-observables/observer-response.png
  content/articles/angular-observables/project-setup.png
Labels: ready for final review, tech tutorial

#5797 Creating a Flipped Box Card in Android Jetpack Compose
  content/articles/creating-a-flipped-box-card-in-android-jetpack-compose/card-graph.png
  content/articles/creating-a-flipped-box-card-in-android-jetpack-compose/compose-project.png
  content/articles/creating-a-flipped-box-card-in-android-jetpack-compose/demo.png
  content/articles/creating-a-flipped-box-card-in-android-jetpack-compose/empty-proj.png
  content/articles/creating-a-flipped-box-card-in-android-jetpack-compose/hero.jpg
  content/articles/creating-a-flipped-box-card-in-android-jetpack-compose/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5761 [Duplicate of #5511] WPF vs WinForms
  content/articles/wpf-vs-winforms/add-window.png
  content/articles/wpf-vs-winforms/hero.jpg
  content/articles/wpf-vs-winforms/index.md
  content/articles/wpf-vs-winforms/results.png
  content/articles/wpf-vs-winforms/visual-studio.png
  content/articles/wpf-vs-winforms/wpf-add.png
  content/articles/wpf-vs-winforms/wpf-window.png
Labels: ready for final review

#5843 Getting Started with Burp Suite
  content/articles/getting-started-with-burpsuite/burp.png
  content/articles/getting-started-with-burpsuite/burpsuite.png
  content/articles/getting-started-with-burpsuite/database-setup.png
  content/articles/getting-started-with-burpsuite/download.png
  content/articles/getting-started-with-burpsuite/foxyproxy.png
  content/articles/getting-started-with-burpsuite/foxysetup.png
  content/articles/getting-started-with-burpsuite/hero.png
  content/articles/getting-started-with-burpsuite/illustration.png
  content/articles/getting-started-with-burpsuite/index.md
  content/articles/getting-started-with-burpsuite/intercept.png
  content/articles/getting-started-with-burpsuite/login.png
  content/articles/getting-started-with-burpsuite/start-burp.png
  content/articles/getting-started-with-burpsuite/starting.png
  content/articles/getting-started-with-burpsuite/temp-proj.png
  content/articles/getting-started-with-burpsuite/welcome-page.png
Labels: ready for final review, article

#5897 Detecting Malicious URL using Machine Learning
  content/articles/detecting-malicious-url-using-machine-learning/dataset-structure.jpg
  content/articles/detecting-malicious-url-using-machine-learning/dataset-used.jpg
  content/articles/detecting-malicious-url-using-machine-learning/hero.jpg
  content/articles/detecting-malicious-url-using-machine-learning/index.md
  content/articles/detecting-malicious-url-using-machine-learning/model-training.jpg
Labels: ready for final review, tech tutorial

#5773 Why DevSecOps Need Security as Code
  content/articles/why-devsecops-need-security-as-code/hero.jpg
  content/articles/why-devsecops-need-security-as-code/index.md
Labels: ready for final review, article

#5752 Road layout design programmatically using matlab
  content/articles/road-layout-design-programatically-using-matlab/hero.jpg
  content/articles/road-layout-design-programatically-using-matlab/index.md
  content/articles/road-layout-design-programatically-using-matlab/roadlayout-a.png
  content/articles/road-layout-design-programatically-using-matlab/roadlayout-b.png
  content/articles/road-layout-design-programatically-using-matlab/roadlayout-c.png
  content/articles/road-layout-design-programatically-using-matlab/roadlayout-d.png
  content/articles/road-layout-design-programatically-using-matlab/roadlayout-e.png
  content/articles/road-layout-design-programatically-using-matlab/roadlayout-f.png
  content/articles/road-layout-design-programatically-using-matlab/roadlayout-g.png
Labels: ready for final review, needs front matter, test reviewer assigned

#5874 [Duplicate] Multi-Output Classification with Machine Learning
  content/articles/multi-output-classification-with-machine-learning/dataset-image.png
  content/articles/multi-output-classification-with-machine-learning/hero.jpg
  content/articles/multi-output-classification-with-machine-learning/index.md
  content/articles/multi-output-classification-with-machine-learning/loaded-dataset.png
  content/articles/multi-output-classification-with-machine-learning/training-process.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5819 Threads and isolate in flutter
  content/articles/threads-and-isolates-in-flutter/hero.jpg
  content/articles/threads-and-isolates-in-flutter/index.md
  content/authors/waigwa-kanoi/avatar.jpg
  content/authors/waigwa-kanoi/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#5841 Building a Checkout Form With Stripe Elements
  content/articles/building-a-checkout-form-with-stripe-elements/appearance.png
  content/articles/building-a-checkout-form-with-stripe-elements/blazorapp.png
  content/articles/building-a-checkout-form-with-stripe-elements/custom.png
  content/articles/building-a-checkout-form-with-stripe-elements/framework.png
  content/articles/building-a-checkout-form-with-stripe-elements/hero.png
  content/articles/building-a-checkout-form-with-stripe-elements/index.md
  content/articles/building-a-checkout-form-with-stripe-elements/name.png
  content/articles/building-a-checkout-form-with-stripe-elements/selectproject.png
  content/articles/building-a-checkout-form-with-stripe-elements/workflow.png
Labels: assigned for review, ready for final review, tech tutorial, reviewer-tryout

#5901 Working with the superhero API
  content/articles/django-application-and-superhero-api/all-hero.png
  content/articles/django-application-and-superhero-api/hero.png
  content/articles/django-application-and-superhero-api/index.md
  content/articles/django-application-and-superhero-api/single-hero1.png
  content/articles/django-application-and-superhero-api/single-hero2.png
Labels: assigned for review, ready for final review, tech tutorial

#5871 [Duplicate]How to collect update and organize python logs
  content/articles/python-logs/hero.png
  content/articles/python-logs/index.md
  content/authors/moris-wanyiri/avatar.jpg
  content/authors/moris-wanyiri/index.md
Labels: duplicate, ready for final review

#5883 Building vue.js app with django api and axios
  content/articles/build-vue-application-with-django-rest-api-and-axios/final_output.jpg
  content/articles/build-vue-application-with-django-rest-api-and-axios/hero.jpg
  content/articles/build-vue-application-with-django-rest-api-and-axios/index.md
  content/articles/build-vue-application-with-django-rest-api-and-axios/output.jpg
  content/articles/build-vue-application-with-django-rest-api-and-axios/test-output.jpg
  content/articles/build-vue-application-with-django-rest-api-and-axios/vue-output.jpg
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5877 Data representation with react and ant design
  content/articles/data-representation-with-react-and-ant-design/basic-line.png
  content/articles/data-representation-with-react-and-ant-design/hero.jpg
  content/articles/data-representation-with-react-and-ant-design/index.md
  content/articles/data-representation-with-react-and-ant-design/react-app.png
  content/articles/data-representation-with-react-and-ant-design/step-line.png
Labels: ready for final review, tech tutorial

#5888 Implementation of convolution integral of continuous time linear time invariant systems in Matlab
  content/articles/implementation-of-convolution-integral-of-continuous-time-linear-time-invariant-systems-in-matlab/convolution-one.png
  content/articles/implementation-of-convolution-integral-of-continuous-time-linear-time-invariant-systems-in-matlab/convolution-three.png
  content/articles/implementation-of-convolution-integral-of-continuous-time-linear-time-invariant-systems-in-matlab/convolution-two.png
  content/articles/implementation-of-convolution-integral-of-continuous-time-linear-time-invariant-systems-in-matlab/hero.jpg
  content/articles/implementation-of-convolution-integral-of-continuous-time-linear-time-invariant-systems-in-matlab/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5902 Working with Geocoder and GeoJson to build a developer locator application
  content/articles/place-locator-with-geojson/empty-map.png
  content/articles/place-locator-with-geojson/hero.jpg
  content/articles/place-locator-with-geojson/index.md
  content/articles/place-locator-with-geojson/map-with-devs.png
Labels: assigned for review, ready for final review, tech tutorial

#6256 Date
  content/articles/place-locator-with-geojson/index.md
Labels: article update

#5762 Getting Started with Optical Character Recognition
  content/articles/getting-started-with-optical-character-recognition/box.png
  content/articles/getting-started-with-optical-character-recognition/hero.png
  content/articles/getting-started-with-optical-character-recognition/index.md
  content/articles/getting-started-with-optical-character-recognition/multiple-lines.png
Labels: ready for final review, tech tutorial

#6258 Date
  content/articles/getting-started-with-optical-character-recognition/index.md
Labels: article update

#5872 [Duplicate]Neumorphism vs Glassmorphism And Their Implementation Via CSS and HTML
  content/articles/neumorphism-vs-glassmorphism-and-their-implementation-via-css-and-html/glassmorphism.png
  content/articles/neumorphism-vs-glassmorphism-and-their-implementation-via-css-and-html/hero.png
  content/articles/neumorphism-vs-glassmorphism-and-their-implementation-via-css-and-html/index.md
  content/articles/neumorphism-vs-glassmorphism-and-their-implementation-via-css-and-html/neumorphism.png
  content/authors/linchez-maina/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#5914 Building a Password Strength Classifier Model Using Machine Learning
  content/articles/building-a-password-strength-classifier-model-using-machine-learning/dataset-array.jpg
  content/articles/building-a-password-strength-classifier-model-using-machine-learning/dataset-used.jpg
  content/articles/building-a-password-strength-classifier-model-using-machine-learning/hero.jpg
  content/articles/building-a-password-strength-classifier-model-using-machine-learning/index.md
  content/articles/building-a-password-strength-classifier-model-using-machine-learning/loaded-dataset.jpg
  content/articles/building-a-password-strength-classifier-model-using-machine-learning/missing-values.jpg
  content/articles/building-a-password-strength-classifier-model-using-machine-learning/removing-missing-values.jpg
Labels: assigned for review, ready for final review, tech tutorial

#5924 How to build a playlist exporter using Mutagen in Python
  content/articles/playlist-exporter-using-python/hero.jpg
  content/articles/playlist-exporter-using-python/index.md
Labels: ready for final review

#5955 Implementing Africa's Talking SMS API using Node JS
  content/articles/implementing-africa-talking-sms-api-using-nodejs/hero.jpg
  content/articles/implementing-africa-talking-sms-api-using-nodejs/index.md
  content/articles/implementing-africa-talking-sms-api-using-nodejs/message-sent-response.png
  content/articles/implementing-africa-talking-sms-api-using-nodejs/simulator-interface.png
  content/articles/implementing-africa-talking-sms-api-using-nodejs/simulator-new-message.png
Labels: ready for final review, tech tutorial

#5921 Creating image handling and cropping component in React.js
  content/articles/image-handling-and-cropping-component-in-react.js/hero.jpg
  content/articles/image-handling-and-cropping-component-in-react.js/index.md
Labels: assigned for review, ready for final review, tech tutorial

#5845 How to Setup the Glassmorphism Frosty Effect in a React.js App with TypeScript
  content/articles/setup-glassmorphism-effect-in-reactjs-app/form-with-glassmorphism-effect.png
  content/articles/setup-glassmorphism-effect-in-reactjs-app/hero.png
  content/articles/setup-glassmorphism-effect-in-reactjs-app/index.md
  content/articles/setup-glassmorphism-effect-in-reactjs-app/styled-home-page.png
Labels: ready for final review, tech tutorial

#5938 [Duplicate]Adding custom floating action button to bottom navigation bar in android
  content/articles/custom-floating-action-button-to-bottom-navigation-bar-in-android/adding_vectors_asset.jpg
  content/articles/custom-floating-action-button-to-bottom-navigation-bar-in-android/creating_project.jpg
  content/articles/custom-floating-action-button-to-bottom-navigation-bar-in-android/hero.jpg
  content/articles/custom-floating-action-button-to-bottom-navigation-bar-in-android/index.md
  content/articles/custom-floating-action-button-to-bottom-navigation-bar-in-android/ui.jpg
  content/authors/jackline-adhiambo/avatar.jpg
  content/authors/jackline-adhiambo/index.md
Labels: duplicate, ready for final review

#5949 Random joke generator in javaScript: A Complete Gude
  content/articles/random-joke-generator-a-complete-guide/hero.jpg
  content/articles/random-joke-generator-a-complete-guide/index.md
  content/articles/random-joke-generator-a-complete-guide/output-box.png
  content/articles/random-joke-generator-a-complete-guide/output-btn.png
  content/articles/random-joke-generator-a-complete-guide/output-file-arrangement.png
  content/articles/random-joke-generator-a-complete-guide/output-joke-container.png
  content/articles/random-joke-generator-a-complete-guide/output-joke.png
  content/articles/random-joke-generator-a-complete-guide/output-title.png
Labels: assigned for review, ready for final review, tech tutorial

#5920 Overview of Rootkits
  content/articles/overview-of-rootkits/hero.jpg
  content/articles/overview-of-rootkits/index.md
Labels: ready for final review

#5961 How To Build A Search Engine For Reddit With JavaScript
  content/articles/search-engine-for-reddit-with-javascript/empty-search.png
  content/articles/search-engine-for-reddit-with-javascript/final.png
  content/articles/search-engine-for-reddit-with-javascript/hero.jpg
  content/articles/search-engine-for-reddit-with-javascript/index.md
Labels: ready for final review, tech tutorial

#5967 How to Create a URL Shortener with React, Django Rest Framework, and SQLite Database
  content/articles/url-shortener-with-react-django/hero.jpg
  content/articles/url-shortener-with-react-django/index.md
  content/articles/url-shortener-with-react-django/redirectedtosameurl.png
  content/articles/url-shortener-with-react-django/workingApp.png
Labels: assigned for review, ready for final review, tech tutorial

#5878 Creating a Hand Gesture Volume Controller using Python and Pycharm
  content/articles/creating-a-hand-gesture-volume-controller-using-python-and-pycharm/hand.jpg
  content/articles/creating-a-hand-gesture-volume-controller-using-python-and-pycharm/hero.jpg
  content/articles/creating-a-hand-gesture-volume-controller-using-python-and-pycharm/index.md
  content/articles/creating-a-hand-gesture-volume-controller-using-python-and-pycharm/pycharm.png
  content/articles/creating-a-hand-gesture-volume-controller-using-python-and-pycharm/results.gif
  content/articles/creating-a-hand-gesture-volume-controller-using-python-and-pycharm/terminal.png
  content/authors/denis-mwangi/avatar.jpg
  content/authors/denis-mwangi/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#6064 Implementing RSA Encryption And Decryption In Python
  content/articles/rsa-encryption-and-decryption-in-python/hero.jpg
  content/articles/rsa-encryption-and-decryption-in-python/index.md
Labels: assigned for review, ready for final review

#6027 How to set up Prisma Client Server that uses MongoDB as the database
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/console-tasks.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/create-task.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/delete-a-task.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/error.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/free-mongodb-cluster.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/get-tasks.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/hero.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/index.md
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/mongodb-atlas-remote-connection.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/mongodb-compass-and-atlas-connection.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/mongodb-tasks.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/task-api.png
  content/articles/how-to-setup-prisma-client-server-that-uses-mongodb/update-a-task.png
Labels: assigned for review, ready for final review

#6242 Threads and isolate in flutter
  content/authors/waigwa-kanoi/avatar.jpeg
  content/authors/waigwa-kanoi/avatar.jpg
Labels: documentation, enhancement

#5957 Data Visualization with Chartify
  content/articles/data-viz-chartify/chartifydoc.png
  content/articles/data-viz-chartify/chartifyeight.png
  content/articles/data-viz-chartify/chartifyfive.png
  content/articles/data-viz-chartify/chartifyfour.png
  content/articles/data-viz-chartify/chartifyone.png
  content/articles/data-viz-chartify/chartifyseven.png
  content/articles/data-viz-chartify/chartifysix.png
  content/articles/data-viz-chartify/chartifythree.png
  content/articles/data-viz-chartify/chartifytwo.png
  content/articles/data-viz-chartify/errormessage.png
  content/articles/data-viz-chartify/hero.png
  content/articles/data-viz-chartify/index.md
Labels: assigned for review, ready for final review, test reviewer assigned

#6317 Fixed Typo
  content-moderators/plagiarism-check-document.md
  content/articles/how-to-build-a-currency-converter-with-react-and-its-material-ui/index.md
Labels: documentation

#5566 Develop a voice password flutter app
  content/articles/develop-a-voice-password-flutter-app/hero.png
  content/articles/develop-a-voice-password-flutter-app/index.md
  content/authors/john-kanoi/avatar.jpg
  content/authors/john-kanoi/index.md
Labels: ready for final review
