Repository section-engineering-education/engineering-education, pull requests merged in 2022-03, with the labels that each got.

#6539 Getting started with Angular heatmap
  content/articles/heatmap-concepts-in-angular/heatmap-default-page.png
  content/articles/heatmap-concepts-in-angular/heatmap-output.png
  content/articles/heatmap-concepts-in-angular/hero.png
  content/articles/heatmap-concepts-in-angular/index.md
Labels: duplicate, ready for final review

#6729 [Duplicate of #6277] Creating Dashboards in React using React Dashboards
  content/articles/articles/nodejs-vs-python/hero.png
  content/articles/articles/nodejs-vs-python/index.md
  content/articles/creating-dashboards-in-react-using-react-dashboards/hero.jpg
  content/articles/creating-dashboards-in-react-using-react-dashboards/index.md
  content/articles/creating-dashboards-in-react-using-react-dashboards/mamp-interface.jpg
  content/articles/creating-dashboards-in-react-using-react-dashboards/mamp-interface.png
  content/articles/creating-dashboards-in-react-using-react-dashboards/mysql-posts.jpg
  content/articles/creating-dashboards-in-react-using-react-dashboards/mysql-posts.png
  content/articles/creating-dashboards-in-react-using-react-dashboards/post-creation.gif
  content/articles/creating-dashboards-in-react-using-react-dashboards/post-creation.png
  content/articles/creating-dashboards-in-react-using-react-dashboards/react-dashboard-interface.jpg
  content/articles/creating-dashboards-in-react-using-react-dashboards/react-dashboard-interface.png
  content/articles/nodejs-vs-python/index.md
  content/authors/patrick-munyaka/avatar.jpg
  content/authors/patrick-munyaka/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#6889 Fixing author info
  content/authors/briana-nzivu/index.md
Labels: author update

#6888 author-update
  content/articles/algorithmic-trading-bot-using-python/index.md
  content/articles/machine-learning-image-classification-with-javascript-and-nyckel/index.md
  content/authors/kamau-victor/avatar.jpg
  content/authors/kamau-victor/index.md
Labels: author update

#6282 Handling User Authentication in Firebase and Vue.js Applications
  content/articles/firebase-vue-authentication/addnewproject.png
  content/articles/firebase-vue-authentication/authentication.png
  content/articles/firebase-vue-authentication/dashboard.png
  content/articles/firebase-vue-authentication/hero.jpg
  content/articles/firebase-vue-authentication/index.md
  content/articles/firebase-vue-authentication/packagemanager.png
  content/articles/firebase-vue-authentication/preset.png
  content/articles/firebase-vue-authentication/testpic.png
Labels: ready for final review

#6237 Getting started with pragmatic navigation in SwiftUI
  content/articles/swiftui-pragmatic-navigation/hero.png
  content/articles/swiftui-pragmatic-navigation/index.md
Labels: assigned for review, ready for final review

#6750 Is nosql dbms a replacement for relational database management system
  content/articles/nosql-dbms-vs-relational-database-management-system/hero.jpg
  content/articles/nosql-dbms-vs-relational-database-management-system/index.md
Labels: duplicate, ready for final review, article

#6358 [Duplicate of #5899] - How to use Symbolic Math toolbox in Matlab to analyze Fourier series
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/hero.jpg
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/index.md
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-eight.png
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-five.png
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-four.png
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-nine.jpeg
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-one.jpeg
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-seven.png
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-six.png
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-three.png
  content/articles/how-to-use-symbolic-math-toolbox-in-matlab-to-analyze-fourier-series/symbolic-two.jpeg.jpeg
Labels: duplicate, ready for final review, test reviewer assigned

#6586 SSH Tunneling
  content/articles/ssh-tunneling/hero.jpg
  content/articles/ssh-tunneling/index.md
  content/articles/ssh-tunneling/local.jpg
  content/articles/ssh-tunneling/remote.jpg
Labels: assigned for review, ready for final review

#6707 [duplicate of 6106]Understanding fibonacci memoization time complexity in javascript
  content/articles/fibonacci-memoization-time-complexity-in-javascript/calltree.jpeg
  content/articles/fibonacci-memoization-time-complexity-in-javascript/hero.jpg
  content/articles/fibonacci-memoization-time-complexity-in-javascript/index.md
  content/articles/fibonacci-memoization-time-complexity-in-javascript/memoized.jpeg
  content/articles/fibonacci-memoization-time-complexity-in-javascript/returntree.jpeg
Labels: duplicate, ready for final review

#6310 How to split a monolithic architecture into micro-frontends
  content/articles/how-to-split-a-monolithic-architecture-into-micro-frontends/forum-page.png
  content/articles/how-to-split-a-monolithic-architecture-into-micro-frontends/hero.jpg
  content/articles/how-to-split-a-monolithic-architecture-into-micro-frontends/index.md
  content/articles/how-to-split-a-monolithic-architecture-into-micro-frontends/landing-page.png
Labels: revisions needed, assigned for review, tech tutorial

#6632 generating randomness with chainlink vrf using brownie (Python)
  content/articles/generating-randomness-with-chainlink-vrf-using-brownie/hero.jpg
  content/articles/generating-randomness-with-chainlink-vrf-using-brownie/index.md
  content/authors/raphael-ndonga/avatar.jpg
  content/authors/raphael-ndonga/index.md
Labels: ready for final review

#6373 Using C++ to build a model for your Python Machine Learning Project
  content/articles/cpp-model-in-a-python-machine-learning-project/derived.png
  content/articles/cpp-model-in-a-python-machine-learning-project/hero.png
  content/articles/cpp-model-in-a-python-machine-learning-project/index.md
  content/articles/cpp-model-in-a-python-machine-learning-project/log-loss.png
  content/articles/cpp-model-in-a-python-machine-learning-project/sigmoid.png
Labels: ready for final review

#6375 Multi-Class Image Classifier using Deep AutoViML
  content/articles/multi-class-image-classifier-using-deep-autoviml/change-runtime-type.png
  content/articles/multi-class-image-classifier-using-deep-autoviml/digrams.jpg
  content/articles/multi-class-image-classifier-using-deep-autoviml/displayed-images.jpg
  content/articles/multi-class-image-classifier-using-deep-autoviml/gpu.png
  content/articles/multi-class-image-classifier-using-deep-autoviml/hero.jpg
  content/articles/multi-class-image-classifier-using-deep-autoviml/index.md
  content/articles/multi-class-image-classifier-using-deep-autoviml/neural-network.jpg
  content/articles/multi-class-image-classifier-using-deep-autoviml/paper-gesture.jpg
  content/articles/multi-class-image-classifier-using-deep-autoviml/predicted-images.jpg
  content/articles/multi-class-image-classifier-using-deep-autoviml/rock-gesture.jpg
  content/articles/multi-class-image-classifier-using-deep-autoviml/runtime.png
  content/articles/multi-class-image-classifier-using-deep-autoviml/scissors-gesture.jpg
  content/articles/multi-class-image-classifier-using-deep-autoviml/training-process.jpg
  content/authors/simon-ndiritu/avatar.jpg
  content/authors/simon-ndiritu/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6361 Understanding Duck Typing in Python
  content/articles/understanding-duck-typing-in-python/hero.jpg
  content/articles/understanding-duck-typing-in-python/index.md
  content/authors/samuel-irungu/avatar.png
  content/authors/samuel-irungu/index.md
Labels: assigned for review, ready for final review

#6611 Building a blog using react hooks strapi v4.0 and prism
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/collection-type.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/content-body1.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/content-body2.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/content.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/fields.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/hero.jpg
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/homepage.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/index.md
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/new-entry.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/review.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/roles.png
  content/articles/building-a-blog-using-react-hooks-strapi-v4.0-and-prism/strapi-admin.png
Labels: ready for final review, tech tutorial

#6476 How to Produce Colors With RGB LEDs Using Arduino and Matlab Graphical User Interface
  content/articles/how-to-produce-colors-with-rgb-leds/hero.jpg
  content/articles/how-to-produce-colors-with-rgb-leds/index.md
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-eight.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-five.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-four.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-nine.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-one.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-seven.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-six.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-ten.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-three.png
  content/articles/how-to-produce-colors-with-rgb-leds/rgb-two.png
Labels: assigned for review, ready for final review, tech tutorial

#6565 Create a registration form using React.js and connecting it with Firebase
  content/articles/registration-form-react.js-firebase/buttons.png
  content/articles/registration-form-react.js-firebase/datainfirebase.png
  content/articles/registration-form-react.js-firebase/defaultsetting.png
  content/articles/registration-form-react.js-firebase/details.jpg
  content/articles/registration-form-react.js-firebase/finalregistrationform.png
  content/articles/registration-form-react.js-firebase/hero.jpeg
  content/articles/registration-form-react.js-firebase/homepage.png
  content/articles/registration-form-react.js-firebase/index.md
  content/articles/registration-form-react.js-firebase/nameoftheproject.png
  content/articles/registration-form-react.js-firebase/newproject.png
  content/articles/registration-form-react.js-firebase/package.png
  content/articles/registration-form-react.js-firebase/realtime-data.PNG
  content/articles/registration-form-react.js-firebase/realtimedatabase.png
  content/articles/registration-form-react.js-firebase/registertheapp.png
  content/articles/registration-form-react.js-firebase/registration.png
  content/articles/registration-form-react.js-firebase/setting.png
  content/articles/registration-form-react.js-firebase/start.png
  content/authors/anubhav-bansal/index.md
Labels: ready for final review, tech tutorial

#6590 How to Get Started with Kotlin Flows API Zip Operator
  content/articles/kotlin-flow-zip-operator/hero.jpg
  content/articles/kotlin-flow-zip-operator/index.md
  content/articles/kotlin-flow-zip-operator/kotlin-flow-zip-demo.jpg
Labels: ready for final review, tech tutorial

#6521 [Android] Handling Permission Appropriately in Jetpack Compose
  content/articles/permission-handling-in-jetpack-compose/create-project.png
  content/articles/permission-handling-in-jetpack-compose/hero.png
  content/articles/permission-handling-in-jetpack-compose/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6538 A Beginner's Guide to Nonlinear Optimization with Bisection Algorithm
  content/articles/bisection-method-in-python/bisection.png
  content/articles/bisection-method-in-python/hero.jpg
  content/articles/bisection-method-in-python/index.md
  content/articles/bisection-method-in-python/no-iter.png
  content/articles/bisection-method-in-python/plot.png
  content/articles/bisection-method-in-python/polynomial-curve.png
Labels: ready for final review, tech tutorial

#6582 Getting started with TinyDB in Python
  content/articles/getting-started-with-tinydb-in-python/hero.jpg
  content/articles/getting-started-with-tinydb-in-python/index.md
  content/authors/catherine-karimi/avatar.jpg
  content/authors/catherine-karimi/index.md
Labels: good first article, ready for final review, tech tutorial

#6419 [duplicate of #6272]Working with system information in c# windows form application
  content/articles/working-with-system-information-in-c-sharp-windows-form-application/environment.png
  content/articles/working-with-system-information-in-c-sharp-windows-form-application/hero.png
  content/articles/working-with-system-information-in-c-sharp-windows-form-application/index.md
  content/articles/working-with-system-information-in-c-sharp-windows-form-application/managementnamespace.png
  content/authors/kipkopus-samuel/avater.png
  content/authors/kipkopus-samuel/index.md
Labels: ready for final review

#6589 Understanding Collections in python
  content/articles/understanding-collections-in-python/hero.png
  content/articles/understanding-collections-in-python/index.md
  content/authors/leah-wangari/avatar.jpeg
  content/authors/leah-wangari/index.md
Labels: ready for final review

#6546 Tracking of objects using the histogram-based tracker in Matlab
  content/articles/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/hero.jpg
  content/articles/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/index.md
  content/articles/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/tracking-five.png
  content/articles/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/tracking-four.png
  content/articles/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/tracking-one.png
  content/articles/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/tracking-six.png
  content/articles/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/tracking-three.png
  content/articles/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/tracking-two.png
Labels: assigned for review, preliminary revision in progress, ready for final review, tech tutorial

#6457 Reading and processing android sensor data using python with CSV read()
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/hero.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-eight.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-eleven.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-five.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-four.jpeg
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-nine.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-one.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-seven.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-six.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-ten.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-three.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/image-two.png
  content/articles/reading-and-processing-android-sensor-data-using-python-with-csv-read/index.md
  content/authors/joseph-odhiambo/avatar.jpeg
Labels: revisions needed, assigned for review

#6593 Introduction to Prisma with Docker
  content/articles/dockerized-prisma-postgres-api/api-cli.png
  content/articles/dockerized-prisma-postgres-api/docker-cli.png
  content/articles/dockerized-prisma-postgres-api/hero.jpg
  content/articles/dockerized-prisma-postgres-api/index.md
  content/articles/dockerized-prisma-postgres-api/post-api.png
  content/articles/dockerized-prisma-postgres-api/post-response.png
  content/articles/dockerized-prisma-postgres-api/prisma-postgres-api.png
  content/articles/dockerized-prisma-postgres-api/running-api.png
  content/articles/dockerized-prisma-postgres-api/test-route.png
Labels: assigned for review, ready for final review, tech tutorial

#6579 Understanding Control Structures in C#
  content/articles/understanding-control structures-in-csharp/hero.jpg
  content/articles/understanding-control structures-in-csharp/index.md
  content/authors/haron-mutati/avatar.png
  content/authors/haron-mutati/index.md
Labels: ready for final review, tech tutorial

#6689 JavaScript Tools Every Developer Should Know
  content/articles/javascript-tools-every-developer-should-know/hero.jpg
  content/articles/javascript-tools-every-developer-should-know/index.md
Labels: assigned for review, ready for final review, article

#6646 How to use edge histogram descriptor to retrieve images in Matlab
  content/articles/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/edge-four.png
  content/articles/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/edge-one.png
  content/articles/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/edge-three.png
  content/articles/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/edge-two.png
  content/articles/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/hero.jpg
  content/articles/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/index.md
Labels: assigned for review, ready for final review

#6727 Building a web script to generate hand-signed PDF documents using the Signature Pad and jsPDF libraries
  content/articles/generate-pdfs-using-jspdf-signature-pad/generated.png
  content/articles/generate-pdfs-using-jspdf-signature-pad/hero.jpg
  content/articles/generate-pdfs-using-jspdf-signature-pad/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6845 [Duplicate of #6592] - An extensive guide of handling images in Django
  content/articles/an-extensive-guide-on-handling-images-in-django/after.jpg
  content/articles/an-extensive-guide-on-handling-images-in-django/before.jpg
  content/articles/an-extensive-guide-on-handling-images-in-django/display.jpg
  content/articles/an-extensive-guide-on-handling-images-in-django/hero.jpg
  content/articles/an-extensive-guide-on-handling-images-in-django/index.md
  content/articles/an-extensive-guide-on-handling-images-in-django/upload.jpg
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#6475 Getting Started with Eigendecomposition in Python
  content/articles/eigendecomposition-in-python/eigenvalues.png
  content/articles/eigendecomposition-in-python/eigenvectors.png
  content/articles/eigendecomposition-in-python/equation.png
  content/articles/eigendecomposition-in-python/hero.png
  content/articles/eigendecomposition-in-python/image.png
  content/articles/eigendecomposition-in-python/index.md
  content/articles/eigendecomposition-in-python/matrices.png
  content/articles/eigendecomposition-in-python/matrix-1.png
  content/articles/eigendecomposition-in-python/matrix-m.png
  content/articles/eigendecomposition-in-python/nor-eigenvectors.png
Labels: duplicate, ready for final review

#6735 How are Telemedicine Apps Enhancing Urgent Care?
  content/articles/How-are-telemedicine-apps-enhancing-urgent-care/hero.jpg
  content/articles/How-are-telemedicine-apps-enhancing-urgent-care/index.md
  content/authors/ann-purity/avatar.jpg
  content/authors/ann-purity/index.md
Labels: assigned for review, ready for final review, article

#6663 Understanding and Implementing Passwordless SSH
  content/articles/implementing-and-understanding-passwordless-ssh/hero.png
  content/articles/implementing-and-understanding-passwordless-ssh/index.md
Labels: duplicate, assigned for review, ready for final review

#6680 How Robotic Data Automation is Accelerating AIOps Implementations
  content/articles/how-robotic-data-automation-is-accelerating-aiops-implementations/hero.jpg
  content/articles/how-robotic-data-automation-is-accelerating-aiops-implementations/index.md
Labels: ready for final review, article

#6800 Effectiveness of SVM in medical data analytics
  content/articles/effectiveness-of-svm-on-health-asessment/hero.jpg
  content/articles/effectiveness-of-svm-on-health-asessment/index.md
Labels: assigned for review, ready for final review, article

#6612 How to Write a Rust GraphQL Server With MongoDB, Juniper and Actix Web (#6265 duplicate)
  content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/creating-todo-mutation-with-mongodb.png
  content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/getting-todos-mongodb-response.png
  content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/getting-todos-query-with-mongodb.png
  content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/hero.jpg
  content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/index.md
  content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/mock-mutation.png
  content/articles/write-a-rust-graphql-server-with-mongodb-juniper-and-actix-web/mock-query.png
Labels: duplicate, assigned for review, ready for final review

#6628 tutorial completed for flutter speech recognition using alan voice
  content/articles/flutter_speech_recognition_using_alan_voice/account.png
  content/articles/flutter_speech_recognition_using_alan_voice/application.png
  content/articles/flutter_speech_recognition_using_alan_voice/hero.png
  content/articles/flutter_speech_recognition_using_alan_voice/index.md
Labels: ready for final review, tech tutorial

#6868 Build Calendar in React Using React-Calendar Library
  content/articles/build-react-calendar-library/booking-app-demo.png
  content/articles/build-react-calendar-library/customized-react-calendar.png
  content/articles/build-react-calendar-library/hero.jpg
  content/articles/build-react-calendar-library/index.md
  content/articles/build-react-calendar-library/react-application-structure.png
  content/articles/build-react-calendar-library/react-calendar-default.png
Labels: ready for final review, tech tutorial

#6863 Quantum AI
  content/articles/quantum-ai/hero.jpg
  content/articles/quantum-ai/index.md
  content/authors/carlos-kahuru/author.md
  content/authors/carlos-kahuru/avatar.jpeg
Labels: good first article, assigned for review, ready for final review, article

#6760 A Gentle Introduction to Exponential Regression in Python
  content/articles/exponential-regression-in-python/a-value.png
  content/articles/exponential-regression-in-python/data-scatterplot.png
  content/articles/exponential-regression-in-python/data.png
  content/articles/exponential-regression-in-python/expo-model.png
  content/articles/exponential-regression-in-python/hero.jpg
  content/articles/exponential-regression-in-python/index.md
  content/articles/exponential-regression-in-python/table.png
Labels: assigned for review, ready for final review, tech tutorial

#6641 How to Implement Zero-Shot Classification using Python
  content/articles/how-to-implement-zero-shot-classification-using-python/hero.png
  content/articles/how-to-implement-zero-shot-classification-using-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6766 Building a Debt Tracker Application with Python and Fauna
  content/articles/building-a -debt-tracker-application-with-python-and-fauna/create-api-key.png
  content/articles/building-a -debt-tracker-application-with-python-and-fauna/create-collection.png
  content/articles/building-a -debt-tracker-application-with-python-and-fauna/create-database.png
  content/articles/building-a -debt-tracker-application-with-python-and-fauna/create-indexes.png
  content/articles/building-a -debt-tracker-application-with-python-and-fauna/dept-tracker.png
  content/articles/building-a -debt-tracker-application-with-python-and-fauna/hero.jpg
  content/articles/building-a -debt-tracker-application-with-python-and-fauna/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6399 Introduction on How to Perform logging for Go applications
  content/articles/how-to-perform-logging-for-golang-applications/hero.jpg
  content/articles/how-to-perform-logging-for-golang-applications/index.md
  content/articles/how-to-perform-logging-for-golang-applications/server-log.png
Labels: assigned for review, ready for final review, tech tutorial

#6872 Understanding COCO Dataset
  content/articles/understanding-coco-dataset/coco-sample.png
  content/articles/understanding-coco-dataset/hero.jpg
  content/articles/understanding-coco-dataset/index.md
Labels: ready for final review

#6992 The Making of Jetpack Compose Form builder
  content/articles/making-jetpack-form-builder/hero.jpg
  content/articles/making-jetpack-form-builder/index.md
Labels: ready for final review

#7205 Updated UPLOAD_INSTRUCTIONS.md with RSS feed authors parameter
  new_contributors/UPLOAD_INSTRUCTIONS.md
  static/images/meta-image-frontmatter.PNG
  static/images/meta-image-frontmatter.png
Labels: documentation

#6720 Implementing Skeleton Loading In Next.js With Tailwind CSS
  content/articles/skeleton-loading-in-nextjs-with-tailwindcss/article-page-with-skeleton-loading-effect.gif
  content/articles/skeleton-loading-in-nextjs-with-tailwindcss/article-page.png
  content/articles/skeleton-loading-in-nextjs-with-tailwindcss/hero.png
  content/articles/skeleton-loading-in-nextjs-with-tailwindcss/home-page.png
  content/articles/skeleton-loading-in-nextjs-with-tailwindcss/index.md
  content/articles/skeleton-loading-in-nextjs-with-tailwindcss/skeleton-card.gif
  content/articles/skeleton-loading-in-nextjs-with-tailwindcss/skeleton-loading.gif
Labels: assigned for review, ready for final review, tech tutorial

#6675 Univariate Time Series using Facebook Prophet
  content/articles/univariate-time-series-using-facebook-prophet/bivariate-data.png
  content/articles/univariate-time-series-using-facebook-prophet/changed-column-names.jpg
  content/articles/univariate-time-series-using-facebook-prophet/first-five-rows.jpg
  content/articles/univariate-time-series-using-facebook-prophet/first-rows.jpg
  content/articles/univariate-time-series-using-facebook-prophet/hero.jpg
  content/articles/univariate-time-series-using-facebook-prophet/index.md
  content/articles/univariate-time-series-using-facebook-prophet/interactive-line-chart.jpg
  content/articles/univariate-time-series-using-facebook-prophet/last-five-rows.jpg
  content/articles/univariate-time-series-using-facebook-prophet/last-rows.jpg
  content/articles/univariate-time-series-using-facebook-prophet/line-graph.jpg
  content/articles/univariate-time-series-using-facebook-prophet/multivariate-data.png
  content/articles/univariate-time-series-using-facebook-prophet/plot-components.jpg
  content/articles/univariate-time-series-using-facebook-prophet/plot-diagram.jpg
  content/articles/univariate-time-series-using-facebook-prophet/predicted-values-head.jpg
  content/articles/univariate-time-series-using-facebook-prophet/predicted-values-tail.jpg
  content/articles/univariate-time-series-using-facebook-prophet/prediction-values.jpg
  content/articles/univariate-time-series-using-facebook-prophet/seasonality-pattern.png
  content/articles/univariate-time-series-using-facebook-prophet/trends.png
  content/articles/univariate-time-series-using-facebook-prophet/univariate-data.png
  content/articles/univariate-time-series-using-facebook-prophet/y-vs-yhat.jpg
Labels: assigned for review, ready for final review, tech tutorial

#6752 An Introduction to DeFi
  content/articles/an-introduction-to-defi/hero.jpeg
  content/articles/an-introduction-to-defi/index.md
Labels: assigned for review, ready for final review, article

#6826 Time Series Analysis and Forecasting using Auto Time Series
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/actual-vs-forecast.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/bar-graph-2019.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/best-model.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/dataset-info.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/dataset-output.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/electricity-consuption-dataset.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/hero.jpg
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/histogram-of-original-time-series.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/index-column.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/index.md
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/line-graph-2019.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/line-graph.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/original-time-series.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/running-facebook-prophet.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/running-machine-learning-models.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/running-non-seasonal-arima.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/running-seasonal-sarimax.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/running-var-model.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/runningp-pyflux-model.png
  content/articles/time-series-analysis-and-forecasting-using-auto-time-series/time-series-components.png
  content/authors/elisha-njeche/avatar.png
  content/authors/elisha-njeche/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6629 Collapsing action tool bar with android material design in Kotlin
  content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/actual.png
  content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/collapsed.png
  content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/design.png
  content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/hero.jpg
  content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/index.md
  content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/nested.png
  content/articles/collapsing-action-tool-bar-with-android-material-design-in-kotlin/title-bg.png
  content/authors/author/avatar.jpg
  content/authors/david-maish/avatar.jpg
  content/authors/david-maish/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6751 Micro Frontends Using Module Federation In Solid.js
  content/articles/microfrontend-using-module-federation-in-solid-js/count.png
  content/articles/microfrontend-using-module-federation-in-solid-js/hero.png
  content/articles/microfrontend-using-module-federation-in-solid-js/index.md
  content/articles/microfrontend-using-module-federation-in-solid-js/micro-frontend.png
  content/articles/microfrontend-using-module-federation-in-solid-js/react-host.png
  content/articles/microfrontend-using-module-federation-in-solid-js/remote-entry.png
  content/articles/microfrontend-using-module-federation-in-solid-js/the-host.png
  content/articles/microfrontend-using-module-federation-in-solid-js/the-remote.png
  content/authors/oyedele-temitope/index.md
Labels: ready for final review, tech tutorial

#7064 Building and Integrating Spring Interceptors In Java [Duplicate #7025]
  content/articles/building-and-integrating-spring-interceptor-in-java/hero.jpg
  content/articles/building-and-integrating-spring-interceptor-in-java/index.md
Labels: assigned for review, ready for final review

#6486 Building web application with Kotlin and TypeScript
  content/articles/building-web-application-with-kotlin-and-typescript/hero.jpg
  content/articles/building-web-application-with-kotlin-and-typescript/index.md
  content/authors/james-nyamwaro/avatar.jpg
  content/authors/james-nyamwaro/index.md
Labels: duplicate, assigned for review, ready for final review

#6705 Understanding layer 2 blockchain
  content/articles/understanding-layer-2-blockchain/hero.jpg
  content/articles/understanding-layer-2-blockchain/index.md
Labels: ready for final review, article

#6732 Collections in C++
  content/articles/collections-in-c++/hero.png
  content/articles/collections-in-c++/index.md
  content/authors/haron-mutati/index.md
  content/authors/haron-wambua/avatar.jpg
  content/authors/haron-wambua/index.md
Labels: duplicate, good first article, ready for final review, tech tutorial

#6792 Wavelet transform analysis of images using WaveletAnalyzer toolbox in Matlab
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/hero.jpg
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-eight.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-eleven.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-five.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-four.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-fourteen.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-nine.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-one.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-seven.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-six.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-ten.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-thirteen.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-three.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-twelve.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/image-two.png
  content/articles/wavelet-transform-analysis-of-images-using-waveletanalyzer-toolbox-in-matlab/index.md
Labels: assigned for review, ready for final review

#6713 Debugging with Stetho in Android
  content/articles/debugging-with-stetho-in-android/browser.png
  content/articles/debugging-with-stetho-in-android/devtool-result.png
  content/articles/debugging-with-stetho-in-android/devtool.png
  content/articles/debugging-with-stetho-in-android/hero.jpg
  content/articles/debugging-with-stetho-in-android/index.md
  content/articles/debugging-with-stetho-in-android/inspect.png
  content/articles/debugging-with-stetho-in-android/layout.png
  content/articles/debugging-with-stetho-in-android/more-details.png
  content/articles/debugging-with-stetho-in-android/new_project.png
  content/authors/anne-sogoli/avatar.jpg
  content/authors/anne-sogoli/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6765 Building QR Code Scanner User Authentication System in Computer Vision
  content/articles/building-qr-code-authentication-system/auth-output.jpg
  content/articles/building-qr-code-authentication-system/authorised-access.jpg
  content/articles/building-qr-code-authentication-system/barcode-output.jpg
  content/articles/building-qr-code-authentication-system/hero.jpg
  content/articles/building-qr-code-authentication-system/index.md
  content/articles/building-qr-code-authentication-system/qr-structure.jpg
  content/articles/building-qr-code-authentication-system/real-time-qr-output.jpg
Labels: assigned for review, ready for final review, tech tutorial

#7034 Socket Programming In The .NET Framework Using C#
  content/articles/socket-programming-in-the-dotnet-framework-using-csharp/console.png
  content/articles/socket-programming-in-the-dotnet-framework-using-csharp/framework.png
  content/articles/socket-programming-in-the-dotnet-framework-using-csharp/hero.png
  content/articles/socket-programming-in-the-dotnet-framework-using-csharp/index.md
  content/articles/socket-programming-in-the-dotnet-framework-using-csharp/name.png
  content/articles/socket-programming-in-the-dotnet-framework-using-csharp/new.png
Labels: assigned for review, ready for final review

#6990 [Duplicate of #6816] - Optimizing ML Models with Optuna
  content/articles/optimizing-ml-models-with-optuna/hero.jpg
  content/articles/optimizing-ml-models-with-optuna/index.md
  content/articles/optimizing-ml-models-with-optuna/trial.jpg
  content/articles/optimizing-ml-models-with-optuna/visualization.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#7080 [Duplicate #6340] CSRF Protection in PHP
  content/articles/php-csrf-protection/anti-csrf.png
  content/articles/php-csrf-protection/csrf.png
  content/articles/php-csrf-protection/file-structure.png
  content/articles/php-csrf-protection/hero.jpeg
  content/articles/php-csrf-protection/index.md
Labels: assigned for review, preliminary revision in progress, ready for final review

#6768 Next.js Blog using Typescript and Notion API
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/body-section.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/conclusion-section.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/cover-image-change.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/cover-image-changed.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/database-posts.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/hero.jpg
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/image-section.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/index.md
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/list-database-skeleton.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/notion-create-new-integration.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/notion-id.png
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/notion-integration.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/notion-integrations.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/notion-secrets.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/notion-share.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/page-content-section.png
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/page-title-change.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/posts-page.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/prerequisites-section.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/selected-integration.PNG
  content/articles/create-a-nextjs-blog-using-typescript-and-notion-api/single-post-page.PNG
Labels: assigned for review, ready for final review, tech tutorial

#6866 Getting Started With Solidity and Binance Smart Chain
  content/articles/binance-smart-chain-tutorial/check-balance-of.png
  content/articles/binance-smart-chain-tutorial/execfuncs.png
  content/articles/binance-smart-chain-tutorial/hero.png
  content/articles/binance-smart-chain-tutorial/index.md
  content/articles/binance-smart-chain-tutorial/remix.png
  content/authors/esther-wanjira/avatar.jpg
  content/authors/esther-wanjira/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6807 Cookies and Sessions in ASP.NET
  content/articles/cookies-and-sessions-in-asp-dot-net/hero.png
  content/articles/cookies-and-sessions-in-asp-dot-net/index.md
  content/articles/cookies-and-sessions-in-asp-dot-net/step-five-a.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-five.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-four.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-nine-a.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-nine-b.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-nine-c.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-nine-d.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-nine-e.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-one.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-seven.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-three.png
  content/articles/cookies-and-sessions-in-asp-dot-net/step-two.png
Labels: assigned for review, ready for final review, tech tutorial

#6922 Comparing okio's okhttp3 and retrofit in performing network calls
  content/articles/comparing-okios-okhttp3-and-retrofit-in-performing-network-calls/hero.png
  content/articles/comparing-okios-okhttp3-and-retrofit-in-performing-network-calls/index.md
  content/articles/comparing-okios-okhttp3-and-retrofit-in-performing-network-calls/new-project.png
  content/articles/comparing-okios-okhttp3-and-retrofit-in-performing-network-calls/user-interface.png
Labels: assigned for review, ready for final review

#6797 Perfoming Update and Delete Operations on your Spreadsheet files using the Apache POI library in Android
  content/articles/android-excel-apachepoi-crud/hero.jpg
  content/articles/android-excel-apachepoi-crud/index.md
  content/articles/android-excel-apachepoi-crud/shot-five.png
  content/articles/android-excel-apachepoi-crud/shot-four.png
  content/articles/android-excel-apachepoi-crud/shot-one.png
  content/articles/android-excel-apachepoi-crud/shot-six.png
  content/articles/android-excel-apachepoi-crud/shot-three.png
  content/articles/android-excel-apachepoi-crud/shot-two.png
Labels: assigned for review, ready for final review

#6891 Getting Started with Streams in Java
  content/articles/getting-started-with-streams-in-java/hero.png
  content/articles/getting-started-with-streams-in-java/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6825 Getting started with Sanity CMS
  content/articles/getting-started-with-sanity-cms/default-schema.png
  content/articles/getting-started-with-sanity-cms/hero.png
  content/articles/getting-started-with-sanity-cms/import-schema.png
  content/articles/getting-started-with-sanity-cms/index.md
  content/articles/getting-started-with-sanity-cms/sanity-screenshot1.png
  content/articles/getting-started-with-sanity-cms/sanity-screenshot2.png
  content/articles/getting-started-with-sanity-cms/terminal.png
  content/articles/getting-started-with-sanity-cms/userSchema.png
Labels: assigned for review, ready for final review, tech tutorial

#6858 Building a simple keyboard using Anvil
  content/articles/building-a-simple-keyboard-using-anvil/blankpanel-webpage.png
  content/articles/building-a-simple-keyboard-using-anvil/design-code.png
  content/articles/building-a-simple-keyboard-using-anvil/hero.png
  content/articles/building-a-simple-keyboard-using-anvil/index.md
  content/articles/building-a-simple-keyboard-using-anvil/main-webpage.png
  content/articles/building-a-simple-keyboard-using-anvil/simple-keyboard.png
  content/articles/building-a-simple-keyboard-using-anvil/styling.jpg
Labels: assigned for review, ready for final review, tech tutorial

#6907 Deep CNN in Python using TensorFlow & Keras for Face Mask Detection
  content/articles/implementing-deep-cnn-in-python/deep-eight.png
  content/articles/implementing-deep-cnn-in-python/deep-five.png
  content/articles/implementing-deep-cnn-in-python/deep-four.png
  content/articles/implementing-deep-cnn-in-python/deep-one.png
  content/articles/implementing-deep-cnn-in-python/deep-seven.png
  content/articles/implementing-deep-cnn-in-python/deep-six.png
  content/articles/implementing-deep-cnn-in-python/deep-three.png
  content/articles/implementing-deep-cnn-in-python/deep-two.png
  content/articles/implementing-deep-cnn-in-python/hero.jpg
  content/articles/implementing-deep-cnn-in-python/index.md
Labels: assigned for review, ready for final review, tech tutorial
