Repository section-engineering-education/engineering-education, pull requests merged in 2022-04, with the labels that each got.

#6864 Building a Multi-class Text Classification model using H2O and Sckit-learn
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/change-runtime-type.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/company-output.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/dataset-output.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/final-model.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/gpu-option.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/h2o-clusters.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/hero.jpg
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/index.md
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/listed-models.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/model-training.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/new-dataset.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/pre-defined-complaints-classes.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/prediction-output.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/renamed-column.png
  content/articles/building-a-multi-class-text-classification-model-using-h2o-and-sckit-learn/runtime.png
Labels: assigned for review, ready for final review, tech tutorial

#7436 Testing Author Feeds
  content/authors/louise-findlay/index.md
  layouts/authors/rss.xml
Labels: feature request

#6757 Wavelet transform analysis of 1-D signals using python
  content/articles/wavelet-transform-analysis-of-1d-signals-using-python/hero.jpg
  content/articles/wavelet-transform-analysis-of-1d-signals-using-python/index.md
  content/articles/wavelet-transform-analysis-of-1d-signals-using-python/wavelet-one.png
  content/articles/wavelet-transform-analysis-of-1d-signals-using-python/wavelet-three.png
  content/articles/wavelet-transform-analysis-of-1d-signals-using-python/wavelet-two.png
Labels: assigned for review, ready for final review, tech tutorial

#7346 [Duplicate of #6755] Introduction to unity engine
  content/articles/introduction-to-unity-engine/allcar.png
  content/articles/introduction-to-unity-engine/allscenes.png
  content/articles/introduction-to-unity-engine/carbody_1.png
  content/articles/introduction-to-unity-engine/cube.png
  content/articles/introduction-to-unity-engine/hero.jpg
  content/articles/introduction-to-unity-engine/hierarchy1.png
  content/articles/introduction-to-unity-engine/index.md
  content/articles/introduction-to-unity-engine/inspector.png
  content/articles/introduction-to-unity-engine/newproject.png
  content/articles/introduction-to-unity-engine/scene1.png
  content/articles/introduction-to-unity-engine/upperbody.png
  content/articles/introduction-to-unity-engine/webgl.png
  content/articles/introduction-to-unity-engine/wheel1.png
Labels: duplicate, ready for final review, tech tutorial

#7118 Prefilling Room Database with JSON Data in Android
  content/articles/prefilling-room-database-with-json-data-in-android/demo.jpeg
  content/articles/prefilling-room-database-with-json-data-in-android/hero.png
  content/articles/prefilling-room-database-with-json-data-in-android/index.md
  content/articles/prefilling-room-database-with-json-data-in-android/json.png
  content/articles/prefilling-room-database-with-json-data-in-android/new-project.png
Labels: assigned for review, ready for final review, tech tutorial

#6895 [Duplicate of #6380] Azure Devops API Development
  content/articles/azure-devops-api-development/artefact.jpg
  content/articles/azure-devops-api-development/ci-build.jpg
  content/articles/azure-devops-api-development/creating-app-service.jpg
  content/articles/azure-devops-api-development/display-name.jpg
  content/articles/azure-devops-api-development/file-rename.jpg
  content/articles/azure-devops-api-development/geme-of-life.jpg
  content/articles/azure-devops-api-development/hero.jpg
  content/articles/azure-devops-api-development/index.md
  content/articles/azure-devops-api-development/intro.jpg
  content/articles/azure-devops-api-development/new-project.jpg
  content/articles/azure-devops-api-development/overview.jpg
  content/articles/azure-devops-api-development/releases.jpg
  content/articles/azure-devops-api-development/repo.jpg
  content/articles/azure-devops-api-development/resource-group.jpg
  content/articles/azure-devops-api-development/service-connections.jpg
  content/articles/azure-devops-api-development/service-principal.jpg
  content/articles/azure-devops-api-development/settings-keys.jpg
  content/articles/azure-devops-api-development/tasks.jpg
  content/articles/azure-devops-api-development/triggers.jpg
Labels: duplicate, ready for final review

#6964 Qiskit for Quantum Computing
  content/articles/qiskit-for-quantum-computing/circuit.png
  content/articles/qiskit-for-quantum-computing/entanglement.png
  content/articles/qiskit-for-quantum-computing/final-circuit.png
  content/articles/qiskit-for-quantum-computing/hero.png
  content/articles/qiskit-for-quantum-computing/histogram.png
  content/articles/qiskit-for-quantum-computing/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6966 How to Build A Swipe Application with React and MongoDB
  content/articles/react-swipe-application/hero.png
  content/articles/react-swipe-application/index.md
Labels: ready for final review, tech tutorial

#6965 An Overview of Swin Transformer
  content/articles/an-overview-of-swin-transformer/hero.png
  content/articles/an-overview-of-swin-transformer/index.md
  content/articles/an-overview-of-swin-transformer/swin-transformer.png
Labels: assigned for review, ready for final review, tech tutorial

#6984 Understanding Blockchains Interoperability via Cosmos Network
  content/articles/understanding-blockchains-interoperability-via-cosmos-network/hero.jpg
  content/articles/understanding-blockchains-interoperability-via-cosmos-network/index.md
Labels: assigned for review, ready for final review, article

#7041 Submitting Data to a Google Form in Android
  content/articles/submitting-data-to-a-google-form-in-android/blank-form.png
  content/articles/submitting-data-to-a-google-form-in-android/define-questions.png
  content/articles/submitting-data-to-a-google-form-in-android/demo.gif
  content/articles/submitting-data-to-a-google-form-in-android/final-form.png
  content/articles/submitting-data-to-a-google-form-in-android/form-response.png
  content/articles/submitting-data-to-a-google-form-in-android/hero.jpg
  content/articles/submitting-data-to-a-google-form-in-android/index.md
  content/articles/submitting-data-to-a-google-form-in-android/new-project.png
  content/articles/submitting-data-to-a-google-form-in-android/pre-filled-link.png
  content/articles/submitting-data-to-a-google-form-in-android/ui.png
  content/authors/calvin-ombati/avatar.jpg
  content/authors/calvin-ombati/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6973 Building a Multiclass image classification model using MobileNet-V2 and TensorFlow
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/another-prediction.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/beans-info.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/cnn-architecture.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/dataset-snip.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/hero.jpg
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/index.md
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/model-architecture.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/neural-network-training.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/number-of-layers.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/printed-output.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/test-results.png
  content/articles/building-a-multiclass-image-classifier-using-mobilenet-v2-and-tensorflow/train-images.png
  content/authors/kelivin-nganga/avatar.jpg
  content/authors/kelivin-nganga/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6971 Understanding wavelet properties and the application of these properties
  content/articles/understanding-wavelet-properties/db6-wavelet.png
  content/articles/understanding-wavelet-properties/haar-wavelet.png
  content/articles/understanding-wavelet-properties/hero.jpg
  content/articles/understanding-wavelet-properties/index.md
  content/articles/understanding-wavelet-properties/sym4-filter.png
  content/articles/understanding-wavelet-properties/sym4-wavelet.png
  content/articles/understanding-wavelet-properties/usa-gdp.png
  content/articles/understanding-wavelet-properties/wavelet-classification.png
  content/articles/understanding-wavelet-properties/wavelet-decomposition.png
  content/articles/understanding-wavelet-properties/wavelet-oscillation.png
  content/articles/understanding-wavelet-properties/wavelet-regularity.png
  content/articles/understanding-wavelet-properties/wavelet-symetry.png
  content/authors/simon-mwaniki/avatar.jpg
  content/authors/simon-mwaniki/avatar.png
Labels: assigned for review, preliminary revision in progress, ready for final review

#7143 [Languages] Quick Response code crash course using Angular 12
  content/articles/angular-crash-course-qr-code/hero.png
  content/articles/angular-crash-course-qr-code/index.md
  content/articles/angular-crash-course-qr-code/output.png
  content/articles/angular-crash-course-qr-code/qr-code.png
Labels: ready for final review, tech tutorial

#6970 App layout design programmatically using Matlab
  content/articles/app-layout-programmatically-using-matlab/applayout-a.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-b.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-c.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-d.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-e.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-f.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-g.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-h.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-i.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-j.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-k.jpg
  content/articles/app-layout-programmatically-using-matlab/applayout-l.jpg
  content/articles/app-layout-programmatically-using-matlab/hero.jpg
  content/articles/app-layout-programmatically-using-matlab/index.md
Labels: assigned for review, ready for final review, tech tutorial

#7061 How to embed a Compose for Desktop application in a Swing-based application
  content/articles/how-to-embed-compose-desktop-application-to-swing-based-application/compose-for-desktop-output.png
  content/articles/how-to-embed-compose-desktop-application-to-swing-based-application/compose-swing-output-2.png
  content/articles/how-to-embed-compose-desktop-application-to-swing-based-application/compose-swing-output.png
  content/articles/how-to-embed-compose-desktop-application-to-swing-based-application/create-compose-desktop-project-step1.png
  content/articles/how-to-embed-compose-desktop-application-to-swing-based-application/create-compose-desktop-project-step2.png
  content/articles/how-to-embed-compose-desktop-application-to-swing-based-application/hero.png
  content/articles/how-to-embed-compose-desktop-application-to-swing-based-application/index.md
  content/articles/how-to-embed-compose-desktop-application-to-swing-based-application/swing-app-output.png
Labels: assigned for review, ready for final review, tech tutorial

#7008 Understanding Cloud-Based Data Architectures
  content/articles/understanding-cloud-based-data-architectures/hero.jpg
  content/articles/understanding-cloud-based-data-architectures/index.md
  content/authors/verah-ombui/avatar.jpg
Labels: assigned for review, ready for final review

#7019 How to Create ERC20 Tokens and Transact using Brownie (Python)
  content/articles/erc20-tokens-and-transact-using-brownie-python/hero.jpg
  content/articles/erc20-tokens-and-transact-using-brownie-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6974 [Article Update] Getting Started with Simplex Method in Python
  content/articles/simplex-method-in-python/arrays.png
  content/articles/simplex-method-in-python/equaiton1.png
  content/articles/simplex-method-in-python/equaiton2.png
  content/articles/simplex-method-in-python/equaiton3.png
  content/articles/simplex-method-in-python/equation4.png
  content/articles/simplex-method-in-python/index.md
  content/articles/simplex-method-in-python/optimize.png
  content/articles/simplex-method-in-python/optimize2.png
  content/articles/simplex-method-in-python/problem.png
  content/articles/simplex-method-in-python/table1.png
  content/articles/simplex-method-in-python/table2.png
  content/articles/simplex-method-in-python/table3.png
  content/articles/simplex-method-in-python/table4.png
  content/articles/simplex-method-in-python/table5.png
  content/articles/simplex-method-in-python/table6.png
Labels: article update

#6819 Implementing Android Jetpack Preferences
  content/articles/implementing-android-jetpack-preferences/hero.png
  content/articles/implementing-android-jetpack-preferences/index.md
  content/authors/mercy-nyakio/avatar.jpeg
  content/authors/mercy-nyakio/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6739 Creating file management application using winforms
  content/articles/creating-file-management-application-using-winforms/changing-the-name-of-the-form.jpg
  content/articles/creating-file-management-application-using-winforms/complete-file-manager.jpg
  content/articles/creating-file-management-application-using-winforms/configuring-the-project.jpg
  content/articles/creating-file-management-application-using-winforms/create-a-new-project.jpg
  content/articles/creating-file-management-application-using-winforms/create-write-read-delete-operations.jpg
  content/articles/creating-file-management-application-using-winforms/files-browsing-controls.jpg
  content/articles/creating-file-management-application-using-winforms/hero.jpg
  content/articles/creating-file-management-application-using-winforms/index.md
  content/articles/creating-file-management-application-using-winforms/the-start-button.jpg
  content/articles/creating-file-management-application-using-winforms/working-file-manager.jpg
  content/authors/sir-maina/avatar.jpg
  content/authors/sir-maina/index.md
Labels: duplicate, good first article, ready for final review, tech tutorial

#7535 Added Similar Articles Section
  assets/scss/components/_all.scss
  assets/scss/components/_card.scss
  layouts/articles/single.html
Labels: CCC - Community Contributed Code

#7572 Fix build error by removing new lines in the middle of template actions.
  layouts/articles/single.html
Labels: Bug

#7102 Understanding daemons in Linux using Node.js
  content/articles/understanding-daemons-in-linux-using-nodejs/hero.png
  content/articles/understanding-daemons-in-linux-using-nodejs/index.md
  content/authors/ghali-muga/avatar.jpg
  content/authors/ghali-muga/index.md
Labels: good first article, ready for final review

#7149 [Duplicate of #6847] - Wand library in python
  content/articles/introduction-to-wand-library-in-python/blurred_image.png
  content/articles/introduction-to-wand-library-in-python/draw_image.png
  content/articles/introduction-to-wand-library-in-python/hero.png
  content/articles/introduction-to-wand-library-in-python/index.md
  content/articles/introduction-to-wand-library-in-python/inverted_image.png
  content/articles/introduction-to-wand-library-in-python/original_image.png
  content/articles/introduction-to-wand-library-in-python/pillow.png
  content/authors/ezra-mukono/avatar.jpg
  content/authors/ezra-mukono/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, tech tutorial

#7262 Creating Chatbot Using Natural Language Processing in Python
  content/articles/creating-chatbot-using-natural-language-processing-in-python/hero.jpg
  content/articles/creating-chatbot-using-natural-language-processing-in-python/index.md
  content/articles/creating-chatbot-using-natural-language-processing-in-python/result.png
  content/articles/creating-chatbot-using-natural-language-processing-in-python/summary.png
Labels: assigned for review, ready for final review, tech tutorial

#6894 Replacing Espresso with Kakao in Writing Automated UI Tests
  content/articles/writing-automated-ui-tests-with-kakao-in-android/hero.jpg
  content/articles/writing-automated-ui-tests-with-kakao-in-android/index.md
  content/articles/writing-automated-ui-tests-with-kakao-in-android/layout-main.png
  content/articles/writing-automated-ui-tests-with-kakao-in-android/layout-register.png
  content/articles/writing-automated-ui-tests-with-kakao-in-android/layout-search.png
  content/articles/writing-automated-ui-tests-with-kakao-in-android/test-pass.png
Labels: assigned for review, ready for final review, tech tutorial

#7148 Data visualization in React JS using Apex Charts
  content/articles/data-visualization-in-react-using-apexcharts/charts.png
  content/articles/data-visualization-in-react-using-apexcharts/folder-structure.png
  content/articles/data-visualization-in-react-using-apexcharts/hero.jpg
  content/articles/data-visualization-in-react-using-apexcharts/index.md
  content/authors/stephanie-opala/avatar.jpg
  content/authors/stephanie-opala/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#7152 Introduction to Frequent Itemset Mining with Python
  content/articles/introduction-to-frequent-itemset-mining-with-python/apriori.png
  content/articles/introduction-to-frequent-itemset-mining-with-python/dataset.png
  content/articles/introduction-to-frequent-itemset-mining-with-python/encoding.png
  content/articles/introduction-to-frequent-itemset-mining-with-python/hero.jpg
  content/articles/introduction-to-frequent-itemset-mining-with-python/importing.png
  content/articles/introduction-to-frequent-itemset-mining-with-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#7171 [Duplicate of #6946] Building a Video Cataloging App with React, Firebase, and React-styled-components.
  content/articles/building-a-video-cataloging-app-with-react-firebase-and-styled-components/hero.jpg
  content/articles/building-a-video-cataloging-app-with-react-firebase-and-styled-components/image1.jpg
  content/articles/building-a-video-cataloging-app-with-react-firebase-and-styled-components/image2.jpg
  content/articles/building-a-video-cataloging-app-with-react-firebase-and-styled-components/image3.jpg
  content/articles/building-a-video-cataloging-app-with-react-firebase-and-styled-components/image4.jpg
  content/articles/building-a-video-cataloging-app-with-react-firebase-and-styled-components/index.md
Labels: duplicate, ready for final review

#6989 Anomaly Detection Model on Time Series data using Isolation Forest
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/aggregated-dataset.png
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/anomalous-datapoints.png
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/detailed-line-chart.png
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/first-line-chart.png
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/hero.jpg
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/index.md
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/new-columns.png
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/ploty-express-diagram.png
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/second-line-chart.png
  content/articles/anomaly-detection-model-on-time-series-data-using-isolation-forest/taxi-dataset.png
  content/authors/collins-kirui/avatar.jpg
  content/authors/collins-kirui/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#7206 Implement Multitenancy with Multiple Databases in Django
  content/articles/implement-multitenancy-with-multiple-databases-in-django/accra.jpg
  content/articles/implement-multitenancy-with-multiple-databases-in-django/default.jpg
  content/articles/implement-multitenancy-with-multiple-databases-in-django/hero.png
  content/articles/implement-multitenancy-with-multiple-databases-in-django/index.jpg
  content/articles/implement-multitenancy-with-multiple-databases-in-django/index.md
  content/articles/implement-multitenancy-with-multiple-databases-in-django/nairobi.jpg
Labels: assigned for review, ready for final review, tech tutorial

#7073 Create a Python App that Extracts images, Scan For text Info, Transcribe and save to a .txt file
  content/articles/extract-text-from-images-using-pytesseract/hero.jpg
  content/articles/extract-text-from-images-using-pytesseract/index.md
  content/articles/extract-text-from-images-using-pytesseract/tesseract.jpg
Labels: assigned for review, ready for final review, needs plagiarism check, tech tutorial

#7594 Fixed Author RSS Feed Conflict
  config/_default/config.toml
  layouts/authors/category.terms.html
  layouts/authors/term.html
Labels: feature request

#6975 Building a Webpage UI with Compose Web
  content/articles/building-a-webpage-ui-with-compose-web/build-gradle-kts-first.png
  content/articles/building-a-webpage-ui-with-compose-web/build-gradle-kts-second.png
  content/articles/building-a-webpage-ui-with-compose-web/create-project.png
  content/articles/building-a-webpage-ui-with-compose-web/hero.png
  content/articles/building-a-webpage-ui-with-compose-web/index.md
  content/articles/building-a-webpage-ui-with-compose-web/run-project.png
  content/articles/building-a-webpage-ui-with-compose-web/settings-gradle-kts.png
Labels: assigned for review, ready for final review, tech tutorial

#7309 Generating Random Datasets With Trumania
  content/articles/generating-random-datasets-with-trumania/hero.jpg
  content/articles/generating-random-datasets-with-trumania/index.md
Labels: assigned for review, ready for final review

#7595 Added Author RSS Feed Docs Back In
  new_contributors/UPLOAD_INSTRUCTIONS.md
  static/images/meta-image-frontmatter.PNG
  static/images/meta-image-frontmatter.png
Labels: documentation

#7229 Building a Time scheduled communication micro-service using Node.js
  content/articles/time-scheduled-communication-microservice/hero.jpg
  content/articles/time-scheduled-communication-microservice/index.md
Labels: ready for final review

#7165 Unit Testing with Vue-test-utils
  content/articles/unit-testing-with-vue-test-utils/hero.png
  content/articles/unit-testing-with-vue-test-utils/index.md
  content/authors/mercy-bassey/avatar.png
  content/authors/mercy-bassey/index.md
Labels: ready for final review, tech tutorial

#7136 How to Develop and Deploy Fast Applications with Vite JS
  content/articles/develop-and-deploy-fast-apps-with-vite-js/dist.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/hero.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/index.md
  content/articles/develop-and-deploy-fast-apps-with-vite-js/installed-dependencies.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/instructions.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/markdown-copy.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/markdown-it.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/npm-run.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/output.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/package-json.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/preview.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/project-name.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/vanilla-js.jpg
  content/articles/develop-and-deploy-fast-apps-with-vite-js/vite-project.jpg
Labels: assigned for review, ready for final review

#7204 Serialization in C++
  content/articles/serialization-in-cplusplus/hero.png
  content/articles/serialization-in-cplusplus/index.md
  content/authors/sarah-wambui/avatar.jpg
  content/authors/sarah-wambui/index.md
Labels: assigned for review, ready for final review

#7217 How to Implement Drag and Drop File Upload in Next.js
  content/articles/nextjs-dnd-file-upload/drag-n-drop-final-app.png
  content/articles/nextjs-dnd-file-upload/dropzone.png
  content/articles/nextjs-dnd-file-upload/hero.png
  content/articles/nextjs-dnd-file-upload/index.md
Labels: assigned for review, ready for final review

#7223 Building a custom user reviews page with stars rating in react, typescript and Bootstrap library
  content/articles/building-a-custom-user-reviews-page-in-react-typescript-and-reactstrap/full-page.jpg
  content/articles/building-a-custom-user-reviews-page-in-react-typescript-and-reactstrap/hero.jpg
  content/articles/building-a-custom-user-reviews-page-in-react-typescript-and-reactstrap/index.md
  content/authors/richard-john/avatar.jpg
  content/authors/richard-john/index.md
Labels: assigned for review, ready for final review

#7133 How Blockchain is Making IoT Smarter
  content/articles/how-blockchain-is-making-iot-smarter/hero.jpg
  content/articles/how-blockchain-is-making-iot-smarter/index.md
Labels: duplicate, assigned for review, ready for final review

#7267 Image colorization using AI and Python
  content/articles/image-colorization-using-ai-and-python/colored-nairobi-railway-station.png
  content/articles/image-colorization-using-ai-and-python/colored-norfolk-hotel.png
  content/articles/image-colorization-using-ai-and-python/hero.png
  content/articles/image-colorization-using-ai-and-python/index.md
  content/articles/image-colorization-using-ai-and-python/kicc.jpg
  content/articles/image-colorization-using-ai-and-python/nairobi-railway-station.jpg
  content/articles/image-colorization-using-ai-and-python/new-colored-stanley-hotel.png
  content/articles/image-colorization-using-ai-and-python/new-kicc.png
  content/articles/image-colorization-using-ai-and-python/new-stanley-hotel.jpg
  content/articles/image-colorization-using-ai-and-python/norfolk-hotel.jpg
Labels: assigned for review, ready for final review, tech tutorial

#7137 Build your first Spark web application
  content/articles/build-your-first-spark-web-application/add-dependency.png
  content/articles/build-your-first-spark-web-application/final-application.png
  content/articles/build-your-first-spark-web-application/hello-world.png
  content/articles/build-your-first-spark-web-application/hero.jpg
  content/articles/build-your-first-spark-web-application/images.png
  content/articles/build-your-first-spark-web-application/index.md
  content/articles/build-your-first-spark-web-application/letter.png
  content/articles/build-your-first-spark-web-application/maven.png
  content/articles/build-your-first-spark-web-application/projectsetup.png
Labels: assigned for review, ready for final review

#7326 How to request runtime application permissions using Dexter- Kotlin
  content/articles/how-to-request-runtime-application-permissions-using-dexter-kotlin/hero.jpg
  content/articles/how-to-request-runtime-application-permissions-using-dexter-kotlin/index.md
  content/authors/janet-kabura/avatar.jpg
  content/authors/janet-kabura/index.md
Labels: ready for final review, tech tutorial

#7170 Storing Custom Types with Custom TypeConverter in Room Database
  content/articles/storing-custom-types-with-custom-type-converter-in-room-database/hero.jpg
  content/articles/storing-custom-types-with-custom-type-converter-in-room-database/index.md
Labels: assigned for review, ready for final review, tech tutorial

#7523 Building a text summarizer with SBERT and Flask
  content/articles/summarize-text-using-sbert-and-flask/hero.jpg
  content/articles/summarize-text-using-sbert-and-flask/index.md
  content/articles/summarize-text-using-sbert-and-flask/result.png
  content/articles/summarize-text-using-sbert-and-flask/summarized.png
  content/articles/summarize-text-using-sbert-and-flask/terminal.png
  content/articles/summarize-text-using-sbert-and-flask/text.png
Labels: assigned for review, ready for final review, tech tutorial

#7266 Ipay mpesa stk push api using python
  content/articles/ipay-mpesa-stk-push-api-using-python/hero.jpeg
  content/articles/ipay-mpesa-stk-push-api-using-python/index.md
  content/articles/ipay-mpesa-stk-push-api-using-python/mpesa-confirm.png
  content/articles/ipay-mpesa-stk-push-api-using-python/prompt.jpeg
Labels: assigned for review, ready for final review, tech tutorial

#7142 Handling missing data: understanding predictive mean matching and regression modelling in R
  content/articles/predictive-mean-matching/hero.jpg
  content/articles/predictive-mean-matching/index.md
  content/articles/predictive-mean-matching/mdpairs-screenshot.PNG
  content/articles/predictive-mean-matching/nhanes-dataset.PNG
  content/articles/predictive-mean-matching/r-pbox-plotting.png
  content/articles/predictive-mean-matching/r-plot2.png
  content/articles/predictive-mean-matching/summary.PNG
  content/authors/valentine-omondi/avatar.png
  content/authors/valentine-omondi/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#7316 [Duplicate #6567] How to build a snake game in javaScript
  content/articles/how-to-build-a-snake-game-with-javascript/apple.PNG
  content/articles/how-to-build-a-snake-game-with-javascript/canvasblank.PNG
  content/articles/how-to-build-a-snake-game-with-javascript/gameoverText.PNG
  content/articles/how-to-build-a-snake-game-with-javascript/hero.PNG
  content/articles/how-to-build-a-snake-game-with-javascript/index.md
  content/articles/how-to-build-a-snake-game-with-javascript/orangesnake.PNG
  content/articles/how-to-build-a-snake-game-with-javascript/score.PNG
  content/articles/how-to-build-a-snake-game-with-javascript/stopexecution.PNG
Labels: duplicate, ready for final review, tech tutorial

#7270 [Duplicate of #7011] - How to Setup and run Applications using TypeScript with Aurelia.js
  content/articles/setup-and-run-applications-using-typescript-with-aureliajs/aurelia-app.png
  content/articles/setup-and-run-applications-using-typescript-with-aureliajs/aurelia-typescript.jpg
  content/articles/setup-and-run-applications-using-typescript-with-aureliajs/hero.png
  content/articles/setup-and-run-applications-using-typescript-with-aureliajs/index.md
  content/articles/setup-and-run-applications-using-typescript-with-aureliajs/test-app.jpg
  content/articles/setup-and-run-applications-using-typescript-with-aureliajs/todo-app.jpg
  content/articles/setup-and-run-applications-using-typescript-with-aureliajs/todo-list.jpg
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#7324 Why do you Need An Event-Driven Architecture for Your IoT Projects?
  content/articles/event-driven-architecture-for-iot-projects/hero.jpg
  content/articles/event-driven-architecture-for-iot-projects/index.md
Labels: ready for final review, article
