Repository section-engineering-education/engineering-education, pull requests merged in 2022-05, with the labels that each got.

#7332 Is Golang the Best Fit for embedded systems?
  content/articles/is-golang-the-best-fit-for-embedded-systems/hero.jpg
  content/articles/is-golang-the-best-fit-for-embedded-systems/index.md
  content/articles/is-golang-the-best-fit-for-embedded-systems/most-wanted-languages.png
Labels: ready for final review, article

#7306 Automating Excel Sheet in Python
  content/articles/automating-excel-sheet-in-python/data.png
  content/articles/automating-excel-sheet-in-python/hero.png
  content/articles/automating-excel-sheet-in-python/index.md
  content/articles/automating-excel-sheet-in-python/maxmin.png
  content/articles/automating-excel-sheet-in-python/output.png
  content/articles/automating-excel-sheet-in-python/pivot.png
Labels: assigned for review, ready for final review

#7350 Getting started with Unit Testing with Spring Boot
  content/articles/getting-started-with-unit-testing-with-spring-boot/hero.png
  content/articles/getting-started-with-unit-testing-with-spring-boot/index.md
  content/articles/getting-started-with-unit-testing-with-spring-boot/output.png
  content/articles/getting-started-with-unit-testing-with-spring-boot/spring-initializer-dependency.png
  content/articles/getting-started-with-unit-testing-with-spring-boot/spring-initializer.png
  content/articles/getting-started-with-unit-testing-with-spring-boot/testing.png
Labels: assigned for review, ready for final review

#7318 Natural language processing using TensorFlow and Bert Model
  content/articles/natural-language-processing-using-tensorflow-and-bert-model/dataset-batch.png
  content/articles/natural-language-processing-using-tensorflow-and-bert-model/hero.png
  content/articles/natural-language-processing-using-tensorflow-and-bert-model/index.md
  content/articles/natural-language-processing-using-tensorflow-and-bert-model/model-summary.png
  content/articles/natural-language-processing-using-tensorflow-and-bert-model/movie-review-dataset.png
  content/articles/natural-language-processing-using-tensorflow-and-bert-model/neural-network-output.png
  content/articles/natural-language-processing-using-tensorflow-and-bert-model/prompt-to-input.png
Labels: assigned for review, ready for final review, tech tutorial

#7314 Creating a Hunt the Wumpus game using Python, Flask, and Socketio
  content/articles/creating-a-simple-hunt-the-wumpus-game-using-python-flask-and-socketio/game-round.png
  content/articles/creating-a-simple-hunt-the-wumpus-game-using-python-flask-and-socketio/game-screen.png
  content/articles/creating-a-simple-hunt-the-wumpus-game-using-python-flask-and-socketio/hello-world-page.png
  content/articles/creating-a-simple-hunt-the-wumpus-game-using-python-flask-and-socketio/hero.jpg
  content/articles/creating-a-simple-hunt-the-wumpus-game-using-python-flask-and-socketio/index.md
  content/articles/creating-a-simple-hunt-the-wumpus-game-using-python-flask-and-socketio/ready-index-page.png
Labels: assigned for review, ready for final review, tech tutorial

#7352 Can Multi-Chain DeFi Protocols replace Legacy Finance?
  content/articles/can-multi-chain-defi-protocols-replace-legacy-finance/hero.jpg
  content/articles/can-multi-chain-defi-protocols-replace-legacy-finance/index.md
Labels: assigned for review, ready for final review, article

#7358 Visualizing Time Series Data With Chart.Js
  content/articles/visualize-time-series-data-with-chart-js/bar-chart.jpg
  content/articles/visualize-time-series-data-with-chart-js/bucket.jpg
  content/articles/visualize-time-series-data-with-chart-js/cd.jpg
  content/articles/visualize-time-series-data-with-chart-js/extract-influxdb.jpg
  content/articles/visualize-time-series-data-with-chart-js/hero.jpg
  content/articles/visualize-time-series-data-with-chart-js/index.md
  content/articles/visualize-time-series-data-with-chart-js/influxdb-cloud.jpg
  content/articles/visualize-time-series-data-with-chart-js/influxdb.jpg
  content/articles/visualize-time-series-data-with-chart-js/line-chart.jpg
  content/articles/visualize-time-series-data-with-chart-js/load-data.jpg
  content/articles/visualize-time-series-data-with-chart-js/start-influxdb.jpg
  content/articles/visualize-time-series-data-with-chart-js/visualize-data.png
Labels: assigned for review, ready for final review, tech tutorial

#7222 A REST API built with Golang without any frameworks, only using the native modules
  content/articles/how-to-build-a-rest-api-with-golang-using-native-modules/hero.png
  content/articles/how-to-build-a-rest-api-with-golang-using-native-modules/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#7340 Implementations of Dependency Injection in C#
  content/articles/implementation-of-dependency-injection-in-csharp/hero.png
  content/articles/implementation-of-dependency-injection-in-csharp/index.md
Labels: assigned for review, ready for final review

#7417 Building an image classification model with Gradio and Keras
  content/articles/building-an-image-classification-model-with-gradio-and-keras/classification-output.png
  content/articles/building-an-image-classification-model-with-gradio-and-keras/cnn-output.png
  content/articles/building-an-image-classification-model-with-gradio-and-keras/flower-classes.png
  content/articles/building-an-image-classification-model-with-gradio-and-keras/hero.jpg
  content/articles/building-an-image-classification-model-with-gradio-and-keras/index.md
  content/articles/building-an-image-classification-model-with-gradio-and-keras/launched-gradio-ui.png
  content/articles/building-an-image-classification-model-with-gradio-and-keras/rose-image.png
  content/articles/building-an-image-classification-model-with-gradio-and-keras/training-set-function.png
  content/articles/building-an-image-classification-model-with-gradio-and-keras/uploaded-image.png
  content/articles/building-an-image-classification-model-with-gradio-and-keras/validation-set-function.png
Labels: assigned for review, ready for final review

#7347 Design and comparative performance analysis of P, I, D, PI, PD, and PID controllers in Matlab
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/Controller-connection.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/I-controllerPerformance.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/P-controller.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/P-controllerPerformance.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/PD-controllerPerformance.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/PI-controllerPerformance.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/PID-controllerPerformance.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/comparison-response.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/controller.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/hero.jpg
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/index.md
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/parameters.png
  content/articles/design-and-comparative-analysis-of-controllers-in-matlab/step-response.png
Labels: assigned for review, preliminary revision in progress, ready for final review

#7491 Understanding Shared Memory Programming With Pthreads and OpenMP
  content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/hero.png
  content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/index.md
  content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/procedure.png
  content/articles/understanding-shared-memory-programming-with-pthreads-and-openmp/system-architecture.png
Labels: duplicate, assigned for review, ready for final review

#7648 adding authors md file with headshot
  content/authors/rajendra-prasad-p/avatar.jpg
  content/authors/rajendra-prasad-p/index.md
Labels: enged-profile

#7263 [Duplicate] Data synchronization and backup management in Networking
  content/articles/data-synchronization-and-backup-management-in-networking/hero.jpg
  content/articles/data-synchronization-and-backup-management-in-networking/index.md
  content/authors/gladwel-kieya/avatar.jpg
  content/authors/gladwel-kieya/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, article

#6909 How to secure php resource with http authentication
  content/articles/how-to-secure-php-resource-with-http-authentication/hero.jpeg
  content/articles/how-to-secure-php-resource-with-http-authentication/index.md
  content/authors/joseph-mwathi/avatar.jpg
  content/authors/joseph-mwathi/index.md
Labels: duplicate, good first article, ready for final review, tech tutorial

#7494 Using Edge Computing to handle Content Migration
  content/articles/using-edge-computing-to-handle-content-migration/edge-compute.png
  content/articles/using-edge-computing-to-handle-content-migration/hero.png
  content/articles/using-edge-computing-to-handle-content-migration/index.md
  content/articles/using-edge-computing-to-handle-content-migration/latency.png
  content/authors/ephraim-njoroge/avatar.jpg
  content/authors/ephraim-njoroge/index.md
Labels: assigned for review, ready for final review

#7286 Univariate Time Series Analysis and Forecasting with ARIMA/SARIMA
  content/articles/univariate-time-series-analysis-with-arima-in-python/acf-plot.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/adf-test-results.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/arima-line-chart.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/datetime-columns.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/dropping-rows.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/first-five.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/hero.jpg
  content/articles/univariate-time-series-analysis-with-arima-in-python/index-column.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/index.md
  content/articles/univariate-time-series-analysis-with-arima-in-python/last-five.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/monthly-sales-line-chart.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/new-dataset-plot.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/pacf-plot.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/renamed-columns.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/sarima-line-chart.png
  content/articles/univariate-time-series-analysis-with-arima-in-python/testing-again.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#7631 Linux services: a step-by-step guide to creating a personal cloud server
  content/articles/step-by-step-guide-to-creating-a-personal-linux-cloud-server/hero.jpg
  content/articles/step-by-step-guide-to-creating-a-personal-linux-cloud-server/index.md
Labels: assigned for review, white label, preliminary revision in progress, needs front matter

#7274 How to Build Templates for Django Applications with HTMX
  content/articles/django-htmx/hero.jpg
  content/articles/django-htmx/index.md
  content/articles/django-htmx/output.png
Labels: assigned for review, ready for final review, article

#7243 Getting Started with Boruta Algorithm in Machine Learning
  content/articles/getting-started-with-boruta-algorithm/boruta.png
  content/articles/getting-started-with-boruta-algorithm/data.png
  content/articles/getting-started-with-boruta-algorithm/hero.png
  content/articles/getting-started-with-boruta-algorithm/index.md
  content/articles/getting-started-with-boruta-algorithm/marged.png
  content/articles/getting-started-with-boruta-algorithm/shandow.png
Labels: assigned for review, ready for final review, tech tutorial

#7396 Creating and manipulating word(.docx) documents in android using Kotlin and the Apache POI library
  content/articles/creating-and-manipulating-word-documents-in-android-using-kotlin/hero.jpg
  content/articles/creating-and-manipulating-word-documents-in-android-using-kotlin/index.md
  content/articles/creating-and-manipulating-word-documents-in-android-using-kotlin/screen.png
  content/articles/creating-and-manipulating-word-documents-in-android-using-kotlin/shot-conc.png
  content/articles/creating-and-manipulating-word-documents-in-android-using-kotlin/shot-doc.png
  content/authors/sandra-moringa/avatar.jpeg
Labels: assigned for review, ready for final review

#7256 Understanding the Downsides of Smart Contracts in Blockchain
  content/articles/understanding-the-downsides-of-smart-contracts-in-blockchain/hero.jpg
  content/articles/understanding-the-downsides-of-smart-contracts-in-blockchain/index.md
Labels: assigned for review, ready for final review, article

#7290 Simple Swap: A Machine Learning Framework for Swapping Faces
  content/articles/simple-swap-for-swapping-faces/6.jpg
  content/articles/simple-swap-for-swapping-faces/ds.jpg
  content/articles/simple-swap-for-swapping-faces/hero.png
  content/articles/simple-swap-for-swapping-faces/index.md
  content/articles/simple-swap-for-swapping-faces/result.jpg
Labels: assigned for review, ready for final review, tech tutorial

#7317 Managing Work Queues With Beanstalk and Supervisor on Ubuntu 20.04 with Laravel 8
  content/articles/managing-queues-beanstalkd/active.png
  content/articles/managing-queues-beanstalkd/hero.png
  content/articles/managing-queues-beanstalkd/index.md
  content/authors/roselyne-odero/avatar.jpeg
  content/authors/roselyne-odero/index.md
Labels: good first article, ready for final review, tech tutorial

#7597 How To Load Test Django Applications With Locust
  content/articles/how-to-test-django-applications-with-locust/all_endpoints_test_table.png
  content/articles/how-to-test-django-applications-with-locust/five_users_test_chart.png
  content/articles/how-to-test-django-applications-with-locust/five_users_test_chart2.png
  content/articles/how-to-test-django-applications-with-locust/five_users_test_graph.png
  content/articles/how-to-test-django-applications-with-locust/hero.jpg
  content/articles/how-to-test-django-applications-with-locust/index.md
  content/articles/how-to-test-django-applications-with-locust/locust_homepage.png
  content/articles/how-to-test-django-applications-with-locust/locust_response.png
  content/articles/how-to-test-django-applications-with-locust/two_fifty_users_chart.png
  content/authors/kolapo-olamidun/avatar.jpg
  content/authors/kolapo-olamidun/index.md
Labels: assigned for review, preliminary revision in progress, needs front matter

#7189 How to Send Code and Verify Email using Tuya API
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/baseUrl.jpg
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/configuration_wizard.png
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/create_cloud_project.png
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/email_services.png
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/frontend.png
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/hero.jpg
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/index.md
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/project_configuration.png
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/verification-code.png
  content/articles/how-to-send-code-and-verify-email-using-tuya-api/verified-email.jpeg
  content/authors/jedidah-mwangi/avatar.jpeg
Labels: assigned for review, ready for final review

#7342 Using Imbalanced-Learn to handle imbalanced text data in Natural Language Processing
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/applied-integer-values.png
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/applied-new-column-names.png
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/array.png
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/data-samples-count.png
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/data-samples.png
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/hero.jpeg
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/index.md
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/new-length-column.png
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/null-values.png
  content/articles/using-imbalanced-learn-to-handle-imbalanced-text-data/rechecking-lengths.png
  content/authors/donnex-wafula/avatar.jpg
  content/authors/donnex-wafula/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#7395 [Duplicate #6677] Automating Job Schedule with Django-Cron in Python Application
  content/articles/automating-jobs-schedule-with-django-cron-in-python/admin.png
  content/articles/automating-jobs-schedule-with-django-cron-in-python/firstpage.png
  content/articles/automating-jobs-schedule-with-django-cron-in-python/hero.png
  content/articles/automating-jobs-schedule-with-django-cron-in-python/index.md
  content/articles/automating-jobs-schedule-with-django-cron-in-python/response.png
  content/articles/automating-jobs-schedule-with-django-cron-in-python/response2.png
Labels: duplicate, assigned for review, ready for final review

#7460 Cirq for Quantum Computing
  content/articles/cirq-for-quantum-computing/circuit.jpg
  content/articles/cirq-for-quantum-computing/hero.png
  content/articles/cirq-for-quantum-computing/index.md
  content/articles/cirq-for-quantum-computing/x-gate.jpg
Labels: assigned for review, ready for final review, tech tutorial

#7479 Consume Solana Blockchain Wallet on Android using the Solana programs
  content/articles/blockchain-on-android-using-the-solana-programs/hero.png
  content/articles/blockchain-on-android-using-the-solana-programs/index.md
  content/articles/blockchain-on-android-using-the-solana-programs/java-interface-file.png
  content/articles/blockchain-on-android-using-the-solana-programs/solana-devnet.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#7381 Multivariate time series using Auto ARIMA
  content/articles/multivariate-time-series-using-auto-arima/check-missing-values.png
  content/articles/multivariate-time-series-using-auto-arima/dataset-resampling.png
  content/articles/multivariate-time-series-using-auto-arima/energy-consumption-dataset.png
  content/articles/multivariate-time-series-using-auto-arima/energy-consumption-plot.png
  content/articles/multivariate-time-series-using-auto-arima/hero.jpg
  content/articles/multivariate-time-series-using-auto-arima/index.md
  content/articles/multivariate-time-series-using-auto-arima/model-output.png
  content/articles/multivariate-time-series-using-auto-arima/model-training.png
  content/articles/multivariate-time-series-using-auto-arima/new-subplots.png
  content/articles/multivariate-time-series-using-auto-arima/pandas-data-frame.png
  content/articles/multivariate-time-series-using-auto-arima/predicted-values.png
  content/articles/multivariate-time-series-using-auto-arima/rechecking-missing-values.png
  content/articles/multivariate-time-series-using-auto-arima/sub-plots.png
  content/articles/multivariate-time-series-using-auto-arima/test-data-frame-predictions.png
  content/articles/multivariate-time-series-using-auto-arima/test-data-frame.png
  content/articles/multivariate-time-series-using-auto-arima/unseen-future-predictions.png
Labels: assigned for review, ready for final review, tech tutorial

#7554 Django Backend Development Autopilot
  content/articles/django-backend-autopilot/django-install.png
  content/articles/django-backend-autopilot/hero.jpg
  content/articles/django-backend-autopilot/index.md
  content/articles/django-backend-autopilot/passed-tests.png
  content/articles/django-backend-autopilot/project-folders.png
  content/articles/django-backend-autopilot/running-the-project.png
  content/articles/django-backend-autopilot/testing-with-github-actions.png
Labels: assigned for review, ready for final review, tech tutorial

#7562 A Guide To Running Ubuntu Machine and Containerizing Python Application on Windows Powershell Core
  content/articles/running-ubuntu-os-and-containerizing-python-application-on-windows-powershell-core/hero.png
  content/articles/running-ubuntu-os-and-containerizing-python-application-on-windows-powershell-core/index.md
Labels: assigned for review, ready for final review

#7457 Implementing Undersampling, Oversampling, and SMOTE Techniques in Deep Neural Networks
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/after-applying-smote.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/after-oversampling.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/after-undersampling.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/classification-report.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/counting-data-samples.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/fitting-the-dnn.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/hero.jpg
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/imbalanced-dataset.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/index.md
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/printing-columns.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/report-after-oversampling.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/report-after-smote.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/report-after-undersampling.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/test-value-count.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/train-value-count.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/training-after-oversampling.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/training-after-undersampling.png
  content/articles/how-to-handle-imbalanced-data-in-deep-neural-networks/training-using-smote.png
Labels: assigned for review, ready for final review, tech tutorial

#7671 Article Update
  content/articles/practical-approach-to-date-and-time-in-javascript/index.md
Labels: article update

#7547 [Duplicate of #7238] - How to build an Internet Service Provider Management System in MERN Stack
  content/articles/build-mern-stack-application-to-manage-isp/allcustomers.jpg
  content/articles/build-mern-stack-application-to-manage-isp/customerDetails.jpg
  content/articles/build-mern-stack-application-to-manage-isp/folder.jpg
  content/articles/build-mern-stack-application-to-manage-isp/hero.jpg
  content/articles/build-mern-stack-application-to-manage-isp/index.md
  content/articles/build-mern-stack-application-to-manage-isp/reactapp.jpg
  content/articles/build-mern-stack-application-to-manage-isp/server.jpg
  content/articles/build-mern-stack-application-to-manage-isp/updateCustomer.jpg
  content/articles/build-mern-stack-application-to-manage-isp/webapp.jpg
  content/authors/bernice-waweru/avatar.jpeg
  content/authors/bernice-waweru/index.md
Labels: duplicate, good first article, ready for final review

#7433 Model monitoring and detecting drifts in machine learning models using Deepchecks
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/checking-concept-drift.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/checking-data-drift.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/concept-drift.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/conditions-summary.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/data-duplicates-test-set.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/data-duplicates-train-set.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/data-points.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/deepchecks-methods.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/hero.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/index.md
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/input-variables.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/model-features.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/model-inference-time.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/performance-report.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/train-test-drift.png
  content/articles/model-monitoring-and-detecting-drifts-using-deepchecks/using-duration-variable.png
Labels: assigned for review, ready for final review, tech tutorial

#7541 Custom Django API with Kotlin MVVM
  content/articles/custom-api-with-kotlin-mvvm/dependency-injection.png
  content/articles/custom-api-with-kotlin-mvvm/domain-and-usecases.png
  content/articles/custom-api-with-kotlin-mvvm/dormain.png
  content/articles/custom-api-with-kotlin-mvvm/folder-organization.png
  content/articles/custom-api-with-kotlin-mvvm/hero.png
  content/articles/custom-api-with-kotlin-mvvm/home-screen.png
  content/articles/custom-api-with-kotlin-mvvm/index.md
  content/articles/custom-api-with-kotlin-mvvm/login-endpoint.png
  content/articles/custom-api-with-kotlin-mvvm/login-screen.png
  content/articles/custom-api-with-kotlin-mvvm/network.png
  content/articles/custom-api-with-kotlin-mvvm/register-endpoint.png
  content/articles/custom-api-with-kotlin-mvvm/register-screen.png
  content/articles/custom-api-with-kotlin-mvvm/requests-and-responses.png
  content/articles/custom-api-with-kotlin-mvvm/splashscreen.png
  content/articles/custom-api-with-kotlin-mvvm/update-profile-endpoint.png
  content/articles/custom-api-with-kotlin-mvvm/utils.png
  content/articles/custom-api-with-kotlin-mvvm/view-package.png
Labels: assigned for review, ready for final review, tech tutorial
