Repository section-engineering-education/engineering-education, pull requests merged in 2022-06, with the labels that each got.

#7672 Author Profile
  content/authors/njoku-ifeanyi-gerald/avatar.jpg
  content/authors/njoku-ifeanyi-gerald/index.md
Labels: author update

#7385 Creating a Video Conferencing App with 100ms SDK in Android
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/dashboard.jpg
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/demo1.png
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/demo2.png
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/demo3.png
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/details.png
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/hero.png
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/index.md
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/new-project.png
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/packages.png
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/subdomain.png
  content/articles/creating-a-video-conferencing-app-with-100ms-sdk-in-android/template.png
  content/authors/tom-leposo/avatar.jpeg
  content/authors/tom-leposo/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#7190 Ethers vs web3
  content/articles/web3js-vs-ethersjs/hero.jpg
  content/articles/web3js-vs-ethersjs/index.md
  content/authors/chigozie-oduah/avatar.jpg
  content/authors/chigozie-oduah/index.md
Labels: assigned for review, ready for final review, article

#7362 Uploading, deleting, and downloading images uploaded to sanity.io
  content/articles/uploading-deleting-and-downloading-images-uploaded-to-sanity-io/afterinput.PNG
  content/articles/uploading-deleting-and-downloading-images-uploaded-to-sanity-io/filestructure.PNG
  content/articles/uploading-deleting-and-downloading-images-uploaded-to-sanity-io/hero.jpg
  content/articles/uploading-deleting-and-downloading-images-uploaded-to-sanity-io/index.md
  content/articles/uploading-deleting-and-downloading-images-uploaded-to-sanity-io/sanitycms.PNG
  content/articles/uploading-deleting-and-downloading-images-uploaded-to-sanity-io/sanitycmsafterupload.PNG
  content/articles/uploading-deleting-and-downloading-images-uploaded-to-sanity-io/websiteview.PNG
  content/authors/benson-raro/avatar.jpg
  content/authors/benson-raro/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#7345 Building a studio landing page with Javascript and GSAP’s scrollTrigger plugin.
  content/articles/building-studio-landing-page-javascript-gsaps-scrolltrigger/codepen.png
  content/articles/building-studio-landing-page-javascript-gsaps-scrolltrigger/hero.jpg
  content/articles/building-studio-landing-page-javascript-gsaps-scrolltrigger/index.md
Labels: assigned for review, ready for final review

#7359 Understanding When to Use Java Server Pages and Servlets
  content/articles/understanding-when-to-use-jsp-and-servlet/hero.jpg
  content/articles/understanding-when-to-use-jsp-and-servlet/index.md
  content/authors/stephine-katul/avatar.png
  content/authors/stephine-katul/index.md
Labels: assigned for review, ready for final review

#7534 Model explanation with Dalex
  content/articles/model-explanation-with-dalex/columns.png
  content/articles/model-explanation-with-dalex/data-frame.png
  content/articles/model-explanation-with-dalex/data-sample.png
  content/articles/model-explanation-with-dalex/detailed-plot.png
  content/articles/model-explanation-with-dalex/final-model.png
  content/articles/model-explanation-with-dalex/hero.jpg
  content/articles/model-explanation-with-dalex/index.md
  content/articles/model-explanation-with-dalex/overall-model-explanation.png
  content/articles/model-explanation-with-dalex/performance-scores.png
  content/articles/model-explanation-with-dalex/plot-diagram.png
  content/articles/model-explanation-with-dalex/sample-data-frame.png
  content/articles/model-explanation-with-dalex/varaible-contribution-to-prediction.png
  content/articles/model-explanation-with-dalex/variable-contribution.png
  content/authors/simon-kamau/avatar.jpg
  content/authors/simon-kamau/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#7511 Implementing a Spring Query Language Spring Boot Search
  content/articles/implementing-a-spring-query-language-spring-boot-search-operations/hero.jpg
  content/articles/implementing-a-spring-query-language-spring-boot-search-operations/index.md
Labels: assigned for review, ready for final review

#7686 Joel kanyi skills updates
  content/authors/joel-kanyi/avatar.jpg
  content/authors/joel-kanyi/index.md
Labels: author update

#7507 Integrating Razorpay in a React-Django(Django Rest Framework) Application
  content/articles/react-django-razorpay-integration/hero.jpg
  content/articles/react-django-razorpay-integration/index.md
  content/articles/react-django-razorpay-integration/paymentmodal.png
  content/articles/react-django-razorpay-integration/payments.png
  content/articles/react-django-razorpay-integration/product.png
  content/articles/react-django-razorpay-integration/razorpay-dashboard.png
  content/articles/react-django-razorpay-integration/razorpay-payment-flow.png
  content/articles/react-django-razorpay-integration/success.png
  content/authors/samfred-kim/avatar.jpg
  content/authors/samfred-kim/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#7533 Security Threats for NFTS and Possible Solutions
  content/articles/security-threats-of-nfts-and-possible-solutions-hardware-wallet/hero.jpg
  content/articles/security-threats-of-nfts-and-possible-solutions-hardware-wallet/index.md
  content/authors/joseph-kinyua/avatar.jpg
  content/authors/joseph-kinyua/index.md
Labels: assigned for review, ready for final review, article

#7476 Univariate time series using Recurrent Neural Networks
  content/articles/univariate-time-series-using-recurrent-neural-networks/ann-vs-rnn.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/compiled-model-summary.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/fitting-the-sequential-model.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/hero.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/index.md
  content/articles/univariate-time-series-using-recurrent-neural-networks/line-graph.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/lstm-structure.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/milk-production-dataset.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/milk-production-plot.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/predicted-values.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/scaled-data-points.png
  content/articles/univariate-time-series-using-recurrent-neural-networks/time-series-components.png
  content/authors/james-maingi/avatar.jpg
  content/authors/james-maingi/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#7425 A Look at RAID and Erasure Coding
  content/articles/data-recovery-raid-and-erasure-coding/hero.jpg
  content/articles/data-recovery-raid-and-erasure-coding/index.md
Labels: ready for final review

#7354 Creating a simple Augmented Reality app in Android
  content/articles/creating-a-simple-augmented-reality-app-in-android/create-ar-project.png
  content/articles/creating-a-simple-augmented-reality-app-in-android/hero.png
  content/articles/creating-a-simple-augmented-reality-app-in-android/index.md
  content/articles/creating-a-simple-augmented-reality-app-in-android/install-sceneform-plugin.png
Labels: assigned for review, ready for final review, tech tutorial

#7526 Why Kafka Is The Future Of Messaging
  content/articles/why-kafka-is-the-future-of-messaging/hero.png
  content/articles/why-kafka-is-the-future-of-messaging/index.md
Labels: ready for final review

#7543 A Begginers Guide to Rollup module bundler
  content/articles/a-beginners-guide-to-rollup-module-bundler/bundle-js.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/create-a-bundle.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/error.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/file-bundle.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/hero.jpg
  content/articles/a-beginners-guide-to-rollup-module-bundler/index.md
  content/articles/a-beginners-guide-to-rollup-module-bundler/install-rollup.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/npm-package.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/plugin-css.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/plugin.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/script.png
  content/articles/a-beginners-guide-to-rollup-module-bundler/terminal.png
Labels: assigned for review, ready for final review

#7645 Making Multipart Requests in Android with Retrofit
  content/articles/making-multipart-requests-in-android-with-retrofit/hero.jpg
  content/articles/making-multipart-requests-in-android-with-retrofit/index.md
  content/articles/making-multipart-requests-in-android-with-retrofit/new-project.png
  content/authors/esther-wanjiru/avatar.jpg
  content/authors/esther-wanjiru/index.md
Labels: ready for final review

#7556 How to Get Started with YARA for Malware Analysis
  content/articles/getting-started-with-yara-for-malware-analysis/hero.jpg
  content/articles/getting-started-with-yara-for-malware-analysis/index.md
  content/articles/mastering-yara-for-malware-analysis-the-right-way/hero.png
  content/authors/felix-vaati/index.md
Labels: assigned for review, ready for final review, tech tutorial

#7586 Securing Localhost URLs using Ngrok and self-signed SSL Certificates in Django
  content/articles/expose-localhost-urls-with-signed-certificate/hero.jpg
  content/articles/expose-localhost-urls-with-signed-certificate/index.md
  content/articles/expose-localhost-urls-with-signed-certificate/ngrok-generated-url.png
  content/articles/expose-localhost-urls-with-signed-certificate/secure-endpoint-images.png
Labels: assigned for review, ready for final review, tech tutorial

#7638 Feed-forward and Recurrent Neural Networks Python Implementation
  content/articles/feedforward-and-recurrent-neural-networks-python-implementation/feedforward.png
  content/articles/feedforward-and-recurrent-neural-networks-python-implementation/hero.png
  content/articles/feedforward-and-recurrent-neural-networks-python-implementation/index.md
  content/articles/feedforward-and-recurrent-neural-networks-python-implementation/plot.png
Labels: assigned for review, ready for final review, tech tutorial

#7599 Weka Feature Selection using Python
  content/articles/feature-selection-weka-python/hero.jpg
  content/articles/feature-selection-weka-python/index.md
Labels: assigned for review, ready for final review, tech tutorial

#7389 Implementation of 2-D Discrete Fourier Transform of square functions and natural images in Matlab
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/3D-squareFunction.png
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/3DMagnitude-spectrum.png
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/hero.jpg
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/index.md
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/lena-crossection.png
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/lena3D-spatialDomain.png
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/lena3D-spectrum.png
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/magnitude-spectrum.png
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/output-figureOne.png
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/output-figureTwo.png
  content/articles/implementation-of-2d-discrete-fourier-transform-of-square-functions-and-natural-images-in-matlab/square-function.png
Labels: assigned for review, preliminary revision in progress, ready for final review, tech tutorial

#7589 Using Face Detection in Flutter to Enhance Security
  content/articles/face-detection-in-flutter-to-enhance-security/hero.jpg
  content/articles/face-detection-in-flutter-to-enhance-security/index.md
  content/authors/naomi-wangari/avatar.jpg
  content/authors/naomi-wangari/index.md
Labels: duplicate, assigned for review, ready for final review

#7706 EngEd Author Profile Update - Skills Section
  content/authors/Kirwa-Elyjah/index.md
Labels: author update

#7502 Continuous Wavelet Transform of Simple and Discontinuous Signals in Python
  content/articles/continuous-wavelet-transform-of-signals/discontinuity-scalogram.jpg
  content/articles/continuous-wavelet-transform-of-signals/discontinuity-signal.jpg
  content/articles/continuous-wavelet-transform-of-signals/discontinuity.jpg
  content/articles/continuous-wavelet-transform-of-signals/frequency-break.jpg
  content/articles/continuous-wavelet-transform-of-signals/hero.jpg
  content/articles/continuous-wavelet-transform-of-signals/index.md
  content/articles/continuous-wavelet-transform-of-signals/scalogram.jpg
  content/articles/continuous-wavelet-transform-of-signals/signal-scalogram.jpg
  content/articles/continuous-wavelet-transform-of-signals/simple-signal.jpg
  content/articles/continuous-wavelet-transform-of-signals/wavelet-plot.jpg
  content/articles/continuous-wavelet-transform-of-signals/wavelet.jpg
Labels: assigned for review, ready for final review, tech tutorial

#7018 Working with AdMob Interstitial Google Ads in the Android application - Kotlin
  content/articles/working-with-admob-interstitial-ads-in-android-using-kotlin/hero.png
  content/articles/working-with-admob-interstitial-ads-in-android-using-kotlin/index.md
  content/authors/david-maina/avatar.jpg
  content/authors/david-maina/index.md
  content/authors/davis-maina/avatar.jpg
  content/authors/davis-maina/index.md
Labels: white label, ready for final review

#7440 Understanding Probability Distributions and their Simulations in R
  content/articles/probability-distributions/chi-square.png
  content/articles/probability-distributions/exponential.png
  content/articles/probability-distributions/hero.jpg
  content/articles/probability-distributions/index.md
  content/articles/probability-distributions/normal.png
  content/articles/probability-distributions/plot.png
  content/articles/probability-distributions/plot2.png
  content/articles/probability-distributions/poisson.png
  content/articles/probability-distributions/standardised-pdf.png
  content/articles/probability-distributions/t-students.png
  content/articles/probability-distributions/uniform.png
Labels: assigned for review, ready for final review

#7447 How to forecast time series data using Neural Network toolbox in Matlab
  content/articles/forecasting-time-series-data-in-matlab/Confusion-Matrix.png
  content/articles/forecasting-time-series-data-in-matlab/Datasets.png
  content/articles/forecasting-time-series-data-in-matlab/Deployed-Solutions.png
  content/articles/forecasting-time-series-data-in-matlab/FeedForward-network.png
  content/articles/forecasting-time-series-data-in-matlab/Input-Data.png
  content/articles/forecasting-time-series-data-in-matlab/Network-Architecture.png
  content/articles/forecasting-time-series-data-in-matlab/Network-Diagram.png
  content/articles/forecasting-time-series-data-in-matlab/Openning-Window.png
  content/articles/forecasting-time-series-data-in-matlab/Performance-Plot.png
  content/articles/forecasting-time-series-data-in-matlab/Recognition-App.png
  content/articles/forecasting-time-series-data-in-matlab/Save-Results.png
  content/articles/forecasting-time-series-data-in-matlab/Selecting-Data.png
  content/articles/forecasting-time-series-data-in-matlab/Simulink-Model.png
  content/articles/forecasting-time-series-data-in-matlab/Test-Data.png
  content/articles/forecasting-time-series-data-in-matlab/Train-Network.png
  content/articles/forecasting-time-series-data-in-matlab/Training-Output.png
  content/articles/forecasting-time-series-data-in-matlab/hero.jpg
  content/articles/forecasting-time-series-data-in-matlab/index.md
Labels: duplicate, tech review

#7552 Implementing Secure Authentication with Keycloak
  content/articles/keycloak-react-app/add-client.png
  content/articles/keycloak-react-app/add-realm.png
  content/articles/keycloak-react-app/add-user.png
  content/articles/keycloak-react-app/admin_dashboard.png
  content/articles/keycloak-react-app/hero.png
  content/articles/keycloak-react-app/home-page.png
  content/articles/keycloak-react-app/index.md
  content/articles/keycloak-react-app/installation-tab.png
  content/articles/keycloak-react-app/resource.png
  content/articles/keycloak-react-app/user1-personal-info.png
Labels: assigned for review, ready for final review

#7477 A beginner guide to SoftMax Regression using TensorFlow
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/cost-function.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/cross-entropy.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/g1.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/g2.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/hero.png
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/index.md
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/logicmatrix.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/logicvector.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/one-hot-encoding.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/softmaxmatrix.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/weight1.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/weight2.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/wfeature.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/wmatrix.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/xfeature.PNG
  content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/xmatrix.PNG
Labels: assigned for review, ready for final review

#7713 Added Reuben Sunday to List of Authors
  content/authors/reuben-sunday/avatar.jpg
  content/authors/reuben-sunday/index.md
Labels: author update

#7546 Proof Of Work Consensus Algorithm In The Blockchain
  content/articles/proof-of-work-consensus-algorithm-in-the-blockchain/hero.jpg
  content/articles/proof-of-work-consensus-algorithm-in-the-blockchain/index.md
Labels: assigned for review, ready for final review, article

#7565 A Gentle Introduction to Exponential Regression in Python
  content/articles/growth-model-in-python/data-table.png
  content/articles/growth-model-in-python/growth-curve.png
  content/articles/growth-model-in-python/hero.jpg
  content/articles/growth-model-in-python/index.md
  content/articles/growth-model-in-python/optimize.png
  content/articles/growth-model-in-python/partial-derivatives.png
Labels: assigned for review, ready for final review

#7634 Understanding IPSec
  content/articles/ip-security/hero.jpg
  content/articles/ip-security/index.md
  content/authors/kanishkvardhan-a-n/avatar.jpg
Labels: assigned for review, ready for final review

#7550 How to Work With Customized Axios for Mulitple Servers in Vue
  content/articles/customized-axios-for-mulitple-servers-in-vue/hero.png
  content/articles/customized-axios-for-mulitple-servers-in-vue/index.md
Labels: ready for final review, tech tutorial

#7540 An Overview of Diffusion Models
  content/articles/overview-of-diffusion-models/hero.png
  content/articles/overview-of-diffusion-models/index.md
Labels: assigned for review, white label, ready for final review, tech tutorial

#7575 Creating a Nested Scroll Music Player App in Jetpack Compose
  content/articles/creating-a-nested-scroll-music-player-in-compose/hero.jpg
  content/articles/creating-a-nested-scroll-music-player-in-compose/index.md
  content/articles/creating-a-nested-scroll-music-player-in-compose/nested-scroll.png
  content/articles/creating-a-nested-scroll-music-player-in-compose/new-compose-project.png
  content/articles/creating-a-nested-scroll-music-player-in-compose/player.png
Labels: assigned for review, white label, ready for final review, tech tutorial

#7578 Getting started with the resource monitoring in Laravel 9
  content/articles/server-resource-monitoring-laravel/hero.png
  content/articles/server-resource-monitoring-laravel/index.md
Labels: assigned for review, white label, ready for final review, tech tutorial

#7591 Working with java synchronization
  content/articles/working-with-java-synchronization/hero.jpg
  content/articles/working-with-java-synchronization/index.md
Labels: duplicate, assigned for review, white label, ready for final review

#7724 adding 3 new tesimonials
  data/testimonialsData.yml
Labels: documentation, ready for review

#7622 controlling-web-pages-visible-to-different-users-using-php
  content/articles/controlling-web-pages-visible-to-different-users-in-php/bootstrap_added.jpg
  content/articles/controlling-web-pages-visible-to-different-users-in-php/code_editor.jpg
  content/articles/controlling-web-pages-visible-to-different-users-in-php/database.jpg
  content/articles/controlling-web-pages-visible-to-different-users-in-php/hero.jpg
  content/articles/controlling-web-pages-visible-to-different-users-in-php/index.md
  content/articles/controlling-web-pages-visible-to-different-users-in-php/project_folder.jpg
  content/articles/controlling-web-pages-visible-to-different-users-in-php/unique.jpg
  content/articles/controlling-web-pages-visible-to-different-users-in-php/xampp_correct.jpg
  content/authors/david-okoth/avatar.png
  content/authors/david-okoth/index.md
Labels: ready for final review

#7570 Create a dynamic footer component with Minze
  content/articles/creating-a-dynamic-footer-component-with-minze/console.png
  content/articles/creating-a-dynamic-footer-component-with-minze/footer-component.png
  content/articles/creating-a-dynamic-footer-component-with-minze/hero.jpg
  content/articles/creating-a-dynamic-footer-component-with-minze/index.md
  content/articles/creating-a-dynamic-footer-component-with-minze/project-structure.png
  content/articles/creating-a-dynamic-footer-component-with-minze/running-minze-project.png
Labels: assigned for review, preliminary revision in progress, ready for final review

#7654 File Upload, Compression, and Encryption Using AES Algorithm In Flutter Applications
  content/articles/file-upload-compression-and-encryption-using-aes-algorithm-in-flutter-applications/firebasestorage-rules.png
  content/articles/file-upload-compression-and-encryption-using-aes-algorithm-in-flutter-applications/get-started.png
  content/articles/file-upload-compression-and-encryption-using-aes-algorithm-in-flutter-applications/hero.jpg
  content/articles/file-upload-compression-and-encryption-using-aes-algorithm-in-flutter-applications/index.md
Labels: tech review, preliminary revision in progress
