Repository section-engineering-education/engineering-education, pull requests merged in 2022-02, with the labels that each got.

#5912 Comparing SQL Delight to Room Database in Android
  content/articles/comparing-sql-delight-to-room-database-in-android/add_note.png
  content/articles/comparing-sql-delight-to-room-database-in-android/demo.png
  content/articles/comparing-sql-delight-to-room-database-in-android/hero.jpg
  content/articles/comparing-sql-delight-to-room-database-in-android/index.md
  content/articles/comparing-sql-delight-to-room-database-in-android/new_delight_file.png
  content/articles/comparing-sql-delight-to-room-database-in-android/new_proj.png
  content/articles/comparing-sql-delight-to-room-database-in-android/notes_list.png
  content/articles/comparing-sql-delight-to-room-database-in-android/sql_delight_plugin.png
Labels: ready for final review, tech tutorial

#6322 [Duplicate of #5782] - Building a lyrics search app using vanilla JavaScript with OVH API
  content/articles/building-a-lyrics-search-app-using-vanilla-javascript-with-ovh-api/console-screenshot.png
  content/articles/building-a-lyrics-search-app-using-vanilla-javascript-with-ovh-api/design-screenshot.png
  content/articles/building-a-lyrics-search-app-using-vanilla-javascript-with-ovh-api/hero.png
  content/articles/building-a-lyrics-search-app-using-vanilla-javascript-with-ovh-api/index.md
  content/authors/bobate-segun/avatar.png
  content/authors/bobate-segun/index.md
Labels: duplicate, assigned for review, ready for final review

#5953 How to denoise images using curvelet transform in Matlab
  content/articles/how-to-denoise-images-using-curvelet-transform-in-matlab/hero.jpg
  content/articles/how-to-denoise-images-using-curvelet-transform-in-matlab/image-five.jpeg
  content/articles/how-to-denoise-images-using-curvelet-transform-in-matlab/image-four.png
  content/articles/how-to-denoise-images-using-curvelet-transform-in-matlab/image-one.jpeg
  content/articles/how-to-denoise-images-using-curvelet-transform-in-matlab/image-six.png
  content/articles/how-to-denoise-images-using-curvelet-transform-in-matlab/image-three.png
  content/articles/how-to-denoise-images-using-curvelet-transform-in-matlab/index.md
Labels: assigned for review, preliminary revision in progress, ready for final review

#5965 Creating a data visualization dashboard using MPAndroid Chart library and SQLite
  content/articles/android-kotlin-mpandroidcharts-sqlite/hero.jpg
  content/articles/android-kotlin-mpandroidcharts-sqlite/index.md
  content/articles/android-kotlin-mpandroidcharts-sqlite/screenshot-one.png
Labels: assigned for review, ready for final review, tech tutorial

#6379 Feature Request: #6363: Test auto comment feature
  .github/workflows/auto-comment.yml
Labels: feature request

#5864 Polymorphism in Java
  content/articles/polymorphism-in-java/hero.jpg
  content/articles/polymorphism-in-java/index.md
Labels: ready for final review, test reviewer assigned, reviewer-tryout

#6386 Fixing Hero Image
  content/articles/polymorphism-in-java/index.md
Labels: article update

#6016 A Guide to Run your React Native Apps with Typescript
  content/articles/guide-to-run-react-native-app-with-typescript/default-landing-screen.jpg
  content/articles/guide-to-run-react-native-app-with-typescript/hero.jpg
  content/articles/guide-to-run-react-native-app-with-typescript/index.md
  content/articles/guide-to-run-react-native-app-with-typescript/post-screen-example.jpg
  content/articles/guide-to-run-react-native-app-with-typescript/posts-screen.jpg
  content/articles/guide-to-run-react-native-app-with-typescript/skeleton-posts-screen.jpg
Labels: ready for final review, tech tutorial

#5966 Building a Reinforcement Learning Environment using OpenAI Gym
  content/articles/building-a-reinforcement-learning-environment-using-openai-gym/hero.png
  content/articles/building-a-reinforcement-learning-environment-using-openai-gym/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6395 Feature #6363: Update - change pull_request to pull_request_target
  .github/workflows/auto-comment.yml
Labels: feature request

#5962 How to Set up Rust API Servers with the Diseal ORM and the PostgreSQL
  content/articles/rust-api-with-diesel-orm-and-postgresql/dummy-todos-query.png
  content/articles/rust-api-with-diesel-orm-and-postgresql/hero.jpg
  content/articles/rust-api-with-diesel-orm-and-postgresql/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6387 Update author file
  content/authors/cosmas-morwabe/index.md
Labels: documentation

#5760 Getting Started With NLP Transformers
  content/articles/getting-started-with-nlp-transformers/hero.jpg
  content/articles/getting-started-with-nlp-transformers/index.md
  content/articles/getting-started-with-nlp-transformers/negative.jpg
  content/articles/getting-started-with-nlp-transformers/notpara.jpg
  content/articles/getting-started-with-nlp-transformers/output.jpg
  content/articles/getting-started-with-nlp-transformers/para.jpg
  content/articles/getting-started-with-nlp-transformers/positive.jpg
  content/articles/getting-started-with-nlp-transformers/transformer.jpg
  content/authors/sharon-atieno/avatar.jpg
  content/authors/sharon-atieno/index.md
Labels: good first article, ready for final review, tech tutorial

#6009 Material Server Response Autocomplete
  content/articles/implementing-autocomplete-using-remote-data-in-angular-12/hero.png
  content/articles/implementing-autocomplete-using-remote-data-in-angular-12/index.md
  content/authors/ochieng-lydia/avatar.jpg
  content/authors/ochieng-lydia/index.md
Labels: good first article, ready for final review, tech tutorial

#5968 Getting Started with Support Vector Regression in Python
  content/articles/support-vector-regression-in-python/dataset.png
  content/articles/support-vector-regression-in-python/error-function.png
  content/articles/support-vector-regression-in-python/hero.jpg
  content/articles/support-vector-regression-in-python/index.md
  content/articles/support-vector-regression-in-python/plot.png
  content/articles/support-vector-regression-in-python/plot0.png
  content/articles/support-vector-regression-in-python/svr-graph.png
  content/articles/support-vector-regression-in-python/y-vriable.png
Labels: assigned for review, ready for final review, tech tutorial

#5974 Getting Started with the Input-Output Streams
  content/articles/php-io-streams/hero.png
  content/articles/php-io-streams/index.md
  content/authors/theresa-atieno/hero.jpeg
  content/authors/theresa-atieno/index.md
Labels: good first article, question, ready for final review, tech tutorial

#6456 Update: Author image
  content/authors/mohan-raj/avatar.jpg
Labels: author update

#6143 [Duplicate of #5701] - How to Build an IP Address Tracker with Mapbox API and Vue.
  content/articles/build-an-ip-address-tracker/hero.jpg
  content/articles/build-an-ip-address-tracker/index.md
  content/authors/abiola-farounbi/avatar.png
  content/authors/abiola-farounbi/index.md
Labels: revisions needed, duplicate, assigned for review, ready for final review, test reviewer assigned

#5989 Creating a finger counter using computer vision, OpenCv and Python
  content/articles/creating-a-finger-counter/hero.jpg
  content/articles/creating-a-finger-counter/index.md
  content/articles/creating-a-finger-counter/model.png
  content/articles/creating-a-finger-counter/project.png
  content/articles/creating-a-finger-counter/results.gif
  content/articles/creating-a-finger-counter/terminal.png
Labels: assigned for review, ready for final review, tech tutorial

#6002 Facilitate media queries using scss mixins
  content/articles/facilitating-css-media-queries-using-scss-mixins/hero.jpg
  content/articles/facilitating-css-media-queries-using-scss-mixins/index.md
  content/authors/afube-angel/avatar.jpg
  content/authors/afube-angel/index.md
Labels: ready for final review

#6020 How to receive emails with emailjs in Vue3
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email1.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email10.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email11.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email12.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email13.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email14.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email15.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email16.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email2.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email3.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email4.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email5.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email6.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email7.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email8.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/email9.png
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/hero.jpg
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/index.md
  content/articles/how-to-receive-emails-using-emailjs-in-vue3/output.png
  content/authors/mercy-bassey/avatar.png
  content/authors/mercy-bassey/index.md
Labels: duplicate, ready for final review

#6022 Introduction to handles and handle pruning in compiler design
  content/articles/handle-and-handle-pruning-compiler-design/hero.jpg
  content/articles/handle-and-handle-pruning-compiler-design/index.md
Labels: ready for final review, tech tutorial

#6026 Getting started with Flutter mrz scanner
  content/articles/flutter-mrz-scanner/hero.png
  content/articles/flutter-mrz-scanner/index.md
Labels: assigned for review, ready for final review

#6046 Simulating a Simple Epidemic Spreading Process on Graphs with Julia
  content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/graph0.png
  content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/graph1.png
  content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/graph2.png
  content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/hero.png
  content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/index.md
  content/articles/simulating-a-simple-epidemic-spreading-process-on-graphs/spreading_infection_2.gif
Labels: ready for final review, tech tutorial

#6050 [Duplicate #5855]End to end SpeechRecognition guide in Python
  content/articles/end-to-end-speech-recognition-guide-in-python/hero.png
  content/articles/end-to-end-speech-recognition-guide-in-python/index.md
  content/authors/jose-yusuf/avatar.jpg
  content/authors/jose-yusuf/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, tech tutorial

#6062 Leveraging OpenAI Gym and the Anytrading Environment for Trading
  content/articles/leveraging-openai-gym-and-the-anytrading-environment-for-trading/evaluation.png
  content/articles/leveraging-openai-gym-and-the-anytrading-environment-for-trading/hero.png
  content/articles/leveraging-openai-gym-and-the-anytrading-environment-for-trading/index.md
  content/articles/leveraging-openai-gym-and-the-anytrading-environment-for-trading/random-step-visualization.png
Labels: ready for final review, tech tutorial

#6210 Understanding PASCAL VOC Dataset
  content/articles/understanding-pascal-voc-dataset/annotation-example.png
  content/articles/understanding-pascal-voc-dataset/hero.jpg
  content/articles/understanding-pascal-voc-dataset/index.md
  content/articles/understanding-pascal-voc-dataset/pascal-voc-sample.png
Labels: assigned for review, ready for final review

#6075 [Duplicate of #4989] - Using logistic regression in pytorch to identify handwritten digits
  content/articles/logistic-regression-for-digits-recognition-pytorch/hero.jpg
  content/articles/logistic-regression-for-digits-recognition-pytorch/index.md
  content/authors/masese-gavin/avatar.jpg
  content/authors/masese-gavin/index.md
Labels: duplicate, ready for final review

#6158 Building a Video Streaming Application with Spring Boot
  content/articles/building-a-video-streaming-app-with-spring/header-info.png
  content/articles/building-a-video-streaming-app-with-spring/hero.jpg
  content/articles/building-a-video-streaming-app-with-spring/index.md
  content/articles/building-a-video-streaming-app-with-spring/network-info.png
Labels: ready for final review, tech tutorial

#6152 Do We Need a Database When We Have Apache Kafka?
  content/articles/do-we-need-a-database-when-we-have-apache-kafka/hero.jpg
  content/articles/do-we-need-a-database-when-we-have-apache-kafka/index.md
Labels: assigned for review, ready for final review

#6069 Face Recognition Using Wavelet Features
  content/articles/face-recognition-using-wavelet-features/hero.jpg
  content/articles/face-recognition-using-wavelet-features/index.md
  content/articles/face-recognition-using-wavelet-features/wavelet-five.png
  content/articles/face-recognition-using-wavelet-features/wavelet-four.png
  content/articles/face-recognition-using-wavelet-features/wavelet-one.png
  content/articles/face-recognition-using-wavelet-features/wavelet-six.png
  content/articles/face-recognition-using-wavelet-features/wavelet-three.png
  content/articles/face-recognition-using-wavelet-features/wavelet-two.png
Labels: assigned for review, ready for final review, tech tutorial

#6102 How to Adjust Image to Higher or Lower Resolution using Python
  content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/fixed.png
  content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/hero.jpg
  content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/high.png
  content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/index.md
  content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/lapsn.png
  content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/low.png
  content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/original.png
  content/articles/image-adjustment-to-higher-or-lower-resolution-using-python/sean.jpg
Labels: assigned for review, ready for final review, tech tutorial

#6126 Understanding and Solving the Problem of Multidex in Android
  content/articles/understanding-multidex-in-android/android-build-system.png
  content/articles/understanding-multidex-in-android/hero.jpg
  content/articles/understanding-multidex-in-android/index.md
Labels: ready for final review

#6206 How Big Data Is Helping Fight Sleep Disorders
  content/articles/how-big-data-is-helping-fight-sleep-disorders/hero.jpg
  content/articles/how-big-data-is-helping-fight-sleep-disorders/index.md
Labels: assigned for review, ready for final review, article

#6111 Understanding hybrid data models
  content/articles/understanding-hybrid-data-models/dataintegrity-fail.png
  content/articles/understanding-hybrid-data-models/hero.jpg
  content/articles/understanding-hybrid-data-models/index.md
  content/articles/understanding-hybrid-data-models/insert-json.png
  content/articles/understanding-hybrid-data-models/json-array-append.png
  content/articles/understanding-hybrid-data-models/json-array.png
  content/articles/understanding-hybrid-data-models/json-field.png
  content/articles/understanding-hybrid-data-models/json-object.png
  content/articles/understanding-hybrid-data-models/json-remove.png
  content/articles/understanding-hybrid-data-models/json-table.png
  content/articles/understanding-hybrid-data-models/jsonvalid.png
  content/articles/understanding-hybrid-data-models/objectdata.png
  content/articles/understanding-hybrid-data-models/scalardata.png
  content/articles/understanding-hybrid-data-models/showtbl.png
  content/articles/understanding-hybrid-data-models/structured.png
  content/authors/george-wekesa/avatar.jpg
  content/authors/george-wekesa/index.md
Labels: good first article, assigned for review, preliminary revision in progress, ready for final review, tech tutorial

#6154 Speech to text transcription model using deep speech
  content/articles/speech-to-text-transcription-model-using-deep-speech/added-audio.jpg
  content/articles/speech-to-text-transcription-model-using-deep-speech/audio-interface.jpg
  content/articles/speech-to-text-transcription-model-using-deep-speech/hero.jpg
  content/articles/speech-to-text-transcription-model-using-deep-speech/index.md
  content/articles/speech-to-text-transcription-model-using-deep-speech/text-transcription.jpg
Labels: ready for final review, tech tutorial

#6523 Minor change to EngEd (main page) & (author page) blurbs towards the top
  _index.md
  layouts/partials/engineering-education/articles-header.html
  layouts/partials/engineering-education/eng-ed-banner.html
Labels: documentation

#6112 Introduction to Secrets Management with Doppler
  content/articles/introduction-to-secrets-management-with-doppler/access.png
  content/articles/introduction-to-secrets-management-with-doppler/cmd-doppler.png
  content/articles/introduction-to-secrets-management-with-doppler/get.png
  content/articles/introduction-to-secrets-management-with-doppler/hero.jpg
  content/articles/introduction-to-secrets-management-with-doppler/index.md
  content/articles/introduction-to-secrets-management-with-doppler/local_configs.png
  content/articles/introduction-to-secrets-management-with-doppler/new-project.png
  content/articles/introduction-to-secrets-management-with-doppler/project.png
  content/articles/introduction-to-secrets-management-with-doppler/project_env.png
  content/articles/introduction-to-secrets-management-with-doppler/scoop.png
  content/articles/introduction-to-secrets-management-with-doppler/secret-example.png
  content/articles/introduction-to-secrets-management-with-doppler/secrets.png
  content/authors/lynette-mwende/avatar.png
  content/authors/lynette-mwende/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6124 Image Classifier using Transfer Learning with Tensorflow
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/another-prediction.jpg
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/dataset-information.jpg
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/displayed-images.jpg
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/hero.jpg
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/index.md
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/model-summary.jpg
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/model-training.jpg
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/prediction-outputs.jpg
  content/articles/image-classifier-using-transfer-learning-with-tensorflow/saving-model.jpg
Labels: ready for final review, tech tutorial

#6071 Manipulating Excel(Spreadsheet) data and files in Android using the Apache POI library
  content/articles/android-excel-apachepoi/device.png
  content/articles/android-excel-apachepoi/excel-sheet.png
  content/articles/android-excel-apachepoi/hero.jpg
  content/articles/android-excel-apachepoi/index.md
  content/articles/android-excel-apachepoi/shot-one.png
Labels: assigned for review, ready for final review, tech tutorial

#6213 Create a Type Ahead Feature in JavaScript using Fetch and Regex
  content/articles/create-an-ajax-type-ahead-feature-for-a-website/console-output.png
  content/articles/create-an-ajax-type-ahead-feature-for-a-website/hero.jpg
  content/articles/create-an-ajax-type-ahead-feature-for-a-website/index.md
  content/articles/create-an-ajax-type-ahead-feature-for-a-website/output.png
  content/articles/create-an-ajax-type-ahead-feature-for-a-website/returned-blobdata.png
Labels: assigned for review, ready for final review, tech tutorial

#6188 How to use the driving scenario app to create scenarios in matlab
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-eight.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-eleven.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-five.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-four.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-nine.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-one.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-seven.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-six.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-ten.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-thirteen.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-three.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-twelve.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/driving-two.png
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/hero.jpg
  content/articles/how-to-use-the-driving-scenario-app-to-create-scenarios-in-matlab/index.md
Labels: assigned for review, ready for final review

#6066 Hyperparameter Tuning In Decision Trees and Random Forests
  content/articles/hyperparmeter-tuning/accuracy-graph.png
  content/articles/hyperparmeter-tuning/hero.jpg
  content/articles/hyperparmeter-tuning/index.md
  content/articles/hyperparmeter-tuning/max-depth-1.png
  content/articles/hyperparmeter-tuning/max-depth-result1.png
  content/articles/hyperparmeter-tuning/max-features.png
  content/articles/hyperparmeter-tuning/max-leaf-node.png
  content/articles/hyperparmeter-tuning/max-leaf-node1.png
  content/articles/hyperparmeter-tuning/max-leaf-nodes.jpg
  content/articles/hyperparmeter-tuning/min-samples-split.png
  content/articles/hyperparmeter-tuning/n-estimator.png
  content/articles/hyperparmeter-tuning/overfitting-1.png
  content/articles/hyperparmeter-tuning/random-base-model.png
  content/articles/hyperparmeter-tuning/random-forest.png
  content/articles/hyperparmeter-tuning/tree-one.png
  content/articles/hyperparmeter-tuning/tree.gif
  content/articles/hyperparmeter-tuning/visualize-output.png
  content/authors/himani-gulati/avatar.jpg
  content/authors/himani-gulati/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6156 [Duplicate of #5919]Data representation using brython
  content/articles/data-representation-using-brython/hero.jpg
  content/articles/data-representation-using-brython/index.md
  content/articles/data-representation-using-brython/piechart1.png
  content/articles/data-representation-using-brython/scatterplot.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial, test reviewer assigned

#6640 [Duplicate #6109] Client-side Authentication with Express Cookie Parser
  content/articles/client-side-auth-with-express-cookie-parser/cookie.png
  content/articles/client-side-auth-with-express-cookie-parser/hero.png
  content/articles/client-side-auth-with-express-cookie-parser/index.md
  content/articles/client-side-auth-with-express-cookie-parser/loggedin.png
  content/articles/client-side-auth-with-express-cookie-parser/login.png
  content/articles/client-side-auth-with-express-cookie-parser/session.png
Labels: ready for final review

#6077 Implementing a GraphQL API server using Go lang and a MongoDB database
  content/articles/implement-graphql-api-using-golang-and-mongodb-database/create-movie.png
  content/articles/implement-graphql-api-using-golang-and-mongodb-database/hero.jpg
  content/articles/implement-graphql-api-using-golang-and-mongodb-database/index.md
  content/articles/implement-graphql-api-using-golang-and-mongodb-database/mongodb-database.png
Labels: ready for final review, tech tutorial

#6252 Working with Currencylayer API and Django
  content/articles/currency-layer-api-in-django/conversion.png
  content/articles/currency-layer-api-in-django/date-selection.png
  content/articles/currency-layer-api-in-django/hero.jpg
  content/articles/currency-layer-api-in-django/index.md
  content/articles/currency-layer-api-in-django/most-recent-rates.png
  content/articles/currency-layer-api-in-django/rate-on-specific-date.png
  content/articles/currency-layer-api-in-django/selecting-currency.png
Labels: assigned for review, ready for final review, tech tutorial

#6194 Getting Started With React, Strapi, and GraphQL
  content/articles/getting-started-with-react-strapi-graphql/add-blogs.png
  content/articles/getting-started-with-react-strapi-graphql/admin.png
  content/articles/getting-started-with-react-strapi-graphql/allblogs.png
  content/articles/getting-started-with-react-strapi-graphql/content-type-builder-screen.png
  content/articles/getting-started-with-react-strapi-graphql/content-type-builder.png
  content/articles/getting-started-with-react-strapi-graphql/fields.png
  content/articles/getting-started-with-react-strapi-graphql/find-findOne.png
  content/articles/getting-started-with-react-strapi-graphql/hero.jpg
  content/articles/getting-started-with-react-strapi-graphql/index.md
  content/articles/getting-started-with-react-strapi-graphql/installation-type.png
  content/articles/getting-started-with-react-strapi-graphql/register.png
  content/articles/getting-started-with-react-strapi-graphql/roles.png
  content/articles/getting-started-with-react-strapi-graphql/singleblog.png
  content/articles/getting-started-with-react-strapi-graphql/text-filed.png
Labels: ready for final review, tech tutorial

#6093 A Guide on How to Impute Time Series Missing Values using Python
  content/articles/missing-values-in-time-series/data-head.png
  content/articles/missing-values-in-time-series/data-plot.png
  content/articles/missing-values-in-time-series/hero.png
  content/articles/missing-values-in-time-series/index.md
  content/articles/missing-values-in-time-series/linear-interpolation.png
  content/articles/missing-values-in-time-series/locf.png
  content/articles/missing-values-in-time-series/mean-imp.png
  content/articles/missing-values-in-time-series/median-imp.png
  content/articles/missing-values-in-time-series/nocb.png
  content/articles/missing-values-in-time-series/null-data.png
  content/articles/missing-values-in-time-series/spline.png
Labels: assigned for review, ready for final review, tech tutorial

#6209 Getting started with Computer network services
  content/articles/computer-net-service/hero.jpg
  content/articles/computer-net-service/index.md
  content/authors/leroy-gor/avatar.jpeg
  content/authors/leroy-gor/index.md
Labels: duplicate, good first article, ready for final review, article

#6137 Anomaly Detection Model on Time Series data
  content/articles/anomaly-detection-model-on-time-series-data/dataset-structure.jpg
  content/articles/anomaly-detection-model-on-time-series-data/five-rows.jpg
  content/articles/anomaly-detection-model-on-time-series-data/hero.jpg
  content/articles/anomaly-detection-model-on-time-series-data/index.md
  content/articles/anomaly-detection-model-on-time-series-data/line-chart.jpg
  content/articles/anomaly-detection-model-on-time-series-data/new-dataframe.jpg
  content/articles/anomaly-detection-model-on-time-series-data/plot-digram.jpg
  content/articles/anomaly-detection-model-on-time-series-data/predicted-values.jpg
  content/articles/anomaly-detection-model-on-time-series-data/renamed-columns.jpg
  content/articles/anomaly-detection-model-on-time-series-data/resampled-dataset.jpg
  content/articles/anomaly-detection-model-on-time-series-data/scatter-plot.jpg
Labels: assigned for review, ready for final review, tech tutorial

#6180 How To Format Form Data As JSON
  content/articles/how-to-format-form-data-as-json/console-response-on-browser.png
  content/articles/how-to-format-form-data-as-json/console-response-on-terminal-from-api.png
  content/articles/how-to-format-form-data-as-json/hero.jpg
  content/articles/how-to-format-form-data-as-json/index.md
  content/articles/how-to-format-form-data-as-json/sample-form.png
  content/authors/gisiora-elvis/avatar.jpg
  content/authors/gisiora-elvis/index.md
Labels: good first article, ready for final review, tech tutorial

#6233 Build a web scraper using ExpressJs, NodeJs and Cheerio
  content/articles/build-a-web-scraper-using-cheerio/cryptodata.PNG
  content/articles/build-a-web-scraper-using-cheerio/hero.jpg
  content/articles/build-a-web-scraper-using-cheerio/index.md
  content/articles/build-a-web-scraper-using-cheerio/port.PNG
  content/articles/build-a-web-scraper-using-cheerio/robots.PNG
Labels: ready for final review, tech tutorial

#6241 Beginer's view of Paytm Loading effect
  content/articles/paytm-loading/hero.png
  content/articles/paytm-loading/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6228 Encapsulation in C++
  content/articles/encapsulation-in-c++/hero.jpeg
  content/articles/encapsulation-in-c++/index.md
Labels: ready for final review, test reviewer assigned

#6286 React Social Authentication using Djoser and Django
  content/articles/social-authentication-with-djoser-in-react-applications/authenticating-with-google.png
  content/articles/social-authentication-with-djoser-in-react-applications/create-new-project-google-console.png
  content/articles/social-authentication-with-djoser-in-react-applications/creating-oauth-client-id.png
  content/articles/social-authentication-with-djoser-in-react-applications/hero.png
  content/articles/social-authentication-with-djoser-in-react-applications/home-page-after-authentication.png
  content/articles/social-authentication-with-djoser-in-react-applications/home-page.png
  content/articles/social-authentication-with-djoser-in-react-applications/index.md
  content/articles/social-authentication-with-djoser-in-react-applications/setting-up-the-uris.png
Labels: assigned for review, ready for final review, tech tutorial

#6292 What is DataOps and Why Data Engineers need it
  content/articles/what-is-dataops-and-why-data-engineers-need-it/hero.jpg
  content/articles/what-is-dataops-and-why-data-engineers-need-it/index.md
Labels: assigned for review, ready for final review, article

#6174 How to Add Form Validations in Android Using Data Binding Regex and Material
  content/articles/form-validation-in-android-using-data-binding-regex-and-material/form.png
  content/articles/form-validation-in-android-using-data-binding-regex-and-material/hero.jpg
  content/articles/form-validation-in-android-using-data-binding-regex-and-material/index.md
  content/articles/form-validation-in-android-using-data-binding-regex-and-material/invalid-form.png
  content/articles/form-validation-in-android-using-data-binding-regex-and-material/new-android-project.png
Labels: assigned for review, ready for final review, tech tutorial

#6321 Comment Moderation Function using Machine Learning with Nyckel
  content/articles/comment-moderation-function-using-machine-learning-from-nyckel/category.png
  content/articles/comment-moderation-function-using-machine-learning-from-nyckel/function.png
  content/articles/comment-moderation-function-using-machine-learning-from-nyckel/hero.png
  content/articles/comment-moderation-function-using-machine-learning-from-nyckel/home.png
  content/articles/comment-moderation-function-using-machine-learning-from-nyckel/index.md
  content/articles/comment-moderation-function-using-machine-learning-from-nyckel/result.png
Labels: ready for final review, tech tutorial

#6191 Introduction To PHP Graphic Techniques
  content/articles/introduction-to-php-graphic-techniques/hero.jpg
  content/articles/introduction-to-php-graphic-techniques/image1.jpg
  content/articles/introduction-to-php-graphic-techniques/image2.jpg
  content/articles/introduction-to-php-graphic-techniques/image3.JPG
  content/articles/introduction-to-php-graphic-techniques/image4.jpg
  content/articles/introduction-to-php-graphic-techniques/index.md
  content/authors/sarah-asuquo/Avatar.jpg
  content/authors/sarah-asuquo/index.md
Labels: duplicate, good first article, ready for final review, tech tutorial

#6394 How to build a Q&A web application using Python and Anvil
  content/articles/building-a-qa-web-application/anvil-server-uplink.jpg
  content/articles/building-a-qa-web-application/design.jpg
  content/articles/building-a-qa-web-application/hero.png
  content/articles/building-a-qa-web-application/index.md
  content/articles/building-a-qa-web-application/results.jpg
  content/articles/building-a-qa-web-application/uplink.jpg
Labels: assigned for review, ready for final review, tech tutorial

#6118 AutoNLP using AutoVIML library for Natural Language Processing
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/best-algorithm.png
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/best-vectorizer.png
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/dataframe-structure.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/dataset-array.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/dataset-information.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/hero.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/index.md
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/nltk-download.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/pipeline-output.png
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/pipeline-steps.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/punctuation-hashtags.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/stop-words-url-counts.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/target-column.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/vectorization-process.jpg
  content/articles/autonlp-using-autoviml-library-for-natural-language-processing/word-count.jpg
  content/authors/james-omina/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6197 Creating a honeypot for network security
  content/articles/creating-a-honeypot-for-network-security/hero.png
  content/articles/creating-a-honeypot-for-network-security/image1.png
  content/articles/creating-a-honeypot-for-network-security/image2.png
  content/articles/creating-a-honeypot-for-network-security/index.md
Labels: assigned for review, ready for final review, article

#6225 Implementing Rate Limiter in Spring Boot
  content/articles/implement-rate-limiting-in-spring-boot/hero.jpg
  content/articles/implement-rate-limiting-in-spring-boot/index.md
  content/articles/implement-rate-limiting-in-spring-boot/post.jpg
  content/articles/implement-rate-limiting-in-spring-boot/pre.jpg
Labels: assigned for review, ready for final review, tech tutorial

#6113 Getting started with Django polymorphic models
  content/articles/django-model-polymorphism/hero.png
  content/articles/django-model-polymorphism/index.md
Labels: assigned for review, ready for final review

#6383 [Duplicate of #6166] - Managing React State with Hookstate
  content/articles/getting-started-with-hookstate/demo1.png
  content/articles/getting-started-with-hookstate/hero.png
  content/articles/getting-started-with-hookstate/index.md
  content/articles/getting-started-with-hookstate/initial-browser-screen.png
  content/articles/getting-started-with-hookstate/terminal.png
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#6446 Implementing Bagging Algorithms in Python
  content/articles/implementing-bagging-algorithms-in-python/bagging-vs-boosting.jpg
  content/articles/implementing-bagging-algorithms-in-python/bootstrapping-process.png
  content/articles/implementing-bagging-algorithms-in-python/diabetes-dataset.jpg
  content/articles/implementing-bagging-algorithms-in-python/hard-voting.png
  content/articles/implementing-bagging-algorithms-in-python/hero.jpg
  content/articles/implementing-bagging-algorithms-in-python/how-bagging-works.jpg
  content/articles/implementing-bagging-algorithms-in-python/index.md
  content/articles/implementing-bagging-algorithms-in-python/missing-values.jpg
  content/articles/implementing-bagging-algorithms-in-python/parallel-training.png
  content/articles/implementing-bagging-algorithms-in-python/scaled-dataset.jpg
  content/articles/implementing-bagging-algorithms-in-python/soft-vs-hard-voting.png
  content/authors/joseph-gatura/avatar.jpg
  content/authors/joseph-gatura/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, tech tutorial

#6195 Getting started with Intents in Android development using Kotlin
  content/articles/getting-started-with-intents-in-android-development-using-kotlin/activity.jpg
  content/articles/getting-started-with-intents-in-android-development-using-kotlin/configure.jpg
  content/articles/getting-started-with-intents-in-android-development-using-kotlin/design.jpg
  content/articles/getting-started-with-intents-in-android-development-using-kotlin/hero.jpg
  content/articles/getting-started-with-intents-in-android-development-using-kotlin/index.md
  content/authors/david-maina/avatar.jpg
  content/authors/david-maina/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6204 Using Supabase as an Alternative to Firebase in Flutter
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/create-new-supabase-project.png
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/demo1.jpg
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/demo2.jpg
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/demo3.jpg
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/hero.jpg
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/index.md
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/new-supabase-project.png
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/new-table.png
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/secrets.png
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/start-supabase.png
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/supabase-project.png
  content/articles/using-supabase-as-an-alternative-to-firebase-in-flutter/table-editor.png
Labels: assigned for review, ready for final review, tech tutorial

#6155 [Security] Getting Started with Nessus Scanner
  content/articles/getting-started-with-nessus-scanner/basic-scan.png
  content/articles/getting-started-with-nessus-scanner/dpkg-nessus.png
  content/articles/getting-started-with-nessus-scanner/hero.jpg
  content/articles/getting-started-with-nessus-scanner/index.md
  content/articles/getting-started-with-nessus-scanner/metasploitable.png
  content/articles/getting-started-with-nessus-scanner/scan.png
  content/articles/getting-started-with-nessus-scanner/vuln.png
  content/authors/adeshina-peter/avatar.jpg
  content/authors/adeshina-peter/index.md
Labels: good first article, assigned for review, ready for final review, tech tutorial

#6542 Spring Boot microservice architecture with Spring Cloud Consul
  content/articles/spring-cloud-consul/consul-dashboard.png
  content/articles/spring-cloud-consul/hero.png
  content/articles/spring-cloud-consul/index.md
  content/articles/spring-cloud-consul/product-service.png
  content/articles/spring-cloud-consul/shop-service.png
Labels: assigned for review, ready for final review

#6467 Testing for Broken Authentication in Web Apps
  content/articles/testing-for-broken-authentication-in-web-apps/admin.png
  content/articles/testing-for-broken-authentication-in-web-apps/attack.png
  content/articles/testing-for-broken-authentication-in-web-apps/burp.png
  content/articles/testing-for-broken-authentication-in-web-apps/error.png
  content/articles/testing-for-broken-authentication-in-web-apps/hero.png
  content/articles/testing-for-broken-authentication-in-web-apps/http.png
  content/articles/testing-for-broken-authentication-in-web-apps/index.md
  content/articles/testing-for-broken-authentication-in-web-apps/index.png
  content/articles/testing-for-broken-authentication-in-web-apps/intruder.png
  content/articles/testing-for-broken-authentication-in-web-apps/login.png
  content/articles/testing-for-broken-authentication-in-web-apps/password-reset.png
  content/articles/testing-for-broken-authentication-in-web-apps/password.png
  content/articles/testing-for-broken-authentication-in-web-apps/payload.png
  content/articles/testing-for-broken-authentication-in-web-apps/question.png
  content/articles/testing-for-broken-authentication-in-web-apps/success.png
Labels: assigned for review, ready for final review, article

#6302 Quantum key distribution: An overview
  content/articles/quantum-key-distribution/hero.jpg
  content/articles/quantum-key-distribution/index.md
  content/authors/oliver-mulwa/avatar.jpg
  content/authors/oliver-mulwa/index.md
Labels: ready for final review, article

#6444 Bridge to Kubernetes: The Perfect Replacement for Azure Dev Spaces
  content/articles/bridge-to-kubernetes-the-perfect-replacement-for-azure-dev-spaces/hero.jpg
  content/articles/bridge-to-kubernetes-the-perfect-replacement-for-azure-dev-spaces/index.md
Labels: assigned for review, ready for final review, article

#6573 [Duplicate #6145] Pathlib vs OS Modules for File and Directory System Operation utilizing Comparable Scenarios
  content/articles/pathlib-vs-os-modules-for-file-and-directory-system-operation/hero.jpg
  content/articles/pathlib-vs-os-modules-for-file-and-directory-system-operation/index.md
  content/authors/akenz-michael/avatar.jpeg
  content/authors/akenz-michael/index.md
Labels: duplicate, good first article, assigned for review, ready for final review, tech tutorial

#6234 [Duplicate of #5365] Introduction to Kernel Methods in Machine Learning
  content/articles/introduction-to-kernel-methods-in-machine-learning/hero.png
  content/articles/introduction-to-kernel-methods-in-machine-learning/index.md
  content/authors/brian-kiplangat/avatar.jpg
  content/authors/brian-kiplangat/index.md
Labels: good first article, ready for final review, tech tutorial

#6246 Comparing AWS Shared Responsibility Models for Different Products
  content/articles/comparing-aws-shared-responsibility-models-for-different-products/hero.jpg
  content/articles/comparing-aws-shared-responsibility-models-for-different-products/index.md
Labels: ready for final review, article

#6332 Natural Language Processing using Gradient Boosting Machine and H2O library
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/converted-dataframe.jpg
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/converted-word-vectors.jpg
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/dataset-array.jpg
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/dataset-information.jpg
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/h2o-cluster.jpg
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/headline-column.jpg
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/hero.png
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/index.md
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/output-column.jpg
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/reviews-column.jpg
  content/articles/natural-language-processing-using-gradient-boosting-machine-and-h2o-library/word-vectors.jpg
  content/authors/willyngashu/avatar.jpg
  content/authors/willyngashu/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6488 Static Application Security Testing using MobSF and Docker
  content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/hero.jpg
  content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/index.md
  content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/report.png
  content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/results.png
  content/articles/how-to-perform-containerized-static-application-security-testing(sast)-using-mobsf-within-a-docker-container/upload.png
Labels: ready for final review, tech tutorial

#6172 How to build a Meme Generator with Vanilla JavaScript, Skeleton and the HTML 5 Canvas
  content/articles/meme-generator-vanilla-javascript-skeleton-html5-canvas/final-image.png
  content/articles/meme-generator-vanilla-javascript-skeleton-html5-canvas/hero.jpg
  content/articles/meme-generator-vanilla-javascript-skeleton-html5-canvas/index.md
  content/articles/meme-generator-vanilla-javascript-skeleton-html5-canvas/meme-generator.png
  content/articles/meme-generator-vanilla-javascript-skeleton-html5-canvas/skeleton-file-structure.png
Labels: ready for final review, test reviewer assigned

#6362 How to build a Java GUI calculator from scratch using Box layout
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/1-ui-overview.png
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/2-horizontalglue-demo.png
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/3-ui-final-view.png
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/4-null-n-multiple-dot-bug.png
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/5-four-by-fiftysix.png
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/6-processoutputnumber-location.png
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/7-final-screenshot-a.png
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/8-final-screenshot-b.png
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/hero.jpg
  content/articles/how-to-build-a-java-gui-calculator-from-scratch-using-box-layout/index.md
Labels: assigned for review, ready for final review, tech tutorial

#6245 An Overview of Jina AI
  content/articles/an-overview-of-jina-ai/hero.png
  content/articles/an-overview-of-jina-ai/index.md
Labels: duplicate, assigned for review, ready for final review

#6464 [Duplicate #6214] How to Integrate Django-Tailwind Styling in an Application
  content/articles/how-to-integrate-django-tailwind-styling-in-an-application/first-page.png
  content/articles/how-to-integrate-django-tailwind-styling-in-an-application/hero.png
  content/articles/how-to-integrate-django-tailwind-styling-in-an-application/index.md
  content/articles/how-to-integrate-django-tailwind-styling-in-an-application/tailwind-init.png
  content/authors/umoh-mercy/avatar.png
  content/authors/umoh-mercy/index.md
Labels: duplicate, good first article, assigned for review, ready for final review

#6262 Use geopy to calculate the distance between two points[Duplicate of #5339]
  content/articles/using-geopy-to-calculate-the-distance-between-two-points/hero.jpg
  content/articles/using-geopy-to-calculate-the-distance-between-two-points/index.md
Labels: duplicate, ready for final review

#6645 [Duplicate of #6445] - How to build a web crawler with Java
  content/articles/how-to-build-a-web-crawler-with-java/bfs.png
  content/articles/how-to-build-a-web-crawler-with-java/crawl-result.png
  content/articles/how-to-build-a-web-crawler-with-java/hero.jpg
  content/articles/how-to-build-a-web-crawler-with-java/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#6384 An Overview of ConvNeXt
  content/articles/an-overview-of-convnext/hero.png
  content/articles/an-overview-of-convnext/index.md
Labels: assigned for review, ready for final review, article

#6409 Implementing AES Encryption And Decryption In Java
  content/articles/implementing-aes-encryption-and-decryption-in-java/hero.png
  content/articles/implementing-aes-encryption-and-decryption-in-java/index.md
Labels: assigned for review, preliminary revision in progress, ready for final review

#6370 Using C# to demonstrate Lock in Thread
  content/articles/using-c-sharp-to-demonstrate-lock-in-thread/hero.jpg
  content/articles/using-c-sharp-to-demonstrate-lock-in-thread/index.md
Labels: assigned for review, ready for final review

#6647 [Duplicate of #6291] - testing-java-projects-using-junit-and-mockito-doing-more-with-mockito
  content/articles/testing-java-projects-using-junit-and-mockito-doing-more-with-mockito/hero.jpg
  content/articles/testing-java-projects-using-junit-and-mockito-doing-more-with-mockito/index.md
Labels: duplicate, assigned for review, ready for final review, tech tutorial

#6459 Understanding Gazpacho in Python and its Application in Web Scraping
  content/articles/understanding-gazpacho-in-python-and-its-application-in-webscraping/final-output.jpg
  content/articles/understanding-gazpacho-in-python-and-its-application-in-webscraping/gazpacho-installation.jpg
  content/articles/understanding-gazpacho-in-python-and-its-application-in-webscraping/hero.jpg
  content/articles/understanding-gazpacho-in-python-and-its-application-in-webscraping/html-soup.jpg
  content/articles/understanding-gazpacho-in-python-and-its-application-in-webscraping/index.md
  content/articles/understanding-gazpacho-in-python-and-its-application-in-webscraping/tablet-titles.jpg
Labels: assigned for review, ready for final review, tech tutorial

#6366 Overview of Microsoft SSIS
  content/articles/overview-of-microsoft-ssis/hero.jpg
  content/articles/overview-of-microsoft-ssis/index.md
  content/authors/denis-oduki/avatar.jpg
  content/authors/denis-oduki/index.md
Labels: good first article, assigned for review, ready for final review

#6683 Is Golang A Good Fit for the Internet of Things Projects?
  content/articles/golang-for-the-internet-of-things-projects/hero.jpg
  content/articles/golang-for-the-internet-of-things-projects/index.md
Labels: assigned for review, ready for final review, article

#6472 API Mocking Tools and Best Practices
  content/articles/api-mocking-tools-and-best-practices/hero.png
  content/articles/api-mocking-tools-and-best-practices/index.md
Labels: assigned for review, ready for final review

#6657 Add comments and likes to articles on author profile pages
  Jenkinsfile
  Makefile
  assets/js/featureToggle.js
  assets/scss/components/_blog-listing.scss
  config/development/config.toml
  config/local/config.toml
  config/production/config.toml
  config/staging/config.toml
  layouts/authors/single.html
Labels: enhancement

#6177 Understanding Embeddings in Machine Learning
  content/articles/understanding-embeddings-in-machine-learning/hero.jpeg
  content/articles/understanding-embeddings-in-machine-learning/index.md
Labels: assigned for review, ready for final review, article

#6117 Digital Twins and IoT for Robotics
  .hugo_build.lock
  content/articles/digital-twins-and-iot-for-robotics/hero.jpg
  content/articles/digital-twins-and-iot-for-robotics/index.md
Labels: assigned for review, ready for final review

#6466 Machine Learning using Pandas Profiling and Scikit-learn Pipeline
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/added-transformer.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/column-transformer.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/correlations-plots.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/customer-churn-dataset.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/customer-id-and-gender.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/dataset-overview.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/dependants-and-tenure.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/dropped-columns.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/first-10-rows.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/hero.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/index.md
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/interaction-section.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/internet-service.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/last-10-rows.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/missing-values.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/monthly-charges-and-total-charges.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/senior-citizen-and-partner.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/transformed-dataset.jpg
  content/articles/machine-learning-using-pandas-profiling-and-scikit-learn-pipeline/transformed-test-dataset.jpg
Labels: assigned for review, ready for final review, tech tutorial

#6527 Quickstart To Nested Data Structures with Deep Watchers
  content/articles/vue-deep-nesting/hero.png
  content/articles/vue-deep-nesting/index.md
Labels: ready for final review, tech tutorial
